contentcuration/contentcuration/management/commands/runserver.py

Fixes browserify subprocess running for windows.

---

contentcuration/contentcuration/dev_settings.py
contentcuration/contentcuration/static/js/exercise_creation/hbtemplates/assessment_item_answer.handlebars
contentcuration/contentcuration/static/js/exercise_creation/hbtemplates/assessment_item_answer_list.handlebars
contentcuration/contentcuration/static/js/exercise_creation/hbtemplates/assessment_item_answer_toolbar_closed.handlebars
contentcuration/contentcuration/static/js/exercise_creation/hbtemplates/assessment_item_answer_toolbar_open.handlebars
contentcuration/contentcuration/static/js/exercise_creation/hbtemplates/assessment_item_edit.handlebars
contentcuration/contentcuration/static/js/exercise_creation/hbtemplates/assessment_item_edit_toolbar_closed.handlebars
contentcuration/contentcuration/static/js/exercise_creation/hbtemplates/assessment_item_edit_toolbar_open.handlebars
contentcuration/contentcuration/static/js/exercise_creation/hbtemplates/exercise_edit.handlebars
contentcuration/contentcuration/static/js/exercise_creation/models.js
contentcuration/contentcuration/static/js/exercise_creation/views.js
contentcuration/contentcuration/static/less/exercises.less

Fixes #17, resolves #18, and closes #21.
@jamalex or @MCGallaspy to test this, run locally using the included dev_settings.py

Exercise author UI fixes

---

contentcuration/contentcuration/static/js/exercise_creation/hbtemplates/assessment_item_multiple.handlebars
contentcuration/contentcuration/static/js/exercise_creation/views.js

Fixes multiple item flagging in downloaded exercises.

Fixes answer rendering in downloaded exercises.

---

contentcuration/contentcuration/serializers.py
contentcuration/contentcuration/static/js/edit_channel/uploader/hbtemplates/edit_metadata_dialog.handlebars
contentcuration/contentcuration/static/js/edit_channel/uploader/hbtemplates/file_upload.handlebars
contentcuration/contentcuration/static/js/edit_channel/uploader/views.js

Disables 'submit files' button until file upload is complete.
Adds option to remove uploaded files.
Shows file size in the content metadata editor.

File Uploader Tweaks

---

contentcuration/contentcuration/views.py

Read commits, self explanatory.

Redirect to channels; Don't require login

---

contentcuration/contentcuration/models.py
contentcuration/contentcuration/serializers.py

ContentCuration launch tasks

---

contentcuration/contentcuration/models.py
contentcuration/contentcuration/serializers.py

the client side has issue now with rendering the newly created tags

new strategy to remove hyphen from uuid

---

contentcuration/contentcuration/management/commands/exportchannel.py

Generate the tokens for Kolibri ContentNode stemmed_metaphone field upon exportchannel
Please merge after  https://github.com/learningequality/kolibri/pull/461  is merged in Kolibri

Support fuzzy search

---

contentcuration/contentcuration/management/commands/exportchannel.py

import the correct path from kolibri

---

contentcuration/contentcuration/view/internal_views.py

Right now, there are a lot of files on the CC server that have no data attached to them. This will help get rid of this problem (might want to remove this later for efficiency)

Added check for corrupted files to reupload

---

.gitignore
contentcuration/contentcuration/dev_settings.py
contentcuration/contentcuration/management/commands/loadconstants.py
contentcuration/contentcuration/settings.py
contentcuration/contentcuration/urls.py
requirements.txt

To enable uploading of content used in https://github.com/learningequality/kolibri/pull/686

HTML5 app content support

---

contentcuration/contentcuration/static/js/edit_channel/uploader/hbtemplates/edit_metadata_editor.handlebars
contentcuration/contentcuration/static/js/edit_channel/uploader/views.js
contentcuration/contentcuration/static/js/edit_channel/utils/autocomplete.js
contentcuration/contentcuration/static/less/uploader.less

Added autocomplete feature for tags

Tag autocompletion

---

contentcuration/contentcuration/management/commands/exportchannel.py
contentcuration/contentcuration/settings.py
requirements.txt

Wait for https://github.com/learningequality/kolibri/pull/1018 to be merged/deployed, then update kolibri dependency version

AssessmentMetaData added to export process

---

contentcuration/contentcuration/view/internal_views.py

We'll garbage collect that later.

Don't delete the old tree.

---

README.md
requirements_dev.txt

Learned a lot going through the install process. Thought others might want to do less learning in the process of getting started

Documentation Update

---

contentcuration/contentcuration/settings.py

This will make our stuff work when we have multiple app servers.

Used a shared cache db for sessions.

---

contentcuration/contentcuration/settings.py
requirements.txt

So we can see the errors as they happen.

add gcloud error reporting capabilities.

---

README.md
contentcuration/contentcuration/dev_settings.py

Based on talks with Aron
Basically getting rid of the sqlite3 option

Updating documentation

---

contentcuration/contentcuration/dev_settings.py

Adding previously deleted code

---

Makefile

Update gunicorn timeout settings

---

contentcuration/contentcuration/wsgi.py
requirements.txt

Was leading to segfaults on my side, submitting PR at @aronasorman's request

Removing google debugger

---

build.js
package.json

So I had started refactoring the build file. It's less robust, but we're not using most of the functionality that I removed (or at least it doesn't seem like we are).
Definitely test it out. It's a little faster and easier to read to my eyes. Requires #259

Build refactor

---

package.json

Removing git dependency per @aronasorman's request. Got my changes upstream :')

Lessify update

---

README.md
requirements_prod.txt

Fixing typo in requirements file
updating documentation

Additional Vagrant Updates

---

contentcuration/contentcuration/view/internal_views.py

inform API user of a improper language string

inform API user of a improper language string

---

Makefile
README.md
provision.sh

Adding `vagrantdevserver` to Makefile
Updating documentation

Makefile and Documentation Updates

---

contentcuration/contentcuration/models.py
contentcuration/contentcuration/static/js/edit_channel/models.js
contentcuration/contentcuration/static/js/edit_channel/new_channel/views.js
contentcuration/contentcuration/static/js/edit_channel/views.js

Added stat tracking for channel creation.

Channel Stats

---

contentcuration/contentcuration/static/css/offline-language-english.css
contentcuration/contentcuration/static/css/offline-theme-slide.css
contentcuration/contentcuration/static/js/bundle_modules/base.js
contentcuration/contentcuration/static/js/edit_channel/new_channel/hbtemplates/channel_create.handlebars
contentcuration/contentcuration/static/js/edit_channel/new_channel/views.js
contentcuration/contentcuration/static/js/utils/offline_helper.js
contentcuration/contentcuration/static/js/utils/snake.js
contentcuration/contentcuration/static/less/channel_create.less
contentcuration/contentcuration/static/less/global-variables.less
package.json

Added check in case user loses connection

---

contentcuration/contentcuration/api.py
contentcuration/contentcuration/forms.py
contentcuration/contentcuration/management/commands/calculateresources.py
contentcuration/contentcuration/management/commands/loadconstants.py
contentcuration/contentcuration/management/commands/restore_channel.py
contentcuration/contentcuration/management/commands/runserver.py
contentcuration/contentcuration/management/commands/syncnodes.py
contentcuration/contentcuration/router.py
contentcuration/contentcuration/tests/test_createchannel.py
contentcuration/contentcuration/tests/test_exportchannel.py
contentcuration/contentcuration/tests/test_fileendpoints.py
contentcuration/contentcuration/urls.py
contentcuration/contentcuration/utils/files.py
contentcuration/contentcuration/view/file_views.py
contentcuration/contentcuration/view/settings_views.py
contentcuration/contentcuration/view/zip_views.py
contentcuration/contentcuration/views.py
package.json
requirements_dev.txt

This addresses #349 directly, but there are a lot of other errors, which I'll list in a follow up issue.

Add flake8 to project + fix most F401 unused import errors

---

contentcuration/contentcuration/management/commands/exportchannel.py

(Cherry-picked to target master)

Fix exportchannel so it doesn't filter out assessment item answers that are 0

---

contentcuration/contentcuration/settings.py
contentcuration/contentcuration/static/js/edit_channel/router.js
contentcuration/contentcuration/static/js/edit_channel/tree_edit/views.js
contentcuration/contentcuration/static/js/edit_channel/uploader/views.js
contentcuration/contentcuration/static/less/content-container.less
contentcuration/contentcuration/templates/channel_edit.html
contentcuration/contentcuration/view/node_views.py
contentcuration/contentcuration/views.py

Changes titles based on content being viewed, shortens urls to 7 character hashes, replaces url when not an essential url change

Url navigation enhancements

---

contentcuration/contentcuration/static/js/bundle_modules/channel_edit.js
contentcuration/contentcuration/static/js/edit_channel/information/hbtemplates/published_modal.handlebars
contentcuration/contentcuration/static/js/edit_channel/information/views.js
contentcuration/contentcuration/static/js/edit_channel/views.js
contentcuration/contentcuration/static/less/content-container.less
contentcuration/contentcuration/templates/channel_edit.html

Changed publish id to modal

---

Makefile
docs/_static/theme_overrides.css
docs/conf.py

Will self-merge to get RTD running.

Add `make docs` target + fix a couple of issues in docs/conf.py

---

contentcuration/contentcuration/static/less/global-variables.less
contentcuration/contentcuration/static/less/styles.less
contentcuration/contentcuration/templates/base.html

Added help link

---

contentcuration/contentcuration/forms.py
contentcuration/contentcuration/management/commands/exportchannel.py
contentcuration/contentcuration/serializers.py
contentcuration/contentcuration/static/js/edit_channel/share/hbtemplates/share_current_user.handlebars
contentcuration/contentcuration/static/js/edit_channel/share/views.js
contentcuration/contentcuration/templates/registration/registration_needed_email.txt
contentcuration/contentcuration/urls.py
contentcuration/contentcuration/view/registration_views.py

Send email if user has not registered yet

Password reset fixes

---

docs/add_content.rst

I know we are close to have this, but I was too eager to announce it in the documentation already... 😕 
Let's state it properly, and I'll revert this to **supported** once it is ready.

Correct the state of ePUB format support in Studio

---

cloudbuild.yaml
contentcuration/contentcuration/management/commands/exportchannel.py
contentcuration/contentcuration/production_settings.py
contentcuration/contentcuration/settings.py

Move the generated DB into the proper storage system, using `django.files.storage`

Fix publishing

---

contentcuration/contentcuration/models.py

Remove assessment item querying when calculating file size

---

README.md

This threw me for a loop.  I had begun to manually collect test dependencies in *requirements_dev.txt*.  Come to find out, lo and behold, there was already a *requirements_test.txt*!

Brief preliminary test documentation

---

Pipfile
README.md
requirements_test.txt

The documentation is a work in progress, and is mostly intended create awareness and spur discussion about how we might better integrate testing into our development workflow.
(See also [this discussion doc!](https://docs.google.com/document/d/18FyqT9Z6lW0vYimbVlhioBi6thCBLrEZOBPMGjdpBg0/edit?usp=sharing))

pytest-watch and --reuse-db for a quicker testing workflow

---

contentcuration/contentcuration/forms.py
contentcuration/contentcuration/serializers.py

Makes it easier for us to verify if someone has accepted our policies

Added policies to serializer

---

contentcuration/contentcuration/management/commands/setup.py

Added order to questions, assigned language to any multi-language files

Fixed setup command

---

contentcuration/contentcuration/static/js/edit_channel/image/views.js

Needed because of an issue Croppie had with webpack:
https://github.com/Foliotek/Croppie/issues/470
Looks like they might have fixed it in newer versions too :man_shrugging:

Hotfix: Fix Croppie

---

contentcuration/contentcuration/management/commands/loadconstants.py
contentcuration/contentcuration/management/commands/setup.py
requirements.txt

I gotta be the enforcer on this one.  The CI failed on this merge.  Looks like some tests need to be updated.

Revert "Use le-utils constant mappings for loadconstants method"

---

contentcuration/contentcuration/forms.py
contentcuration/contentcuration/static/less/settings.less
contentcuration/contentcuration/templates/registration/registration_information_email.txt
contentcuration/contentcuration/templates/registration/registration_information_form.html
contentcuration/contentcuration/templates/settings/account.html
contentcuration/contentcuration/templates/settings/storage.html
contentcuration/contentcuration/templates/settings/storage_request_email.txt
contentcuration/contentcuration/templatetags/license_tags.py
contentcuration/contentcuration/urls.py
contentcuration/contentcuration/views/settings.py
contentcuration/contentcuration/views/users.py
requirements_test.txt

User can now request storage from the Settings > Storage page, which will send an email to us notifying us of request

Added storage request form to Settings > Storage page

---

contentcuration/contentcuration/static/less/details.less

Instead of changing the stroke width, hovering on a pie slice will change the opacity

Change opacity on hover instead of stroke width

---

k8s/templates/studio-deployment.yaml

For better performance and more reliable upgrading.

give one whole CPU!! to the studio app

---

contentcuration/contentcuration/management/commands/exportchannel.py
contentcuration/contentcuration/management/commands/generate_usercsv.py
contentcuration/contentcuration/static/js/edit_channel/details/views.js

Even if celery fails, make sure user can try to publish again

Added finally statement to export channel code

---

contentcuration/contentcuration/views/files.py

No effect, uploading files is still slow.

Revert "disable mptt updates on file_Create, slows down everything!"

---

Pipfile.lock

Update our deps, to take advantage of the latest bug and security fixes

update python deps to their latest versions

---

contentcuration/contentcuration/tests/base.py
contentcuration/contentcuration/tests/test_createchannel.py
contentcuration/contentcuration/tests/test_garbage_collection.py
contentcuration/contentcuration/tests/testdata.py

Jordan, here are the changes I was making to the test infrastructure. I added in the bucket tweaks, let me know if this would work for you!

Test refactor

---

contentcuration/contentcuration/management/commands/setup.py
contentcuration/contentcuration/settings.py
contentcuration/contentcuration/test_settings.py
contentcuration/contentcuration/urls.py
contentcuration/contentcuration/views/files.py

So Kolibri servers can download content on Studio development servers.

Serve the content DB through Studio on debug mode

---

contentcuration/contentcuration/static/js/edit_channel/exercise_creation/views.js

This is a WIP, currently all it does is improves the validity check on the question content pulled from the model. This may not be enough to fix the problem, but should at least give us more insight into what is going wrong.
#892 
See steps listed in #892 

[WIP] Work on fix for question UI problem

---

contentcuration/contentcuration/views/internal.py

Otherwise exercises won't have images!

use default_storage for mapping assessment items

---

contentcuration/contentcuration/decorators.py
contentcuration/contentcuration/tests/base.py
contentcuration/contentcuration/tests/test_authentication.py
contentcuration/contentcuration/views/base.py
contentcuration/contentcuration/views/internal.py

Fixes channel URL handling and exercise and other file creation for ricecooker runs.

Develop to master

---

contentcuration/contentcuration/static/js/edit_channel/exercise_creation/views.js

Merge develop to master

---

contentcuration/contentcuration/tests/base.py

It's important to get enough sleep, but sleeping while testing isn't good!

Don't sleep for 5 seconds each time we create a bucket, pls. kthxbye

---

deploy/nginx.conf.jinja2

See #924 for the PR to develop

Hotfix: django-level caching for the channel endpoint

---

deploy/nginx.conf.jinja2

See #943 for the PR to develop

[Hotfix] nginx-level caching to the public channel and the user's editable channel endpoints

---

contentcuration/contentcuration/static/js/edit_channel/utils/string_helper.js
contentcuration/contentcuration/static/less/file-uploader.less
contentcuration/contentcuration/static/less/modal-styles.less

Perform in the following order

Updated translations with epub string

---

contentcuration/contentcuration/tests/test_gcs_storage.py
contentcuration/contentcuration/utils/gcs_storage.py

Merge and fix one failing test.

Master to develop merge

---

contentcuration/contentcuration/management/commands/restore_channel.py

Get query by sort order to reduce time

---

README.md

Adds install instructions for pre-commit

Update readme to include pre-commit hooks

---

contentcuration/contentcuration/templates/base.html

Gives us recording / playback capabilities for user sessions, which hopefully will help us troubleshoot some issues with the software.

Add FullStory integration.

---

PULL_REQUEST_TEMPLATE.md

Remove autoflagging from PR template - except for Radina (by request).
Add Micah and Kevin to PR template for reviewers.

Remove autoflagging from PR template - except for Radina.

---

contentcuration/contentcuration/tests/test_contentnodes.py
contentcuration/contentcuration/views/nodes.py

The `sync_files` operation was assuming that only a single file per per present would exist e.g. video_high_res, thumbnail, etc.
This assumption fails for subtitles, which all have preset `video_subtitles` and there are multiple of them, one for each language.
https://github.com/learningequality/studio/issues/1063
- Merge this PR into `develop`
- Go to [this video](https://develop.studio.learningequality.org/channels/9e5305326ed742d0892479dea825a514/edit/53b6269/ae31e04) and confirm it has only a single subtitle file
- Go to the [containing folder](https://develop.studio.learningequality.org/channels/9e5305326ed742d0892479dea825a514/edit/53b6269) and select the checkbox for this video
- Click `SYNC` button in top menu bar and make sure sync files is enabled
- Confirm video has more …

Fix for missing subs issue

---

contentcuration/contentcuration/tests/test_contentnodes.py
contentcuration/contentcuration/views/nodes.py

See https://github.com/learningequality/studio/pull/1082 for details.
This is a hotfix patch to fix https://github.com/learningequality/studio/issues/1063 in prod.

Hotfix to master for subs sync issue 

---

README.md

Added instructions for increasing listeners on Linux machine

Added linux instructions to readme

---

contentcuration/contentcuration/forms.py
contentcuration/contentcuration/templates/settings/storage.html

Updated storage form to use Django 1.11 field names

Storage hotfix

---

contentcuration/contentcuration/static/js/bundle_modules/base.js
contentcuration/contentcuration/templates/base.html

Addresses a couple more scenarios that shouldn't be generating Sentry error reports, namely 403 access denied errors, and cases where responseText isn't set for whatever reason.

Sentry ajax error handler tweaks

---

contentcuration/contentcuration/tests/test_gcs_storage.py
contentcuration/contentcuration/utils/gcs_storage.py

This is needed to publish files with empty thumbnails.

Check if the file we're uploading is not empty before we upload

---

.travis.yml
Pipfile
Pipfile.lock
README.md
package.json

Adds code coverage, so we can determine our current level of test coverage and increase it!
- yarn run services,  if you haven't started them
- yarn run unittests

Add code coverage to Studio

---

contentcuration/contentcuration/static/less/content-container.less
contentcuration/contentcuration/static/less/queue.less
contentcuration/contentcuration/templates/base.html
contentcuration/contentcuration/templates/channel_edit.html

This is a patch to the Channel Edit view more responsive.  
Addresses #1105 .
I used flexbox to make the Channel Edit toolbar more responsive, then used CSS `calc` to set the height of the tree list views.
This is more of a workaround than a fix.  A cleaner and more stable responsive layout will be easier to achieve once we refactor much of our interface to use Vue instead of Backbone, so that our DOM structure isn't dependent on our backbone logic.  Once our DOM is more flat, we should be able to get a truly responsive layout with much simpler CSS.

Channel edit page more responsive

---

contentcuration/contentcuration/static/less/content-container.less
contentcuration/contentcuration/static/less/queue.less
contentcuration/contentcuration/templates/base.html
contentcuration/contentcuration/templates/channel_edit.html

This is a hotfix for #1105.
See [here](https://github.com/learningequality/studio/pull/1136) for details...

Hotfix more responsive channel edit page

---

contentcuration/contentcuration/management/commands/migrate_preferences.py
contentcuration/contentcuration/management/commands/restore_channel.py
contentcuration/contentcuration/management/commands/setup.py
contentcuration/contentcuration/views/admin.py

Print statement to print function conversion. This is just some easy prep for a py 3 conversion, and wanted to get it in rather than let the branch rot. 

Python 3 support step 1: Convert from print statement to function.

---

contentcuration/contentcuration/serializers.py
contentcuration/contentcuration/static/js/edit_channel/channel_settings/views.js
contentcuration/contentcuration/static/js/edit_channel/exercise_creation/views.js
contentcuration/contentcuration/static/js/edit_channel/image/views.js
contentcuration/contentcuration/static/less/content-container.less
contentcuration/contentcuration/templates/base.html
contentcuration/contentcuration/tests/test_fileendpoints.py
contentcuration/contentcuration/tests/test_rest_framework.py
contentcuration/contentcuration/views/files.py

Staging into develop

---

contentcuration/contentcuration/static/js/edit_channel/queue/views.js
contentcuration/contentcuration/static/less/queue.less

Fixed problem where overflow on clipboard items was throwing the styling off
Before:
After:

Fixed clipboard list items

---

contentcuration/contentcuration/static/less/content-container.less
contentcuration/contentcuration/templates/channel_edit.html

Update "Show ID" button to "Show Token"
Addresses https://github.com/learningequality/studio/issues/883

Show token

---

contentcuration/contentcuration/static/less/channel_create.less

Fixed channel list alignment

---

.pre-commit-config.yaml
CHANGELOG.md
contentcuration/contentcuration/templates/export/channel_detail_pdf.html
contentcuration/contentcuration/templates/export/channel_detail_pdf_condensed.html
contentcuration/contentcuration/templatetags/export_tags.py
contentcuration/contentcuration/utils/export_writer.py

Reverts learningequality/studio#1198

Revert "Force pdfs to use font from font file"

---

CHANGELOG.md
contentcuration/contentcuration/static/js/edit_channel/archive/views.js
contentcuration/contentcuration/static/js/edit_channel/move/views.js
contentcuration/contentcuration/static/js/edit_channel/views.js

Fixes an issue where single items could not be restored in the trash dialog.

Fix individual item restore functionality in the trash dialog

---

k8s/images/app/Dockerfile

Uncache docker packages

---

contentcuration/contentcuration/permissions.py

Getting 403 errors when trying to edit channel collections as a non-admin user

Added channel set to permissions class

---

CHANGELOG.md
contentcuration/contentcuration/static/js/bundle_modules/base.js

Just a quick fix to ensure 404s and network errors (status code 0) return a descriptive error message on Sentry rather than the generic and unhelpful "error" message we get now.

Add descriptive error messages for 404s and network errors.

---

CHANGELOG.md

Removes duplicate "Unreleased" section and fix that was submitted to master instead

Remove duplicate section

---

package.json
yarn.lock

Added @vue/test-utils to dependencies (missing from vue migration PRs)

Added @vue/test-utils to dependencies

---

k8s/templates/_helpers.tpl
k8s/templates/celery-dashboard.yaml
k8s/templates/studio-deployment.yaml

I added some missing volume mounts to the dashboard pod. Along the way I refactored the volumes and volume mounts to a shared helper template.

Fixes to get the celery dashboard running

---

contentcuration/contentcuration/static/js/bundle_modules/sandbox.js
contentcuration/contentcuration/static/js/sandbox/Sandbox.vue
contentcuration/contentcuration/templates/base.html
contentcuration/contentcuration/templates/sandbox.html
contentcuration/contentcuration/urls.py
contentcuration/contentcuration/views/base.py
webpack.config.js

* Moves entry bundle JS to end of DOM body to allow easy attachment to a DOM node.
* Adds an extra bundle that acts as a sandbox for Vue components.

Adds a Vue component Sandbox

---

package.json
webpack.config.js
yarn.lock

Adds babel-polyfill to fix issues with undefined Symbol on IE. Note that IE is an unsupported browser, so this mostly just serves to stop the error reports from coming in.
Addresses #1352 

Add babel-polyfill to base JS module.

---

contentcuration/contentcuration/dev_settings.py

Adds a profile tab to the Django Debug Toolbar, which will tell you where the time was spent for page loads.

Django Debug Toolbar has a profiling panel. Let's use it.

---

contentcuration/contentcuration/static/js/bundle_modules/ChannelEditIndex.vue
contentcuration/contentcuration/static/js/bundle_modules/channel_edit.js
contentcuration/contentcuration/static/js/bundle_modules/channel_list.js
contentcuration/contentcuration/static/js/edit_channel/channel_list/mixins.js
contentcuration/contentcuration/static/js/edit_channel/channel_list/tests/channelEditor.spec.js
contentcuration/contentcuration/static/js/edit_channel/channel_list/tests/channelItem.spec.js
contentcuration/contentcuration/static/js/edit_channel/channel_list/tests/channelListPage.spec.js
contentcuration/contentcuration/static/js/edit_channel/channel_list/views/ChannelDetailsPanel.vue
contentcuration/contentcuration/static/js/edit_channel/channel_list/views/ChannelEditor.vue
contentcuration/contentcuration/static/js/edit_channel/channel_list/views/ChannelList.vue
contentcuration/contentcuration/static/js/edit_channel/channel_list/views/ChannelListPage.vue
contentcuration/contentcuration/static/js/edit_channel/channel_list/vuex/actions.js
contentcuration/contentcuration/static/js/edit_channel/channel_list/vuex/getters.js
contentcuration/contentcuration/static/js/edit_channel/channel_list/vuex/mutations.js
contentcuration/contentcuration/static/js/edit_channel/channel_list/vuex/store.js
contentcuration/contentcuration/static/js/edit_channel/router.js
contentcuration/contentcuration/static/less/channel_list.less
contentcuration/contentcuration/templates/channel_list.html
webpack.config.js

1. Adds Vue Router to the ChannelListPage (`channel_list` django template). Provides routing for different list types, as well as the channel detail panel.
1. Separates `channel_list` functionality from `channel_edit.js` bundle
1. 
- Ivan ivanistheone …

Manage Channel List Page with Vue Router

---

contentcuration/contentcuration/utils/export_writer.py

Fixed typo in string formatter
Addresses https://github.com/learningequality/studio/issues/1393

Fixed variable in string

---

contentcuration/contentcuration/static/js/edit_channel/exercise_creation/views.js

Fixed issue with exercise images not showing up
Addresses https://github.com/learningequality/studio/issues/1331

Fixed regex for exercise images

---

contentcuration/contentcuration/templates/settings/preferences.html
contentcuration/contentcuration/templates/settings/storage.html
contentcuration/contentcuration/templates/settings/tokens.html

Wait for jQuery to load, part 2

---

.travis.yml
Makefile
package.json

Title says it all! 
Addresses #1132 

Add code coverage reports to the CI build process.

---

contentcuration/contentcuration/api.py
contentcuration/contentcuration/tests/test_sushibar_endpoints.py
contentcuration/contentcuration/urls.py
contentcuration/contentcuration/views/internal.py
docs/api_endpoints.md

Removes some dead code so that people don't try to write tests for it. :)
Code is dead code, so should be no changes!

Test cleanup

---

contentcuration/contentcuration/tests/views/test_views_internal.py
contentcuration/contentcuration/views/internal.py

* Adds tests for the check_version endpoint
Fixes #1413

Add tests for internal check version endpoint.

---

contentcuration/contentcuration/tests/views/test_contentnode_views.py

Adds tests for get_nodes_by_ids, get_nodes_by_ids_complete, and get_nodes_by_ids_simplified. 
Addresses #1428

Add tests for the get_nodes_by_ids series of endpoints.

---

README.md

A couple doc tweaks that I made in response to setup issues that were reported. Apparently I forgot to push a PR for them!

Fix issues with Linux environment setup docs.

---

contentcuration/contentcuration/serializers.py
contentcuration/contentcuration/tests/views/test_contentnode_views.py
contentcuration/contentcuration/views/nodes.py

* Prefetches foreign keys.
* Removes unused property.

Modest optimizations for get_nodes_by_ids

---

Pipfile
Pipfile.lock
contentcuration/contentcuration/settings.py
contentcuration/contentcuration/urls.py

Adds Django Prometheus to produce a queryable metric report at /metrics.

Add django prometheus integration.

---

contentcuration/contentcuration/static/js/edit_channel/models.js

Fix for API call now returning proper JSON.

---

Makefile

Adds more threads as we do not seem to be fully utilizing CPU when fulfilling requests. Also make the numbers configurable via environment variables.

Increase number of threads on production

---

contentcuration/contentcuration/static/js/edit_channel/sharedComponents/ProgressOverlay.vue
contentcuration/contentcuration/static/js/edit_channel/sharedComponents/__tests__/progressOverlay.spec.js

The operation description indicates that the operation is in progress, so switch to a finished message when the operation completes.

Display an operation finished message when the operation completes.

---

.travis.yml

Workaround an issue where something is making stdout I/O non-blocking.

---

contentcuration/contentcuration/static/js/bundle_modules/base.js
contentcuration/contentcuration/static/js/edit_channel/sharedComponents/ProgressOverlay.vue

Merge network error tweaks to master

---

contentcuration/contentcuration/views/nodes.py

After observations at the hack session that the size calculation endpoint was very slow, attempt to reduce the time it takes.

Reduce permissions overhead where possible

---

contentcuration/contentcuration/static/js/edit_channel/import/views/ImportListItem.vue
contentcuration/contentcuration/static/js/edit_channel/import/vuex/importUtils.js
contentcuration/contentcuration/views/base.py

Optimizes the accessible channels endpoint by only returning precisely the data required and sidestepping DRF serialization.
- Go to a channel for which you have edit privileges.
- Attempt to import content.
- Confirm that you can import content.
Uses a single query to fetch all the data needed and only the data needed.
- Radina @radinamatic …

Accessible Channels Optimization

---

contentcuration/contentcuration/ricecooker_versions.py

Added comments to ricecooker file for future reference in updating versions

Added comments to ricecooker versions

---

contentcuration/contentcuration/views/base.py

* Forces Django to do a subquery on the channel filter to prevent a join on the returned queryset.

Accessible channels optimization optimization

---

contentcuration/contentcuration/tests/test_db_stats.py
contentcuration/contentcuration/utils/db_stats.py

Also switch channel stats to report total channel count.

Fix stats issue with key names and with extra spaces in some values.

---

contentcuration/contentcuration/forms.py
contentcuration/contentcuration/templates/policies/policy_accept.html
contentcuration/contentcuration/templates/registration/registration_information_form.html
contentcuration/contentcuration/templates/settings/preferences.html
contentcuration/contentcuration/templates/settings/profile.html
contentcuration/contentcuration/templates/settings/storage.html
contentcuration/contentcuration/templates/settings/tokens.html

Removed jquery from form templates as much as possible

Removed jquery from django form templates

---

contentcuration/contentcuration/forms.py
contentcuration/contentcuration/tests/test_db_stats.py
contentcuration/contentcuration/tests/testdata.py
contentcuration/contentcuration/utils/db_stats.py

Hotfix for stats PR for master.

Stats hotfix for master

---

contentcuration/contentcuration/static/js/edit_channel/tree_edit/views.js
contentcuration/contentcuration/static/js/edit_channel/vuexModules/asyncTask.js

Applies the task stacking calls change in develop as a hotfix to master.

Task stacking calls hotfix

---

contentcuration/contentcuration/views/users.py

Fixes https://github.com/learningequality/studio/issues/1013

Use https for emails

---

contentcuration/contentcuration/tests/test_asynctask.py
contentcuration/contentcuration/urls.py

Just pushes the task optimization PR to master. Ran some manual tests on develop and everything ran okay, so I think it's good to go!

Port task optimization PR to master

---

contentcuration/contentcuration/tests/test_makemessages.py

Only run makemessages test on CI server as it can alter committed files.

---

contentcuration/contentcuration/templates/registration/registration_information_form.html
contentcuration/contentcuration/templates/settings/storage.html

Fixes https://github.com/learningequality/studio/issues/1607

Switched to scrollTop for browser compatibility

---

Makefile

Remove migration check for now, as it is causing issues.

---

docker/Dockerfile.dev
k8s/images/app/Dockerfile

This PR upgrades studio's dockerfile to use bionic, and then the subsequent changes from there to get the docker image to build and work.

upgrade studio app docker image to bionic

---

contentcuration/contentcuration/utils/publish.py

Adds a delay_mptt_updates wrapper to publish code

Added delay_mptt_updates to publish command

---

.gitignore
Pipfile.lock

Used 
pipenv update
to update Pipfile.lock (goes to pypi and checks what are the latest version of packages that satify the "spec" in Pipfile) 
then manually selected only changes partial commit using
git add -p Pipfile.lock
____
other things I tried that didn't work (still updates all the package versions in Pipfile.lock)
1. `pipenv update --selective-upgrade le-utils`
2. `pipenv update --selective-upgrade --keep-outdated le-utils`

Update le-utils to latest version

---

contentcuration/contentcuration/static/js/edit_channel/exercise_creation/views.js
contentcuration/contentcuration/static/js/edit_channel/file_upload/hbtemplates/format_item.handlebars
contentcuration/contentcuration/static/js/edit_channel/preview/hbtemplates/preview_templates/video.handlebars
contentcuration/contentcuration/static/js/edit_channel/publish/views/PublishView.vue
contentcuration/contentcuration/static/js/edit_channel/sharedComponents/LanguageDropdown.vue
contentcuration/contentcuration/templates/export/channel_detail_pdf.html
contentcuration/contentcuration/templates/export/channel_detail_pdf_condensed.html
contentcuration/contentcuration/templates/settings/issues.html
contentcuration/contentcuration/utils/export_writer.py
contentcuration/contentcuration/views/internal.py

Fixes https://github.com/learningequality/studio/issues/1677

Minor fixes

---

contentcuration/contentcuration/settings.py
contentcuration/contentcuration/templates/base.html
contentcuration/contentcuration/templates/policies/policy_accept.html

When preparing demo servers I noticed a couple of problems probably related to our recent updates of bundling mechanism. Please see code comments.

Fix bundling issues

---

.eslintrc.js
Pipfile
Pipfile.lock
contentcuration/contentcuration/production_settings.py
contentcuration/contentcuration/settings.py
contentcuration/contentcuration/static/js/bundle_modules/base.js
contentcuration/contentcuration/templates/base.html
deploy/chaos/loadtest/locustfile.py
package.json
yarn.lock

Title says it all!
Note that right now I'm enabling the frontend errors for any *.studio.learningequality.org host, so that we can test it on develop at the bug bash. Afterwards, I'll submit a PR to limit it to production.

Switch from the legacy raven Sentry library to its current SDK.

---

contentcuration/contentcuration/management/commands/setup.py
deploy/chaos/loadtest/locustfile.py

Helpful change was added for bug in `yarn run devsetup`, so merging in.
https://github.com/learningequality/studio/pull/1748

Merge develop into vue-refactor

---

docs/architecture.md

* removed repeated links to external documentation for maintainability
* added bullet points
* relative paths
* shorter sentences

possible edits to docs

---

contentcuration/contentcuration/frontend/channelEdit/views/ChannelEditIndex.vue

Adds the new `GlobalSnackbar` component to the `ChannelEditIndex` components.
GlobalSnackbar and its Vuex module are available for use. 
Vuex module defined here: https://github.com/learningequality/studio/blob/vue-refactor/contentcuration/contentcuration/frontend/shared/vuex/snackbar/index.js it has a pretty simple API
In `ChannelEditIndex` add a `created` hook like:
```
created() {
this.$store.dispatch('showSnackbar', { text: 'Hello world.", actionText: "Goodbye" });
}
```
Then go to the Channel Edit Index - see the snackbar show up.
Do the same in a child view of the ChannelEdit routing section and navigate to it and see the snackbar showing up. 
It will then be ready for use!

Add globalsnackbar to channeleditindex

---

README.md

Added nodeenv command to documentation.
Fixes #1779 

Add nodeenv to documentation

---

contentcuration/contentcuration/static/js/administration/hbtemplates/channel_tab.handlebars
contentcuration/contentcuration/static/js/administration/views.js
contentcuration/contentcuration/tasks.py
contentcuration/contentcuration/templates/export/public_channels_email.txt
contentcuration/contentcuration/templates/export/public_channels_subject.txt
contentcuration/contentcuration/utils/channels.py
contentcuration/contentcuration/views/admin.py

Moves admin page Download pdf and Download csv actions to email workflow to avoid timeouts
Addresses https://github.com/learningequality/studio/issues/992
Addresses https://github.com/learningequality/studio/issues/772
Addresses https://github.com/learningequality/studio/issues/777

Moved admin page exporting formats to email workflow

---

contentcuration/contentcuration/utils/publish.py

The requirements fixes in earlier version of this PR were implemented in https://github.com/learningequality/studio/pull/1804/files#diff-a24204f7139342bdf2a7d7d13ca4dab0L22
so only small py3 fix remains
To make targeted edit of a specific package in requirements files:
1. delete the line you want to change in `requirements-dev.txt`  (otherwise it will stay pinned)
2. make the modification in `requirements-dev.in`
3. Run `pip-compile requirements-dev.in`. The result of this will be an updated `requirements-dev.txt`, which interestingly 
4. Commit the both `requirements-dev.txt` and `requirements-dev.in`
Unlike pipenv that updates ALL requirements versions, the Step 3 in the above will only update the files not pinned in requirements.txt so it's much easier to make isolated upgrades.

Minor py3 unicode fix to make yarn run devsetup work

---

package.json
webpack.config.js
yarn.lock

Changes our JS minification from uglify js to terser js

Change from uglify to terser.

---

contentcuration/contentcuration/viewsets/channel.py

Uses a subquery to determine the primary token of a channel.

~10x speed up of catalog endpoint

---

contentcuration/contentcuration/frontend/channelEdit/views/trash/TrashModal.vue
contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
contentcuration/contentcuration/viewsets/tree.py

There was an issue with the trash tree not loading because the tree viewset was filtering by the main_tree only

Fixed trash tree call

---

contentcuration/contentcuration/catalog_settings.py
contentcuration/contentcuration/frontend/channelList/router.js
contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogFilters.vue
contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogList.vue
contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelItem.vue
contentcuration/contentcuration/frontend/channelList/views/Channel/__tests__/catalogFilters.spec.js
contentcuration/contentcuration/frontend/channelList/views/ChannelListIndex.vue
contentcuration/contentcuration/frontend/channelList/vuex/channelList/actions.js
contentcuration/contentcuration/frontend/shared/views/channel/ChannelDetailsModal.vue
contentcuration/contentcuration/frontend/shared/views/details/Details.vue
contentcuration/contentcuration/frontend/shared/views/files/Thumbnail.vue
contentcuration/contentcuration/static/js/edit_channel/sharedComponents/LanguageDropdown.vue
contentcuration/contentcuration/templates/base.html
contentcuration/contentcuration/templates/channel_list.html
contentcuration/contentcuration/viewsets/channel.py

* Makes channel cards focusable when navigating by keyboard
* Added help text under the Includes checkbox items
* Removed exercises and topics from formats list
* Updated "Kolibri Library" on toolbar and tab title to "Kolibri Content Library"
* Added hover state to channel cards to indicate they are interactable
* Added header to channel details images
* Made search happen on change (debounced)
* Enabled tabbing through filter list
* Fixed responsive sizing to make filters hide on xsOnly
* Enable multiple language selections
* Added "Clear filters" button
* Retain channel details modal locations on refresh

Updates to catalog UI

---

docs/architecture.md

Whoever is here right now - I hope you're having a good day today!

Tiny PR :) (Add a note to architecture documentation)

---

contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogFilters.vue
contentcuration/contentcuration/frontend/channelList/views/ChannelListIndex.vue
contentcuration/contentcuration/frontend/channelList/vuex/channelList/actions.js
contentcuration/contentcuration/frontend/shared/analytics/tracker.js
contentcuration/contentcuration/frontend/shared/views/Pagination.vue
contentcuration/contentcuration/frontend/shared/views/PrimaryDialog.vue
contentcuration/contentcuration/frontend/shared/views/channel/ChannelDetailsModal.vue
contentcuration/contentcuration/frontend/shared/views/channel/ChannelTokenModal.vue
contentcuration/contentcuration/static/js/edit_channel/sharedComponents/LanguageDropdown.vue
contentcuration/contentcuration/static/js/edit_channel/views.js
contentcuration/contentcuration/templates/channel_list.html
contentcuration/contentcuration/viewsets/channel.py

(see commit messages for list of fixes)

Catalog UI fixes

---

contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/FormulasMenu/FormulasMenu.vue

Add translation strings for formulas editor symbols.
Closes #1850.

Add symbols translations

---

contentcuration/contentcuration/frontend/shared/data/resources.js

Fix resource filtering

---

contentcuration/contentcuration/frontend/shared/data/resources.js
contentcuration/contentcuration/viewsets/channel.py

One of the causes of query complexity is multiple joins - this can be reduced by reducing the amount of annotations over additional tables. This will not completely solve query complexity in channel queries, but will help to reduce the incidence of it.
* Only add filtering specific annotation for channels in the backend when needed.
* Allow filtering specific annotation to be applied in the frontend so that repeated queries through indexeddb will return the results.

Remove annotations unless required for filtering

---

contentcuration/contentcuration/viewsets/channel.py

Fixes regression caused by #1886

Don't load editor and viewer ids on catalog endpoint.

---

contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogFAQ.vue
contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogList.vue
contentcuration/contentcuration/frontend/shared/views/ExpandableList.vue
contentcuration/contentcuration/frontend/shared/views/Pagination.vue
contentcuration/contentcuration/frontend/shared/views/channel/ChannelDetailsModal.vue
contentcuration/contentcuration/frontend/shared/views/details/Details.vue
contentcuration/contentcuration/frontend/shared/views/details/DetailsRow.vue
contentcuration/contentcuration/models.py
contentcuration/contentcuration/tests/test_contentnodes.py

* Expandable list toggle text wasn't switching betwen `Show more` and `Show less`
* Sample content thumbnails were using deprecated default thumbnails

Fixed a couple of UI issues on the details modal

---

contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogFilters.vue
contentcuration/contentcuration/frontend/channelList/views/ChannelListIndex.vue
contentcuration/contentcuration/frontend/channelList/vuex/channelList/__tests__/module.spec.js
contentcuration/contentcuration/frontend/shared/data/resources.js
contentcuration/contentcuration/frontend/shared/views/channel/mixins.js
contentcuration/contentcuration/frontend/shared/vuex/channel/__tests__/module.spec.js
contentcuration/contentcuration/frontend/shared/vuex/channel/actions.js
package.json
yarn.lock

* Fix 403 errors on details modal by calling catalog endpoints directly
* Fix Firefox download csv option

Fixed firefox and permissions issues

---

contentcuration/contentcuration/frontend/channelList/index.js
contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogList.vue
contentcuration/contentcuration/frontend/shared/mixins.js
contentcuration/contentcuration/frontend/shared/utils.js
contentcuration/contentcuration/frontend/shared/views/ExpandableList.vue
contentcuration/contentcuration/frontend/shared/views/channel/ChannelCatalogFrontPage.vue
contentcuration/contentcuration/frontend/shared/views/channel/ChannelCatalogPrint.vue
contentcuration/contentcuration/frontend/shared/views/channel/ChannelDetailsModal.vue
contentcuration/contentcuration/frontend/shared/views/channel/__tests__/channelDetailsModal.spec.js
contentcuration/contentcuration/frontend/shared/views/channel/mixins.js
contentcuration/contentcuration/frontend/shared/views/details/Details.vue
contentcuration/contentcuration/frontend/shared/views/details/DetailsRow.vue
contentcuration/contentcuration/frontend/shared/views/files/Thumbnail.vue

Integrates client side catalog PDF generation into the user interface.

Client side generation interface integration

---

deploy/nginx.conf.jinja2

Reverts learningequality/studio#1880

Revert "Cherry-pick: in Nginx, block access to `/content/` root"

---

contentcuration/contentcuration/frontend/shared/data/applyRemoteChanges.js
contentcuration/contentcuration/frontend/shared/data/changes.js
contentcuration/contentcuration/frontend/shared/data/constants.js
contentcuration/contentcuration/frontend/shared/data/index.js
contentcuration/contentcuration/frontend/shared/data/mergeChanges.js
contentcuration/contentcuration/frontend/shared/data/resources.js
contentcuration/contentcuration/frontend/shared/data/serverSync.js
contentcuration/contentcuration/frontend/shared/vuex/channel/__tests__/module.spec.js
contentcuration/contentcuration/frontend/shared/vuex/channel/actions.js
contentcuration/contentcuration/urls.py
contentcuration/contentcuration/viewsets/base.py
contentcuration/contentcuration/viewsets/channel.py
contentcuration/contentcuration/viewsets/common.py
contentcuration/contentcuration/viewsets/sync/constants.py
contentcuration/contentcuration/viewsets/sync/endpoint.py
contentcuration/contentcuration/viewsets/user.py
yarn.lock

* Refactors Resource classes
* Unifies all changes into a single indexeddb table
* Adds a channel user viewset
* Stops annotating editor and viewer ids onto channels
Needs follow up to make editor/viewer editing on a channel work

Create a new mechanism for loading and editing many to many fields but don't quite apply it

---

contentcuration/contentcuration/frontend/shared/data/changes.js
contentcuration/contentcuration/frontend/shared/data/resources.js
contentcuration/contentcuration/frontend/shared/vuex/channel/mutations.js
contentcuration/contentcuration/viewsets/common.py

- Fix state overwriting content defaults with partial update
- Fix resource layer not merging content defaults
- Fix server viewset to parse HTML dot notation updates

Fix channel saving issues

---

contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSetModal.vue

Conditionalizes channel loading.

Only load channels for channelSets when there are channels to load

---

deploy/nginx.conf.jinja2

Conflict in nginx template, resolves solely in favour of master.

Merge master into develop

---

contentcuration/contentcuration/static/js/edit_channel/queue/views.js
contentcuration/contentcuration/static/js/edit_channel/views.js
contentcuration/contentcuration/static/js/utils/analytics.js
contentcuration/contentcuration/templates/administration.html
contentcuration/contentcuration/templates/base.html
contentcuration/contentcuration/templates/channel_edit.html
contentcuration/contentcuration/templates/channel_list.html
contentcuration/contentcuration/templates/channel_not_found.html
contentcuration/contentcuration/templates/exercise_edit.html
contentcuration/contentcuration/templates/exercise_list.html
contentcuration/contentcuration/templates/staging_not_found.html
contentcuration/contentcuration/templates/unauthorized.html
contentcuration/contentcuration/templates/unsupported_browser.html

In preparation for the launch of the new vue-refactored Studio, we'd like to ensure we have good tracking so we can benchmark the improvements when it's finally launched.

Google Tag Manager integration

---

contentcuration/contentcuration/dev_settings.py
contentcuration/contentcuration/not_production_settings.py
contentcuration/contentcuration/profile_settings.py
contentcuration/contentcuration/sandbox_settings.py
contentcuration/contentcuration/test_settings.py

Separate out base non production settings from test settings

Don't cross-contaminate settings.

---

contentcuration/contentcuration/static/js/edit_channel/channel_list/views/ChannelItem.vue
contentcuration/contentcuration/static/js/edit_channel/channel_list/views/ChannelListPage.vue
contentcuration/contentcuration/static/js/edit_channel/publish/views/PublishView.vue
contentcuration/contentcuration/static/js/edit_channel/queue/hbtemplates/queue_item.handlebars
contentcuration/contentcuration/static/js/edit_channel/queue/hbtemplates/queue_list.handlebars
contentcuration/contentcuration/static/js/edit_channel/sharedComponents/CopyToken.vue
contentcuration/contentcuration/static/js/edit_channel/tree_edit/hbtemplates/container_area.handlebars
contentcuration/contentcuration/static/js/edit_channel/tree_edit/hbtemplates/content_container.handlebars
contentcuration/contentcuration/static/js/edit_channel/tree_edit/hbtemplates/content_list_item.handlebars
contentcuration/contentcuration/static/js/edit_channel/uploader/hbtemplates/edit_metadata_dialog.handlebars
contentcuration/contentcuration/static/js/edit_channel/uploader/hbtemplates/edit_metadata_editor.handlebars

Added data-gtag attribute to all elements we'd like have the text available as our tracking labels in Google Tag Manager

Added data-gtag attribute to elements we're tracking in Google Tag Manager

---

contentcuration/contentcuration/static/js/edit_channel/import/vuex/importActions.js
contentcuration/contentcuration/static/js/edit_channel/models.js
contentcuration/contentcuration/static/js/edit_channel/queue/views.js
contentcuration/contentcuration/static/js/edit_channel/tree_edit/views.js
contentcuration/contentcuration/static/js/edit_channel/views.js
contentcuration/contentcuration/templates/administration.html
contentcuration/contentcuration/templates/base.html
contentcuration/contentcuration/templates/channel_edit.html
contentcuration/contentcuration/templates/channel_list.html
contentcuration/contentcuration/templates/channel_not_found.html
contentcuration/contentcuration/templates/exercise_edit.html
contentcuration/contentcuration/templates/exercise_list.html
contentcuration/contentcuration/templates/staging_not_found.html
contentcuration/contentcuration/templates/unauthorized.html
contentcuration/contentcuration/templates/unsupported_browser.html
contentcuration/contentcuration/views/base.py

- Adds a studio version to data layer for GA view separation
- Adds current user and current channel data to the data layer
- Adds analytics events for drag events on tree and clipboard
- Adds analytics events for task related operations
- Removes old analytics events

Analytics updates

---

k8s/helm-deploy.sh

This PR is to fix the issues introduced by my previous PR #1997 
- There was an inline comment in the helm arguments
- There was a missing backslash in the helm arguments

Fix helm argument error

---

contentcuration/contentcuration/utils/publish.py

Fix legacy empty extra_fields

---

contentcuration/contentcuration/frontend/shared/views/Icon.vue

There's [an issue in Vuetify < 2.5](https://github.com/vuetifyjs/vuetify/issues/3462) where sometimes the order of CSS asset imports can mess with `VIcon` alignment.  A workaround is to use the `important!` flag on the `.v-icon` `display` attribute.
Since we already have a custom `Icon` component wrapping `VIcon`, I put the style fix in there.
This fixes the clipboard icon alignment in the channel tree view.
Addresses #1964  …

Fix `Icon` component's icon alignment

---

.gitignore

see #2082 which is still valid

ignore Pipfile

---

contentcuration/contentcuration/settings.py
contentcuration/contentcuration/utils/sentry.py
contentcuration/contentcuration/viewsets/sync/endpoint.py

* Report PII to Sentry with Django integration
* Add first pass exception handling inside sync endpoint to prevent 500s

Error handling

---

package.json
yarn.lock

previously it was pinned to develop
cannot pin to the head of a repo because the hash changes often, messing up the cache

pin design system to latest stable

---

contentcuration/contentcuration/frontend/shared/data/resources.js
contentcuration/contentcuration/frontend/shared/vuex/channel/actions.js
contentcuration/contentcuration/viewsets/channel.py

Does synchronous creation on first create for a channel
Fixes #1872 and fixes #2026
* Create a channel
* Verify that it redirects you to the channel page and you don't get a 404
Adds a synchronous creation method to the Resource class and uses it for Channel creation.

Create channels synchronously

---

contentcuration/contentcuration/db/models/manager.py
contentcuration/contentcuration/management/commands/setup_perftest_data.py
contentcuration/contentcuration/utils/db_tools.py

* Uses Django bulk create and a future MPTT method to insert testing data into the DB faster
- Run setup_perftest_data management command
- Confirm that it correctly generates some test data
Use Django bulk create for DB insertion
Use MPTT method build_tree_nodes for tree generation
Use filename for Django file field to speed up File object generation

Generate trees faster for testing data

---

contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue

Fixes [this issue](https://www.notion.so/learningequality/Consider-making-Trash-a-location-not-an-action-458a7da249b8479e831c9c131b1ee0c4)

Moved open trash action to channel dropdown

---

contentcuration/contentcuration/frontend/channelEdit/components/move/MoveModal.vue
contentcuration/contentcuration/frontend/channelEdit/components/move/NewTopicModal.vue
contentcuration/contentcuration/frontend/channelEdit/components/move/__tests__/moveModal.spec.js

Fixes [this issue](https://www.notion.so/learningequality/Thumbnails-text-are-WAY-too-big-in-the-move-modal-and-it-s-hard-to-reorient-myself-to-what-I-was-do-745108b242c14734bb89501e0829561a)

Updated styling on move modal to be more compact

---

contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeEditListItem.vue
contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
contentcuration/contentcuration/frontend/channelEdit/constants.js
contentcuration/contentcuration/frontend/channelEdit/getters.js
contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
contentcuration/contentcuration/frontend/channelEdit/views/NodePanel.vue

Added comfortable view option

---

contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue

Added selection counts

---

contentcuration/contentcuration/context_processors.py
contentcuration/contentcuration/frontend/channelEdit/views/files/ContentRenderer.vue
contentcuration/contentcuration/frontend/channelEdit/views/files/FilePreview.vue
contentcuration/contentcuration/frontend/channelEdit/views/files/__tests__/contentNodeThumbnail.spec.js
contentcuration/contentcuration/frontend/channelEdit/views/files/__tests__/filePreview.spec.js
contentcuration/contentcuration/frontend/channelEdit/views/files/thumbnails/ContentNodeThumbnail.vue
contentcuration/contentcuration/frontend/shared/vuex/file/__tests__/module.spec.js
contentcuration/contentcuration/frontend/shared/vuex/file/getters.js
contentcuration/contentcuration/frontend/shared/vuex/file/utils.js
contentcuration/contentcuration/templates/base.html
docker-compose.yml
package.json

Tweaks are:
- compute the content storage url for a piece of content locally
- allow CORS for non-docker compose local development

Fix file previewing through various tweaks

---

contentcuration/contentcuration/utils/nodes.py

Fix issues with move tasks reporting complete before reindexing, and improve performance for the case where partial tree reindexing is more efficient.

Hotfixes -> master

---

contentcuration/contentcuration/serializers.py
contentcuration/contentcuration/tests/test_serializers.py
contentcuration/contentcuration/viewsets/base.py

Back merge master into develop
Explicitly adds __repr__ method to base.py serializers for safety.

Master into develop

---

contentcuration/contentcuration/templates/unsupported_browser.html

1. Simplifies `unsupported-browser.html` by removing the `base.html` parent template (with all the extra JavaScript). Fixes #1361 
1. Adds a style tag
1. Updates copy 
With new copy and self-contained styles. …

Simplify and style unsupported_browser.html

---

contentcuration/contentcuration/viewsets/base.py

* Prevents values viewsets from doing a repr call that might query a full DB table

Don't repr valuesviewsets.

---

contentcuration/contentcuration/frontend/channelEdit/components/AnswersEditor/AnswersEditor.vue
contentcuration/contentcuration/frontend/channelEdit/components/AssessmentEditor/AssessmentEditor.vue
contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemEditor/AssessmentItemEditor.vue
contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemPreview/AssessmentItemPreview.vue
contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemToolbar.vue
contentcuration/contentcuration/frontend/channelEdit/components/RelatedResourcesTab/RelatedResourcesTab.vue
contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
contentcuration/contentcuration/frontend/channelEdit/components/edit/EditView.vue
contentcuration/contentcuration/frontend/channelEdit/constants.js
contentcuration/contentcuration/frontend/channelEdit/translator.js
contentcuration/contentcuration/frontend/channelEdit/utils.js
contentcuration/contentcuration/frontend/channelEdit/views/files/ContentRenderer.vue
contentcuration/contentcuration/frontend/channelEdit/views/files/__tests__/contentNodeThumbnail.spec.js
contentcuration/contentcuration/frontend/channelEdit/views/files/supplementaryLists/SupplementaryList.vue
contentcuration/contentcuration/frontend/channelEdit/views/files/thumbnails/ContentNodeThumbnail.vue
contentcuration/contentcuration/frontend/shared/views/LanguageDropdown.vue
contentcuration/contentcuration/frontend/shared/views/LicenseDropdown.vue
contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/FormulasMenu/FormulasMenu.vue
contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/ImagesMenu/ImagesMenu.vue
contentcuration/contentcuration/frontend/shared/views/MasteryDropdown.vue
contentcuration/contentcuration/frontend/shared/views/VisibilityDropdown.vue

Addressing some of the quick fixes from the QA session
1. [Add some margin above "Achieving Mastery" in mastery criteria help dialog](https://www.notion.so/learningequality/Add-some-margin-above-Achieving-Mastery-in-mastery-criteria-help-dialog-9c18b2047f774245bd51c722c1b8ce9b)
2. [Answer checkbox for multiselect question needs to be primary color](https://www.notion.so/learningequality/Answer-checkbox-for-multiselect-question-needs-to-be-primary-color-032526ceda2740a3a7b1e1e3fccd8e0f)
3. [Small images in exercise image uploader should be centered](https://www.notion.so/learningequality/Small-images-in-exercise-image-uploader-should-be-centered-977b7f012fc34c8d8017d03c2b2ccba0)
4. [Edit question icon should align to top of container](https://www.notion.so/learningequality/Edit-question-ico …

Fixed various styling and functional issues on edit modal

---

contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogFAQ.vue

Allows multiple questions on FAQ page to be open at once
Fixes https://github.com/learningequality/studio/issues/2052

Don't close open questions when user clicks a question on catalog FAQ page

---

contentcuration/contentcuration/templates/base.html
contentcuration/contentcuration/viewsets/base.py
contentcuration/contentcuration/viewsets/sync/endpoint.py

This PR includes the following changes: 
* Filters the edit queryset to include the updated items only for bulk update
* Ensures that `valid_data` uses the mapped serializer data instead of the original change data passed in
* Sends an error report to Sentry when a single change in the `sync` call takes longer than 10 seconds.
* Sets the Sentry user data on the frontend when we have it. …

A couple misc. fixes

---

contentcuration/contentcuration/urls.py
contentcuration/contentcuration/utils/nodes.py

Merge move UX hotfixes to master 

---

contentcuration/contentcuration/viewsets/sync/endpoint.py

See above, hopefully this will help us get more data on slow sync operations.

Raise and handle sync error events to get Sentry to fill out the traceback

---

contentcuration/contentcuration/frontend/settings/pages/Account/index.vue
contentcuration/contentcuration/frontend/settings/pages/SettingsIndex.vue
contentcuration/contentcuration/frontend/settings/pages/Storage/index.vue
contentcuration/contentcuration/frontend/shared/views/CopyToken.vue
contentcuration/contentcuration/frontend/shared/views/files/FileStorage.vue
contentcuration/contentcuration/frontend/shared/views/files/Uploader.vue
contentcuration/contentcuration/frontend/shared/views/files/__tests__/fileStorage.spec.js
contentcuration/contentcuration/frontend/shared/vuex/session/index.js
contentcuration/contentcuration/models.py
contentcuration/contentcuration/serializers.py
contentcuration/contentcuration/urls.py
contentcuration/contentcuration/views/admin.py
contentcuration/contentcuration/views/base.py
contentcuration/contentcuration/views/settings.py
contentcuration/contentcuration/views/users.py
requirements.in
requirements.txt

* Does some small optimizations to space calculation
* Defers loading of space related (and token) data to increase page load times
* Cleans up unused Python code
Reduces page load bottleneck that was dependent on the DB
- Open the edit modal, confirm storage size shows
- Open settings page, confirm Account and Storage tabs load as expected

Somewhat optimize django page loading

---

contentcuration/contentcuration/frontend/channelEdit/components/AnswersEditor/AnswersEditor.vue

Just updating the string for the number field validation in the Answer Editor.

update numeric validation string

---

contentcuration/contentcuration/tests/viewsets/test_channel.py
contentcuration/contentcuration/tests/viewsets/test_contentnode.py
contentcuration/contentcuration/viewsets/common.py
contentcuration/contentcuration/viewsets/contentnode.py

* Replicates the content defaults selective update logic for ContentNode extra fields
* Fixes #2319
- Updating the Mastery Model should now persist

Fix nested field updates for extra_fields.

---

contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/__tests__/plugins/formulas/formula-html-to-md.spec.js
contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/__tests__/plugins/formulas/formula-md-to-html.spec.js
contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/__tests__/plugins/image-upload/image-html-to-md.spec.js
contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/__tests__/plugins/image-upload/image-md-to-html.spec.js
contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/image-upload/image-html-to-md.js
contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/image-upload/image-md-to-html.js
docs/markdown_editor_viewer.md

More specs and documentation for markdown editor

---

contentcuration/contentcuration/frontend/shared/data/resources.js

The parent transaction for assessment item deletion was missing the ContentNode table to allow it to update assessment item counts
This PR fixes this by doing assessment item count updating in a follow up transaction, not nested inside the same transaction
It also consolidates the logic into a single method to ensure consistency.

Fix assessment item deletion transaction error

---

contentcuration/contentcuration/models.py
contentcuration/contentcuration/tests/viewsets/test_channel.py
contentcuration/contentcuration/viewsets/channel.py

* Restores edit and view annotation for admin users on the channel viewset

Fix channel viewset for admins

---

contentcuration/contentcuration/tests/viewsets/test_channel.py
contentcuration/contentcuration/viewsets/channel.py

* Sets up admin channel filter set to only include fields that will be on the queryset

Fix admin channel filter fields to not filter by invalid fields.

---

contentcuration/contentcuration/tests/base.py
contentcuration/contentcuration/tests/viewsets/test_clipboard.py
contentcuration/contentcuration/viewsets/clipboard.py
contentcuration/contentcuration/viewsets/common.py

* Adds tests for the clipboard viewset
* Fixes bug where get_edit_queryset was undefined
* Fixes bug where extra_fields updates would be ignored
Fixes #2348 
- Ensure you can delete something from the clipboard

Clipboard fixes

---

contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue

* Adds string for inline copy status flagging

Add translation for copying status.

---

contentcuration/contentcuration/frontend/shared/data/serverSync.js

* Adds a boolean flag to indicate when a sync is in progress to prevent initiating another sync
- Make a change
- Make sure only one call to sync happens at once

Wait for syncing to finish before trying to sync again.

---

contentcuration/contentcuration/frontend/channelEdit/views/files/thumbnails/ContentNodeThumbnail.vue
contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogFilters.vue
contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelItem.vue
contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
contentcuration/contentcuration/frontend/shared/views/channel/ChannelThumbnail.vue
contentcuration/contentcuration/frontend/shared/views/details/Details.vue
contentcuration/contentcuration/frontend/shared/views/files/Thumbnail.vue
contentcuration/contentcuration/frontend/shared/views/form/MultiSelect.vue
contentcuration/contentcuration/templates/channel_list.html
contentcuration/contentcuration/views/base.py

Addresses the following:
* [Channel list item open in new tab icon is flipped](https://www.notion.so/learningequality/Channel-list-item-open-in-new-tab-icon-is-flipped-e8c0b9b17d4c43f8b133256a4334c7c6)
* [Need icon change for "View on Kolibri"](https://www.notion.so/learningequality/Need-icon-change-for-View-on-Kolibri-2d317cc832c1412291cd0bfeb4979ade)
* [Licenses filter dropdown isn't working](https://www.notion.so/learningequality/Licenses-filter-dropdown-isn-t-working-4ddeb819471644d3b604e0ea31d3c964)
* [Improve horizontal alignment of sample content labels](https://www.notion.so/learningequality/Improve-horizontal-alignment-of-sample-content-labels-a27a0204bc004d919bc0a0d15b368655)
* [Update channel thumbnail default view](https://www.notion.so/learningequality/Update-channel-thumbnail …

Channel list ui fixes

---

contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue

Fixed license and edit modal toolbar issue

---

contentcuration/contentcuration/settings.py
contentcuration/contentcuration/viewsets/common.py
contentcuration/contentcuration/viewsets/contentnode.py
contentcuration/search/viewsets/contentnode.py

* Reduces some fields in the ContentNode viewset annotations plus several unneded order by setnences
* Optimizes SearchContentNodeViewSet 
Searching in all the sections excepting Content Library now is usable. Searching in the whole content library is not (yet?)

Reduce unneded fields

---

contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeChangedIcon.vue
contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/detailsTabView.spec.js
contentcuration/contentcuration/frontend/channelEdit/views/NodePanel.vue
contentcuration/contentcuration/frontend/channelEdit/views/files/FileUploadItem.vue
contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/__tests__/actions.spec.js
contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/__tests__/getters.spec.js
contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/getters.js
contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/mutations.js
contentcuration/contentcuration/frontend/shared/data/applyRemoteChanges.js
contentcuration/contentcuration/frontend/shared/data/resources.js
contentcuration/contentcuration/frontend/shared/utils/helpers.js
contentcuration/contentcuration/frontend/shared/vuex/channel/actions.js
contentcuration/contentcuration/viewsets/contentnode.py

* Fixes a range of issues mostly stemming from improper local state preservation during syncing
* Ensures that move operations and create operations are properly reapplied to data returned from the backend
* Reverts previous work to propagate descendant annotations in IndexedDB and instead uses recursive Vuex getters
* Fixes issues with content node metadata not getting saved due to apparently flaky behaviour when doing a deep watch of the diffTracker object
* Does this by doing an explicit call to updateNotes to achieve autosave behaviour with a memoized debounced version of the function to debounce on a per node id basis
* Fixes an issue where file upload would attempt to access an id on a null object when an upload was in progress and not erroring
Fixes #2467
Fixes #2478
Fixes #2381 …

Fix data flow issues

---

contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue

Only adds a placeholder for individual items, will follow up in a separate PR with multiple items selected

Added placeholder for dragged item

---

contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/utils.js
contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSetModal.vue

Fix isNew references

---

contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/actions.js
contentcuration/contentcuration/frontend/shared/data/resources.js

* Prevent never syncing changes because of an illegal move

Throw a big error if try to move a child to be its own parent

---

contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeChangedIcon.vue
contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/BrowsingCard.vue
contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchResultsList.vue
contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.vue
contentcuration/contentcuration/frontend/channelEdit/views/files/FileUploadItem.vue
contentcuration/contentcuration/frontend/channelEdit/views/files/supplementaryLists/SupplementaryItem.vue
contentcuration/contentcuration/frontend/channelEdit/views/files/thumbnails/ContentNodeThumbnail.vue
contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogFilters.vue
contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelStar.vue
contentcuration/contentcuration/frontend/channelList/views/Channel/components/LanguageFilter.vue
contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
contentcuration/contentcuration/frontend/shared/views/channel/ChannelThumbnail.vue

Issues addressed:
* [I find it confusing that there's a "delete channel" button on the new channel edit modal](https://www.notion.so/learningequality/I-find-it-confusing-that-there-s-a-delete-channel-button-on-the-new-channel-edit-modal-c2162f6ac35b451e9602db01bbb58e2e)
* [Would be nice to have a snackbar confirmation when adding a channel to the starred list?](https://www.notion.so/learningequality/Would-be-nice-to-have-a-snackbar-confirmation-when-adding-a-channel-to-the-starred-list-abd170b9968042ab9a9d704ce21fac43)
* [Content Library → Search with "Languages" with "Assessments" clicked: Number in parenthesis after "language" does not match the number of results](https://www.notion.so/learningequality/Content-Library-Search-with-Languages-with-Assessments-clicked-Number-in-parenthesis-a …

String updates

---

.pre-commit-config.yaml
contentcuration/contentcuration/frontend/shared/views/__tests__/feedbackForm.spec.js
contentcuration/contentcuration/frontend/shared/views/errors/FeedbackForm.vue

Temporary fix for broken feedback form (replaces built-in form with embedded google form for non-admin users)

Embed a google form for submitting feedback for now

---

contentcuration/contentcuration/frontend/shared/styles/vuetify.css

Updates this CSS rule
```css
/deep/ .v-label.error--text {
-webkit-animation: none;
animation: none;
}
```
In `vuetify.css` To remove the 'shake' animation that is applied to the `label` whenever the input is invalidated. This was the only solution I could find after doing some research in Vuetify's issue tracker, since this animation is not controllable within the `props` for these components.
Fixes #2153
Here are GIFS from the "Create Account" form, which has all of the affected components except for `TextArea`.
Before GIF
After GIF
Modified the global vuetify.css stylesheet
- …

Disable ‘shake’ animation from VTextField and VTextArea

---

contentcuration/contentcuration/frontend/administration/pages/Channels/ChannelDetails.vue
contentcuration/contentcuration/frontend/administration/pages/Channels/ChannelTable.vue
contentcuration/contentcuration/frontend/administration/pages/Users/UserDetails.vue
contentcuration/contentcuration/frontend/administration/pages/Users/UserTable.vue
contentcuration/contentcuration/frontend/administration/router.js

Flattens `routes` array for administration/router.js
Fixes #2050

Flatten `routes` array for administration/router.js

---

contentcuration/contentcuration/templates/base.html

* Conditionalizes Sentry dependent code on Sentry being defined on window
* Initializes user specific variables outside of conditional tags to prevent references to uninitialized variables
Fixes #2634
Would fix an issue for Sentry being undefined, but we can't get Sentry reports of it!

Don't let errors happen when Sentry or user are not initialized.

---

contentcuration/contentcuration/frontend/accounts/pages/Create.vue
contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
contentcuration/contentcuration/frontend/channelEdit/components/RelatedResourcesList/RelatedResourcesList.vue
contentcuration/contentcuration/frontend/channelEdit/components/ResourcePanel.vue
contentcuration/contentcuration/frontend/channelEdit/components/move/MoveModal.vue
contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/BrowsingCard.vue
contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ChannelInfoCard.vue
contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ChannelList.vue
contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ContentTreeList.vue
contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchFilterBar.vue
contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchFilters.vue
contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchOrBrowseWindow.vue
contentcuration/contentcuration/frontend/channelEdit/views/files/supplementaryLists/SupplementaryItem.vue
contentcuration/contentcuration/frontend/settings/pages/Account/index.vue
contentcuration/contentcuration/frontend/settings/pages/Storage/RequestForm.vue
contentcuration/contentcuration/frontend/shared/views/Breadcrumbs.vue
contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownViewer/MarkdownViewer.vue
contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
contentcuration/contentcuration/frontend/shared/views/details/DetailsRow.vue
contentcuration/contentcuration/frontend/shared/views/form/MultiSelect.vue

Fixes the following issues reported at the last QA session:
* [Search icon needs notranslate class](https://www.notion.so/learningequality/Search-icon-needs-notranslate-class-8f923ae09a4a4efcac97001475a2f5ad)
* [Channel list in search filter should have notranslate class](https://www.notion.so/learningequality/Channel-list-in-search-filter-should-have-notranslate-class-0c910bbc538f4026a24d341d696ba207)
* [Channels that need to be deleted need notranslate class under delete account section](https://www.notion.so/learningequality/Channels-that-need-to-be-deleted-need-notranslate-class-under-delete-account-section-de33cab24d2b488fa9b246e95e9a292f)
* [Public channel question in storage request form need notranslate class](https://www.notion.so/learningequality/Public-channel-question-in-storag …

Minor translation/UI fixes

---

contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/actions.js
contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/getters.js

Incomplete resources validation

---

contentcuration/contentcuration/not_production_settings.py
contentcuration/contentcuration/tasks.py
contentcuration/contentcuration/views/settings.py
contentcuration/contentcuration/views/users.py
contentcuration/contentcuration/viewsets/channel.py

Fixes https://github.com/learningequality/studio/issues/1666
Fixes https://github.com/learningequality/studio/issues/2674

Pass request langauge code to task args

---

contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
contentcuration/contentcuration/frontend/channelEdit/views/progress/ProgressModal.vue
contentcuration/contentcuration/frontend/shared/data/resources.js
contentcuration/contentcuration/tasks.py

Fixes https://github.com/learningequality/studio/issues/2685
Fixes https://github.com/learningequality/studio/issues/2691

Publish fix

---

contentcuration/contentcuration/frontend/shared/views/details/Details.vue

Makes channel source thumbnails in channel details modal much cleaner

Standardized channel thumbnail styling

---

contentcuration/contentcuration/management/commands/fix_duplicate_assessment_items.py
contentcuration/contentcuration/models.py
contentcuration/contentcuration/templates/base.html
contentcuration/contentcuration/templates/updates.html

Fixes https://github.com/learningequality/studio/issues/2735

Added dedupe assessments command (+ back-merge from master)

---

contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue

Fixes thumbnail uploading/replacing
Fixes https://github.com/learningequality/studio/issues/2560

Add updateFile action back in

---

contentcuration/contentcuration/frontend/settings/pages/SettingsIndex.vue
contentcuration/contentcuration/frontend/shared/views/policies/PolicyModals.vue

Fixes double vertical scrollbar in Settings/About Studio and horizontal scrollbar in Settings/Account
Addresses #2712
Because Vuetify, [by default, turns on an html scrollbar](https://vuetifyjs.com/en/getting-started/frequently-asked-questions/#questions), I added `overflow:hidden` to the parent component to turn it off.
Similarly, I added `overflow-x:hidden` to the component that renders the content in `Account` so it doesn't have a horizontal scrollbar that appears when the window is resized and the user scrolls the the far left/right of the screen.
This might need to be revisited when we switch to KDS.
- Micah …

Fix double vertical scrollbar in Settings/About Studio and horizontal scrollbar in Settings/Account

---

cloudbuild-production.yaml

Use cloudbuild-production.yaml from develop

---

k8s/images/app/Dockerfile

With #2750 I accidentally copied develop's Dockerfile. This revives master's Dockerfile so things can build successfully again.

Revive old master dockerfile

---

contentcuration/contentcuration/management/commands/mark_incomplete.py

Make the mark incomplete command mark as True as well as False.

Mark incomplete false and true

---

contentcuration/contentcuration/frontend/channelEdit/views/files/ContentRenderer.vue
contentcuration/contentcuration/frontend/channelEdit/views/files/EpubRenderer.vue
contentcuration/contentcuration/frontend/channelEdit/views/files/FilePreview.vue

Fixes https://github.com/learningequality/studio/issues/949

Added epub renderer

---

contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelList.vue
contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue

Issue: 
Also fixed tab title on new channels

Fixed issue where creating a channel could open the sharing tab

---

contentcuration/contentcuration/viewsets/task.py

Consolidates task filtering with Channel permission methods for doing just that.

Consolidate task filter for channel

---

contentcuration/contentcuration/management/commands/fix_exercise_complete.py
contentcuration/contentcuration/management/commands/mark_incomplete.py

Updates mark_incomplete to use mastery_model
Makes a new management command to fix the residual completeness issues for exercises

Correct complete setting for exercises.

---

contentcuration/contentcuration/views/settings.py

Fixes https://github.com/learningequality/studio/issues/2822

Added deleted filter to settings channels

---

contentcuration/contentcuration/frontend/channelEdit/components/ResourcePanel.vue

Fixes https://github.com/learningequality/studio/issues/2798

Make sure actions on resource panel don't get pushed offscreen

---

contentcuration/contentcuration/management/commands/fix_exercise_complete.py

Properly chunk complete=True updating.
Add chunking for operations that might otherwise hold a long table lock.

Update for fix exercise complete to not skip nodes

---

contentcuration/contentcuration/management/commands/setup.py
contentcuration/contentcuration/utils/db_tools.py

Update the development setup script to reflect our `complete` validation strategy

---

contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelList.vue

Fixes https://github.com/learningequality/studio/issues/2814

Don't paginate starred channel list for more rapid updates

---

contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue

Fixes https://github.com/learningequality/studio/issues/2811

Don't close channel edit modal on "Keep editing" button click

---

contentcuration/contentcuration/frontend/channelEdit/components/publish/PublishModal.vue

Fixes https://github.com/learningequality/studio/issues/2799

Fixed typo in publish modal

---

contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue

Fixes https://github.com/learningequality/studio/issues/2551

Switched order in which incomplete and uploading node validation messages are shown

---

contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreePage/index.vue
contentcuration/contentcuration/frontend/shared/data/resources.js

Releases a fix for copying items to the clipboard.

Release 2021-02-01 B

---

contentcuration/contentcuration/frontend/shared/views/form/EmailField.vue
contentcuration/contentcuration/frontend/shared/views/form/__tests__/emailField.spec.js
contentcuration/contentcuration/models.py
contentcuration/contentcuration/tests/views/test_users.py

Adds frontend and backend implementation of trimming emails of whitespace before using for input.
Fixes #2942
Fixes #2943

Trim whitespace for email addresses

---

contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreePage/index.vue

This PR fixes a linter failure on develop (may be related to some conflicts [when merging hotfixes to develop](https://github.com/learningequality/studio/pull/2946)?)
Related to https://github.com/learningequality/studio/pull/2939

Fix a linter issue (RouterNames -> RouteNames)

---

.github/ISSUE_TEMPLATE/enhancement_template.md
.github/ISSUE_TEMPLATE/issue_template.md

Made updates to the issues templates based on feedback from our team.
N/A
___
Reviewers, please check to see if the changes reflect the notes you gave me.
___

Updates to issues templates

---

contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelList.vue
contentcuration/contentcuration/viewsets/channel.py

Merge down master

---

contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue

* Adds a defensive check when tagName is referenced in an event handler
1. Ensure that clicking on content tiles still works
Fixes #2844
----
PR process:
Testing:
___

Check event has a target before checking the target tagName.

---

contentcuration/contentcuration/viewsets/channel.py

* Removes use of regex in admin channels search
* Replaces with explicitly ORed Q filters doing an `icontains` match against each option
1. Go to admin page
2. Search channels
3. See results!
* Fixes #2920
----
PR process:
Testing:
___

Don't pass unsanitized inputs into regex.

---

contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogFAQ.vue

Updated the 'customContentAnswer' for catalog FAQ.
I figured this was low risk enough even for me to try it out... 😌 
cc @bjester since you self-assigned.
1. Step 1
2. Step 2
3. ...
Fixes #3080 
PR process:
Testing:
___

Update 'customContentAnswer' for catalog FAQ

---

contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogFAQ.vue

Follow-up from #3085.
...
?
___
[Slack conversation](https://learningequality.slack.com/archives/C0LK8QS9J/p1618860798235800).
----
PR process:
Testing:
___

Update 'customContentAnswer' in catalog FAQ

---

contentcuration/contentcuration/viewsets/channel.py

* Catches integrity errors when assigning an editor to a newly created channel
* Assuming this happens if the same change gets applied twice
All tests still pass
Fixes #3049
PR process:
Testing:
___

Catch duplicate editor assignment for newly created channels.

---

contentcuration/locale/CSV_FILES/contentcuration/locale/ar_SA/LC_FRONTEND_MESSAGES/contentcuration-messages.json
contentcuration/locale/CSV_FILES/contentcuration/locale/es_ES/LC_FRONTEND_MESSAGES/contentcuration-messages.json
contentcuration/locale/CSV_FILES/contentcuration/locale/fr_FR/LC_FRONTEND_MESSAGES/contentcuration-messages.json
contentcuration/locale/CSV_FILES/contentcuration/locale/hi_IN/LC_FRONTEND_MESSAGES/contentcuration-messages.json
contentcuration/locale/CSV_FILES/contentcuration/locale/pt_BR/LC_FRONTEND_MESSAGES/contentcuration-messages.json
contentcuration/locale/ar/LC_MESSAGES/contentcuration-messages.json
contentcuration/locale/es_ES/LC_MESSAGES/contentcuration-messages.json
contentcuration/locale/fr_FR/LC_MESSAGES/contentcuration-messages.json
contentcuration/locale/hi_IN/LC_MESSAGES/contentcuration-messages.json
contentcuration/locale/pt_BR/LC_MESSAGES/contentcuration-messages.json

Copies existing translations for new "Close" button label
Resolves: https://github.com/learningequality/studio/issues/3122
----
___

Copy translations for close button label

---

contentcuration/contentcuration/models.py

We were not checking if a user is anonymous before checking if they were an admin. This fixes that.
1. Go to catalog without being logged in
2. Look at a channel detail
Fixes #3144 
----
PR process:
Testing:
___

Check if user is anonymous before checking if admin.

---

contentcuration/contentcuration/utils/pagination.py

* Fixes regression where additional distinct after the final filtering post-pagination was removed
* Adds distinct back in
1. Go to Users interface in admin
2. Search for a user by name, where that user is an editor of more than one channel
3. Verify that the user does not get listed more than once
___
----
PR process:
Testing:
___

Call DISTINCT after filtering queryset by ids from pagination

---

integration_testing/features/create-a-collection.feature
integration_testing/features/delete-a-collection.feature
integration_testing/features/edit-a-collection.feature

Adding:
create-a-collection.feature
edit-a-collection.feature
delete-a-collection.feature

Gherkin scenarios for channel collections

---

contentcuration/contentcuration/tasks.py
contentcuration/contentcuration/tests/test_asynctask.py

* Counts a not found content node as a successful deletion
* Adds tests for deletion of existent and non-existent nodes
Fixes #3203 
----
PR process:
Testing:
___

Don't error if trying to delete a contentnode that doesn't exist.

---

.github/workflows/frontendlint.yml

* Augments the frontend linting github action to auto-format and push changes

Push automated code fixes.

---

contentcuration/contentcuration/frontend/shared/vuex/channel/actions.js

Gets rid of superfluous await and return on `context.commit` which is synchronous and returns nothing.
https://deepsource.io/gh/learningequality/studio/issue/JS-0111/occurrences?page=1
----
PR process:
Testing:
___

Don't await synchronous function

---

contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/MarkdownEditor.vue

Implements recommended performance improvement from https://deepsource.io/gh/learningequality/studio/issue/JS-D007/occurrences?page=1
Uses regex test instead of match when the results of the match are not needed
Does Markdown editing still work as expected?
From reading the code, this seems very low risk to me (except that when I originally changed the code, I just changed `match` to `test`, but had to change it so that I was calling the method on the regexp, rather than the string).
----
PR process:
Testing:
___

Use regex test instead of match for existence

---

contentcuration/contentcuration/tasks.py

* Catch DoesNotExist error when deletion actually happens, in case it has happened in parallel to the task.
Fixes #3203 
----
PR process:
Testing:
___

Catch contentnode doesnotexist during deletion as well as before.

---

contentcuration/contentcuration/frontend/channelEdit/components/AddRelatedResourcesModal.vue

* Fixes improperly formatted inline style by adding appropriate spacing
1. Resource drawer for Add Related Resources is properly proportioned
Fixes https://sonarcloud.io/project/issues?id=learningequality_studio&open=AXqNhqKhE0xM7HAtZYRB&resolved=false&severities=BLOCKER&types=BUG
----
PR process:
Testing:
___

Add spaces in calc expression to allow parsing.

---

contentcuration/contentcuration/frontend/shared/app.js

* Verifies the origin of the event matches the current origin before responding to it.
1. Logout and navigation away is unchanged
Fixes the vulnerability reported here: https://sonarcloud.io/project/issues?id=learningequality_studio&open=AXqNhqD5E0xM7HAtZYPL&resolved=false&types=VULNERABILITY
----
PR process:
Testing:
___

Fix cross-origin event listener vulnerability.

---

contentcuration/contentcuration/management/commands/garbage_collect.py
contentcuration/contentcuration/settings.py
contentcuration/contentcuration/utils/garbage_collect.py

* Added more logging to the garbage collection utilities and management command
* Catches an error that seems to happen during deletion of orphanage nodes
* Uses timezone aware datetime to prevent warning
1. Ran the garbage_collect management command
```
Cleaning up contentnodes from the orphan tree
INFO:command:Cleaning up contentnodes from the orphan tree
INFO:root:Deleted 0 node(s) from the orphanage tree
Cleaning up deleted chef nodes
INFO:command:Cleaning up deleted chef nodes
Cleaning up feature flags
INFO:command:Cleaning up feature flags
Cleaning up tasks
INFO:command:Cleaning up tasks
INFO:root:Deleted 0 successful task(s) from the task queue
```
----
PR process:
Testing:
___

Catch errors, prevent warning, and add more logging to garbage collection

---

k8s/templates/garbage-collect-cronjob.yaml

* I think the command was just being echoed, not run?

Update garbage collect command to match other jobs

---

contentcuration/contentcuration/frontend/shared/data/index.js

Update had an error, function was never invoked.
Fixes #3266

Invoke elector die function rather than just referencing it.

---

contentcuration/contentcuration/utils/minio_utils.py
requirements-dev.in
requirements-dev.txt

**:warning: First, test this PR with python 3.6 enviornment and then only merge it.:warning:** 
`minio` was pinned to `3.0.3` which is incompatible with python versions above 3.6. This PR upgrades the `minio` dependency to its latest major. There has been a lot of breaking changes since then, so, suitable changes has been made to make Kolibri studio work with `minio 7.1.1`.
I tested setting up Kolibri studio on python 3.9 and its working absolutely fine.  
___
To test these changes the reviewer should setup Kolibri studio on python 3.6 and then on version python 3.9. Kolibri studio should work on both the python versions without any dependency conflicts.  
Yes, we must test this PR with python 3.6 enviornment as I can't install python 3.6 on my machine due to Ubuntu 21.10 reasons.
Closes …

chore: minio 3.0.3 -> 7.1.1

---

package.json
yarn.lock

Updates the commit hash to the latest version 1.3.0, which allows the changes made in support for 0.15 (i.e. learning activities) are now available on Studio
PR process:
Testing:
___

Update kds version to latest release v1.3.0

---

contentcuration/contentcuration/models.py

- On @vkWeb's [postgresql 12 upgrade PR](https://github.com/learningequality/studio/pull/3333), I was able to reproduce the issue we've been experiencing with Github action python tests stalling
- I was able to identify that postgres was busy running a query related to storage calculations
- The query needed optimization, and this does enough to prevent the issue for now
Run the full test suite
___
----
PR process:
Testing:
___

Use EXISTS strategy for better performance

---

contentcuration/contentcuration/frontend/settings/pages/Storage/index.vue

Resolves #3285 
Changed way storage is calculated in User's own settings.
Tested with the current storage fill i have 2 B out of 524 MB counts em out correctly
Cant test changes cause my upload process seems to be bugged.
Screenshots (if applicable)
[image](https://user-images.githubusercontent.com/71641765/160635875-ee64efa8-2f1e-4ee9-a640-94bd8e1aca8b.png)
Does this introduce any tech-debt items?
There seems to be another type of calculation done in FIleStorage. Don't know if we need to consolidate.
Are there any risky areas that deserve extra testing?
Test storage increase and decrese. 
References
My reference for the change.
https://developers.google.com/web/updates/2017/08/estimating-available-storage-space)
Comments
There are a lot of errors when I fixed this.
PR process: …

#3285:Sorted issue by referencing google design

---

README.md

change the command to run the celery, avoiding the connection refusing error.
1. Step 1
2. Step 2
3. ...
___
----
PR process:
Testing:
___

Update README.md celery cmd changed i.e. 'yarn run celery'

---

.github/workflows/pythontest.yml
.pre-commit-config.yaml
README.md
contentcuration/contentcuration/apps.py
contentcuration/contentcuration/management/commands/setup.py
contentcuration/contentcuration/utils/minio_utils.py
contentcuration/contentcuration/utils/storage_common.py
docker-compose.yml
docs/manual_setup.md
package.json
requirements-dev.in
requirements-dev.txt
requirements.in
requirements.txt
yarn.lock

Cherry picks of #3271, #3300, #3311, #3333, and #3349 to hotfixes to attempt to fix builds/deployment.
Supersedes #3396

Deployment relevant cherry picks for hotfixes

---

docker-compose.yml

Similarly to https://github.com/learningequality/studio/pull/2777, this PR fixes files preview and upload locally, but this time when services are run via Docker. It does so by adding `http://127.0.0.1:8080` address to `MINIO_API_CORS_ALLOW_ORIGIN` Docker configuration (therefore it matches our [minio configuration in package.json](https://github.com/learningequality/studio/blob/unstable/package.json#L35) used we running services without Docker). This fixes the `No 'Access-Control-Allow-Origin' header is present on the requested resource.` CORS error:
1. Navigate to a channel
2. Open the side panel of a document resource that has some files and see that the file preview is rendered and there is no CORS error in the console
PR process:
Testing:
___

Fix files on localhost when services are run via Docker

---

contentcuration/contentcuration/models.py

Immediately returns `True` for a user space check if the user is an admin

Add admin trap door for space checks.

---

Makefile

Needed for setting up dummy cronjob

Add makefile target for set_file_duration command

---

Makefile

Adds makefile target for cronjob

Add makefile target for set_default_learning_activities

---

.github/dependabot.yml
runtime.txt

Follows instructions here: https://github.com/dependabot/dependabot-core/issues/4062 for pinning the Python version for dependabot upgrades
Adds a dependabot.yml file to configure automated dependency upgrades.

Attempt to do automated dependency upgrades.

---

contentcuration/contentcuration/utils/nodes.py
contentcuration/contentcuration/views/internal.py

Adds support for ricecooker to set duration property on files and suggested_duration on ContentNodes.

Add support for file duration and node suggested duration for ricecooker

---

contentcuration/contentcuration/settings.py

> I just got an email from Postmark stating that they're deprecating API calls via HTTP, and that we have to switch to HTTPS. Seems we have until November 30th.
Updates settings to enable `POSTMARK_SSL` according to [this code](https://github.com/dstufft/django-postmark/blob/master/postmark/backends.py#L23)
https://learningequality.slack.com/archives/C0WHZ9FPX/p1662161093351529
----
PR process:
Testing:
___

Use SSL for Postmark API

---

contentcuration/contentcuration/frontend/shared/vuex/session/index.js

This pr removes "[`first_name: 'Guest'`](https://github.com/learningequality/studio/blob/unstable/contentcuration/contentcuration/frontend/shared/vuex/session/index.js#L10)" as there is no implemented use of it within studio. It also reverts the code back to its old state prior to the string translation changes.
NA
No
___
Closes https://github.com/learningequality/studio/issues/2619
----
PR process:
Testing:
___

Removes guest string

---

contentcuration/contentcuration/frontend/channelEdit/components/edit/EditView.vue

- String extraction is complicated when using variables for string keys, so this removes those and creates JSDoc references instead to maintain references to those variables
https://learningequality.slack.com/archives/C0LE9NLCE/p1662595256874999
----
PR process:
Testing:
___

Don't use variables for string keys

---

contentcuration/contentcuration/frontend/administration/pages/Channels/ChannelActionsDropdown.vue

This PR fixes the view editors display
#2886
PR process:
Testing:
___

fix_editor_display

---

Makefile

- `compilemessages` is failing because of the following error, and `collectstatic` is run through infra magic
```
CommandError: Can't find msgfmt. Make sure you have GNU gettext tools 0.15 or newer installed.
```
----
PR process:
Testing:
___

Remove all make dependencies since they weren't being run anyway

---

contentcuration/contentcuration/settings.py
deploy/nginx.conf.jinja2

- In reviewing @ozer550's work, I seemed to have missed the Redis connection settings being `localhost` which won't work in production
- Adds sensible changes for proxy http version and turns off gzip on the ws location
----
PR process:
Testing:
___

Fix redis connection trying localhost in deployment

---

contentcuration/contentcuration/viewsets/base.py

- I've looked into [this issue](https://github.com/learningequality/studio/issues/3526) and I confirm that it is reproducible, but currently it's hard to see what's going wrong
- This fixes an issue in capturing the error and traceback of fake tasks like copying so I can better debug the referenced issue
https://github.com/learningequality/studio/issues/3526
----
PR process:
Testing:
___

Fix traceback handling for fake tasks

---

contentcuration/contentcuration/frontend/channelEdit/views/progress/ProgressModal.vue

- Hides the channel's published status while showing the sync progress in the header
| --- | --- |
| ![Screenshot from 2022-10-05 10-32-57](https://user-images.githubusercontent.com/819838/194125836-ddcb09bc-3afc-476b-99c2-00d8b9524d38.png) | ![Screenshot from 2022-10-05 10-32-38](https://user-images.githubusercontent.com/819838/194125855-86839cbc-d8a6-4f87-95e8-e07d8c2f675c.png) |
Refers https://github.com/learningequality/studio/issues/3710
----
PR process:
Testing:
___

Hide published status when showing sync progress

---

contentcuration/contentcuration/frontend/shared/data/resources.js

The [logic](https://github.com/learningequality/studio/blob/5789d29f00f94e7f0bdf475b9eee347add22d0fc/contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/utils.js#L26) for determining whether a folder has new or updated descendants checks the children's status on whether it has changed, or has new/updated descendants if it's a folder. In the case when not all descendants haven't been loaded into the frontend, the logic may not properly represent a folder's published state. This PR updates the publish logic to not only mark all nodes as published, but to also reset the `has_new_descendants` and `has_updated_descendants` flags.
1. Create a new channel
2. Add a folder `Folder A` and a resource to the channel root
3. Add 2 more levels of folders inside `Folder A`, `B` inside …

Reset new/updated descendant flags on publish

---

contentcuration/contentcuration/utils/celery/tasks.py

- Adds logging around task `fetch_or_enqueue` functionality to determine the cause for this [Sentry error](https://sentry.io/organizations/learningequality/issues/3491890256/?environment=hotfixes&project=1252819&query=is%3Aunresolved)
1. Ran Studio and enqueued tasks
https://sentry.io/organizations/learningequality/issues/3491890256/?environment=hotfixes&project=1252819&query=is%3Aunresolved
----
PR process:
Testing:
___

Add logging around task fetching and requeuing

---

contentcuration/locale/ar/LC_MESSAGES/contentcuration-messages.csv
contentcuration/locale/ar/LC_MESSAGES/django.po
contentcuration/locale/es_ES/LC_MESSAGES/contentcuration-messages.csv
contentcuration/locale/es_ES/LC_MESSAGES/django.po
contentcuration/locale/fr_FR/LC_MESSAGES/contentcuration-messages.csv
contentcuration/locale/fr_FR/LC_MESSAGES/django.po
contentcuration/locale/hi_IN/LC_MESSAGES/contentcuration-messages.csv
contentcuration/locale/hi_IN/LC_MESSAGES/django.po
contentcuration/locale/pt_BR/LC_MESSAGES/contentcuration-messages.csv
contentcuration/locale/pt_BR/LC_MESSAGES/django.po

Pulled from Crowdin, incl the extracted messages CSV as well.

Translations from unstable

---

contentcuration/contentcuration/viewsets/channel.py

- The `demo_server_url` was likely unintentionally removed from the `values` for the `CatalogViewSet`
- The response from this endpoint is cached, but this data shouldn't be sensitive to changes in user authentication
1. First, set a `demo_server_url` for a channel in your local database:
```bash
$ python contentcuration/manage.py shell
Python 3.9.13 (main, Sep 12 2022, 13:34:59) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from contentcuration.models import Channel
>>> c = Channel.objects.filter(pk='<channel_id>').update(demo_server_url='http://localhost:8000')
```
2. Flush the redis cache: `redis-cli -n 1 flushall`
3. Open Studio's public channels page as an anonymous user
4. Verify the kebab 3-dot menu is …

Add demo server URL to catalog response

---

contentcuration/contentcuration/frontend/shared/client.js

* Uploads error as attachment to sentry event

Upload error as attachment.

---

contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ChannelList.vue
contentcuration/contentcuration/frontend/shared/client.js
contentcuration/contentcuration/viewsets/channel.py

This is a patch release to further address query performance issues with the 'My Channels' page
| PR | Issues | Category | QA Focus |
| --- | --- | --- | --- |
| #3839 | #3835 | Bug fix | 'My Channels' view and channel publishing |

Patch release v2022.11.23

---

package.json
yarn.lock

This PR aims to fix #3922 
Added .git suffix to the aphrodite fork as no resolvers exist for the incomplete url we had in our package.json
1. edited the package.json
2. ran `yarn install`
3. observed the install to run without the aforementioned errors
Please do let me know if the same should be done in the yarn.lock file as well
PR process:
Testing:
___

package.json - added .git suffix to aphrodite fork

---

contentcuration/contentcuration/settings.py
contentcuration/contentcuration/urls.py
contentcuration/kolibri_public/admin.py
contentcuration/kolibri_public/apps.py
contentcuration/kolibri_public/models.py
contentcuration/kolibri_public/tests.py
contentcuration/kolibri_public/views.py

This is a work in progress. Do not merge!
1. Step 1
2. Step 2
3. ...
___
closes #3927
----
PR process:
Testing:
___

 A new Django app for housing Kolibri-specific public APIs (work in progress) 

---

contentcuration/contentcuration/frontend/shared/data/resources.js

Set missing user_id on change related with ChannelSet.
1. Created a collection
2. Tried to delete it.
3. Collection gets deleted!
PR process:
Testing:
___

Add user_id to ChannelSet object

---

contentcuration/contentcuration/static/feature_flags.json

Updates schema of feature_flag.json for AI features.
___
* closes #4023  
----
PR process:
Testing:
___

Adds 'ai_feature' flag to schema

---

contentcuration/contentcuration/viewsets/file.py

Adds a defensive check for when duration is less than or equal to 0.
1. Upload a 0 duration file.
2. Check whether the response is a 4xx.
___
Does manual verification checks out green?
Refers https://github.com/learningequality/studio/issues/4021.
@ozer550 will add frontend validation that will fully close https://github.com/learningequality/studio/issues/4021.
----
PR process:
Testing:
___

Defensive file duration check

---

contentcuration/contentcuration/tests/viewsets/test_file.py

Test for zero duration File upload returning a 400 status code.
Added a test for this edge case.
1. Ran the test
PR process:
Testing:
___

Add test for zero duration file upload

---

contentcuration/contentcuration/frontend/shared/data/serverSync.js

* Instantiates a vue object in serverSync.js in order to use its $watch method
1. Ensured that no error occurred when first opening Studio, due to the $watch invocation
2. Ensured that a change subsequently synced upon making an edit
Fixes #4103
PR process:
Testing:
___

Use an instantiated vue object to reference $watch from for ESM compatibility

---

contentcuration/kolibri_public/management/commands/export_channels_to_kolibri_public.py

* Catches all errors when trying to republish problem channels too

Catch any and all errors in exporting channels.

---

contentcuration/contentcuration/frontend/administration/mixins.js

Fixes #4249 
After adding any kind of filter the `descending` query param was returning value as a string like 'true' or 'false'. Due to this the expression `params.descending?` was always evaluated as true and adding `-` to ordering param.
PR process:
Testing:
___

fix ordering issue

---

contentcuration/automation/admin.py
contentcuration/automation/apps.py
contentcuration/automation/models.py
contentcuration/automation/tests.py
contentcuration/automation/views.py
contentcuration/contentcuration/dev_settings.py
contentcuration/contentcuration/frontend/channelEdit/components/AssessmentEditor/AssessmentEditor.vue
contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemEditor/AssessmentItemEditor.vue
contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
contentcuration/contentcuration/frontend/channelEdit/components/edit/EditView.vue
contentcuration/contentcuration/frontend/shared/constants.js
contentcuration/contentcuration/frontend/shared/leUtils/FormatPresets.js
contentcuration/contentcuration/frontend/shared/leUtils/Languages.js
contentcuration/contentcuration/frontend/shared/views/ContentNodeIcon.vue
contentcuration/contentcuration/frontend/shared/vuetify/theme.js
contentcuration/contentcuration/frontend/shared/vuex/file/__tests__/module.spec.js
contentcuration/contentcuration/frontend/shared/vuex/file/actions.js
contentcuration/contentcuration/frontend/shared/vuex/file/utils.js
package.json
requirements.in
requirements.txt
yarn.lock

Merges latest unstable into transcription branch

Merge latest unstable into transcription branch

---

contentcuration/contentcuration/tests/utils/test_cloud_storage.py
contentcuration/contentcuration/utils/cloud_storage.py

Implements the backend boilerplate for CloudStorages like GCS, AWS S3, etc.
- Class for CloudStorage Backend.
- Tests for CloudStorage Backend. 
Code Review
closes #4285 
PR process:
Testing:
___

Add CloudStorage backend boilerplate

---

.github/workflows/containerbuild.yml
docker-compose.yml
docker/Dockerfile.postgres.dev

- Adds GitHub workflow that builds the postgres image with pg vector installed
1. Pushed and saw the workflow passed
___
Push or merge PRs on Github. 
PR needs to be merged in order to test updates to docker-compose.yml
https://github.com/learningequality/studio/issues/4341
----
PR process:
Testing:
___

Add GH workflow for building postgres image

---

.github/workflows/containerbuild.yml

The container build should skip pushing images during a PR so it only tests building them, but in combo with deduplication of action tasks, that caused this to not run after a merging https://github.com/learningequality/studio/pull/4362
https://github.com/learningequality/studio/issues/4341
----
PR process:
Testing:
___

Disable skip after success, b/c push skip on PR

---

docker-compose.yml

- Corrects issue where the image declaration (mostly for tagging) was in the wrong spot in `docker-compose.yml`
https://github.com/learningequality/studio/pull/4362
Closes https://github.com/learningequality/studio/issues/4341
----
PR process:
Testing:
___

Fix issue with image in wrong place

---

contentcuration/contentcuration/frontend/shared/views/form/CountryField.vue

Fixes #4352 
Removed `@change="searchInput = ''"` and introduced a timeout of 1ms in clearing the search input box whenever the user has selected a particular country. The issue that occurred may have been because of asynchronous nature.
1. On the login page, click on create an account CTA.
2. Fill in all details on the signup page.
3. For the "Where do you plan to use Kolibri Studio? (check all that apply)*", search India, and check the checkbox.
Now search another country, and you will notice that the checkboxes state is being managed correctly now.
https://github.com/learningequality/studio/assets/72318730/a20deeb7-ff57-46c6-8284-a5a56d5576f9
___
----
PR process:
Testing:
___

Fixes Checkbox issue 4352 on Create Account page

---

contentcuration/contentcuration/frontend/shared/views/FullscreenModal.vue

Added beforeDestroy hook to ensure the HTML scroll is restored when the component is destroyed.
Added the beforeDestroy lifecycle hook in the component.
In the beforeDestroy hook, the hideHTMLScroll(false) is called to restore the HTML scroll.
Tested the changes to ensure that the scroll behavior is restored when navigating away from the component.
https://github.com/learningequality/studio/assets/77477551/f7e6384b-311d-4272-bc86-99ffe09156e0
Closes https://github.com/learningequality/studio/issues/4208
___
----
PR process:
Testing:
___

fix:scroller

---

contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeEditListItem.vue
contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
package.json
yarn.lock

Replace placeholder icons with the final icons,
___
Check that all icons that currently are in the `studio-usability-enhancements` feature branch match with the [figma specs](https://www.figma.com/file/2jKELXxkiJAIlIew26DsqO/Studio-Usability-Enhancement?type=design&node-id=1118-99902&mode=design&t=kROSyoZmjghZaFqO-0).
Closes #3425
KDS version containing the new icons should be released before mergin this PR.
----
PR process:
Testing:
___

Replace studio usability enhancements icons

---

Makefile

Fixes #4406
This pull request addresses an issue where Docker-Compose branch isolation may fail to work as expected for valid branch names. The current implementation encounters difficulties with certain branch names, leading to unintended behavior during project isolation.
- Updated the Makefile to improve the handling of branch names for Docker Compose project isolation.
- Ensured compatibility with valid branch names by addressing issues related to character substitutions.
___
----
PR process:
Testing:
___

Fix Docker-Compose Branch Isolation for Valid Branch Names

---

deploy/nginx.conf.jinja2

- Cloudflare has a timeout of 100 seconds, but our requests were still timing out at 60 seconds
- This copies the particular configuration change, but nothing else
- I don't exactly know if this will fail to build due to leaving out the other updates in https://github.com/learningequality/studio/pull/4336 but those have some complicated git history with https://github.com/learningequality/studio/pull/4343
Originally implemented in: https://github.com/learningequality/studio/pull/4336
Related issues fixed in: https://github.com/learningequality/studio/pull/4343
----
PR process:
Testing:
___

Copies nginx proxy timeout configuration update

---

.github/workflows/notify_team_new_comment.yml

This is a copy of the action we use in Kolibri.
@vkWeb will later on explore if we can extract some common logic. For now, we agreed it's okay to copy it so we can receive notifications soon.
Note that before we merge, Studio needs to be granted access to organization-level Slack secret. @rtibbles could you please allow it?
If code looks correct, we can merge and see.
----
PR process:
Testing:
___

Add action to notify us on Slack about GH issues comments from contributors community

---

deploy/nginx.conf.jinja2

- Switch content reverse proxy back to using `Host: $proxy_host` as GCS does not like it if it's different
Fixes regression from https://github.com/learningequality/studio/pull/4564
----
PR process:
Testing:
___

Switch back to $proxy_host

---

contentcuration/contentcuration/frontend/shared/mixins.js

Adds a string "ZIM" for the "zim" kind.
Fixes [#4205](https://github.com/learningequality/studio/issues/4205)
I don't have any zim files imported locally to test this, but this seemed like a very straight forward fix.
----
PR process:
Testing:
___

Add zim string.

---

contentcuration/contentcuration/frontend/administration/pages/Channels/ChannelTable.vue
contentcuration/contentcuration/frontend/administration/pages/Users/UserTable.vue
contentcuration/contentcuration/frontend/channelEdit/components/AnswersEditor/AnswersEditor.vue
contentcuration/contentcuration/frontend/channelEdit/components/AssessmentEditor/AssessmentEditor.vue
contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemPreview/AssessmentItemPreview.vue
contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/Channel.vue
contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNode.vue
contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/index.vue
contentcuration/contentcuration/frontend/channelEdit/components/ResourcePanel.vue
contentcuration/contentcuration/frontend/channelEdit/components/edit/AccessibilityOptions.vue
contentcuration/contentcuration/frontend/channelEdit/components/edit/CompletionOptions.vue
contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
contentcuration/contentcuration/frontend/channelEdit/components/edit/EditList.vue
contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ContentTreeList.vue
contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchFilters.vue
contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchResultsList.vue
contentcuration/contentcuration/frontend/channelEdit/views/sync/SyncResourcesModal.vue
contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogFilters.vue
contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogList.vue
contentcuration/contentcuration/frontend/channelList/views/Channel/components/LanguageFilter.vue
contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSelectionList.vue
contentcuration/contentcuration/frontend/shared/views/form/ContentDefaults.vue
contentcuration/contentcuration/frontend/shared/views/form/MultiSelect.vue

Recently we removed VCheckbox from the studio codebase, so we updated the Checkbox wrapper component to use KCheckbox instead, but this has bring a number of inconsistencies that havent been resolved yet. (Probably after this PR there could be any other place with a wrong behaviour).
I have manually checked all instances of `<Checkbox>` in the codebase and saw them rendered in the browser one by one.
| --- | --- |
| Disabled and hidden labels on AssesmentPreview | |
| ![image](https://github.com/user-attachments/assets/03e68482-fc87-4f84-aa75-00608753f79b) | ![image](https://github.com/user-attachments/assets/1350cc6e-7b60-4da6-b113-c9d7429edd0e) |
| Select all not working in clipboard, and not showing copy actions |  |
| …

Fix checkbox issues

---

contentcuration/contentcuration/tests/testdata.py
contentcuration/contentcuration/viewsets/feedback.py

* Tweaks how we save feature flags on the user fixture object so that even if the user already exists, the feature flags get updated
* Adds both has_permissions and has_object_permissions methods to the permissions checks for safety
1. Reran the tests!
___
----
PR process:
Testing:
___

Tweak feedback tests to ensure feature flags are set.

---

contentcuration/contentcuration/frontend/shared/views/Breadcrumbs.vue

This pr fixes the breadcrumb wrapping issue experienced when resizing a window with a long folder title
1. Create a folder with a really long title
2. Try to resize the window while observing the breadcrumb
3. It shouldn't wrap, but should get truncated as the resizing happens
https://github.com/user-attachments/assets/d6e67aaa-7dc2-40f2-8596-33f8ad12a5da
___
Fixes #4653
----
PR process:
Testing:
___

Fixes the breadcrumb wrap for long folder names

---

contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeEditListItem.vue

This pr prevents users with view-only permissions from editing a channel title and description.
- See https://github.com/learningequality/studio/issues/4701
**Before**
**After**: Option now removed if view-only
No
1. Create a user A, and sign in as user A
3. Create a channel and add some content.
5. Create another user B 
7. Open a channel and select the 'Share channel' option
8. Share the channel with user B by selecting the Can view option
9. The Edit title and description icon next to the resources and folders should not be visible
Fixes #4701 
----
PR process:
Testing:
___

Add edit permission check on edit title and description icon button

---

contentcuration/contentcuration/frontend/shared/views/ResizableNavigationDrawer.vue

Change the default value of `ResizableNavigationDrawer ` width.
1. Clear site data and cookies
2. inspect view details side bar initial width
Before:
----------
After:
closes #4723 
----
PR process:
Testing:
___

Fix default sidebar width

---

contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditSourceModal.vue
contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/__tests__/EditSourceModal.spec.js
contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
contentcuration/contentcuration/frontend/channelEdit/getters.js
contentcuration/contentcuration/frontend/channelEdit/mutations.js
contentcuration/contentcuration/frontend/channelEdit/store.js
contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
contentcuration/contentcuration/frontend/shared/views/AboutLicensesModal.vue
contentcuration/contentcuration/frontend/shared/views/LicenseDropdown.vue

Reverts learningequality/studio#4716

Revert "Update how About License information is displayed in EditSourceModal"

---

contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditBooleanMapModal.vue
contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/__tests__/EditBooleanMapModal.spec.js
contentcuration/contentcuration/frontend/shared/views/contentNodeFields/CategoryOptions.vue
contentcuration/contentcuration/frontend/shared/views/form/ExpandableSelect.vue

Reverts learningequality/studio#4714

Revert "Fixed field is required' validation"

---

contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditLanguageModal.vue
contentcuration/contentcuration/frontend/channelList/views/Channel/components/LanguageFilter.vue
contentcuration/contentcuration/frontend/shared/views/form/Checkbox.vue
package.json
yarn.lock

Fixes RTL direction in languages list and languages filter.
Reproduced #4728 and verified both examples were solved.
___
Reproduce #4728.
Fixes #4728
----
PR process:
Testing:
___

Fix RTL in Language filter

---

contentcuration/contentcuration/frontend/shared/mixins.js

This PR adds a missing string for the IMSCP variation of the HTML5 file type.
1. Select an HTML 5 file
2. Observe the file upload section for any missing stings
___
- See manual verification above
Fixes #4789
- We will need to do translations for the added string
----
PR process:
Testing:
___

Adds missing string(IMSCP) for HTML5 file type

---

contentcuration/contentcuration/frontend/shared/data/resources.js

* Reverts accidental change to the updateAsAdmin method.
* Restores the original function as REST Updating is still allowed via the users admin endpoint.
1. Go to admin panel
2. Go to users section
3. Edit storage allowance for a user and save
4. See no error
Fixes [#4790](https://github.com/learningequality/studio/issues/4790)
----
PR process:
Testing:
___

Revert accidental change to update as admin method.

---

docs/host_services_setup.md
docs/local_dev_docker.md
docs/local_dev_host.md
package.json

Pinned the versions of Yarn and Node to use with Volta.
1. Cloned a fresh repository.
2. Installed all the dependencies and set up the project.
No
Fixes #4817 
PR process:
Testing:
___

Pin node and yarn versions

---

contentcuration/contentcuration/utils/gcs_storage.py
contentcuration/contentcuration/utils/storage_common.py

- I missed access to the client where it was accessing the client property, which isn't available on the new Composite class added in https://github.com/learningequality/studio/pull/4926
Round 3: https://github.com/learningequality/studio/pull/4926
Can you upload files after merge?

Allow access to GCS client externally

---

CONTRIBUTING.md
README.md

- Changes info@ to contributors@ as a general contributing contact
- Adds GSOC contact

Update contact information in the contributing guidelines

---

requirements.in
requirements.txt

This pr updates `pillow` version to `11.2.1` after `11.2.0` was removed from the pypi.
https://github.com/python-pillow/Pillow/issues/8886
Builds should run successfully

Updates pillow version

---

contentcuration/automation/migrations/0001_initial.py
contentcuration/automation/models.py
contentcuration/contentcuration/frontend/RecommendedResourceCard/components/RecommendedResourceCard.vue
contentcuration/contentcuration/tests/viewsets/test_recommendations.py
contentcuration/contentcuration/viewsets/recommendation.py

This pr does the following
- Makes the `topic_id` field in the recommendations cache more strict by preventing nulls
- Streamlines the targeted exceptions in the recommendations API
- Fixes the bug on the recommended resource cards channel name
https://github.com/learningequality/studio/pull/5014
- All tests and build should run successfully without errors.

More tweaks from #5014 review

---

.github/dependabot.yml

Corrects package ecosystem in the dependabot config
The documentation does not say pnpm v10 is compatible, but we'll see after this is merged https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#configuration-options-for-dependabotyml
https://github.com/learningequality/studio/pull/5007/checks?check_run_id=41374078088

Switch package ecosystem to npm

---

Makefile

Remove no longer needed deploy migration

---

.github/workflows/call-manage-issue-header.yml

A companion to https://github.com/learningequality/.github/pull/28

Update manage issue header workflow events

---

contentcuration/contentcuration/frontend/settings/pages/Storage/index.vue

Updated LoadingText with KCircularLoader KDS component.
Video: 
https://github.com/user-attachments/assets/b4a8519a-dc53-485b-be65-0146e4ca3312
[5080](https://github.com/learningequality/studio/issues/5080)
When storageUseByKind is null. KCircularLoader should be shown.

Updated LoadingText to KCircularLoader KDS component

---

contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchOrBrowseWindow.vue

This pr fixes responsiveness issues experienced by users who have the search recommendations feature turned off.
**Before**
https://github.com/user-attachments/assets/faf1df14-6cc7-4380-858b-f7ae045e8ee2
**After**
https://github.com/user-attachments/assets/655149fa-a9fa-4494-9a08-71c4bba6edb0
Fixes ##5381
- Login with a user who has has the AI feature turned off
- Import resources from other channels

Fix responsiveness for non search recommendations users

---

.github/workflows/pythontest.yml
docker-compose.yml

We experienced the effects of the image availability brownout to alert us to the upcoming changes https://github.com/bitnami/containers/issues/83267
Test failure in
https://github.com/learningequality/studio/actions/runs/17814923541/job/50676546489?pr=5399
Do the changes match the guidance?

Update minio image to legacy repo
