learningequality/studio

- contentcuration/contentcuration/frontend/channelEdit/vuex/currentChannel/__tests__/module.spec.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/currentChannel/actions.js
- contentcuration/contentcuration/tests/test_node_views.py
- contentcuration/contentcuration/tests/viewsets/test_contentnode.py
- contentcuration/contentcuration/urls.py
- contentcuration/contentcuration/views/nodes.py
- contentcuration/contentcuration/viewsets/contentnode.py
* Changes total size calculation to be a detail view for one node, as it is now only ever used for that purpose
* Move into contentnode to leverage node fetching and permissions on the ContentNodeViewset
* Recast as File object filtering to give more consistent performance on larger trees
Works towards #1523 but does not resolve it
```
When: You click publish
Then: The modal should appear with a size estimate in a short amount of time
```
> Move and update size calculations for nodes.

- .gitignore
- contentcuration/contentcuration/models.py
When dealing with invitations, the model for `Channels` had not been updated to include `revoked`, `declined`, and `accepted`, as per the new `Invitation` models. This PR updates that in the `pending_channels`
> Add additional fields for pending channels

- contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelList.vue
- contentcuration/contentcuration/frontend/channelList/views/Channel/__tests__/channelList.spec.js
- contentcuration/contentcuration/frontend/channelList/vuex/channelList/actions.js
- contentcuration/contentcuration/frontend/shared/vuex/channel/actions.js
- contentcuration/contentcuration/frontend/shared/vuex/channel/index.js
- contentcuration/contentcuration/frontend/shared/vuex/channel/mutations.js
This PR reverts our use of pagination on the channelList in Studio. It essentially just removes much of the added code from [this previous PR](https://github.com/learningequality/studio/pull/2788/files#diff-286de1f5ca6af1ae4b033d0eb77cd8698436b647a9b6aad82d3a3ff70171a962R13)
Fixes #3005 
1. Add a new channel 
2. Navigate back to channel page 
3. All channels should continue to appear (none should disappear from the bottom) 
This will require re-adding pagination at a later date, as needed
___
PR process:
Testing:
___
> Remove pagination code

- contentcuration/contentcuration/frontend/shared/views/channel/ChannelSharingTable.vue
- contentcuration/contentcuration/frontend/shared/vuex/channel/__tests__/module.spec.js
- contentcuration/contentcuration/frontend/shared/vuex/channel/getters.js
1. In the `getChannelInvitations` SPA, we filter out declined, revoked, and accepted Invitations so that they do not appear in the `ChannelSharing` page, even if they are still available in memory in the `channel/invitationsMap` or indexedDB. Fixes #2989 
2. In `ChannelSharingTable`, if a user is removed as a viewer, we also remove all invitations still in memory (in Vuex) for that user. This prevents that user's stale and accepted invite from reappearing in the table. Fixes #2990
Because these fixes make the starting state for #1404 impossible, it also Fixes #1404
For Fix 1
1. Using the `user@c.com` created by the `devsetup` script, I invite `a@a.com` to be viewer of "empty channel". 
2. After logging in as `a@a.com`, I decline the invitation.
2. After logging back in as `user@c.com`, I …
> Filter out revoked/declined/accepted invitations when loading sharing page; delete invalid invitations when view-access is revoked

- contentcuration/contentcuration/management/commands/mark_incomplete.py
- contentcuration/contentcuration/tests/views/test_views_internal.py
- contentcuration/contentcuration/views/internal.py
1. In `views.internal::create_nodes`, adds checks to validate the title and license. Sets the new node's `complete` field to false if the checks fail.
2. Some code cleanup
(I'm not sure how to test this, since I think this API is only used via Sushi Chef)
* Read the code carefully, does any of the new code do anything unsafe (e.g. commit a potential Key Error)
Partially addresses #2806, (does not invalidate nodes based on rest of criteria in `mark_complete.py`)
> Add license and title validation to `views.internal::create_nodes`

- contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
- contentcuration/contentcuration/frontend/shared/views/form/ContentDefaults.vue
- contentcuration/contentcuration/frontend/shared/views/form/__tests__/contentDefaults.spec.js
Make content defaults component reactive when updated data are provided by its parent (expected behavior of v-model) and a couple of other smaller fixes related to content defaults updates. Please see commit messages for details.
Fixes [part (1) ](https://github.com/learningequality/studio/issues/2888#issuecomment-795316259) of #2888. Please check https://github.com/learningequality/studio/issues/2888#issuecomment-795316259 before reviewing to understand the bug reported as there are more issues depending on `/sync` timing.
1. Login to Studio
2. Click a Channel
3. Click the pencil icon to load the channel's edit details page
4. Make some amendments of the channel's content defaults
5. Click Save Changes button
6. Make sure to close the channel's edit details page before `/sync` gets …
> Content defaults reactivity fixes

- contentcuration/contentcuration/utils/pagination.py
This PR adds `.distinct()` to the pagination queryset. It is for the purpose of fixing pagination in the admin table, but hopefully will improve pagination overall. 
Fixes #2998 
1. Signed in as an admin 
2. On the /administration page, searched a query
3. The correct count and users returned with correct pagination
Before: 
After:
___
Testing with the Admin Table users tab 
1. Ensure you db has a number of users with editing permissions on various channels 
2. Sign in as an admin 
3. On the /administration page, go the the users tab and search 
4. The correct count and users should return, and the pagination should be correct 
----
PR process:
Testing:
___
> add distinct to pagination querysets

- contentcuration/contentcuration/tasks.py
* Catch and log non-existent users.
Fixes #2825 
* Upload a file
* Finish up editing the contentnode
* Go to upload a new file
* Confirm that your storage has still updated properly
> First pass fix for non-existent users being passed to the calculate user storage task

- contentcuration/contentcuration/dev_urls.py
- contentcuration/contentcuration/production_settings.py
- contentcuration/contentcuration/settings.py
- contentcuration/contentcuration/urls.py
To not run django in production mode I have made some changes in settings file as I added condition to it and done some changes in URL file too.
Issue - #3016
___
We can simply check if we can access the admin panel in production mode.
----
PR process:
Testing:
___
> Remove Django Admin in production mode

- contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreePage/index.spec.js
- contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreePage/index.vue
Use KModal instead of VDialog on the staging tree page and related updates.
1. Go to a staging tree page
2. Open and close summary modal
3. Open deploy modal and cancel deploy
4. Open deploy modal and confirm channel deploy
| --------- | ------ |
| ![summary-details-before](https://user-images.githubusercontent.com/13509191/109797463-cf5df500-7c19-11eb-8560-d29a2461728e.png) | ![summary-details-after](https://user-images.githubusercontent.com/13509191/109797476-d553d600-7c19-11eb-8bb6-a3b4d22aed75.png) |
| ![deploy-before](https://user-images.githubusercontent.com/13509191/109797540-e6044c00-7c19-11eb-9a2e-dfc3aa1f3bf6.png) | ![deploy-after](https://user-images.githubusercontent.com/13509191/109797555-ea306980-7c19-11eb-9a4a-057d07149c0c.png) |
Nothing that I am aware …
> KDS to Studio: KModal on staging tree page

- contentcuration/contentcuration/db/models/expressions.py
- contentcuration/contentcuration/db/models/query.py
- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/viewsets/contentnode.py
We're receiving quite a bit of Sentry errors for attempts to create duplicate tags and tag-node relationships. This PR moves to creating them one by one, as @rtibbles suggested, but also uses a more complex, single, query to obtain all of the necessary information to create the tags and relations. It may still encounter attempts to duplicate tags or relations due to more than one user attempting to create the same tag at the same time, but since it uses `get_or_create` it shouldn't error any longer.
- PostgreSQL allows you to create pseudo temp tables from a [list of values](https://www.postgresql.org/docs/9.6/queries-values.html), like used when bulk inserting. I added some new classes to allow for using a VALUES list in a CTE. I'm planning on submitting a PR to `django_cte` to support …
> Create tag relations one by one, and use CTEs to minimize queries doing so

- babel.config.js
- contentcuration/contentcuration/frontend/shared/app.js
- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/image-upload/index.js
- jest_config/setup.js
* We were using the `entry` option for `useBuiltIns` for `babel/preset-env`
* This was causing some things to not be fully polyfilled
* Switching to `usage` seems to do the trick instead, which allows us to defer to babel as to which things should be polyfilled.
1. Build studio frontend code: `yarn run build`
2. Run only `yarn run runserver`
3. Visit your local devserver via BrowserStack with a version of Opera browser < 56
4. Confirm in the developer console that `Array.prototype.flat` is defined, and that no errors from calling the method `flat` occur in the JS console on the Channel List page.
Fixes #2855
----
PR process:
Testing:
___
> Use 'usage' to ensure polyfills.

- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/tasks.py
- contentcuration/contentcuration/utils/user.py
We observed some slowdowns on `hotfixes` likely due to the user storage calculation query. We recently added `get_or_create_async_task` to only queue a task if there isn't one pending. The queuing of the user storage calculation task was using another approach, based off a cache value that may not work as expected (and observed odd behavior locally).
Updated the queuing of the user storage calculation task to use `get_or_create_asyn_task`, and updated one instance that could call the function multiple times with the same user.
1. Upload a file
2. Verify a calculation task was queued and executed
3. Move the file to trash
4. Verify a calculation task was queued and executed
We should move `contentcuration.utils.user.calculate_user_storage` to the User model, since we require a User object …
> Use get_or_create_async_task for queuing user storage calc task

- contentcuration/contentcuration/tests/utils/test_nodes.py
- contentcuration/contentcuration/utils/nodes.py
The query I added to check if files have been modified since the last cached calculation for a channel's size is just as slow the calculation query itself. The bottleneck is the join between content nodes and files, exacerbated by the filtering.
Commented out the code and made it return True so it always recalculates channel size.
Came out of QA for release: https://github.com/learningequality/studio/pull/3062
----
> Disable modified_since check, since needs further query optimization

- contentcuration/contentcuration/frontend/channelEdit/vuex/currentChannel/getters.js
- contentcuration/contentcuration/frontend/shared/vuex/session/index.js
* Adds isAdmin getter to session vuex module
* Uses isAdmin getter to allow editing and managing of any channel, regardless of whether a user is a direct admin
1. Create a new super user with `./contentcuration/manage.py createsuperuser`
2. Activate the super user
3. Login
4. Navigate to any channel
5. Confirm that the UI now lets you edit
Fixes #3015
PR process:
Testing:
___
> Enable admin editing of channels in the UI.

- contentcuration/contentcuration/tests/utils/test_nodes.py
- contentcuration/contentcuration/tests/viewsets/test_contentnode.py
- contentcuration/contentcuration/utils/nodes.py
Synchronous calculations of resource size are taking too long.
Changes the constant used to determine whether it should try calculation synchronously or not such that it shouldn't try to do so
1. Open a small channel
3. Click <kbd>Publish</kbd>
4. You should observe a loading spinner until the resource size task completes
5. Verify you see the channel size once it does complete
Addresses: https://github.com/learningequality/studio/issues/3084
Follow up: https://github.com/learningequality/studio/issues/3089
Gherkin: [integration_testing/features/publish-channel.feature](https://github.com/learningequality/studio/blob/hotfixes/integration_testing/features/publish-channel.feature)
----
___
> Quick change to disable synchronous calculation of resource size

- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/tasks.py
- contentcuration/contentcuration/tests/test_models.py
- contentcuration/contentcuration/views/base.py
- contentcuration/contentcuration/views/internal.py
- contentcuration/contentcuration/views/nodes.py
- contentcuration/contentcuration/views/users.py
- contentcuration/contentcuration/viewsets/base.py
- contentcuration/contentcuration/viewsets/user.py
Consolidates all our permission checking against `filter_view_queryset` and `filter_edit_queryset` class methods.
Removes permissions from users for the now unused orphan tree.
Did not change the semantics for internal views - but wondering if we want to move completely to 404s instead of 403s.
These endpoints should be covered by unit tests.
This might need some integration testing with ricecooker.
Fixes #3071 by making `filter_edit_queryset` filter nothing for admins.
----
PR process:
Testing:
___
> Clean up and consolidate permissions.

- contentcuration/contentcuration/tasks.py
- contentcuration/contentcuration/tasks_test.py
- contentcuration/contentcuration/tests/test_asynctask.py
- contentcuration/contentcuration/tests/utils/test_nodes.py
- contentcuration/contentcuration/utils/celery/tasks.py
- contentcuration/contentcuration/utils/nodes.py
[Reports from QA](https://github.com/learningequality/studio/pull/3090) after we made the channel size calculation always asynchronous suggests that we should keep synchronous calculation. Since the previous threshold was 5000 nodes and logging showed that 50-60 seconds was the upper limit for slow calculations, I've set it to 10% of that or 500 nodes to hopefully get close to a max of 5 seconds for synchronous calculation.
Unit testing
___
Verify publishing works
Resolves: https://github.com/learningequality/studio/issues/3089
Resolves: https://github.com/learningequality/studio/issues/3106
Resolves: https://github.com/learningequality/studio/issues/3105
----
PR process:
Testing:
___
> Reinstate synchronous channel size calculation with lower threshold, and resolve misc task related issues

- contentcuration/contentcuration/frontend/channelEdit/views/progress/ProgressModal.vue
- contentcuration/contentcuration/frontend/channelEdit/views/progress/__tests__/progressModal.spec.js
This PR adds a condition based on canManage to determine if Publish Modal is visible. 
Fixes #3079 
1. Share a channel as "view only" with an admin user
2. Log in as the channel owner/creator in one window, and in an incognito window, also log in as the admin user who has "view only" permissions
3. Update and publish the shared channel as the user with editor permissions. 
4. Without these changes, the modal should appear in the "view-only" admin window, even though the user cannot access/click in to the modal themselves. With the changes, the modal should not appear.
Before 
After
Not that I am aware of 
___
Please follow the manual QA process above.
The Progress/Publish modal in general is a bit of a fragile piece of code, so going over more than once manually may be helpful (I have …
> Add editing permissions condition to view/display Publish Modal

- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SavedSearchesModal.vue
Replace `ResponsiveDialog` by `KModal` in `SavedSearchesModal`
1. Open the channel editor page for a channel that you can edit
2. Click "ADD" dropdown button in the upper right corner
3. Select "Import from channels"
4. Type a search string to search input and click "SEARCH" button
5. Click "View saved searches" (to see some searches in "Saved searches" modal, you can click "Save search" before opening the modal)
|----------|--------|
| ![loading-before](https://user-images.githubusercontent.com/13509191/113100644-f3522d80-91fb-11eb-9b6e-da052cdb895d.png) | ![loading-after](https://user-images.githubusercontent.com/13509191/113100664-f8af7800-91fb-11eb-8f66-9cc17c2690bc.png) |
| ![no_searches-before](https://user-images.githubusercontent.com/13509191/113100688-ff3def80-9 …
> KDS to Studio: Replace ResponsiveDialog by KModal in SavedSearchesModal

- contentcuration/contentcuration/tests/viewsets/test_user.py
- contentcuration/contentcuration/viewsets/user.py
Fixes regression whereby can_edit and can_view were not getting annotated on the User queryset for the ChannelUser endpoint.
Adds regression test to try to catch this in the future.
Fixes #3125
> Make sure to always annotate can_edit and can_view.

- .github/workflows/pythontest.yml
* Adds a check for no ungenerated migrations to CI
* Remove meaningless codecov reports.
Ran the command on the command line. It confirmed there were no ungenerated migrations.
Fixes #804 
Command adapted from https://github.com/learningequality/kolibri/blob/develop/tox.ini#L28
Testing:
___
> Add migration check to tests.

- contentcuration/contentcuration/frontend/shared/views/channel/ChannelSharing.vue
- contentcuration/contentcuration/frontend/shared/views/channel/__tests__/channelSharing.spec.js
Adds some extra restrictions to the email validation to protect against `<` and `>` being wrapped around email addresses.
Adds many tests to ensure we are not being too restrictive of valid email addresses, adds some tests of other emails we can safely exclude.
Examples drawn from here: https://en.wikipedia.org/wiki/Email_address#Examples
Unit tests
___
Check that valid email addresses can still have channels shared with them.
Check that `<this@this.com>` cannot be shared with.
Fixes #3021
Testing:
___
> Enhance email regex to catch common errors

- contentcuration/contentcuration/frontend/shared/data/resources.js
* Rectifies a massive oversight whereby only collection fetches had local changes applied to them
* Uses the same setData logic as used in fetchCollection when we fetch a model that is stored in indexedDB
Follow the steps in Part 2 of https://github.com/learningequality/studio/issues/2888#issuecomment-795316259
This is most easily done by increasing the sync interval in `serverSync.js` to something huge.
Fixes #2888 
Fixes #3018 
----
PR process:
Testing:
___
> Use setData for model fetches as well as collection fetches.

- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
- contentcuration/contentcuration/frontend/shared/constants.js
- contentcuration/contentcuration/static/feature_flags.json
- contentcuration/contentcuration/viewsets/contentnode.py
Adds the ability to mark exercises as "channel quizzes," but only for admin users or users who have the feature enabled
- Adds a feature flag for "channel quiz" functionality
- Adds a checkbox to toggle "channel quiz" modality only when editing an exercise
- Updates logic for saving content node extra fields so the new modality gets saved
1. Sign in as non-admin user
2. Open a channel that has exercises
3. Edit an exercise
4. Verify you do not see the new checkbox
5. In another browser or incognito session, sign in as an admin
6. As the admin, update the non-admin's account enabling the channel quiz feature
7. Refresh the non-admin's page
8. Edit an exercise
9. Observe the new checkbox
10. Enable the channel quiz functionality
11. Save your edits
12. Verify the change is saved in the …
> User-scoped channel quiz feature

- contentcuration/contentcuration/frontend/shared/views/InfoModal.vue
- contentcuration/contentcuration/frontend/shared/views/__tests__/infoModal.spec.js
- contentcuration/contentcuration/frontend/shared/views/__tests__/masteryDropdown.spec.js
- contentcuration/contentcuration/frontend/shared/views/__tests__/visibilityDropdown.spec.js
Replace `ResponsiveDialog` by `KModal` in `InfoModal`, which affects the following:
- storage request form in settings
- visibility, license, and mastery model dropdowns on resource edit page
**Storage request form in settings**
1. Go to "Settings" -> "Storage" tab
2. Click "Open form" in "Request more space" section
3. See the help icon next to "Who can use your content?"
4. Click the icon
5. See the modal with information on licenses to appear
6. Close the modal by clicking "Close" button or by pressing "Escape" key
**Visibility dropdown on resource edit page**
1. Go to a channel editor for a channel that you can edit
2. Go to the edit page for a resource
3. Navigate to "Audience" section of "Details" tab
4. See the help icon next to "Visible to" dropdown
5. Click the icon
6. See the …
> KDS to Studio: Replace ResponsiveDialog by KModal in InfoModal

- contentcuration/locale/CSV_FILES/contentcuration/locale/ar_SA/LC_FRONTEND_MESSAGES/contentcuration-messages.json
- contentcuration/locale/CSV_FILES/contentcuration/locale/es_ES/LC_FRONTEND_MESSAGES/contentcuration-messages.json
- contentcuration/locale/CSV_FILES/contentcuration/locale/fr_FR/LC_FRONTEND_MESSAGES/contentcuration-messages.json
- contentcuration/locale/CSV_FILES/contentcuration/locale/hi_IN/LC_FRONTEND_MESSAGES/contentcuration-messages.json
- contentcuration/locale/CSV_FILES/contentcuration/locale/pt_BR/LC_FRONTEND_MESSAGES/contentcuration-messages.json
- contentcuration/locale/ar/LC_MESSAGES/contentcuration-messages.json
- contentcuration/locale/es_ES/LC_MESSAGES/contentcuration-messages.json
- contentcuration/locale/fr_FR/LC_MESSAGES/contentcuration-messages.json
- contentcuration/locale/hi_IN/LC_MESSAGES/contentcuration-messages.json
- contentcuration/locale/pt_BR/LC_MESSAGES/contentcuration-messages.json
Copies existing translations for new added string in https://github.com/learningequality/studio/pull/3152/files
> Sprint release 2021-05-10 strings

- contentcuration/contentcuration/utils/publish.py
Recently there were some errors with filenames in assessment item markdown.  It appears that these errors might be narrowly isolated, but in order to get a better idea of how widespread they are, this PR adds some additional context when logging errors during publishing.
Addresses https://github.com/learningequality/studio/issues/2891
This just adds the `channel_id` to any publishing related error messages that get logged.  It also does a basic integrity check on the checksum and extension of assessment item related filenames and logs an error if they're malformed.  
I intentionally do not raise any additional exceptions, since that is spelled out as a decision in the publishing code.  At some point it'd be nice if errors were actually handled on a case by case basis, but to implement …
> log some context when a malformed filename is encountered during publishing

- contentcuration/contentcuration/frontend/administration/mixins.js
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchFilterBar.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchFilters.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/mixins.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/utils/pagination.py
- contentcuration/contentcuration/viewsets/assessmentitem.py
- contentcuration/contentcuration/viewsets/base.py
- contentcuration/contentcuration/viewsets/channel.py
- contentcuration/contentcuration/viewsets/channelset.py
- contentcuration/contentcuration/viewsets/clipboard.py
- contentcuration/contentcuration/viewsets/contentnode.py
- contentcuration/contentcuration/viewsets/file.py
- contentcuration/contentcuration/viewsets/invitation.py
- contentcuration/contentcuration/viewsets/task.py
- contentcuration/contentcuration/viewsets/user.py
- contentcuration/search/viewsets/contentnode.py
- contentcuration/search/viewsets/savedsearch.py
- requirements-dev.txt
- requirements.in
- requirements.txt
After numerous issues arising because of pagination, this creates a prototype to ensure full integration of both the ValuesViewset and the frontend resource layer with both ordering and pagination.
This means that we can use standard Django Rest Framework `ordering` syntax for specifying the ordering of results from the API (https://www.django-rest-framework.org/api-guide/filtering/#orderingfilter) and this will be properly interpreted by both the backend and the IndexedDB `where` wrapper command.
In addition, this adds support in the backend for PageNumberPagination to be added to any ValuesViewset class when needed, and to leverage the efficiency gains that were added specifically to the AdminChannel and AdminUser viewsets.
In the frontend it adds support for PageNumberPagination and …
> Pagination integration proof of concept

- contentcuration/search/tests.py
- contentcuration/search/viewsets/contentnode.py
* Adds basic coverage for some commonly used filters on search endpoint.
* Fixes extant use of `user.is_anonymous` as a method not a property
* Updates `django_filter` initialization arguments from `name` to `field_name`
1. Search for anything on the search page
2. See no 500s
___
Fixes #3168
----
PR process:
Testing:
___
> Fixes two Django 1.11 to 3.2 upgrade issues in search.

- contentcuration/contentcuration/urls.py
* Copies latest URLs path from Django 3.2
1. Attempt to request reset password link
2. Navigate to reset password link
3. Reset password
Fixes #3173
----
PR process:
Testing:
___
> Fix password reset for Django 3.2 upgrade

- contentcuration/contentcuration/frontend/shared/views/form/CountryField.vue
* We currently get country name data from the `countries` npm package
* We specifically load the data for each supported locale
* We had not updated this for Portuguese
1. Create an account
2. Check that the countries are actually listed
___
Fixes #3167
A follow up issue is filed [here](https://github.com/learningequality/studio/issues/3175) to address the implementation details that caused this bug.
----
PR process:
Testing:
___
> Load portuguese country name data for country listing

- contentcuration/contentcuration/frontend/accounts/pages/Main.vue
* Our redirect after login was hard coded to `'/channels'` which caused it to redirect to the default language, English, after login
* The only thing I am confused by is how this ever worked
1. Switch to a non-English language on the sign in page
2. Sign in
3. Be redirected to Channels in your chosen language
Fixes #3169
PR process:
Testing:
___
> Redirects using a reverse URL rather than hardcoded 'channels'

- package.json
* Adds an alias so that it doesn't matter which command devs run!
> Alias devserver-hot to devserver:hot to reduce annoyance.

- contentcuration/contentcuration/frontend/accounts/pages/Create.vue
- contentcuration/contentcuration/frontend/accounts/pages/Main.vue
- contentcuration/contentcuration/frontend/accounts/pages/__tests__/create.spec.js
- contentcuration/contentcuration/frontend/accounts/pages/__tests__/main.spec.js
- contentcuration/contentcuration/frontend/shared/views/OfflineText.vue
- Adds some error banners when someone attempts to sign in or register while offline.
- Disables the submit buttons for signing in or finishing registration while offline.
- Adds an offline icon to the top of the screen while offline.
Addresses #https://github.com/learningequality/studio/issues/2938
> Offline sign-in and registration error messages

- contentcuration/contentcuration/tests/test_chef_pipeline.py
- contentcuration/contentcuration/views/internal.py
* Uses `set` method to set tags rather than assignment
* Adds tests of tag setting via ricecooker endpoints
1. Automatic tests
Fixes #3199
----
PR process:
Testing:
___
> Fix tag assignment in ricecooker endpoints.

- contentcuration/contentcuration/frontend/shared/views/ResizableNavigationDrawer.vue
* Handles a ref being undefined when a computed prop is first calculated
* Adds extra defensive checks in case it happens after mounting
1. Add a topic
2. Confirm no error from ResizableNavigationDrawer that cannot read `$el of undefined`
___
----
PR process:
Testing:
___
> Handle a ref being undefined during computed prop computation.

- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
* If `randomize` is undefined on an Exercise ContentNode's extra_fields, the publishing task defaults to set it to true
* In the frontend if it is undefined, it shows it as unchecked in the interface
* This brings the frontend inline with the backend
1. Create a new exercise
2. Observe that the Randomize question order for learners checkbox is checked
3. Go into the IndexedDB contentnode table and search for the id of this new exercise
4. Observe that extra_fields is still an empty object
Fixes #3244
----
PR process:
Testing:
___
> Make randomize default to true in the frontend

- contentcuration/contentcuration/apps.py
- contentcuration/contentcuration/management/commands/setup.py
- contentcuration/contentcuration/utils/minio_utils.py
- contentcuration/contentcuration/utils/storage_common.py
- requirements-dev.in
- requirements-dev.txt
- requirements.in
- requirements.txt
Makes minio a dev dependency instead and avoids loading it if the storage backend is GCS
1. Dev server starts up
___
Resolves dependabot security advisory: https://github.com/learningequality/studio/security/dependabot/requirements.txt/urllib3/closed
----
PR process:
Testing:
___
> Move minio to dev requirements, update urllib3

- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/mathquill/mathquill.js
- package.json
- webpack.config.js
- yarn.lock
- Update KDS to https://github.com/learningequality/kolibri-design-system/pull/256
- Remove Webpack injection of jQuery and replaced with single usage in exercise editing
- Publish modal description validation feedback properly displayed
- Math formulas can be inserted into exercise
___
----
PR process:
Testing:
___
> Update KDS and dev env fixes

- Makefile
- contentcuration/contentcuration/utils/celery/app.py
- contentcuration/contentcuration/utils/celery/tasks.py
*Testing on hotfixes separately*
- Adds celery task options that will cause interrupted tasks to be requeued
- Adds celery app method for querying what's in the queue
- Removes flags added in https://github.com/learningequality/studio/pull/1519
1. Step 1
2. Step 2
3. ...
When a worker is forcibly interrupted, it should restore (unacknowledged) tasks to the queue:
```
[2021-09-23 16:22:57,214: INFO/MainProcess] Connected to redis://localhost:6379/0
[2021-09-23 16:22:57,223: INFO/MainProcess] celery@phlack ready.
[2021-09-23 16:22:57,233: INFO/MainProcess] Received task: calculate_user_storage_task[69d10852-22ea-48a0-809d-d97ade8a2218]  ETA:[2021-09-23 14:32:37.734031-07:53] 
[2021-09-23 16:23:16,978: INFO/MainProcess] Received task: export_channel_task[1789ac915aca4519bf04a8c7755f5efc] …
```
> [hotfixes] Configure task behavior to acknowledge after execution to trigger requeuing when interrupted

- .pre-commit-config.yaml
Changes protocol for precommit hooks to prevent issues caused by https://github.blog/2021-09-01-improving-git-protocol-security-github/
> Don't use git:// protocol for unauthenticated github access.

- contentcuration/contentcuration/frontend/shared/client.js
- contentcuration/contentcuration/frontend/shared/vuex/file/actions.js
- contentcuration/contentcuration/tests/viewsets/test_file.py
- contentcuration/contentcuration/viewsets/file.py
This PR fixes the wrong status code 418 being responded to insufficient storage on user's disk.
___
Is 400 the expected status code or we should return something else?
Refers https://github.com/learningequality/studio/issues/3285
----
PR process:
Testing:
___
> fix: wrong status code on insufficient storage

- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditView.vue
This PR fixes #3153 though it doesn't explain the underlying code that makes the bug properly. 
After trying to narrow down the issue for a while, and consulting Marcella on it, I discovered that the ImmediateSave all function can't be called since details tab is not loaded, that is blocking the save or exit functionality of the View.
I tried multiple solutions to this issue, tested why it wasn't showing up, and upon consulting Marcella she suggested we add another check in EditView to see if details tab exists pre function call. that resolved the issue.
1. Opened all possible combination of details tab editing and related view editing and clicked exit at all possible steps.
We need to find the main reason details tab is not loaded when it's active in EditView, in EditModal.
___
1. Go to …
> Error when clicking the Finish or Close button 

- .gitignore
- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/tests/test_exportchannel.py
- contentcuration/contentcuration/tests/views/test_views_internal.py
- contentcuration/contentcuration/tests/viewsets/test_contentnode.py
- contentcuration/contentcuration/utils/publish.py
- contentcuration/contentcuration/views/internal.py
- contentcuration/contentcuration/viewsets/contentnode.py
Tags greater than 30 characters won't get published after we merge this PR.
Closes https://github.com/learningequality/studio/issues/3296.
----
PR process:
Testing:
___
> fix: don't publish tags greater than 30 chars

- contentcuration/contentcuration/frontend/channelEdit/vuex/task/index.js
Fixes #3291
Adds two conditions to manage 403 errors -- one when the router is available, and one when it is not
1. Sign in and open 2 tabs in studio
2. Navigate to the channel editor
3. Sign out in one tab 
4. The other tab should sign out and redirect to the login screen also (it might be a slight lag) and neither console should register any 403 errors
Any conditions I have missed?
PR process:
Testing:
___
> Add error handling in updateTaskList to reduce constant logging of 403s

- contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNode.vue
I've implemented a reduced cursor as to not confuse the user
1. Tested on english, it works now as Blaine suggester, On Arabic there is an issue.
2. Step 2
3. ...
We need to clear the LTR issues with the clipboard but those are complex and need a different PR
___
Open Studio, go to a Channel, copy something to the clipboard with at least 2 levels, and mouseover the part infront of the checkbox
This is a solution that is suggested by the comment. 
My other course of action was moving the padding to the child component of List_node but the issue is that the child component is created by Vuetify ?. I think. it requires to be fixed proper to make the entire row draggable again. 
That would require extensive right to left language fixes as well. 
PR process:
Testing:
___ …
> Draggable resize

- contentcuration/contentcuration/tests/test_exportchannel.py
- contentcuration/contentcuration/tests/testdata.py
- contentcuration/contentcuration/utils/publish.py
When a node's completion criteria has a `model` of either `time` or `approx_time`, the exported `ContentNode` created during channel publishing is set to have the `threshold` written to the `duration` field. 
Does this PR performs the expected overriding behaviour?   
Closes https://github.com/learningequality/studio/issues/3322.
**PR process:**
**Studio-specifc:**
**Testing:**
**This section is for reviewers to fill out.**
> fix: override exported content nodes duration to completion criteria threshold

- package.json
- yarn.lock
git:// started failing recently, and no docker build can happen
Github recently deprecated the git:// url for pulling in dependencies. We still have jsPDF using that git:// url, so docker builds on all branches should be failing.
[Unstable failed build](https://console.cloud.google.com/cloud-build/builds;region=global/6d35b777-c535-4d98-a341-4f085409bdb9?project=contentworkshop-159920)
[Hotfixes failed build](https://console.cloud.google.com/cloud-build/builds;region=global/6d35b777-c535-4d98-a341-4f085409bdb9?project=contentworkshop-159920)
This fix simply changes the git:// url to an https:// url. And builds are now succeeding on my end!
Run a docker build:
```bash
docker build -f k8s/images/app/Dockerfile .
```
> fix: use the jspdf https url instead of git://

- contentcuration/contentcuration/frontend/shared/constants.js
- contentcuration/contentcuration/frontend/shared/mixins.js
Imports the metadata constants from `le-utils` and adds the strings from metadata that were used in kolibri. 
Referenced both the constants and some strings to make sure they were available in vue files and was able to access both.
Does adding this in the existing translation mixin file make sense, or would it be better to create a separate file for this? (Originally I added it separately, but then I thought that might be more confusing, if it was the only thing that was handled differently).
PR process:
Testing:
___
> Import constants from le-utils and add metadata translation mixin

- contentcuration/contentcuration/utils/publish.py
This PR Logs an exception to sentry when publishing takes more than one hour.
1. Step 1
2. Step 2
3. ...
___
Closes #3269
----
PR process:
Testing:
___
> Log to sentry when publishing takes too long

- contentcuration/contentcuration/tests/viewsets/test_contentnode.py
- contentcuration/contentcuration/viewsets/contentnode.py
Adds `suggested_duration` field to viewset and serializer.
1. Console logging node object on front end now does include `suggested_duration` field
PR process:
Testing:
___
> Add suggested_duration field and test for writability

- contentcuration/contentcuration/constants/completion_criteria.py
- contentcuration/contentcuration/frontend/shared/leUtils/CompletionCriteria.js
- contentcuration/contentcuration/frontend/shared/utils/jsonSchema.js
- contentcuration/contentcuration/tests/test_completion_criteria.py
- package.json
- requirements.in
- requirements.txt
- yarn.lock
- Upgrades `le-utils` [with changes](https://github.com/learningequality/le-utils/pull/103) that allow percentages for the threshold of the pages model
- Updates completion criteria validation after breaking out the mastery schema into standalone file
___
Are the tests satisfactory?
https://github.com/learningequality/le-utils/pull/103
----
PR process:
Testing:
___
> Update completion criteria validator after breaking out mastery schema

- contentcuration/contentcuration/viewsets/channel.py
- contentcuration/contentcuration/viewsets/user.py
When admins were added, on our backend we were setting `is_admin=True` but DRF checks against `is_staff` so this PR implements a custom `IsAdminUser` DRF permission class to fix the issue.  
1. Log in as admin user `a@a.com` on studio from the `unstable` branch. 
2. Add `user@b.com` or any other user as an admin. 
3. Log out and log in as `user@b.com`. 
4. Open `Administration`: http://localhost:8080/en/administration. Open networks tab on dev console, you'll see 403 errors. 
5. Now, on switching to this PR's branch, the above issue is fixed. The `Administration` view is fully functional.      
Now when we add admins do they get expected access?
Closes https://github.com/learningequality/studio/issues/3348. 
PR process:
Testing:
> fix(admin): custom admin permission class

- contentcuration/contentcuration/tests/viewsets/test_contentnode.py
- contentcuration/contentcuration/viewsets/common.py
- contentcuration/contentcuration/viewsets/contentnode.py
* Updates the metadata labels to not squash previous edits with new changes
* Updates handling of JSONFieldDictSerializer to remove keys when they are set as `None` to match the expected behaviour from Dexie generated update events.
* Adds regression tests for this behaviour
Ran the new tests!
> Tests and updates for addition/deletion of metadata labels

- contentcuration/contentcuration/frontend/channelEdit/components/edit/AccessibilityOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/accessibilityOptions.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/detailsTabView.spec.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
- contentcuration/contentcuration/frontend/shared/constants.js
- contentcuration/contentcuration/frontend/shared/mixins.js
Add metadata, strings, tests for accessibility field in the edit modal (`DetailsTabView`)
1. Go to the edit modal
2. Look for the new "Accessibility" section below "Audience"
3. Make sure the checkboxes are visually working 
4. Use the network tab in developer tools and check in the `/sync` endpoint that the checked items are being sent in as `true` when checked and the key is removed when a checkbox is unchecked
This is the first of the new metadata fields to be included in the edit modal.
___
Run the tests:
- For `AccessibilityOptions` component using `yarn run test-jest contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/accessibilityOptions.spec.js`
Manually (see also the [Gherkin stories for Accessibility …
> Edit modal - add accessibility field

- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
* Makes the use of the diffTracker to generate getter values actually find the values in the diffTracker (where they are keyed by node id, and then the key for the property) rather than just keying directly by the property
* This should fix the apparent editing lag that was observed by @sairina in her recently merged #3366 
* This issue was originally introduced in https://github.com/learningequality/studio/pull/2443/commits/599e338e7965e677c3a2470b027f47d76a84b5d8
1. Check an accessibility checkbox
2. See it be immediately checked
> Actually use diffTracker values for display to the user.

- contentcuration/contentcuration/tests/base.py
- contentcuration/contentcuration/tests/test_assessment_item_keypair_constraint_migration_.py
- contentcuration/contentcuration/tests/test_authentication.py
- contentcuration/contentcuration/tests/test_contentnodes.py
- contentcuration/contentcuration/tests/test_createchannel.py
- contentcuration/contentcuration/tests/test_sync.py
- contentcuration/contentcuration/tests/test_zipcontentview.py
- contentcuration/contentcuration/tests/utils/test_garbage_collect.py
- contentcuration/contentcuration/tests/utils/test_nodes.py
- contentcuration/contentcuration/tests/views/test_views_internal.py
Consolidated StudioTestCase with BaseTestCase
All test should pass.
closes #1076 
----
PR process:
Testing:
___
Co-authored-by: Vivek Agrawal <vivekmittalagrawal@gmail.com>
@vkWeb
> consolidated StudioTestCase and BaseTestCase

- contentcuration/contentcuration/frontend/channelEdit/components/edit/LearningActivityOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/LevelsOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/ResourcesNeededOptions.vue
- contentcuration/contentcuration/frontend/shared/views/LanguageDropdown.vue
- contentcuration/contentcuration/frontend/shared/views/LicenseDropdown.vue
- contentcuration/contentcuration/frontend/shared/views/VisibilityDropdown.vue
Attaches menus in `VSelect` components to their parents.
___
Manual QA on these fields to make sure they all stay with their parent when you scroll outside of the dropdown menu.
Look for edge cases - like what happens when we scroll to the top and bottom of the screen - and note in a follow-up issue.
As seen in [this comment](https://github.com/learningequality/studio/pull/3376#pullrequestreview-956328982) 
PR process:
Testing:
___
> Attach menus to their parents

- contentcuration/contentcuration/tests/viewsets/test_contentnode.py
- contentcuration/contentcuration/viewsets/common.py
- contentcuration/contentcuration/viewsets/contentnode.py
* Fixes a bug whereby if the 'options' key or any other subkey of extra_fields did not exist, it would break upon assignment of a sub key
* Fixes a bug where completion criteria would not get updated inside the options object by ensuring that the writable keys are explicitly described on a serializer - there's some slight redundancy as a result
* Creates regression tests for the two bugs above
> Fix two previously unreported bugs in nested updates to extra_fields

- contentcuration/contentcuration/tests/test_serializers.py
- contentcuration/contentcuration/tests/viewsets/test_contentnode.py
- contentcuration/contentcuration/viewsets/contentnode.py
#3382 did a lot of good things, but failed to account for partial updates of completion criteria - as such, the validation happens prematurely, so that if a change is just made to the threshold, and not the model, validation will fail because threshold is missing from the update.
This defers validation until after the instance has been updated in memory, and runs validation then, before any save has happened, therefore triggering a validation error and preventing incorrect data from being saved.
1. Wrote regression test.
2. Saw that it failed.
3. Made it pass.
4. Rejoiced.
> Fix partial updating of completion criteria

- contentcuration/contentcuration/frontend/channelEdit/components/edit/CategoryOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/LearningActivityOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/LevelsOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/ResourcesNeededOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/categoryOptions.spec.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
- contentcuration/contentcuration/frontend/shared/constants.js
- contentcuration/contentcuration/frontend/shared/mixins.js
- contentcuration/contentcuration/frontend/shared/views/LanguageDropdown.vue
- contentcuration/contentcuration/frontend/shared/views/LicenseDropdown.vue
- contentcuration/contentcuration/frontend/shared/views/VisibilityDropdown.vue
- Add category field to edit modal
- Add tests for category field component
- Commit history will be cleaned, and needs to be rebased after #3370 is merged
1. Checked to see if behavior of the checkboxes in the dropdown and the chips work appropriately
2. Checked for data to be sent correctly to the backend
3. Checked to see if tests passed
|Chip and dropdown|
|--|
|<img width="973" alt="Screen Shot 2022-04-25 at 9 01 30 PM" src="https://user-images.githubusercontent.com/13563002/165218847-a1be2e0d-a77f-4e09-9584-a2757da71162.png">|
|Chip overflow|
|--|
|<img width="973" alt="Screen Shot 2022-04-25 at 9 02 03 PM" src="https://user-images.githubusercontent.com/13563002/165218694-96883e6b-c225-4640-8482-bcbe1d972cf0.png">|
The code is pretty spaghetti-ish and could use some refactoring, …
> Edit modal - add "Category" field to "Basic information" section

- contentcuration/contentcuration/tests/test_serializers.py
- contentcuration/contentcuration/tests/viewsets/test_contentnode.py
- contentcuration/contentcuration/viewsets/contentnode.py
- Add tests for validation happening in the update method.
- Properly handle validation in update method for completion criteria.
Ran tests.
> Fix completion criteria validation in serializer

- integration_testing/features/allow-marking-as-complete.feature
- integration_testing/features/edit-category-field.feature
- integration_testing/features/edit-completion-field.feature
- integration_testing/features/edit-learnin- level-field.feature
- integration_testing/features/edit-learning-activity-field.feature
- integration_testing/features/edit-multiple-resources-at-the-same-time.feature
- integration_testing/features/edit-what-you-will-need-field.feature
- integration_testing/features/new-layout-in-the-edit-modal.feature
- integration_testing/features/new-metadata-defaults-while-uploading-or-creating-new-files.feature
- integration_testing/features/view-new-metadata-in-previewers-across-studio.feature
- integration_testing/features/view-new-metadata-in-the-channel-details-modal.feature
- integration_testing/features/view-new-metadata-on-cards-and-list-items-in-the-studio-topic-tree-view.feature
- integration_testing/features/wip-edit-accessibility-field.feature
- integration_testing/features/wip-toggle-make-this-a-quiz-in-assessment-options.feature
New feature files for:
- New layout in the edit modal
- Edit learning level field
- Edit learning activity field
- Edit 'what you will need' field
- Allow marking as complete
- [WIP] Edit accessibility field
- Edit completion field
- Edit category field
- [WIP] Toggle *Make this a quiz* in assessment options of a Practice resource
- New metadata defaults while uploading or creating new files
- Edit multiple resources at the same time in the edit modal
- View new metadata in previewers across Studio
- View new metadata on cards and list items across Studio
- View new metadata in the channel details modal
> Adding the new Studio Gherkin scenarios from Notion to GitHub

- contentcuration/contentcuration/tests/views/test_views_internal.py
- contentcuration/contentcuration/views/internal.py
Adds support to the internal ricecooker endpoint to pass in a list of values for each of the new metadata labels.
Ensures it is a list of items and raises a 400 if not.
Validates the values against the internal constants and raises a 400 if invalid.
Sets the values on the model as a map that keys from the value to `True`.
Adds tests to the internal views tests to ensure this behaviour.
Fixes #3356
> Add support to ricecooker endpoint for metadata labels.

- contentcuration/contentcuration/tests/viewsets/test_contentnode.py
- contentcuration/contentcuration/utils/db_tools.py
- contentcuration/contentcuration/viewsets/contentnode.py
- Removed m n and mastery_model from ExtraFieldsSerializer.
- Added callable consolidate_extra_fields function to consolidate previous mastrey criteria 
- Changed unit tests
- Created new tests for set and unset completion_criteria cases.
1. Ran all tests related to contentnode
- Needs more robust validation in def to_internal_value function (we need to create a new issue for this)
PR process:
Testing:
___
> Consolidate mastery criteria

- contentcuration/contentcuration/settings.py
- contentcuration/contentcuration/utils/celery/tasks.py
- Due to the consequences of the [visibility timeout setting](https://github.com/learningequality/studio/issues/3395), this [rolls back late acknowledgment](https://github.com/learningequality/studio/pull/3304) until we can update celery
- Increases the visibility timeout setting from the default 1hr to 4hrs to reduce the likelihood of duplicated tasks
1. Step 1
2. Step 2
3. ...
___
Fixes https://github.com/learningequality/studio/issues/3395
----
PR process:
Testing:
___
> Rollback late acknowledgement and configure visibility timeout

- contentcuration/contentcuration/frontend/channelEdit/views/files/FileUpload.vue
Excludes any presets for 'dependency' presets from listings - these are only used for ricecooker nodes, so can be safely excluded from the UI for now.
Screenshot:
Fixes #3439
> Exclude dependency presets from listings.

- contentcuration/contentcuration/management/commands/set_file_duration.py
Adds a fallback using ffmpeg in cases where the container header parsing with ffprobe does not produce a valid value.
This is somewhat intensive as it actually decodes the entire stream in order to get the duration, but should be relatively foolproof.
> Add stream parsing fallback for duration setting.

- contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
Updates the `verifyChannel` function to have an alternate condition for if a user is an admin (and thus should be able to share the channel, even if they don't have explicitly set editor permissions)
1. Created channel UserA 
2. Signed in as admin a@a.com
3. Accessed this channel through admin panel under "Users" tabs
4. Shared channel - it now works! 
https://user-images.githubusercontent.com/17235236/177856888-cdf8b3b6-8fd7-43a3-aaf7-cc419ad97e07.mp4
I do not think so!
___
See manual verification above
Fixes #3258 
PR process:
Testing:
___
> Add a conditional check for if user is an admin for channel sharing

- contentcuration/contentcuration/tests/viewsets/test_contentnode.py
- contentcuration/contentcuration/viewsets/contentnode.py
* Adds some simple validation for the threshold field to ensure it is either a string, integer coerceable or dict.
* Ensures that updates to the `threshold` key of `completion_criteria` can be made granularly when `threshold` is an object
* For example, just updating the `m` value of an `m of n` mastery model
* Ensures that partial updates to extra fields that contain the old way of encoding mastery model (at the top level) successfully write the entire representation into the completion criteria format.
* Adds regression tests for both scenarios
> Add threshold field validation and properly handle updates to mastery models in all scenarios

- contentcuration/contentcuration/frontend/channelEdit/components/edit/ActivityDuration.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/CompletionOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/MasteryCriteriaGoal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/MasteryCriteriaMofNFields.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/activityDuration.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/completionOptions.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/masteryCriteriaGoal.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/masteryCriteriaMofNFields.spec.js
Wrote tests for PR #3455 
Ran the tests
Tests run fine, but could use a lot of refactoring!
___
Check that the tests successfully run
It's possible I missed a few states in the `CompletionOptions` component.
Fixes #3205 
----
PR process:
Testing:
___
> Edit modal - add completion/duration dropdowns and mastery fields tests

- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/tests/test_contentnodes.py
- contentcuration/contentcuration/tests/views/test_views_internal.py
- contentcuration/contentcuration/views/internal.py
* Creates a `mark_complete` method for ContentNode
* Includes all criteria from the `mark_incomplete` management command
* Applies at the end of node creation
* Creates tests for the various conditions
Fixes #2806
Not entirely sure how we should audit this - we definitely had some issues with the mark_incomplete management command when we ran it on historic data - but I don't have a strong sense of how much of that was affecting cheffed channels.
> Set complete marking on nodes created by ricecooker

- contentcuration/contentcuration/frontend/channelEdit/components/edit/ActivityDuration.vue
This PR fixes the default upload duration being shown in raw seconds. Now, we show the `duration` in `HH:MM:SS` format.
**Before:**
**After:**
___
1. Sign up with a@a.com.
2. Start editing a sample video file.
3. Observe the time shown beside "Completion -> Duration" field when "Exact time to complete" is selected.
Closes https://github.com/learningequality/studio/issues/3465.
----
PR process:
Testing:
___
> Fix default upload duration being shown in raw seconds

- contentcuration/contentcuration/frontend/shared/vuex/file/utils.js
- contentcuration/contentcuration/tests/viewsets/test_file.py
- contentcuration/contentcuration/viewsets/file.py
- Calls ceiling on the file duration on both the frontend and the backend to ensure it's an integer
1. Ran tests
2. Uploaded a file to studio and ensured it still works
___
Fixes https://github.com/learningequality/studio/issues/3454
----
PR process:
Testing:
___
> Ensure file duration is an integer

- contentcuration/contentcuration/frontend/shared/analytics/plugin.js
- Calls `dataLayer.reset()` according to [official documentation](https://developers.google.com/tag-platform/devguides/datalayer#reset)
- Also adds manual removal of `gtm.element` since `dataLayer.reset()` doesn't seem to affect it, but should be safe as long as it occurs in a function queued onto the dataLayer 
1. Logged into the Studio (dev) view in Google Analytics (see this [notion page](https://www.notion.so/learningequality/Analytics-Definitions-cdbd1b47da304486b059ebaa62c1eb8f) for more info) 
2. Observed events triggered as I used my local instance of Studio
3. Implemented the PR changes
4. Ensured that the changes produced no regressions to the data in GA
Fixes https://github.com/learningequality/studio/issues/3428
Again, `dataLayer.reset()` didn't do the trick, so I added a …
> Add reset and cleanup of dataLayer to prevent memory leaks

- .github/workflows/pythontest.yml
- .gitignore
- README.md
- docker-compose.yml
- docs/manual_setup.md
- Expands, clarifies, and removes some documentation regarding the setup of studio for development
- Pulls in redis version changes made by @ozer550 to reflect what's currently running in production
1. Ran `make dcservicesup`
----
PR process:
Testing:
___
> Small documentation updates

- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
- contentcuration/contentcuration/frontend/channelEdit/components/ResourcePanel.vue
- contentcuration/contentcuration/frontend/shared/views/ContentNodeLearningActivityIcon.vue
- contentcuration/contentcuration/frontend/shared/vuetify/icons.js
Replaces destructured imports from lodash with imports from specific lodash submodules to prevent entire lodash code being included in the build.
Should reduce build size somewhat, and seems to reduce the memory usage growth over time of the devserver.
> Use individual lodash imports as lodash does not allow tree shaking.

- contentcuration/contentcuration/frontend/shared/analytics/plugin.js
From feedback given by @MisRob:
- I increased the reset interval to 5 minutes
- Prevented requeuing of the reset function if the dataLayer hasn't changed
- Added logic to stop processing of dataLayer items once it reaches the queued reset function
1. Opened the channel edit page
2. Clicked around, generating events
3. Left the tab idle for a while
4. Verified that reset was triggered
5. Continued to leave the tab idle
6. Verified that additional resets were skipped until new events occur
https://github.com/learningequality/studio/pull/3475#issuecomment-1205095791
----
PR process:
Testing:
___
> Adjust the reset interval, and logic to prevent excess resets

- contentcuration/contentcuration/frontend/channelEdit/components/edit/AccessibilityOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/ActivityDuration.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/CategoryOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/CompletionOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/LearningActivityOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/LevelsOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/ResourcesNeededOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/learningActivityOptions.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/levelsOptions.spec.js
- contentcuration/contentcuration/frontend/shared/views/HelpTooltip.vue
- contentcuration/contentcuration/frontend/shared/views/LicenseDropdown.vue
- contentcuration/contentcuration/frontend/shared/views/VisibilityDropdown.vue
- contentcuration/contentcuration/frontend/shared/views/__tests__/licenseDropdown.spec.js
- contentcuration/contentcuration/frontend/shared/views/__tests__/visibilityDropdown.spec.js
- Updates attachment of menus to not use ID's defined outside of the component
- Updates all edit modal menus to use parent attachment pattern, to display below the field, to not show above edit modal toolbar when scrolling, and to be lazily loaded
- Updates the license dropdown to always show above the field, because it's the last field and generally showing below would cause overflow
- Fixes broken help tooltips in the edit modal
1. Open to edit a resource
2. Use any and all fields with dropdowns
3. Verify the dropdown shows below the field, except for the License field where it should show above
4. Ensure the fields still operate appropriately
5. Scroll while a dropdown is open, and ensure it remains in place relative to the field
Since this affects nearly every field in the edit …
> Resolve remaining issues with dropdown positioning and broken help tooltips

- contentcuration/contentcuration/apps.py
- contentcuration/contentcuration/tests/test_change_signals.py
- contentcuration/contentcuration/tests/test_websocket_consumer.py
- contentcuration/contentcuration/tests/utils/websocket_helper.py
- contentcuration/contentcuration/tests/viewsets/test_contentnode.py
- contentcuration/contentcuration/utils/websocket_helper.py
- contentcuration/contentcuration/viewsets/websockets/consumers.py
- contentcuration/contentcuration/viewsets/websockets/signals.py
Added mechanism to broadcast change object model via Django signals.
Added the following features:
1. Signals on save of Change object.
2. Broadcast changes to frontend once signal gets triggered.
3. Test the signals and its decision tree.
1. Ran all tests
The create_changes function(applies changes in bulk) does not use the save method so the signal will not be triggered but it won't matter in our case as told by @rtibbles sir.
Testing:
___
> Feat change log broadcasting

- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
- contentcuration/contentcuration/frontend/shared/views/Breadcrumbs.vue
- contentcuration/contentcuration/viewsets/contentnode.py
- When changing the title of a channel, the name in the breadcrumbs wasn't updating because that was saved into the content node table of IndexedDB with the channel's original title. Instead of having that require updating in IndexedDB, I've simply removed that functionality and made the first breadcrumb always use the channel's name
1. Open a channel for editing
2. Click to edit the channel details
3. Update the channel's name
4. Save the changes
5. Verify the breadcrumbs have also been updated
Fixes https://github.com/learningequality/studio/issues/3295
----
PR process:
Testing:
___
> Always use the channel title for the first breadcrumb

- contentcuration/contentcuration/api.py
- contentcuration/contentcuration/frontend/channelEdit/components/edit/CompletionOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/__tests__/actions.spec.js
- contentcuration/contentcuration/frontend/shared/data/__tests__/ContentNodeResource.spec.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/frontend/shared/utils/validation.js
- contentcuration/contentcuration/frontend/shared/utils/validation.spec.js
- contentcuration/contentcuration/tests/utils/test_user.py
- contentcuration/contentcuration/utils/publish.py
- contentcuration/contentcuration/utils/user.py
- contentcuration/contentcuration/views/internal.py
- contentcuration/contentcuration/viewsets/base.py
- contentcuration/contentcuration/viewsets/contentnode.py
- contentcuration/contentcuration/viewsets/sync/base.py
- contentcuration/contentcuration/viewsets/sync/endpoint.py
- Fixes task progress, for things like publishing, not being reported to the frontend
- Fixes issue where newly uploaded files fail to be added to the clipboard
- Fixes issue where newly uploaded files do not have proper ordering in the current topic/folder view
- Fixes issue where completion criteria options do not render when creating a new exercise
- Adds decorator that de-duplicates attempts to queue the user storage calculation task
1. Published a large channel and ensure that % progress is updated
2. Uploaded a file to a channel and successfully added it to the clipboard
3. Re-ordered newly uploaded files successfully 
----
PR process:
Testing:
___
> Misc fixes to channel editing experience

- contentcuration/contentcuration/utils/gcs_storage.py
Fixes [#3473](https://github.com/learningequality/studio/issues/3473)
Does this by raising `FileNotFoundError` from our GCS backend, rather than throwing an `AttributeError` because the GCS client library returned `None`.
> Raise FileNotFoundError when file cannot be found on GCS.

- .github/workflows/deploytest.yml
- .github/workflows/frontendlint.yml
- .github/workflows/frontendtest.yml
- .github/workflows/pythontest.yml
Limits the branches that get CI builds run to only our canonical branches.
Does this to prevent double builds of feature and dependabot branches on the main repo.
> Limit push builds to unstable, hotfixes, and master.

- README.md
Update readme to include instructions for Apple Silicon M1 computers.
___
Make sure to update user docs if necessary.
----
PR process:
----
> Fix for `grpcio` dependencies for Apple M1 computers in `readme`

- contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNodeOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/index.vue
- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchOrBrowseWindow.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/currentChannel/actions.js
- contentcuration/contentcuration/frontend/shared/data/changes.js
- contentcuration/contentcuration/frontend/shared/data/constants.js
- contentcuration/contentcuration/frontend/shared/data/index.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/frontend/shared/data/serverSync.js
- Removes the troubled change-locking implementation of the frontend change tracker used for reverting changes
- Resolves some issues with snackbars related to copying and moving nodes, and clipboard operations too, to ensure that the snackbars display
1. Duplicating a node and undo it
2. Copying a node to the clipboard
3. Moving a node
4. Delete a node and undo it
----
PR process:
Testing:
___
> Clean up frontend change tracker and snackbars related to undoing operations

- contentcuration/contentcuration/frontend/channelEdit/components/edit/ActivityDuration.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/activityDuration.spec.js
This updates the duration value to check for both values in the potential array (high and low resolution video), and uses the prop rather than a data calculation.
Fixes #3472
1. Upload a video 
2. Ensure the duration is correctly displaying
3. Click on the file name to change the video file
4. select a different file of a different length 
5. Check to ensure that the new correct duration is now reflected
https://user-images.githubusercontent.com/17235236/183918564-329751a6-6bb4-4740-8a29-2323761a565a.mp4
Not that I am aware of
___
You can follow the manual QA steps listed above
There was one scenario that seemed a bit wonky, but I haven't be able to reproduce consistently. 
1. Video file that is the same for both high and low resolution options 
2. Replace the high resolution file …
> Update duration to check for second value in files array

- contentcuration/contentcuration/frontend/channelEdit/components/ResourcePanel.vue
At some point (I think during linting), I dropped the `new` from 
```
const formatter = new Intl.ListFormat()
```
This caused an error when rendering any lists (reported in the accessibility criteria, but I suspect it would be anywhere multiple items can be selected). 
1. Add a new item (I tried this for both .mp4 and .pdf as reported in the original issue @pcenov filed)
2. Select multiple accessibility criteria
3. Open `View Detail` - the content should display and there should be no console errors.
___
See manual verification steps above
I think that we should wait to consider this "done" until the issue with the chips is resolved. While on the code side, I don't see how there would be any difference, I do think it would be good to double check and make sure there isn't anything I'm not …
> Add 'new' to Intl.ListFormat

- .eslintrc.js
- contentcuration/contentcuration/frontend/shared/app.js
- contentcuration/contentcuration/frontend/shared/client.js
- contentcuration/contentcuration/templates/base.html
- package.json
- yarn.lock
* In spite of commit comments to the contrary, we had never stopped using the long deprecated Raven sentry frontend integration
* Migrates Studio to use the `@sentry/vue` integration to better capture frontend errors
* Follows standard integration steps, but only in production builds
Fixes #3497
> Migrate to using the Sentry browser/vue library, Stop relying on Raven.

- .github/workflows/deploytest.yml
- package.json
* Removes the 'last 2 versions' requirement from our browserslist
Changes our resolved supported browsers from:
```
and_chr 101
and_ff 100
and_qq 10.4
and_uc 12.12
android 101
baidu 7.12
bb 10
bb 7
chrome 101
chrome 100
edge 101
edge 100
firefox 101
firefox 100
firefox 91
ie 11
ie 10
ie_mob 11
ie_mob 10
ios_saf 15.4
ios_saf 15.2-15.3
kaios 2.5
op_mini all
op_mob 64
op_mob 12.1
opera 86
opera 85
safari 15.5
safari 15.4
samsung 16.0
samsung 15.0
```
to:
```
and_chr 101
chrome 100
chrome 99
edge 100
firefox 99
firefox 91
ios_saf 15.4
ios_saf 15.2-15.3
ios_saf 14.5-14.8
op_mini all
safari 15.4
samsung 16.0
```
> Update browserslist to exclude IE and other low usage browsers

- contentcuration/contentcuration/frontend/shared/data/serverSync.js
- contentcuration/contentcuration/tests/test_change_signals.py
- contentcuration/contentcuration/viewsets/base.py
- contentcuration/contentcuration/viewsets/sync/endpoint.py
- contentcuration/contentcuration/viewsets/websockets/consumers.py
- contentcuration/contentcuration/viewsets/websockets/signals.py
This PR implements the broadcasting of tasks using WebSockets. It removes the existing mechanism which involved fake task object that was being created. Now the task status is directly being broadcasted at the time of update and added to the TASK table of the frontend.
- Direct broadcasting of Task progress
- Delegated consumer functions for error, task, and change broadcasting.
Manually it can be checked by publishing a channel!
contentcuration/contentcuration/tests/test_asynctask.py tests are failing with ```celery.exceptions.TimeoutError: The operation timed out``` error.
----
Testing:
___
> remould frontend to remove fake task object

- contentcuration/contentcuration/db/models/manager.py
- contentcuration/contentcuration/tests/test_contentnodes.py
- contentcuration/contentcuration/utils/db_tools.py
* Adds test for  copying metadata fields
* Adds copying behaviour to copy metadata fields
1. Add metadata to a node
2. Copied the node
3. Verified that the copy had the fields
Original:
Copy:
Note: I was unable to replicate either in tests or in the UI the issue of tags not copying.
Fixes [#3525](https://github.com/learningequality/studio/issues/3525)
> Add test for and support for copying metadata fields.

- webpack.config.js
* Fixes regression from the removal of vuetify-loader whereby source styles for Vuetify were now being imported, clashing with our vendored and excluded vuetify.css
* Adds a webpack ignore plugin to ignore these imports
* Fixes RTL issues
1. Switch to Arabic.
2. Confirm RTL works
Fixes [#3499](https://github.com/learningequality/studio/issues/3499)
> Ignore any imports of vuetify src style files to defer to our vendored css

- contentcuration/contentcuration/frontend/channelEdit/components/edit/CompletionOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/completionOptions.spec.js
This PR makes a slight adjustment to how audio and video completion duration is handled. 
Per the spec, all four options should be available and selectable in the "duration" dropdown, and the "completion" dropdown should be hidden, with the values set in the background.
Fixes #3527 
1. Add a video file
2. See no completion dropdown
3. See "duration" dropdown with 4 selectable options
4. All 4 options, including reference, work
https://user-images.githubusercontent.com/17235236/186763834-c9bd87cd-6e9b-4c0c-8c2f-7ca152dcd508.mp4
Please see the testing steps above. This can be done with audio and video files
With manual QA, I went through other file types, and I don't believe I've caused any regressions, but I'm less familiar with the data structure than the front end, and it's possible my …
> Update reference selection for duration for audioVideo resources

- contentcuration/contentcuration/settings.py
- requirements.in
- requirements.txt
* We were adding pycountry to our locale paths
* A quick grep of the code base showed no usage of ` _(...)` `gettext` that would require strings that don't already exist in Django or are our own internal strings.
Check that the server still runs fine.
Check that all language names are properly translated in the frontend language changing interfaces.
> Remove unused pycountry dependency.

- contentcuration/contentcuration/views/internal.py
- contentcuration/contentcuration/views/zip.py
- requirements.in
- requirements.txt
Removes the Python Raven dependency that was still being used, in favour of the sentry_sdk.
I followed the migration guide here: https://docs.sentry.io/platforms/python/migration/
> Remove deprecated Raven pip dependency.

- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
- contentcuration/contentcuration/frontend/shared/data/__tests__/ContentNodeResource.spec.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
The trash tree root node doesn't have `channel_id` annotated on it, so when deleting resources which moves them to the trash tree, the corresponding change event was missing the `channel_id` since it relied on the destination node having it. This updates that logic to fallback to the source node's `channel_id`, which should only ever be the case for moving to the trash tree.
This also adds the channel ID to node creation, since as a side effect, creating a new topic/folder and then immediately trying to delete it would fail given the newly added defensive check that prevents unset `channel_id` on the change objet.
1. Create a topic
2. Delete a topic
3. Ensure the deletion change is `allowed` by the sync endpoint
4. Retry the above in quick succession
Fixes …
> Ensure channel ID is set on move change to trash tree

- contentcuration/contentcuration/frontend/shared/data/serverSync.js
* Currently our `handleChanges` listener only triggers a sync when changes to our IndexedDBResource tables are made that are CREATE, UPDATE, or DELETE (the change types that Dexie Observable natively creates).
* This means that our custom change operations: MOVE, COPY, PUBLISH, and SYNC, will be ignored, until the sync endpoint polling happens.
* To remedy this, this PR implements an extra check in the handleChanges listener function to look for newly created changes in our specific changes table, so that we can trigger a sync when one of our custom changes has been created.
Carried out copy and move operations and confirmed that they were included in an almost immediate sync call to the backend.
I don't think so - ultimately, I think we could drop Dexie Observable and use something …
> Add a check for new entries in the changes table to ensure swift syncing of non-Dexie observable changes.

- contentcuration/contentcuration/frontend/channelEdit/components/ResourcePanel.vue
- contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogList.vue
- contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelList.vue
- contentcuration/contentcuration/frontend/shared/views/details/Details.vue
* `sortBy` was being used under the assumption that it could be passed field names prefixed with `-` to reverse the ordering. This is not the case.
* Updates these uses of `sortBy` to use `orderBy` with an additional array of `asc`/`desc` to specify the order of sorting.
* Fixes ordering on the catalog list page as the ordering from the API is lost once items are retrieved from vuex - resorts using the `name` parameter.
Checked sorting by `modified` time on My Channels page.
Checked sorting on Catalog list page.
Update to my channels - all channels shown in descending order of last modified:
Update to catalog list - all channels now properly sorted by name when displayed:
Fixes #3559
Fixes #3294
> Update sorting of channel items and fix erroneous use of `sortBy`

- contentcuration/contentcuration/decorators.py
- contentcuration/contentcuration/management/commands/garbage_collect.py
- contentcuration/contentcuration/tests/test_decorators.py
- contentcuration/contentcuration/tests/utils/test_garbage_collect.py
- contentcuration/contentcuration/utils/garbage_collect.py
- contentcuration/contentcuration/utils/publish.py
- contentcuration/contentcuration/utils/user.py
- contentcuration/contentcuration/viewsets/sync/base.py
This PR adds a function that cleans up File objects to the garbage collection utilities. Files with no associated ContentNode AssessementItem or SlideShow will be deleted, as well as files that have not been modified since the date specified (defaults to one month ago if no date is given).
The garbage collect management command is updated to run this function for any files not modified in the last month. This PR also includes a code clean-up of the decorators.py file. Sections deleted within this file were unused.
Tests for this function have been added to the test_garbage_collect.py file. Tests for the deletion of files that meet the specified requirements (no ContentNode AssessementItem or SlideShow association, and have not been modified in 1 month) and the non-deletion of files that …
> Cleanup stale files

- Makefile
- deploy/nginx.conf.jinja2
Change nginx configuration to add daphne server. Proxy pass websocket requests to Daphne.
- Created recipe for daphne server
- Reduced NUM_PROCS to two for the daphne server.
- Configured nginx file to proxy pass to daphne server for any incoming websocket request.
> Add recipe for daphne server and change nginx file

- Makefile
- contentcuration/contentcuration/management/commands/set_file_duration.py
- contentcuration/contentcuration/management/commands/set_orm_based_has_captions.py
* Fixes a remaining bug with the set file duration job whereby even with a fully streamed file, the duration cannot be inferred
* Adds a management command and make file entry to infer whether video resource nodes should have the has captions metadata applied to them, and applies it
1. Ran the new management command, confirmed that it added the label for a node with subtitles that matched the language of the video.
2. Ran it again and confirmed no additional nodes were updated
First run:
```
Setting 'has captions' for video kinds
INFO:command:Setting 'has captions' for video kinds
Set has captions metadata for 1 nodes
INFO:command:Set has captions metadata for 1 nodes
Finished setting all has captions metadata for 1 nodes in 0.044237375259399414 seconds
INFO:command:Finished setting all …
```
> Data migration updates

- contentcuration/contentcuration/frontend/channelEdit/views/files/FileUploadItem.vue
- contentcuration/contentcuration/frontend/channelEdit/views/files/__tests__/fileUploadItem.spec.js
This pr translates the hard coded "file" name for all file uploads with no name, particularly those uploaded via `ricecooker`. The hard coded "file" remains as is on the backend, but on the frontend it is set to a translated, meaningful string("Unknown filename") to the user.
1. Select a Channel>Select a Resource>Edit
2. Any file with no name should display  "file" as its name
3. If you are unable to find a resource with a file name "file", you may want run the following commands to change all system files to the name '"file". Once done with your checks, you can always rerun the database setup command to reset the database. You might want to use an isolated database for this especially if you already have imported channels you may not want to re-import
- `cd contentcuration`
- …
> adds translated user friendly string for files with no name

- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/LearningActivityOptions.vue
- contentcuration/contentcuration/tests/test_exportchannel.py
- contentcuration/contentcuration/utils/publish.py
* Does a minor refactor of the publish code to do a depth first traversal of the content node tree, in order to more easily pass down inheritance (should also make it easier to optimize this code in future)
* Makes `categories`, `resource_types`, `grade_levels`, and `learner_needs` 'inheritable' fields, whereby setting it on an ancestor topic will set it on any descendant node as well
* Prevents `learning_activities` and `accessibility_labels` being set on topics at publish
* Prevents `learning_activities`, `accessibility_labels`, and `completion_criteria` from being set in the edit modal
* Adds backend tests for all the publish update
Learning activity is disabled for topics, other fields are just hidden.
Add metadata labels to topics. Confirm they are on descendants on publish. Check …
> Topic metadata label updates

- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
- contentcuration/contentcuration/frontend/shared/leUtils/ContentKinds.js
- This PR defaults the learning activity for some content kinds when a file/node is uploaded/created
1. Upload a PDF
2. Ensure that "Read" learning activity is defaulted
Fixes https://github.com/learningequality/studio/issues/3373
----
PR process:
Testing:
___
> Default learning activities on upload for some content kinds

- contentcuration/contentcuration/asgi.py
- contentcuration/contentcuration/frontend/shared/data/applyRemoteChanges.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/frontend/shared/data/serverSync.js
- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/settings.py
- contentcuration/contentcuration/tests/test_change_signals.py
- contentcuration/contentcuration/tests/test_serializers.py
- contentcuration/contentcuration/viewsets/base.py
- contentcuration/contentcuration/viewsets/channel.py
- contentcuration/contentcuration/viewsets/websockets/consumers.py
- contentcuration/contentcuration/viewsets/websockets/signals.py
This pr remolds the serverSync.js to fully and properly support incoming events from WebSockets. It removes the polling interval used for syncing with the backend.
- Changes ServerSync.js to add event listeners for websocket events 
- Removes polling in regular intervals 🥳🥳
- Forces created_by_id of change object to not be null
- Additional hacks around some IGNORED_SOURCE change objects
Ran pytest
Some of the internal logic of Publishing is still broken. The bar always shows that we can publish even tho there are no changes made.
Every thing is at risk!!!!!!
----
PR process:
Testing:
___
> Feat server sync js cleanup

- Makefile
- I didn't correctly handle conflicts to merge changes to the Makefile; turned out `make altprodserver` isn't being called in production which explains why the broken/missing targets weren't causing issues
1. `make altprodserver`
----
PR process:
Testing:
___
> Fix bad merging of Makefile changes

- contentcuration/contentcuration/frontend/shared/views/CopyToken.vue
- contentcuration/contentcuration/frontend/shared/views/errors/TechnicalTextBlock.vue
- package.json
- yarn.lock
* Removes the clipboard polyfill which is only useful for browsers that we don't support anyway.
1. Copy auth token from Settings page
2. Copy a channel token from channel edit page
Supersedes #3582
> Removes use of the clipboard-polyfill and just uses the native API instead

- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/frontend/shared/vuex/session/index.js
- Recent changes that use stricter logic when applying Vuex updates caused a regression where behavior did not match the code
1. Sign out
2. Sign back in again
3. Ensure that the header shows that you are signed in
Previously:
----
PR process:
Testing:
___
> Fixes reactivity issues with signing in

- contentcuration/contentcuration/frontend/shared/data/applyRemoteChanges.js
- contentcuration/contentcuration/frontend/shared/data/constants.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
- Copy and move changes would fail to be applied when relayed to other editors/browsers
- Refactors transaction handling to open a transaction when applying each type of change
- This is likely slower but allows finer grained transaction management on per-change basis
1. Open two separate browsers
2. Sign into Studio on each browser
3. Open the same channel in each browser
4. In one browser, duplicate a resource
5. In the other browser, watch for the duplicate to appear-- it should
To wrap up parallel websocket integration work, we may want to consider implementing a FIFO queue when receiving changes or other updates over the websocket before passing along to `applyChanges`
___
Fixes https://github.com/learningequality/studio/issues/3635
----
PR process:
Testing:
___
> Fixes relaying of copy/move changes with refactoring

- contentcuration/contentcuration/viewsets/file.py
* Fixes small edge case that was showing up for graphie file uploads in ricecooker
* The graphie files' original filename had no extension, so the files were being uploaded to the checksum with no file extension, and then seemed to have not been uploaded.
* This uses the supplied file_format as the default extension to prevent this.
> Use the file format as the default extension in case the passed in name for the file does not have one.

- contentcuration/contentcuration/frontend/shared/utils/validation.js
- contentcuration/contentcuration/frontend/shared/utils/validation.spec.js
Adds a simple existence check to `files` array used in validation.
Fixes #3642 
1. Open to edit channel details
2. Set defaults for all options, including the important license field
3. Upload a PDF or another resource which will automatically default the Learning Activity
4. Click Finish without interacting with the edit form
5. Observe that the "error" is no longer present and the file is valid
https://user-images.githubusercontent.com/17235236/190653971-0abc1569-5509-424d-909c-0edaca0b2a95.mp4
___
1. Open to edit channel details
2. Set defaults for all options, including the important license field
3. Upload a PDF or another resource which will automatically default the Learning Activity
4. Click Finish without interacting with the edit form
5. Observe that the "error" is no longer …
> Add files existence and length check so validation is run later

- contentcuration/contentcuration/frontend/channelEdit/components/edit/AccessibilityOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/accessibilityOptions.spec.js
- contentcuration/contentcuration/frontend/shared/constants.js
- integration_testing/features/wip-studio-edit-modal/wip-edit-accessibility-field.feature
@thanksameeelian and I cohacked on this
- Hides the tooltip for the "Has captions or subtitles" accessibility option since it's self-explanatory
- Reorder the accessibility options so that "Has captions or subtitles" is first
1. Clicked to 'Edit details' a video resource
2. Verified that the tooltip info icon does not show for the option
3. Verified that the option is first
___
Fixes https://github.com/learningequality/studio/issues/3610
----
PR process:
Testing:
___
> Hide tooltip for certain accessibility options and reorder them

- contentcuration/contentcuration/frontend/channelEdit/components/AssessmentEditor/AssessmentEditor.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/AssessmentEditor/AssessmentEditor.vue
- contentcuration/contentcuration/frontend/channelEdit/components/AssessmentTab/AssessmentTab.vue
- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditView.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/__tests__/getters.spec.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/getters.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/getters.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/utils.js
- contentcuration/contentcuration/frontend/shared/constants.js
- contentcuration/contentcuration/frontend/shared/data/constants.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/frontend/shared/data/serverSync.js
- contentcuration/contentcuration/frontend/shared/vuex/indexedDBPlugin/index.js
- As shown in the screenshot below, the frontend was creating change events and syncing them for fields that only have meaning on the frontend
- This PR adds defensive checks at several levels to prevent syncing of fields that are only used on the frontend
1. Open the developer console for tracking syncs
2. Copy an exercise resource
3. Open the new copy for editing, but don't edit anything
4. Verify you don't see any frontend fields, like `isNew` or `__last_fetch`, being synced to the backend
- Exercise / assessment editing
----
PR process:
Testing:
___
> Refactor frontend-only fields and defensiveness

- webpack.config.js
* [Only use full hashes for production builds.](https://webpack.js.org/guides/build-performance/#avoid-production-specific-tooling)
* [Turn off pathinfo for development.
](https://webpack.js.org/guides/build-performance/#output-without-path-info)
This seemed to slightly reduce memory usage during builds, but I couldn't get a consistent measure.
1. Ran devserver, confirmed it still ran as expected.
> Implement webpack performance suggestions from docs.

- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/tests/test_models.py
- contentcuration/contentcuration/tests/viewsets/test_file.py
- contentcuration/contentcuration/viewsets/file.py
Enhanced validation while uploading files with invalid formats. closes #3650   
- Validates for file_formats in save() method before saving the File objects and raises validation error if file_format is invalid.
- Raises a 400 HttpResponseBadRequest if the user tries to upload a file with an invalid format.
- Ran pytest
- Tried to upload a file with an invalid format 
----
PR process:
Testing:
- [] If there are any front-end changes, before/after screenshots are included
___
> Validate file format in upload_url endpoint

- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchFilters.vue
- contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogFilters.vue
- contentcuration/contentcuration/frontend/shared/views/form/MultiSelect.vue
- @AllanOXDi and I cohacked on this
- Enforce that `<MultiSelect>` component requires the `item-text` prop to avoid using an empty string for selecting the key in the items array for option label display
- Updates other usages of the component to pass `item-text`, since they had the same issue
1. Signed into Studio
2. Opened 'Content Library'
3. Clicked 'Licenses' and 'Format' fields
4. Verified that option labels were present
| Licenses | Formats |
| --- | --- |
| ![Screenshot from 2022-09-22 11-34-50](https://user-images.githubusercontent.com/819838/191825187-949ed217-0929-4e64-86dd-e2eaf2b72e15.png) | ![Screenshot from 2022-09-22 11-35-01](https://user-images.githubusercontent.com/819838/191825214-44e78f7e-74e9-408b-9dff-79af42f2b766.png) |
Fixes …
> Resolve missing option labels in content library filters

- contentcuration/contentcuration/tests/test_exportchannel.py
- contentcuration/contentcuration/utils/publish.py
* Don't make intervening folders inherit inherited properties
* Still pass down the properties to descendant resources
* Adds language as an inherited property
Add inherited metadata labels and language to a folder - see that on publish in Kolibri, it gets set on descendant resources, but not on the intervening folders.
Follow up from QA https://github.com/learningequality/studio/pull/3578#issuecomment-1253821126
----
Testing:
___
> Topic metadata updates

- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
Refactors the helper that defines the getter for nested object fields, used for the new metadata, so that it extracts the object keys during the mapping of nodes, and produces the intersection of those values between all selected nodes
1. Opened a channel for editing
2. Selected multiple nodes
3. Set metadata fields
4. Finish editing
5. Verified metadata was appropriately saved
6. Open only one of the selected resources for editing
7. Verify the previously set metadata is shown
8. Make further edits to the single node's metadata
9. Verified metadata was appropriately saved
Fixes https://github.com/learningequality/studio/issues/3663
----
PR process:
Testing:
___
> Resolve issues affecting the bulk editing of new metadata fields

- contentcuration/contentcuration/frontend/channelEdit/components/edit/CategoryOptions.vue
The entire row of the category options select was clickable, but didn't toggle the checkbox unless you clicked the checkbox or its label directly.
1. Toggle on and off category options
----
PR process:
Testing:
___
> Resolve issue with selection mismatch between autocomplete and checkbox

- contentcuration/contentcuration/frontend/shared/vuex/file/utils.js
- contentcuration/contentcuration/tests/viewsets/test_file.py
- contentcuration/contentcuration/viewsets/file.py
* Uses floor instead of ceil for file durations
* Do this to ensure that duration never exceeds actual duration and makes it tricky to get full progress for duration based progress
* If ceil-ed, then users might have to skip back a second in a video in Kolibri for it to be marked as complete.
Address concerns raised here: https://github.com/learningequality/studio/pull/3317#issuecomment-1252373687
> Coerce all file durations with floor instead of ceil.

- contentcuration/contentcuration/frontend/shared/data/changes.js
- @vkWeb and I cohacked on this
- Fixes an issue where reverting a move wouldn't propagate to the backend because we don't allow explicit updates to `parent` and `lft` through the API
- This broke when the change-locking implementation was removed because it would have resulted in no changes syncing to the backend when the user reverted the change
- Fixes the error `Unable to revert changes without tracking some changes` when reverting changes after sitting idle for a while
1. Open a channel for editing
2. Open a folder/topic with several resources
3. Remove the first resource
4. Immediately undo its removal
5. Verify it reappeared in the right position
6. Remove a resource that isn't the first nor the last
4. Immediately undo its removal
5. Verify it reappeared in the right position
3. …
> Generate a reverse move when reverting a move

- contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/mutations.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/__tests__/mutations.spec.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/mutations.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/importFromChannels/mutations.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/task/index.js
- contentcuration/contentcuration/frontend/channelList/vuex/channelSet/mutations.js
- contentcuration/contentcuration/frontend/shared/data/mergeChanges.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/frontend/shared/vuex/channel/mutations.js
- contentcuration/contentcuration/frontend/shared/vuex/file/mutations.js
- contentcuration/contentcuration/frontend/shared/vuex/session/index.js
* Coerces channel_id returned from the API to be a hex string rather than `-` separated uuid for easier cross reference
* Removes a duplicated (and possibly unreported error producing during change squashes) version of `applyMods` and uses the version from `applyRemoteChanges`
* Updates all indexedDB update applying mutations to set the entire vuex map to ensure that new keys get set
* Updates the assessment item mutation to handle the compound `contentnode,assessment_id` id key
* Updates the file mutation to ensure that deletions applied in the indexedDB applyMods propagate to the other relevant maps
* In so doing makes the fileUploadsMap the single source of truth, that then just copy to the other maps
Primarily tested this to ensure publishing was working as intended. …
> Update IndexedDB mutations

- contentcuration/contentcuration/frontend/channelEdit/components/edit/AccessibilityOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/ActivityDuration.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/CompletionOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/ResourcesNeededOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/accessibilityOptions.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/activityDuration.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/resourcesNeededOptions.spec.js
- contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreePage/index.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchFilterBar.vue
- contentcuration/contentcuration/frontend/channelEdit/views/progress/ProgressModal.vue
- contentcuration/contentcuration/frontend/channelEdit/views/progress/__tests__/progressModal.spec.js
- contentcuration/contentcuration/frontend/shared/mixins.js
- contentcuration/contentcuration/frontend/shared/translator.js
- contentcuration/contentcuration/frontend/shared/utils/validation.js
- contentcuration/contentcuration/frontend/shared/utils/validation.spec.js
* Updates strings according to feedback from string review
* Updates _most_ 'field required' specific messages to a generic 'This field is required' - with the exception of the license description which has additional explanatory text as to why a description is needed.
* Removes string typos that were copy pasted from Kolibri strings
* Sorts the 'Requirements' dropdown
* Separates out peers and teachers to align with original spec
* Adds a contextual hint to add further description in case of catch all 'other supplies' selection
* Moves the For Beginners annotation out of the dropdown and into a separate checkbox under the Audience section
1. Verified updated sorting and display of requirements dropdown
2. Confirmed functionality and backend persistence of new for beginners checkbox
I …
> Strings n things

- contentcuration/contentcuration/frontend/shared/data/__tests__/ContentNodeResource.spec.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/tests/test_sync.py
- contentcuration/contentcuration/utils/sync.py
* Avoids using `get_or_create` as will error out when there are multiple ContentTag objects for the same `tag_name` and null channel combination
* Removes unused code in models.py that I discovered in the course of this
* Adds a test for syncing tags and a regression test for this fix
* Fixes a bug that would happen after copying a node due to not setting `original_channel_id` on a ContentNode during the copy operation on the frontend
* Fixes a bug that prevented any refresh of data from the backend if any changes were present in the changes table, even if they had been synced
1. Import a resource from one channel into another channel
2. In the source channel apply a tag "testtag"
3. In Django shell (`./contentcuration/manage.py shell`) create a tag with the same `tag_name` property
``` …
```
> Minimal fix for duplicate tags for null channel errors

- contentcuration/contentcuration/tests/test_exportchannel.py
- contentcuration/contentcuration/tests/testdata.py
- contentcuration/contentcuration/utils/nodes.py
- contentcuration/contentcuration/utils/publish.py
- contentcuration/contentcuration/viewsets/contentnode.py
* Fixes completely wrong logic in the publish code for extracting the mastery model
* Consolidates logic from the viewset to reuse in publishing too
* Adds tests for proper publishing of both old format and new format mastery models (at top level of extra_fields, and in the completion criteria)
1. Wrote a regression test, saw that it failed.
2. Fixed the behaviour.
3. Regression test passed.
Fixes #3676
> Fix mastery criterion publishing

- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
- contentcuration/contentcuration/frontend/channelEdit/components/ResourcePanel.vue
Adds necessary conditions (due to a mis-match of strings/mapping) to ensure that all string references are able to be translated on the Resource Panel as well as on the display chips
Fixes #3664
1. Add a resource
2. Add all levels to the resource - ensuring accurate display in the dropdown and in the chips within the form 
3. Save and exit. Check the display in the comfortable/default view on the main channel page to ensure chips are displaying strings accurately 
4. Open the side panel and ensure that the strings are displaying correctly for all levels there. 
This does not add any _new_ tech-debt, but it also doesn't resolve the strings problem, which should probably be revisited. The translation logic in general for all of the metadata work is replicated in a lot of places at this …
> Fix metadata 'level' labeling

- contentcuration/contentcuration/frontend/channelEdit/components/edit/CompletionOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/completionOptions.spec.js
- integration_testing/features/wip-studio-edit-modal/edit-completion-field.feature
As decided in Slack, "Reference" should be moved to the "Completion" dropdown, rather than the duration dropdown. Now, reference is an option for audio, video, and documentation resources. This moves that and makes some small edits to ensure everything works smoothly, and updates gherkin scenarios. 
Fixes #3673
Fixes #3659  (mostly because this UI no longer exists as a result of these changes)
1. Open the edit modal for a document, audio, or video resource
2. Reference should be an option under completion on the form
3. If reference is selected, no duration form should be visible, and the "reference hint" should be displayed
4. If "When time spent is equal to duration" is selected, there are duration options to select below 
5. "Reference" is no longer present as a "duration" option
___ …
> Updates to completion duration for references

- contentcuration/contentcuration/management/commands/loadconstants.py
- contentcuration/contentcuration/settings.py
- contentcuration/contentcuration/templates/registration/welcome_new_user_email.html
- contentcuration/contentcuration/views/users.py
This PR fixes the broken links and updates the spacing between the paragraphs in the Studio welcome email. A new `SITE` object has been added to include the hotfixes branch, some `domain` variables for `SITE` objects have been updated, and the way the `SITE_ID` is retrieved within `settings.py` has been refactored.
___
Fixes #3677 
----
PR process:
Testing:
___
> Fixed paragraph formatting and broken links within studio welcome email

- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeOptions.vue
- contentcuration/contentcuration/frontend/shared/data/constants.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
- @ozer550 and cohacked on this
- Prevents making HEAD requests to the backend if the requested resource may not have been created on the backend yet, preventing 'Page not found' when opening newly created folders
- Fixes issue opening non-existent tabs in the edit modal, causing a blank screen when editing details
For https://github.com/learningequality/studio/issues/3699
1. Stop celery
2. Open a channel for editing
3. Create a new folder
4. Open the folder
5. Verify you don't see 'Page not found'
For https://github.com/learningequality/studio/issues/3681
1. Click to edit the channel's details
2. Click the Sharing tab
3. Close the modal
4. Click on the kebab menu for a folder
5. Click to create a new folder
6. Verify the edit modal details fields aren't missing
Fixes …
> Resolve issues with editing and browsing newly added topics

- contentcuration/contentcuration/frontend/accounts/pages/Create.vue
- contentcuration/contentcuration/frontend/administration/pages/Users/UserStorage.vue
- contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemEditor/AssessmentItemEditor.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/ActivityDuration.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/CategoryOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/CompletionOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/LearningActivityOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/LevelsOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/MasteryCriteriaGoal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/ResourcesNeededOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/BrowsingCard.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ChannelList.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ImportFromChannelsModal.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchFilterBar.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchFilters.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchOrBrowseWindow.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchResultsList.vue
- contentcuration/contentcuration/frontend/shared/styles/main.less
- contentcuration/contentcuration/frontend/shared/views/ContentNodeLearningActivityIcon.vue
- contentcuration/contentcuration/frontend/shared/views/LanguageDropdown.vue
- contentcuration/contentcuration/frontend/shared/views/LicenseDropdown.vue
- contentcuration/contentcuration/frontend/shared/views/VisibilityDropdown.vue
- contentcuration/contentcuration/frontend/shared/views/channel/ChannelSharing.vue
- contentcuration/contentcuration/frontend/shared/views/files/ImageOnlyThumbnail.vue
- contentcuration/contentcuration/frontend/shared/views/form/ContentDefaults.vue
- contentcuration/contentcuration/frontend/shared/views/form/CountryField.vue
- contentcuration/contentcuration/frontend/shared/views/form/DropdownWrapper.vue
- contentcuration/contentcuration/frontend/shared/views/form/MultiSelect.vue
- contentcuration/contentcuration/viewsets/contentnode.py
-  We recently switched Studio's dropdowns to `absolute` positioning instead of the `fixed` positioning
- It relies on a selector, usually an ID, for attaching the menu, and when building reusable components the use of ID complicates things
- Additionally, switching this caused issues with automatic placement of the dropdowns depending on its location in the viewport
- Consolidated dropdown behavior (hopefully once and for all) using a new component that uses scoped slots to provide an `attach` attribute to Vuetify selects, autocompletes, and menus
- With the consolidated behavior in the new component, it now automates the dropdown position so that the dropdown shows above the field if there isn't sufficient space below the field
- Refactors and simplifies the layout of import search to …
> Dropdown consolidation, layout fixes, and RTL updates

- contentcuration/contentcuration/frontend/administration/components/ClipboardChip.vue
- contentcuration/contentcuration/frontend/administration/components/__tests__/clipboardChip.spec.js
- contentcuration/contentcuration/frontend/shared/views/CopyToken.vue
- contentcuration/contentcuration/frontend/shared/views/errors/TechnicalTextBlock.vue
* Adds existence checks everywhere that `navigator.clipboard` is referenced
* Hides copy buttons and prevents the clipboard being used
1. Checked that token copying still works in admin and non-admin
Fixes #3637
> Do existence check on navigator.clipboard

- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ChannelList.vue
- contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelList.vue
- contentcuration/contentcuration/viewsets/channel.py
* Sets a default ordering on the channel endpoint.
* Adds and uses custom ordering for import fetches.
1. Check ordering on import from channels for content library - should be sorted by name
2. Check ordering on import from channels for 'my channels' - should be sorted by last modified
3. Check ordering on channel list pages that this has not changed
My channels - last modified sort:
Content library - name sort:
My channels page - last modified sort:
Content Library - name sort:
Might want to come back and cleanup how we are handling ordering slightly - Kolibri handles it a bit better, and leaning on that would allow us to sort by multiple fields from the frontend.
Makes updates suggested here: https://github.com/learningequality/studio/pull/3592#issuecomment-1262182442
> Tweaks to channel ordering for import from channels

- contentcuration/contentcuration/frontend/channelEdit/components/edit/CompletionOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/completionOptions.spec.js
- contentcuration/contentcuration/static/feature_flags.json
This PR removes the channel quiz/practice quiz feature flag, based on a conversation with Richard. This feature was causing complications in the edit modal around completion and duration options. 
1. Sign in as a **non-admin**
2. Add or edit a contentNode, opening the Edit Modal
3. The completion option should be available, for all content types
___
See above
Are the of the right UI options available for all exercises now? 🤔 I'm not actually 100% sure
https://github.com/learningequality/studio/pull/3705#issuecomment-1265613257
PR process:
Testing:
___
> Remove feature flag for channel quizzes, thus fixing completion/duration dropdowns

- contentcuration/contentcuration/asgi.py
- contentcuration/contentcuration/viewsets/websockets/consumers.py
- contentcuration/contentcuration/viewsets/websockets/routing.py
Added a route for checking the status of Daphne service. 
- Added an HTTP consumer which handles only the health check route.
- Daphne blocks any other HTTP route in production.
1. Ran yarn run runserver (all routes working properly).
2. Ran Daphne server using ```make daphneserver```.
3. Go to /healthz route.
4. Responds with 200 ok.
PR process:
Testing:
___
> Added a healthcheck route for Daphne server.

- contentcuration/contentcuration/frontend/shared/views/ContentNodeLearningActivityIcon.vue
- contentcuration/contentcuration/frontend/shared/vuetify/icons.js
* #3344 inadvertently used translated strings to select the appropriate learning activity icon
* This went undetected until we actually had translations in place, so for non-English languages this broke
* This fixes this by removing the translation step from the icon selection
1. Switch to a non-English interface language
2. Look at the tree view for items with learning activities assigned
3. See them displayed properly
Updated behaviour to fix automated tests also.
Fixes #3748
> Fix i18n induced issues with learning activity icons.

- contentcuration/contentcuration/frontend/channelEdit/components/edit/CategoryOptions.vue
- contentcuration/contentcuration/frontend/shared/views/form/DropdownWrapper.vue
- Applies `.forceRTLMenu` within `<DropdownWrapper>` when the menu should be positioned to the right with RTL languages, specifically when there's a max width on the menu, like the case of the `<LanguageDropdown>`
- Swaps padding rule depending on RTL language for display of `<CategoryOptions>`
1. Change language to RTL language
2. Open a channel and click edit a resource's details
3. Check the Category and Language dropdowns
Fixes https://github.com/learningequality/studio/issues/3754
Fixes https://github.com/learningequality/studio/issues/3755
----
PR process:
Testing:
___
> Resolve RTL dropdown issues

- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
- Updates the logic in the edit modal for when to allow display and editing of Learning Activity and Completion Criteria during bulk edits, according to the following rules:
- When all selected nodes are the same kind and aren't topics, the completion criteria shows
- When any of the selected nodes are topics, learning activity is disabled
- When all selected are documents, completion criteria isn't required
1. Open a channel with a variety of resources and folders
2. Select multiple resources and folders, and edit them
3. Verify the above rules according to what's selected in the edit modal
Fixes https://github.com/learningequality/studio/issues/3759
----
PR process:
Testing:
___
> Learning Activity and Completion Criteria logic on when bulk editable

- contentcuration/contentcuration/frontend/channelEdit/components/edit/CompletionOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/MasteryCriteriaGoal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/MasteryCriteriaMofNFields.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
- contentcuration/contentcuration/frontend/shared/data/mergeChanges.js
- contentcuration/contentcuration/frontend/shared/data/serverSync.js
- contentcuration/contentcuration/viewsets/contentnode.py
- Corrects defensive behavior on handling M of N values, arising when adding a new exercise
- Prevents overwriting of M or N values when user changes one of them, requiring multiple edits from the user
- Allows `learner_managed` to be null so that the field is deleted in the serializer
- Fixes undocumented issue where errored or disallowed changes would be reapplied during fetch
1. Manually remove the `allow_null=True` change to the `learner_managed` field
2. Start or restart the celery workers
3. Create a new exercise and set invalid M of N values
4. Observe you should receive errors for the change since it should also set `learner_managed` to null
5. Edit the exercise again and apply valid M of N values distinctly different than last time
6. Click <kbd>Finish</kbd>
7. Edit the exercise …
> Prevents reapplication of errored or disallowed changes and resolves issues handling M of N and `learner_managed` values

- contentcuration/contentcuration/frontend/channelEdit/components/edit/CompletionOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/completionOptions.spec.js
- requirements.in
- requirements.txt
- yarn.lock
* Updates le-utils and kolibri-constants to 0.1.42 to add `determined_by_resource` as a valid completion criterion.
* Uses it to both set and read data to and from the backend
* Updates tests to confirm that the modal properly sets this.
1. Edit an HTML5 app
2. Set to determined by resource
3. Ensure that it gets properly set
Fixes #3750
> Allow determined by resource to be stored as a value.

- contentcuration/contentcuration/frontend/shared/vuex/file/utils.js
* Uses the /content/storage URL to access files in the frontend
1. Ensure that file preview and thumbnail generation still work
2. Check that the source URL is from the local origin
Fixes #3764
> Stop using the google storage API url in production to prevent CORS issues

- contentcuration/contentcuration/frontend/shared/data/serverSync.js
- contentcuration/contentcuration/viewsets/sync/endpoint.py
* Ensures that tasks that are long running in their application and emit their own changes during their running (like copying, publishing, syncing etc.) get properly finalized and marked as succeeded
* Does this by looking for changes that are marked as `synced` but with no errors nor disallowed, which means they have been sent to the backend and are awaiting application
* If this value is less than the currently registered max rev for the channel, it sends that instead.
1. Do a long running copy.
2. Ensure that the sync returns allowed, then that it returns the in progress tracking, and then that the change event is included in success (and that the channel rev sent to the backend is the server_rev for the copy change until it has succeeded
Fixes #3753
> Find unapplied changes and ensure we get updates from the backend about those.

- contentcuration/contentcuration/frontend/channelEdit/components/edit/ActivityDuration.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/CompletionOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/completionOptions.spec.js
These changes are to ensure that data is persisted correctly in the front and back end, and there are no "invisible" validations that cause data to not be saved as expected.
**This has been implemented and checked for: video, audio, document, html5, and h5p. Practice quizzes are _not_ behaving as expected, but for the sake of review, I am opening this now.** I hope to update practice quizzes within the next few hours, but it seems to be an isolated problem specific to quizzes mastery models, so I hope it does not impact any of these other changes.
For each file type listed above
1. Add a file
2. Ensure all required field are filled out
3. Save
4. Re-open edit modal and ensure completion/duration was saved
5. Move on to next completion/duration option (as applicable). Save, and repeat …
> Completion duration updates

- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/frontend/shared/data/serverSync.js
- contentcuration/contentcuration/views/base.py
Reverts changes from #3771
Instead changes the max rev setting for events received from the backend to filter out server generated events
Also changes how we send max rev from the backend to do the same filtering
Adds use of the visibility API for the active channel tracking so that switching back to a browser tab is sufficient to mark a channel as active, rather than needing to click inside the window
1. Do an import of a folder
2. Ensure that clicking into the folder properly lists it
1. Open a different browser session
2. Initiate an import into the same channel in that session
3. Click back to the window/tab of the original session and ensure the copied item appears once the copy completes
Fixes issue reported here: https://github.com/learningequality/studio/pull/3771#issuecomment-1292 …
> Only use non-server generated events for max rev setting

- contentcuration/contentcuration/context_processors.py
- contentcuration/contentcuration/frontend/shared/app.js
- contentcuration/contentcuration/settings.py
- contentcuration/contentcuration/templates/base.html
* Seeing a bunch of errors in sentry from the frontend both from dev environments and from people randomly running forks of Studio, this seemed important to resolve
* Updates how we do our frontend Sentry integration to use the same DSN, Environment, and Release variables as the backend
I'm not really sure how to test this except to do it live!
Fixes #2644
> Updates our frontend sentry config to be harmonized with drawing from secrets in the backend

- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
* Doing bulk editing of new metadata causes issues as we are not doing individualized updates to the metadata in the same way we do for tags
* The full spec (with indeterminate checkbox states) can't be implemented using the VSelect components currently being used for much of the UI
* The simplest fix this close to release seems to be just disabling all bulk editing for new metadata - this means that when we release, bulk editing will be unchanged from current production
1. Select multiple resources
2. See that no new metadata is editable
We will need to address this at least when we implement the new bulk editing workflows.
Updating the data processing to match how we handle the 'merge' behaviour for bulk editing in tags will be the first step
We will also need a way to indicate …
> Disable bulk editing of all new metadata

- contentcuration/contentcuration/constants/completion_criteria.py
- contentcuration/contentcuration/frontend/channelEdit/components/edit/CompletionOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/MasteryCriteriaGoal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/completionOptions.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/masteryCriteriaGoal.spec.js
- contentcuration/contentcuration/frontend/shared/constants.js
- contentcuration/contentcuration/frontend/shared/utils/validation.js
- contentcuration/contentcuration/tests/test_serializers.py
- contentcuration/contentcuration/tests/viewsets/test_contentnode.py
- contentcuration/contentcuration/viewsets/contentnode.py
- contentcuration/locale/ar/LC_MESSAGES/contentcuration-messages.json
- contentcuration/locale/es_ES/LC_MESSAGES/contentcuration-messages.json
- contentcuration/locale/fr_FR/LC_MESSAGES/contentcuration-messages.json
- contentcuration/locale/hi_IN/LC_MESSAGES/contentcuration-messages.json
- contentcuration/locale/pt_BR/LC_MESSAGES/contentcuration-messages.json
- integration_testing/features/wip-studio-edit-modal/edit-completion-field.feature
Cohack with @rtibbles that began as changes to address [feedback](https://github.com/learningequality/studio/pull/3777#issuecomment-1295067138), but resulted in some broader refactoring.
- Completion and duration should now work for _all_ content types 
- The descriptive aspect of duration has been hidden for now, so duration setting is only showed if a time based completion criterion is set. This was done due to the confusing interface language in the case that the it was being set descriptively.
- The learner managed state is moved into the completion options component, so that when it is set when no other completion criterion is set, the default completion criteria state to ensure validity.
- To simplify frontend state management, backend completion criteria validation is only run when …
> More completion duration updates

- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/frontend/shared/data/serverSync.js
- contentcuration/contentcuration/views/base.py
- contentcuration/contentcuration/viewsets/sync/endpoint.py
* Reverts previous changes to max rev calculation logic, and instead explicitly polls the backend for server_revs that are marked as synced but not applied, errored, or disallowed in the frontend
* Makes the blocking of collection refreshes for ContentNodes more targeted, to prevent changes only to tree structure for local nodes (i.e. for fetches for parents or ids queries).
1. Add a time.sleep to the `_clone_node` method of the `CustomContentNodeTreeManager` to make copies run slowly to replicate the error from production
2. Copy two folders in the same `import from channels` modal, to ensure two copy operations are started
3. When the first copy operation has finished, check that you can click into the folder and that the contents load
4. When the second copy operation has finished, …
> Ensure changes get properly cleared as succeeded and make refresh blocking more targeted

- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
* Uses lodash get to get values from extra_fields rather than direct property access, to ensure that falsy values are not overridden by the default value.
1. Unchecked 'randomize' on an exercise
2. Waited for save. Reopened edit modal.
3. Confirmed it remained unchecked.
https://user-images.githubusercontent.com/1680573/200354598-9e1172d1-d3b5-46b2-be3a-92c45aa1e3b6.mp4
Fixes #3800
> Do defaulting better to allow falsey values.

- contentcuration/contentcuration/frontend/channelEdit/components/edit/CompletionOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
* Uses uniqWith to do a deep comparison of options objects
* If all options are not unique then just return `nonUnique` for the entire value passed into `CompletionOptions`
* Disable editing of learner managed when non-unique
* Ensure that the completionDropdown shows an empty placeholder, forcing the user to make a selection there first in bulk edits
1. Edit one item to have a specific set of completion criteria
2. Select two other items of the same kind that have a different criteria
3. Confirm that you can now (restrictedly) edit these in sync and have it persist
https://user-images.githubusercontent.com/1680573/200079054-80bf74fc-52f7-4869-8908-8d0cc9bda18a.mp4
This is not an ideal user experience, but doing it better would involve more specific reading and patching of the nested …
> Bulk completion criteria fix

- contentcuration/contentcuration/tests/test_exportchannel.py
- contentcuration/contentcuration/utils/publish.py
* When the thumbnail encoding is not set on a content node at publish time, it gets generated from its thumbnail file, and set on the node. This node is then saved.
* Adding the extra_field migration standardization has caused issues, because it modifies the extra_fields dict during the transformation, so when it got saved with a new thumbnail encoding these updates also got saved
* This fixes this issue by restricting the save to only the `thumbnail_encoding` field
* Adds regression tests for both legacy and new style exercises
Fixes #3799
> Prevent modification of contentnode extra_fields during publish

- contentcuration/contentcuration/utils/sentry.py
- contentcuration/contentcuration/viewsets/base.py
- contentcuration/contentcuration/viewsets/channel.py
- contentcuration/contentcuration/viewsets/sync/base.py
- contentcuration/contentcuration/viewsets/sync/utils.py
- yarn.lock
* Adds user details and context when logging errors from change application logic
* Upgrades sentry-vue to latest
1. Make a node complete in the edit modal
2. Select DetailsTabView in the Vue devtools
3. Execute `$vm0.update({extra_fields: {options: { completion_criteria: {model: 'nah'}}}})` in the console to trigger a change that will cause an error during change application
4. Confirm that the error is still logged properly
Have not been able to confirm the sentry logging through testing, but I have followed the API, which allows for `user`, `contexts`, `extras` etc. as additional keyword arguments to `report_exception`.
> Enhance sentry logging for change event application

- contentcuration/contentcuration/tests/test_asynctask.py
- contentcuration/contentcuration/utils/celery/tasks.py
- Replaces usage of `add_pending_result` since it does not save 'extended' task information anymore, with usage of `store_result` and fake request context object to properly pass along the 'extended' info (this is a hack)
- Adds a new test that validates task result models contain necessary information
- Updates existing `fetch_or_enqueue` test to ensure it matches results created through `enqueue`
Ran the tests
Resolves https://github.com/learningequality/studio/issues/3820
----
PR process:
Testing:
___
> Fix missing information on pending task results

- contentcuration/contentcuration/tests/test_asynctask.py
- contentcuration/contentcuration/utils/celery/tasks.py
- Compares encoded and decoded version of task kwargs which prevents mismatches when the kwargs possibly contain UUID values (or other serializable objects)
Ran the tests... with the new regression test covering UUID values
----
PR process:
Testing:
___
> Fix task duplication when kwargs contain UUIDs

- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/tests/test_contentnodes.py
* Fixes regression induced by more rigorous completion setting in the internal API endpoint
* Adds test for and allows exercise nodes to be complete if they have raw data AssessmentItems (like KA assessments)
Wrote the test, ran the test!
> Allow exercises with raw_data set to be complete.

- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ChannelList.vue
- contentcuration/contentcuration/viewsets/channel.py
* Reverts changes to ordering on the server side Channel endpoint made here: https://github.com/learningequality/studio/commit/91298354ce200d3ffb763a772a89ede263de856e
1. Confirm that the channel list page still works
> Revert server side ordering to fix performance issues.

- contentcuration/contentcuration/frontend/shared/client.js
* Changes sentry error collection for failed requests to captureException
* Simplify handling of context and just use the raw error object for simplicity
1. Load Studio
2. In Network tools, turn 'throttling' to Offline
3. Confirm that the console logging still works for errors
4. Add `raise Exception` to the `post` method of the sync endpoint in `endpoint.py`
5. Confirm that the resultant 500 errors are properly logged to the console
> Better sentry client errors

- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ChannelList.vue
- contentcuration/contentcuration/viewsets/channel.py
- Reverts the reverted ordering changes to the channel list query
- Resolves query performance issues handling references to the channel in the `unpublished_changes` annotation query
1. Manually tweaked the query to use the outermost channel reference
2. Tested tweaked query in production for user who's had issues
3. Verified the query was using a better query plan and completed (much) faster
4. Reverted the removal of ordering channels by modified date
5. Repeated above testing of the query plan
6. Verified the API response in local dev server also remained unchanged
```
QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ …
```
> Optimize use of channel in unpublished_changes query

- contentcuration/contentcuration/decorators.py
- contentcuration/contentcuration/management/commands/reconcile_change_tasks.py
- contentcuration/contentcuration/tests/helpers.py
- contentcuration/contentcuration/tests/test_asynctask.py
- contentcuration/contentcuration/tests/test_decorators.py
- contentcuration/contentcuration/utils/celery/app.py
- contentcuration/contentcuration/utils/celery/tasks.py
- contentcuration/contentcuration/utils/user.py
- contentcuration/contentcuration/views/internal.py
- Adds method to `CeleryTask` class that help manage tasks in production using the celery control interface, and ensure task result is marked accordingly
- Prevents storage calculation tasks from being enqueued for admins
- Adds delay of storage calculation to cheffing API endpoint which handles bulk node creation
- Adds management command that reconciles queued and active tasks with what's in the DB and any unapplied changes
- Ran tests
- Ran management command
- Ran server and made a change to channel
----
PR process:
Testing:
___
> Add task helpers and stop enqueuing storage calculation tasks for admins

- contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
- contentcuration/contentcuration/viewsets/base.py
This PR fixes the double submit error while creating a new channel.
Ref #3833
Step 1: Try to create a new channel from studio, and observe what is happening on clicking create button.
Step 2: You may also try on a slow network connectivity
PR process:
Testing:
___
> disabled double submit while creating a channel

- contentcuration/contentcuration/frontend/shared/client.js
- @bjester [mistakenly used](https://github.com/learningequality/studio/pull/3855) `serializer` instead of `serialize` for the custom param serializer in axios options when updating it to version 1.x; strangely, it was still being invoked although without effect
The [axios docs](https://github.com/axios/axios#request-config):
```js
// `paramsSerializer` is an optional config in charge of serializing `params`
paramsSerializer: {
encode?: (param: string): string => { /* Do custom ops here and return transformed string */ }, // custom encoder function; sends Key/Values in an iterative fashion
serialize?: (params: Record<string, any>, options?: ParamsSerializerOptions ), // mimic pre 1.x behavior and send entire params object to a custom serializer func. Allows consumer to control how params …
```
> Fix axios key name for custom param serializer

- contentcuration/contentcuration/frontend/accounts/pages/Main.vue
- package.json
- yarn.lock
This pr removes the misleading offline message on the sign-in page. it also updates the dependency url for `jsPDF` to its new location on Github.
See #3226 for steps
___
1. Go to `/en/accounts/#/` unauthenticated
2. Open Chrome's Dev Tools and the Network tab or Click the Toggle device toolbar
3. Change network throttling to "Offline"
4. The misleading offline message should not be displayed on the sign-in.(See before and after screenshots)
Closes #3226 
----
PR process:
Testing:
___
> Remove misleading offline indicator

- contentcuration/contentcuration/frontend/shared/languageSwitcher/LanguageSwitcherList.vue
This pr fixes the language bar on the sign-in page so that the bullet points are correctly displayed.
See #3384 
Before
After
___
1. Go to `/en/accounts/#/` and observe the language section. The bullet points should be displayed between the languages correctly.
Closes #3384 
----
PR process:
Testing:
___
> Added bullet points between languages on sign-in page

- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/MarkdownEditor.vue
- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/utils.js
- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/__tests__/utils.spec.js
- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/formulas/formula-md-to-html.js
- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/image-upload/image-md-to-html.js
- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/image-upload/index.js
- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/registerCustomMarkdownField.js
* Removes unnecessary reordering of HTML to MD conversion that was causing MD to be unnecessarily escaped
* Adds regression test
* Removes regression caused by applying 'editing' to all custom components
* Sets 'editing' attribute only in the MarkdownEditor component
1. Add an image to a question
2. Publish the channel
3. Confirm the image is in the exercise (on a local machine can search your `.minio_data` folder for the `perseus` file and confirm that the archive contains the image
1. Confirm that the Image context menu only appears when the markdown is being displayed in edit mode.
2. Confirm that it does not appear when the markdown is displayed in view only.
> Fix markdown conversion for assessments

- requirements.in
- requirements.txt
- Upgrades `google-cloud-kms==1.4.0`
1. `pip install -r requirements.txt`
2. `yarn run runserver`
----
PR process:
Testing:
___
> Upgrade google-cloud-kms

- contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/actions.js
- contentcuration/contentcuration/frontend/shared/client.js
- contentcuration/contentcuration/frontend/shared/data/serverSync.js
- Adds the response status code to the error report message sent to Sentry to better group the errors
- Reports disallowed changes to Sentry so we can gain insight into when this occurs, if it does
- Updates request that loads nodes for the clipboard to chunk them in order to avoid 414 URI too long errors
1. Added content to 2 channels
2. Copied content from both channels to clipboard
3. Opened the clipboard
Fixes https://github.com/learningequality/studio/issues/3841
----
PR process:
Testing:
___
> Add status code to sentry errors, report disallowed errors, and chunk clipboard requests

- contentcuration/contentcuration/frontend/shared/styles/main.less
- contentcuration/contentcuration/frontend/shared/views/MainNavigationDrawer.vue
This PR fixes hidden focus navigation when using the tab key.
Fixes #3786 
https://user-images.githubusercontent.com/103313919/207542270-fe0eb917-d771-461c-8ded-0dac76bc9d85.mp4
Step 1:Navigate the menu using the tab key when the navigation drawer is open.Try it again when the drawer is closed. 
----
PR process:
Testing:
___
> fixed focus on navigation through the navigation drawer

- contentcuration/search/management/commands/set_contentnode_tsvectors.py
Me and @bjester recently co-hacked on slow performance of `make set-tsvectors` command on hotfixes. Blaine sir came up with a CTE that reduced the execution time exponentially! We analyzed the CTE and realized that the only concern we had was that the `published` boolean field being non-indexed can dramatically slow down our query. Even indexing `published` shouldn't make any difference because database will need to traverse the half of the leaf nodes any way.
So, this PR optimizes the performance of `make set-tsvectors` by first bringing in all the published `channel_id`s and `tree_id`s to python memory. Then our query utilizes these values to query for tsvectors. `tree_id` being indexed seems a good choice for querying.
Our optimization should bring the estimated completion time of …
> Optimized tsvectors insertion 🚀

- contentcuration/contentcuration/frontend/shared/data/index.js
- When a user opens more than one Studio tab, we have leader election logic which determines the browser tab that will be the lead for syncing all the tabs' changes to the backend
- According to the documentation for the library `broadcast-channel` that we use for leader election:
> Duplicate leadership can happen on rare occurences like when the [CPU is on 100%](https://web.archive.org/web/20201221051328/https://github.com/pubkey/broadcast-channel/issues/385) for longer time, or the browser [has throttled the javascript timers](https://web.archive.org/web/20201221051312/https://github.com/pubkey/broadcast-channel/issues/414).
- On a Windows machine, with lower hardware specifications, Studio may run into situations where 'duplicate leadership' is detected, causing an error in that logic …
> Reset elector when a duplicate leader is detected and capture errors in Sentry

- contentcuration/locale/es_ES/LC_MESSAGES/contentcuration-messages.json
- Updates the Spanish translation of the 'Reflect' learning activity to 'Reflexionar' instead of 'Reflejar'
1. Build frontend resources
2. Run the django server
3. Change language to Spanish
4. Verify translation of 'Reflect' activity 
Resolves: https://github.com/learningequality/studio/issues/3912
----
PR process:
Testing:
___
> Update Spanish translation of 'Reflect' in JSON file

- contentcuration/contentcuration/frontend/accounts/pages/Create.vue
- contentcuration/contentcuration/frontend/accounts/pages/__tests__/create.spec.js
- contentcuration/contentcuration/frontend/shared/layouts/ImmersiveModalLayout.vue
This PR aims to consolidate the sign-up experience for users in Studio. Currently, a first-time user has to agree to two mandatory opt-ins at sign-up  Terms of Service and privacy policy these processes are separated and require users to complete multiple steps to fully sign up. Consolidating these processes into a single, cohesive flow will make it as simple and straightforward as possible for users to opt-in or sign up in Studio.
closes #3834
1. Navigate to sign in page > create account
Before
After:
https://www.figma.com/file/1tQQ0Sw1yDjzO66hyjLVPM?node-id=556:4666#323944643
PR process:
Testing:
___
> Consolidate agreement opt-ins during account creation

- contentcuration/contentcuration/tests/viewsets/test_assessmentitem.py
- contentcuration/contentcuration/viewsets/assessmentitem.py
Validates JSON fields for answers and hints in AssessmentItem
1. Added custom fields and validations for hints and answers.
2. Adapted get_filenames_from_assessment according to new validations.
3. Added tests for both fields.
1. Ran Pytest
2. Open a channel 
3. Create an assessment with hints and multiple answers.
4. Save them.
PR process:
Testing:
___
> Validates JSON fields for AssessmentItem

- Makefile
- README.md
- `volta install yarn` installed version `4.0.0-rc.37` which doesn't work properly because it attempts to install dev dependencies for KDS, creating a node/engine version conflict
- Adds check to `Makefile` to support either installation method for docker compose, since the new plugin method uses the command `docker compose` instead of `docker-compose`
1. Ran `make dcbuild`
2. Coordinated with @ozer550 on `volta install yarn@1` and confirmed it worked
yarn issue
```
Packing kolibri-design-system@https://github.com/learningequality/kolibri-design-system.git#commit=e9a2ff34716bb6412fe99f835ded5b17345bab94 from sources
Using Yarn Classic for bootstrap. Reason: "__metadata" key not found in yarn.lock, must be a Yarn classic lockfile
➤ YN0000: Downloading https://classic.yarnpkg.com/latest.js …
```
> Make yarn version explicit and support alternate install method for docker compose

- contentcuration/contentcuration/wsgi.py
Disabled browser monitoring by new relic (addresses #3890)
Added 
```
newrelic.agent.disable_browser_autorum()
```
to  contentcuration/contentcuration/wsgi.py
This call disables automatic browser monitoring 
This has been disabled as we're getting an error coming from New Relic , but since we haven't been using it, it'd be no harm to just disable it
1. Step 1
2. Step 2
3. ...
not known
https://docs.newrelic.com/docs/apm/agents/python-agent/supported-features/browser-monitoring-python-agent/#disabling_instrumentation
Targets unstable branch as there were no straightforward ways to test this implementation
PR process:
Testing:
___
> Remove new relic frontend monitor - disabled browser autorun

- contentcuration/contentcuration/frontend/administration/pages/Channels/ChannelActionsDropdown.vue
- contentcuration/contentcuration/frontend/administration/pages/Channels/ChannelItem.vue
Fixes #3905 
1. Remove `this.name` from the search Vue component 
Following these steps: https://github.com/learningequality/studio/issues/3905#issuecomment-1422888546
___
Following these steps: https://github.com/learningequality/studio/issues/3905#issuecomment-1422888546
----
PR process:
Testing:
___
> Admin Page Editor Link Fix

- contentcuration/contentcuration/management/commands/count_public_resources.py
- contentcuration/contentcuration/management/commands/fix_duplicate_assessment_items.py
- contentcuration/contentcuration/management/commands/fix_exercise_complete.py
- contentcuration/contentcuration/management/commands/garbage_collect.py
- contentcuration/contentcuration/management/commands/mark_incomplete.py
- contentcuration/contentcuration/management/commands/reconcile_change_tasks.py
- contentcuration/contentcuration/management/commands/restore_channel.py
- contentcuration/contentcuration/management/commands/set_content_mimetypes.py
- contentcuration/contentcuration/management/commands/set_default_learning_activities.py
- contentcuration/contentcuration/management/commands/set_file_duration.py
- contentcuration/contentcuration/management/commands/set_orm_based_has_captions.py
- contentcuration/contentcuration/management/commands/set_storage_used.py
- contentcuration/contentcuration/management/commands/setup.py
- requirements.in
- requirements.txt
Removes dependency and adds simple logging statements in place
Removes superfluous basic logging config setup from management commands that caused duplicate logging
Ran the three affected management commands with progress bar removed, confirmed they still ran.
> Remove progressbar dependency.

- contentcuration/contentcuration/frontend/shared/data/index.js
- contentcuration/contentcuration/frontend/shared/data/serverSync.js
* Move resource listener registration to run in all tabs, not just the leader tab.
* This was preventing the logout listener being triggered in all open tabs
1. Run Studio.
2. Login.
3. Open another tab.
4. Logout in one tab - confirm that it redirects to the account page in every tab.
Fixes [#3915](https://github.com/learningequality/studio/issues/3915)
> Propagate logout to all open tabs

- contentcuration/contentcuration/tests/test_sync.py
- contentcuration/contentcuration/utils/sync.py
* Adds support to the sync utility to sync the new metadata labels
* Adds a regression test to verify the fix
1. Wrote regression test.
2. Fixed behaviour!
Noticed in QA by @pcenov here: https://github.com/learningequality/studio/pull/3701#issuecomment-1265605036
Testing:
___
> Adds regression test for and fixes metadata label syncing.

- contentcuration/kolibri_content/constants/schema_versions.py
- contentcuration/kolibri_public/import_metadata_view.py
- contentcuration/kolibri_public/tests/test_content_app.py
- contentcuration/kolibri_public/tests/test_importmetadata_api.py
- contentcuration/kolibri_public/urls.py
- contentcuration/kolibri_public/views.py
- contentcuration/kolibri_public/views_v1.py
* Adds a v2 ChannelMetadata endpoint
* Adds a v2 ImportMetadata endpoint (matching tweaks made in https://github.com/learningequality/kolibri/pull/10250)
* Adds tests for both endpoints
* Adds appropriate public cache headers to both endpoints and tests them both
* Updates the device info endpoint to support newer version requests from newer Kolibri instances, including returning a min_content_schema_version to signal to Kolibri's whether they can import from this instance
Automated testing, over and over again!
> Channel metadata and import metadata public endpoints

- .gitignore
- .run/devserver.run.xml
- Adds run configuration that's needed for using in-IDE debugging capabilities of Jetbrains/Intellij IDEs
1. Pull branch
2. Open supported IDE
3. You should have a run configuration called "devserver", shown in the screen shot
4. Press the green play button
5. Terminal should open and devserver should start
To debug, you press the bug looking icon next to the play icon
----
PR process:
Testing:
___
> Run configuration for the devserver supported by Jetbrains/Intellij IDEs

- contentcuration/kolibri_public/management/commands/export_channels_to_kolibri_public.py
Adds a tweak to the management command for importing previously published channels to ensure that the channel database of the public channel is migrated, so that the schema is readable by Django.
1. Downloaded the channel database for this channel: https://unstable.studio.learningequality.org/en/channels/d0cb2b465843584e9c72969ea5ea5519/
2. Ran through the steps of the management command manually
3. Ensured an error only occurred because the Channel wasn't in the contentcuration tables (the last step in the process)
> Migrate channel databases before import to guarantee compatible schema.

- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
Updates order of nested folders within breadcrumbs.
1. Create or update channel with multiple nested folders.
2. Confirm that the breadcrumb reflects the correct sequence of the nested folders.
Before
After
Closes #3842 
PR process:
Testing:
___
> Updates nested folder order in breadcrumb

- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
- contentcuration/contentcuration/frontend/channelEdit/components/ResourcePanel.vue
- contentcuration/contentcuration/frontend/shared/constants.js
- contentcuration/contentcuration/frontend/shared/views/channel/ChannelDetailsModal.vue
- contentcuration/contentcuration/frontend/shared/views/details/Details.vue
- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/viewsets/common.py
* Adds an aggregation helper class for label maps
* Uses it to return categories and levels for channel details
* Displays those channel details in the channel details modal - makes a slight deviation from the spec after consultation with @jtamiace to use chips instead of comma separation for consistency with other elements
* Cleans up ContentLevels constants, as they were being defined twice
* Removes unnecessary prefetch_related and select_related in node details method - seems to have no impact on performance either way
1. Add levels and categories to resources and topics in a channel
2. Verify that they appear, deduplicated in the channel details modal
3. Note that our  caching may cause stale data to the be returned to the frontend, so the cache needs to be cleared
Fixes …
> Levels and categories in channel details modal

- contentcuration/kolibri_public/search.py
- contentcuration/kolibri_public/tests/test_content_app.py
- requirements-dev.in
- requirements-dev.txt
* Fix language label generation.
* Add test for language pagination labels.
1. Added automated test.
2. Ran the server and went to http://127.0.0.1:8080/api/public/v2/contentnode/?max_results=1 to ensure that the returned labels included languages in the right format
Fixes #4017
> Properly map language labels

- Makefile
- contentcuration/contentcuration/management/commands/reconcile_publishing_status.py
- contentcuration/contentcuration/utils/celery/app.py
- contentcuration/contentcuration/utils/celery/tasks.py
This PR reverts celery's late acknowledgement config that was enabled on https://github.com/learningequality/studio/pull/3304.
1. Added `time.sleep(10000)` to publish function to make it wait for long time.
2. Start publishing a channel.
3. Quickly press `ctrl+c` twice on celery's terminal. The second `ctrl+c` tap should be quick otherwise python handles the interrupt.
4. Make sure the channel is marked still as `publishing` even though the worker has crashed.
5. Run the management command `python contentcuration/manage.py reconcile_publishing_status`.
6. You'll see the publishing status is resetted to `False` for that channel.
___
Performing manual verfication steps.
Closes https://github.com/learningequality/studio/issues/3968.
----
PR process:
Testing:
___
> Revert Celery Late Acknowledgement

- contentcuration/contentcuration/frontend/shared/views/ToolBar.vue
- contentcuration/contentcuration/viewsets/sync/utils.py
- package.json
- Updates toolbar to pass along `#extension` slot content to Vuetify's component to fix missing link to the staging tree
- Updates logging of sync exceptions to report stack trace, helpful within celery workers
- Updates `yarn run celery` to run with `--concurrency=1` instead of the default matching the quantity of CPUs available
___
1) Have Studio running locally at `http://localhost:8080`
1) Use `ricecooker` to create a cheffed channel:
```
CONTENTWORKSHOP_URL=http://localhost:8080 python tests/test_chef_integration.py
```
3) Open the channel in your local Studio
4) Verify you see the same as the screenshot
Observed in reviewing https://github.com/learningequality/studio/pull/3997
----
PR process:
Testing:
___
> Fix missing staging tree link in UI

- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
- contentcuration/contentcuration/frontend/channelEdit/views/progress/ProgressModal.vue
- contentcuration/contentcuration/frontend/channelEdit/views/progress/__tests__/progressModal.spec.js
- contentcuration/contentcuration/frontend/channelEdit/views/sync/SyncResourcesModal.vue
- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/frontend/shared/data/serverSync.js
- contentcuration/contentcuration/tests/test_contentnodes.py
- contentcuration/contentcuration/tests/test_sync.py
- contentcuration/contentcuration/tests/viewsets/base.py
- contentcuration/contentcuration/utils/sync.py
- contentcuration/contentcuration/viewsets/channel.py
This pr updates the syncing modal to look as shown below;
See https://github.com/learningequality/studio/issues/3986
No
___
1. Login into Kolibri studio
2. Go to `/en/channels/#/my-channels`
3. Setup 2 channels, one to upload content to(A), and the other to import content from the first into(B)
4. Select select channel B and perform the syncing
5.  You should be presented with progress on start syncing and notification on completion of syncing
Fixes https://github.com/learningequality/studio/issues/3986
----
PR process:
Testing:
___
> Updates syncing metadata fields on syncing modal

- contentcuration/contentcuration/frontend/channelEdit/components/move/MoveModal.vue
Fixes #3940
This PR adds an additional condition that would make the button disabled - when the `move` has been initiated. It also adds a small loading spinner to indicate that the move is in progress
1. Use devtools to set connection speed to slow 3G
2. Copy a number of resources to clipboard 
3. Move to another folder
https://user-images.githubusercontent.com/17235236/228911762-6a17fff9-9e87-4adc-8410-ee3094eac2f7.mp4
___
Please see the steps outline under manual verification. Using the slow connection, and having a long-ish list of resources to be moved is important to actually see this happen.
----
PR process:
Testing:
___
> Disables "Move here" button in copy workflow once it has been clicked 

- contentcuration/contentcuration/tests/test_sync.py
- contentcuration/contentcuration/utils/sync.py
This PR fixes `sync_node_files` algorithm to remove additional files from imported / copied nodes.
1. Create a PDF file type contentnode and copy it.
2. Add an EPUB document to the copied node.
3. Sync channel by clicking on three-dot menu then 'Sync resources' and then make sure 'Files' option is ticked and click on 'Continue'.
4. Notice in the backend database the additional EPUB of the copied node no longer exists.
___
Does manual verification and unit test passes?
Closes https://github.com/learningequality/studio/issues/3818.
----
PR process:
Testing:
___
> Remove additional files upon channel sync

- contentcuration/contentcuration/tests/test_asynctask.py
- Temporarily skip the tests until @bjester can fix them https://github.com/learningequality/studio/issues/3916
1. Ran tests
Yes if we do not re-enable them at some point
___
Tests pass in Github actions?
https://github.com/learningequality/studio/issues/3916
----
PR process:
Testing:
___
> Skip flaky tests for now until I can fix them

- contentcuration/contentcuration/frontend/channelList/router.js
This pr updates the url path to open the `ChannelDetailsModal` so that it opens in a new tab correctly. Fixes #4026 
- URL path changed from `/public/:channelId` to /`public/:channelId/details`
___
1. While unauthenticated, view the public catalog page and open the channel details modal (via the info icon) in a new tab.
2. While authenticated, view the content library page and open the channel details modal (via the info icon) in a new tab.
PR process:
Testing:
___
> Fixes inability to open channel details modal in new tab

- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
Fixes https://github.com/learningequality/studio/issues/3910
This PR adds a `nextTick` and sets `selected` to the nodes available in the edit modal before proceeding with the `handleClose` function, regardless of whether the user had selected all of them or not. Without having one or more nodes selected, `DetailsTab.vue` is not available, and therefore, accessing the saving functionality by reaching down through the child components to $refs.detailsTab is not possible. So, there is no `immediateSaveAll` and nothing happens.
[No Details Tab exists, since no items are checked]
This is admittedly a bit of a hacky workaround, and there is undoubtedly a better solution. However, beginning a refactor of the EditModal, even if narrowly scoped to rearrange some of this saving logic, feels risky …
> Ensure the saving and validation runs on bulk edit, even if user has not selected all nodes

- contentcuration/contentcuration/frontend/shared/views/policies/PoliciesModal.vue
- contentcuration/contentcuration/frontend/shared/views/policies/__tests__/policiesModal.spec.js
resolves #4014 
1. Locally, if the agree checkbox is not checked the continue button is disabled.
2. Only when we check the checkbox the continue button is clickable.
Unchecked: 
Checked:
___
----
PR process:
Testing:
___
> Disable checkbox based on policyAccepted

- Makefile
In order to get the infrastructure side of https://github.com/learningequality/studio/issues/3994 ready, we need an existing target to connect it with, which this adds.
___
The change doesn't do anything-- just make sure the `Makefile` isn't broken (tabs <> spaces)
https://github.com/learningequality/studio/issues/3994#issuecomment-1520471710
----
PR process:
Testing:
___
> Add new Makefile target for post-deploy migration flows

- Makefile
- contentcuration/contentcuration/frontend/shared/leUtils/MasteryModels.js
- deploy/generatejsconstantfiles.py
From issue #2797 
Made Changes in the ordering of dropdown elements in `contentcuration/contentcuration/frontend/shared/leUtils/MasteryModels.js`
No 
___
[Screencast from 26-04-23 04:51:13 PM IST.webm](https://user-images.githubusercontent.com/81693090/234566389-9059cada-d575-45ea-9039-18a01b4dc818.webm)
I have made minor changes kindly let me know if it needs futhur changes
----
PR process:
Testing:
___
> Fix #2797  incorrect order of options in the Exercise > Edit Details page > Assessment options

- .github/dependabot.yml
* Adds Github Actions to the dependabot managed upgrades
* Sets the time to make upgrade PRs at midnight UTC to avoid them popping up in the middle of the workday PST
I have made the same change on multiple repos, and it seems to be working!
> Add Github actions to dependabot managed upgrades and fix time for upgrades to midnight UTC

- contentcuration/contentcuration/management/commands/count_public_resources.py
Ideally, we want the "same" piece of content across multiple languages to have distinct content_ids, so that progress isn't shared etc. We already knew this wasn't the case for Khan Academy channels, for legacy reasons, but it turns out there are other channels in the same boat. This PR calculates uniqueness when counting items in the library as a combination of content_id and language_id.
This bumps the count up from 147K to almost 190K distinct content items in the public library.
1. Tested out management command and ensured the numbers all made sense
Testing:
___
> Factor in language when counting distinct content items

- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeEditListItem.vue
- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
- contentcuration/contentcuration/frontend/channelEdit/components/StudioTree/StudioTree.vue
- contentcuration/contentcuration/frontend/channelEdit/views/progress/ContentNodeCopyTaskProgress.vue
Extracted just the strings from https://github.com/learningequality/studio/pull/4060 to let our team start the translation work.
----
PR process:
Testing:
___
> Strings for handling of copy failures

- contentcuration/contentcuration/frontend/channelEdit/__tests__/utils.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/ResourcePanel.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/CompletionOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/utils.js
- contentcuration/contentcuration/frontend/shared/constants.js
- contentcuration/contentcuration/frontend/shared/mixins.js
- Displays "Completion" and "Duration" metadata in the resource side panel
- Adds new strings for related error messages to be likely used in the upcoming work
| _Edit modal settings_  |  Reference material | Viewed in its entirety | When time spent is equal to duration - Short activity  | When time spent is equal to duration - Long activity  | When time spent is equal to duration - Time to complete  | Determined by the resource |
|---|---|---|---|---|---|---|
| *Side panel*  | ![Screenshot from 2023-05-05 14-45-17](https://user-images.githubusercontent.com/13509191/236461572-95961229-e06c-4f49-8feb-e97afb32fd5a.png) | ![Viewed in its entirety ](https://user-images.githubusercontent.com/13509191/236464485-4617f06a-d1c8-425b-8875-e20b5792922a.png) | ![Screenshot from 2023-05-05 …
> Add completion criteria to the side panel

- Makefile
- Follow up to https://github.com/learningequality/studio/pull/3654 which had a known issue with the `Change` table, which has an auto incrementing integer field that breaks when making changes to a channel after initialization, despite rebuilding sequences
- Uses `--exclude-table-data` flag to exclude the table's data from the export according to the documentation https://www.postgresql.org/docs/current/app-pgdump.html
1. Ran `make .docker/postgres/init.sql` to create an export/backup
2. Checked out a new branch
3. Ran `make dcservicesup` where it restored from the export
4. Ran the devserver and made changes to a channel
https://github.com/learningequality/studio/pull/3654
----
PR process:
Testing:
___
> Ignore change event data in database export/init.sql

- contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/actions.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/__tests__/actions.spec.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/importFromChannels/actions.js
- contentcuration/contentcuration/frontend/channelList/vuex/channelList/__tests__/module.spec.js
- contentcuration/contentcuration/frontend/channelList/vuex/channelSet/__tests__/module.spec.js
- contentcuration/contentcuration/frontend/shared/__tests__/app.spec.js
- contentcuration/contentcuration/frontend/shared/app.js
- contentcuration/contentcuration/frontend/shared/data/__tests__/ContentNodeResource.spec.js
- contentcuration/contentcuration/frontend/shared/data/__tests__/changes.spec.js
- contentcuration/contentcuration/frontend/shared/data/__tests__/serverSync.spec.js
- contentcuration/contentcuration/frontend/shared/data/applyRemoteChanges.js
- contentcuration/contentcuration/frontend/shared/data/changes.js
- contentcuration/contentcuration/frontend/shared/data/constants.js
- contentcuration/contentcuration/frontend/shared/data/index.js
- contentcuration/contentcuration/frontend/shared/data/registry.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/frontend/shared/data/serverSync.js
- contentcuration/contentcuration/frontend/shared/logging.js
- contentcuration/contentcuration/frontend/shared/utils/testing.js
- contentcuration/contentcuration/frontend/shared/utils/validation.js
- contentcuration/contentcuration/frontend/shared/vuex/channel/__tests__/module.spec.js
- contentcuration/contentcuration/frontend/shared/vuex/channel/actions.js
- contentcuration/contentcuration/frontend/shared/vuex/file/__tests__/module.spec.js
- contentcuration/contentcuration/views/pwa.py
- webpack.config.js
* Attempts to prevent issues with background tabs sleeping timers and saving memory by making each tab responsible for the creation and persistence to the backend of edits made in the tab context
* Creates Change classes mapping to each Change type to handle proper instantiation of the change and persistence to the indexedDB changes table
* Updates all `put` operations to be `add` operations (new in Dexie v3) to make explicit create vs update changes
* Adds change creation logic into `add`, `update`, and `delete` methods
* Updates existing move, copy, publish, sync, and deploy changes to use the new Change classes
* Removes unused methods on the resource class that modify tables, to prevent future developers from using them without the appropriate change updates
* Updates the server sync …
> Localize change sync operations

- contentcuration/contentcuration/frontend/channelEdit/components/ResourcePanel.vue
- contentcuration/contentcuration/frontend/shared/mixins.js
This pr fixes the continuous loading spinner when previewing a searched channel resource.
- Select a channel
- Click "Add" button, then select "Import from other channels"
- Search for channel resources using a desired keyword
- Click on the result card(s) that come(s) up
-  Preview modal opens but spinner keeps on loading
- Select a channel
- Click "Add" button, then select "import from other channels"
- Search for channel resources using a desired keyword
- Click on the result card(s) that come(s) up
- Preview modal should display information about the selection
Fixes https://github.com/learningequality/studio/issues/3956
----
PR process:
Testing:
___
> Fixes loading spinner issue

- contentcuration/contentcuration/frontend/shared/styles/modulePlaceholder.js
- modulePlaceholder.js
- webpack.config.js
Makes an update to webpack to ensure that the /vuetify/src/stylus is properly overridden.
Run a local version of the production environment - seems to work!
https://github.com/learningequality/studio/assets/17235236/87faf765-50ae-42cc-9e8b-36ad4e4a46c4
```
yarn build
yarn run runserver
```
using Arabic
Fixes reopened https://github.com/learningequality/studio/issues/3499
The random empty placeholder file is 1) in a weird place and 2).... kind of confusing?  I just don't know a logical place to move it but can do so and update the path. 
(Also, since I will be out Friday, reviewer(s) pushing a change to this directly is 1000% fine with me)
----
PR process:
Testing:
___
> Update webpack for proper RTL build, using a placeholder module

- Makefile
- contentcuration/kolibri_public/management/commands/export_channels_to_kolibri_public.py
Updates management command to publish existing public channels to be more robust
> Update Kolibri public channel export to kolibri_public to be more robust

- webpack.config.js
Modifies the changes made in my last PR to update RTL vuetify stylus files. The devserver was breaking
1. Run `yarn run devserver`
2. Run `yarn run devserver:hot`
3. Run `yarn run build` `yarn run runserver` 
All should build
___
----
PR process:
Testing:
___
> Update webpack (again) to ensure devserver doesn't break

- contentcuration/contentcuration/frontend/channelEdit/components/edit/SavingIndicator.vue
- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
- contentcuration/contentcuration/frontend/shared/__tests__/app.spec.js
- contentcuration/contentcuration/frontend/shared/app.js
- contentcuration/contentcuration/frontend/shared/data/index.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/frontend/shared/vuex/syncProgressPlugin/index.js
* Switches the Vuex plugin for monitoring unsynced changes to use a liveQuery rather than the Dexie Observable `db.on('changes'` in the hope of more reliability
* Switches the final use of the Resource listeners to use a liveQuery to increase reliability of redirect on logout
* Updates the SavingIndicator component to make it use the global state when no nodeIds prop is passed
* Adds the SavingIndicator component to the channel edit toolbar
1. Checked that the vuex state properly updated when there were unsynced changes
2. Confirmed that the current beforeunload handler does properly alert if there are unsynced changes when closing the tab
3. Opened a second tab and logged out in that, confirmed that both tabs redirected to the accounts page
4. Made a change and quickly exited from the …
> Display sync changes in channel edit toolbar

- contentcuration/contentcuration/tests/test_exportchannel.py
- contentcuration/contentcuration/utils/publish.py
* Removes an unnecessary json.dumps during publish that was double wrapping the JSON
1. Wrote a regression test.
Fixes #4141
> Prevent options being a string rather than JSON

- .editorconfig
- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/__tests__/actions.spec.js
- contentcuration/contentcuration/frontend/shared/data/__tests__/applyRemoteChanges.spec.js
- contentcuration/contentcuration/frontend/shared/data/__tests__/changes.spec.js
- contentcuration/contentcuration/frontend/shared/data/applyRemoteChanges.js
- contentcuration/contentcuration/frontend/shared/data/changes.js
- contentcuration/contentcuration/frontend/shared/data/constants.js
- contentcuration/contentcuration/frontend/shared/data/locks.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/frontend/shared/data/serverSync.js
- contentcuration/contentcuration/frontend/shared/utils/deferred.js
- jest_config/jest.conf.js
- jest_config/setup.js
- package.json
Supersedes: https://github.com/learningequality/studio/pull/3733
Adds logic that increments and decrements the `total_count`, `resource_count`, and `coach_count` when adding, updating, copying or moving nodes. The code processes change events, either caused by writes to indexedDB or changes from other users, and uses that information to update the ancestor node counts accordingly
1. Create a new channel
2. Add a folder `Folder A`, then a `Folder B` inside of that, and `Folder C` inside of `B`
3. Upload a resource to `Folder C`
4. Go back to the `My Channels` page
5. Reopen the channel
6. Observe the resource count on `Folder A`
7. Duplicate the resource in `Folder C`
8. Repeat steps 4-6
9. Mark one of the resources in `Folder C` as coach content
10. Repeat steps 4-6, but verify the coach …
> Update aggregate counts when adding, updating, copying, or moving nodes

- contentcuration/contentcuration/frontend/shared/views/Breadcrumbs.vue
This pr updates the breadcrumb item `isFirst` property and adds the `isFirst` property to `VListTileTitle` in `Breadcrumbs.vue` which fixes the incorrect folder order/layout for folders with long titles.
Before:
After:
1. Open a channel with multiple nested folders
2. Rename a folder so that it's name is longer than 50 characters
3. Navigate to the nested folders and also try resizing the browser window size
4. Confirm that only the first navigation item is the channel name and if the folder title is too long, it should be truncated
Fixes #4006 
PR process:
Testing:
___
> Fixes incorrect folder order/layout for folders with long titles

- contentcuration/contentcuration/frontend/shared/data/__tests__/ContentNodeResource.spec.js
- contentcuration/contentcuration/frontend/shared/data/__tests__/changes.spec.js
- contentcuration/contentcuration/frontend/shared/data/applyRemoteChanges.js
- contentcuration/contentcuration/frontend/shared/data/changes.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
This pr fixes the failure  of the undo button to revert back the changes on delete a resource(s) in a channel.
https://github.com/learningequality/studio/assets/5203639/365ceefb-5e4e-4943-ae44-df45bb383c2b
No
- Login into studio
- Select a particular channel
- Try to delete a resource by checking an item(s) and clicking on the "Delete" icon
- You will be presented with a Snackbar with a success message and an `UNDO` button to undo the changes made
- Click the undo button before the Snackbar dismisses.
Fixes #4116 
----
PR process:
Testing:
___
> Fixes undo button on snackbar

- contentcuration/contentcuration/tests/test_exportchannel.py
- contentcuration/contentcuration/utils/publish.py
* Removes all json.dumps that are now being written to JSONFields and so are unnecessary - updates tests accordingly
* Prevents assessment metadata processing from editing data that is later written into the exported channel database by doing a deepcopy of the dict - updates tests accordingly
Just the automated tests.
> Fix publish regression and prevent superfluous data export

- contentcuration/contentcuration/frontend/channelEdit/components/ResourceDrawer.vue
- contentcuration/contentcuration/frontend/channelEdit/components/ResourcePanel.vue
- contentcuration/contentcuration/frontend/channelEdit/constants.js
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ContentTreeList.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ImportFromChannelsModal.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchResultsList.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/importFromChannels/actions.js
- contentcuration/contentcuration/frontend/shared/data/public.js
- Converts exercise mastery to completion criteria for a public API response
- Fixes issue previewing exercises in import search, caused by `?tab=` routing
- Rendering topics in search failed without `resource_count`
- Changes page size options to reduce likelihood of failed searches
- Changes default page size to 10 instead of 25
- Enforces page size is one of available options
- Adds hacks if we fail to side-load some nodes
- Only loads `published` nodes when browsing (not searching) through public channels
Initially this was done to test fixes aimed at resolving JSON parsing issues
1. I manually edited `fetchResourceSearchResults` Vuex action to use same search API response as on `hotfixes`
2. I manually edited the public `ContentNodeViewset` to proxy requests to hotfixes
3. I observed …
> Finalize public API integration with import search 

- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/importFromChannels/actions.js
- contentcuration/contentcuration/frontend/shared/data/public.js
- Adds `parent` when converting from public node format to Studio's IDs
1. Create a channel
2. Add a topic and put content in the topic
3. Make the channel public
4. Publish the channel
5. Create a second channel
6. Use the import search to search for resources added to the topic in the first channel
7. Preview resources from search
8. Click the 'Go to location' and ensure it opens the correct topic and resource panel preview
It appears the search results are rendering in an order that is different than what is returned from the server.
Fixes: https://github.com/learningequality/studio/issues/4168
----
PR process:
Testing:
___
> Fix broken 'Go to location' link in Import Search

- contentcuration/kolibri_public/tests/test_mapper.py
- contentcuration/kolibri_public/utils/mapper.py
* Adds ancestor annotation during the mapping process
* Adds a test for ancestor annotation during the mapping process
1. Reran the export to kolibri_public management command with Hsoub Academy
2. Verified that the ancestors were being properly returned from the API endpoint, e.g.:
Fixes #4177
----
PR process:
Testing:
___
> Add ancestor annotation to kolibri_public export mapper.

- contentcuration/contentcuration/tests/test_exportchannel.py
- contentcuration/contentcuration/utils/publish.py
- contentcuration/contentcuration/viewsets/base.py
- contentcuration/contentcuration/viewsets/contentnode.py
- contentcuration/contentcuration/viewsets/sync/utils.py
- Updates the change tracker to re-raise exceptions, ensuring we can actually report them to Sentry
- Updates publishing to skip exercises that have missing/broken mastery criteria, as if they were incomplete
- Updates copy operation to match other types of changes, by using try/except to catch and attach errors
1. Ran tests
Resolves https://github.com/learningequality/studio/issues/4163
Followup https://github.com/learningequality/studio/issues/4173
----
PR process:
Testing:
___
> Skip broken exercises and properly report exceptions

- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
This pr Prevent "Source" fields edits for copied/imported resources. Also please see this [comment](https://github.com/learningequality/studio/issues/3111#issuecomment-1599071565) for context on fix made
Please see issues #3111  and #4090. 
No
___
1. Create a channel A and channel B.
2. Upload a file in channel A and then import the same file in channel B.
3. Edit all details of the file in channel B.
5. You should not be able to edit any of the fields under the "Source" section of the edit form.
Fixes https://github.com/learningequality/studio/issues/3111 and https://github.com/learningequality/studio/issues/4090
----
PR process:
Testing:
___
> Prevent source edits for copied/imported resources

- contentcuration/contentcuration/frontend/shared/views/MainNavigationDrawer.vue
- Closes the navigation drawer when clicking the 'Change language' navigation item, launching the modal to switch languages
1. Signed in
2. Shrunk the viewport to the reported issue size
3. Opened the navigation drawer
4. Clicked 'Change language'
5. Observed the nav drawer closed when the modal opened
Fixes #4185
----
PR process:
Testing:
___
> Close nav drawer when clicking to change language

- contentcuration/contentcuration/middleware/locale.py
Kolibri public APIs were not ignoring language settings because our custom middleware allowed language settings to get applied. This PR fixes that by setting the default language before the view function runs.
1. Change the UI language to something other than English.
1. Query the public API for something that doesn't exist, e.g. https://unstable.studio.learningequality.org/api/public/v2/contentnode/8e6574944e1949c197faa22ff3c918dc/
1. Observe the detail message is still indeed in English.
___
Performing manual verification steps should provide good confidence.
Closes https://github.com/learningequality/studio/issues/4118.
----
PR process:
Testing:
___
> Fix to ignore language settings for kolibri public APIs

- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/tests/test_exportchannel.py
- contentcuration/contentcuration/utils/publish.py
- contentcuration/contentcuration/viewsets/channel.py
- contentcuration/kolibri_content/router.py
- contentcuration/kolibri_public/tests/test_mapper.py
* Adds preemptive handling of channels that are completely empty, to prevent Integrity Errors caused by trying to create a ChannelMetadata object when there is no root node to make a Foreign Key to
* Adds a regression test to handle this
* Adds some better clean up of database connections that are created by the content database context manager - otherwise tests that test errors in the publishing process always produce errors during teardown
* Migrates to a custom exception class for errors raised when the root node is not publishable, so it can be specially handled to not set the channel as publishable again
1. Created a regression test that replicated the issue
2. Fixed the issue
3. Reran the test
4. Profit!
This doesn't do anything about how someone was able to publish a channel while …
> Empty channels publish handling

- contentcuration/kolibri_public/models.py
* Code copied from Kolibri was doing OR filtering for multiple metadata labels rather than AND
* This has been fixed in Kolibri in https://github.com/learningequality/kolibri/pull/10986/commits/f832ef0201569db19c2cffcf5b395bbfbb297306
* This copies that fix to Studio
This is currently reliant on the regression tests in Kolibri to guarantee this behaviour.
This is required to finalize the fix for the issues described here: https://github.com/learningequality/kolibri/issues/10975#issuecomment-1634875196 where selecting multiple categories or learning activities would show resources that matched ANY, not ALL.
----
PR process:
Testing:
___
> Fix bitmask filtering by multiple labels for AND rather than OR

- contentcuration/contentcuration/db/models/manager.py
- contentcuration/contentcuration/tests/test_contentnodes.py
* Adds `ignore_conflicts=True` when bulk creating Tag through objects to prevent errors from duplicated entries which break copying, but are not an issue.
* Adds a TODO for future cleanup of Tag creation to leverage the same
I couldn't reproduce this so went for the minimal fix - as long as the Python tests pass, I think this is adequately covered by automated tests.
Fixes #4221
----
PR process:
Testing:
___
> Prevent errors when creating already existing tag through model entries.

- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchFilters.vue
- contentcuration/contentcuration/frontend/shared/views/form/MultiSelect.vue
Fixes #4166 
----
PR process:
Testing:
___
> added text truncate in import channel dropdown

- contentcuration/contentcuration/frontend/shared/data/changes.js
- contentcuration/contentcuration/frontend/shared/vuex/indexedDBPlugin/index.js
This PR fixes undo of copying. The problem was that the delete operation wasn't triggering vuex state update.
1. Create a channel then create a contentnode.
2. Attempt its copying.
3. Wait for copy to finish, when snackbar appears upon copy completion, click on 'UNDO'.
4. See whether the node gets removed or not. Refresh the page and make sure the node doesn't show up. 
___
Performing manual verification steps should make the PR good to merge.
Closes https://github.com/learningequality/studio/issues/4204.
----
PR process:
Testing:
___
> Fixes undo of copying

- contentcuration/kolibri_public/import_metadata_view.py
- contentcuration/kolibri_public/tests/test_importmetadata_api.py
Fixes issue with import metadata public endpoint where mptt fields would be excluded.
Caused by the lack of mptt fields on abstract model's meta
1. Updated tests
2. Made tests print out all the fields being returned
3. Confirmed the mptt fields were now being properly returned!
> Enhance tests and add special handling for mptt fields.

- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
- contentcuration/contentcuration/frontend/shared/vuex/file/__tests__/module.spec.js
- contentcuration/contentcuration/frontend/shared/vuex/file/actions.js
- contentcuration/contentcuration/frontend/shared/vuex/file/utils.js
- package.json
- yarn.lock
This code aims to extract metadata from H5P content package.
This Pr is a part of GSoC Project linked with the [issue #4081](https://github.com/learningequality/studio/issues/4081).
- Checked if the uploaded file is h5p or not
- Extract metadata through `getH5PMetadata`
1. Use jszip to load the uploaded H5P file asynchronously.
2. Once loaded, parse h5p.json file and read the file as text
3. Then parse the text to json so that we can extract the data.
4. Data extracted are:
- title
- language
- authors
- license 
----
PR process:
Testing:
___
> Implementation to extract metadata from H5P Content Package

- contentcuration/automation/admin.py
- contentcuration/automation/apps.py
- contentcuration/automation/models.py
- contentcuration/automation/tests.py
- contentcuration/automation/views.py
- contentcuration/contentcuration/dev_settings.py
Adds an empty Django app "automation" that will be the API for new AI features.
1. Step 1
2. Step 2
3. ...
___
----
PR process:
Testing:
___
> New django app 'automation' for future AI features

- contentcuration/contentcuration/frontend/channelEdit/utils.js
This pr fixes the incorrect value displayed when `Practice quiz` is selected as the `Completion` type for a new Exercise.
1. Sign in to Studio and open a channel
2. Create an exercise and set the Completion to `Practice quiz`.
3. The resource metadata window show `Practice quiz` as `Completion` value.
4. Edit the completion process to another type and that no regressions are present
https://github.com/learningequality/studio/assets/5203639/21be1885-9f02-47d0-9aa3-5423611e86b5
No
___
After setting up the project's development dependencies, and ensuring that Studio is running locally;
1.  Sign in to Studio and open a channel
2. Create an exercise and set the Completion to `Practice quiz`.
3. The resource metadata window show `Practice quiz` as `Completion` value.
4. Edit the completion …
> Fixes incorrect value for Practice quiz

- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeEditListItem.vue
- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/StudioTree/StudioTree.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/StudioTree/StudioTree.vue
- contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreePage/index.spec.js
- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ImportFromChannelsModal.vue
- contentcuration/contentcuration/frontend/channelEdit/views/NodePanel.vue
- contentcuration/contentcuration/frontend/channelEdit/views/progress/ContentNodeCopyTaskProgress.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/getters.js
- contentcuration/contentcuration/frontend/shared/data/__tests__/ContentNodeResource.spec.js
- contentcuration/contentcuration/frontend/shared/data/__tests__/changes.spec.js
- contentcuration/contentcuration/frontend/shared/data/changes.js
- contentcuration/contentcuration/frontend/shared/data/constants.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/viewsets/contentnode.py
- contentcuration/contentcuration/viewsets/sync/constants.py
This PR brings in the capability to retry failed copies and detection of failing copies.
To generate copy error state on the frontend, I raised an exception from the backend copy function. These are the checks I've performed:-
1. Checked whether error in the `changesForSyncing` table are detected.
3. Checked whether importing from channels errors out.
4. Checked whether copying completes.
5. Checked whether retrying completes successfully when the exception is removed from the backend code.
6. Checked whether after multiple failures, retrying still reaches success upon exception removal.
7. Copying multiple nodes together by selecting them works as expected.
8. When copy is failed, the node can be removed.
The below screenshot is the current design, it's matching with the expected design. …
> Allow users to retry copy failures

- contentcuration/contentcuration/frontend/shared/data/serverSync.js
This PR fixes frontend errors due to missing attributes on change objects. Particularly fixes the move and delete operations. `oldObj` and `parent` were missing in move operation and `oldObj` was missing for delete operation.
1. Create a channel.
2. Share it with another user.
3. Create several nodes, and move the nodes.
4. The changes should be reflected on other user's frontend without any console errors.
___
Performing manual verification steps should be enough.
Closes https://github.com/learningequality/studio/issues/4209.
----
PR process:
Testing:
___
> Fix missing attributes from change objects

- contentcuration/search/viewsets/contentnode.py
This PR makes import from other channel search super fast (reduced query time by almost half) by removing annotations that are no longer needed due to Kolibri public API providing those information.
Just make sure that import search works.
___
Making sure that import search works should make this PR good to go.
Closes https://github.com/learningequality/studio/issues/4266.
----
PR process:
Testing:
___
> Super Duper Fast Import Search :rocket:

- contentcuration/contentcuration/frontend/shared/views/LanguageDropdown.vue
- contentcuration/contentcuration/frontend/shared/views/form/MultiSelect.vue
This pr fixes the incorrectly truncated channel titles in 'Channel/source' and 'Language' dropdowna in the 'Import from channels' page search filters by adding the `dir="auto"` attribute to the dropdowns to allow for automatic handling of the text directions.
1. Go to https://hotfixes.studio.learningequality.org/en/accounts/#/ and sign in
2. Change the language to Arabic.
3. Open a channel and select the 'Import from channels' option
4. Perform a search and observe the channel titles and languages(the long texts) in the 'Channel/source' and 'Language' drop-downs respectively.
**After:**
___
1. Go to http://localhost:8080/en/accounts/#/ and sign in
2. If you need more channels. you can use the command below;
- `python manage.py restore_channel <channelId> --download-url …
> Fixes incorrectly truncated channel titles in 'Channel/source' and 'Language' dropdowns

- contentcuration/kolibri_public/tests/test_public_v1_api.py
- contentcuration/kolibri_public/views_v1.py
- Adds instance ID to the public info API response, using `le-utils` function for generating it used in both Kolibri and now Studio
1. Added the instance ID
2. Updated test to check it
3. Verified test passed
___
- Tests pass?
- `api/public/info` returns it?
https://github.com/learningequality/le-utils/pull/111
----
PR process:
Testing:
___
> Add instance ID to public API response

- contentcuration/automation/tests/appnexus/test_base.py
- contentcuration/contentcuration/utils/transcription.py
Adds a blueprint of Whisper Backend and Adapter needed for transcription project. 
Closes #4284 
----
PR process:
Testing:
___
> Adds whisper backend

- contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreePage/index.vue
- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.vue
- contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelItem.vue
This pull request replaces occurrences of the `router-Link` tag with `KrouterLink`.
https://github.com/learningequality/kolibri-design-system/issues/219
If this pull request is accepted and merged, I plan to submit additional pull requests addressing other issue with more extensive changes. The current pull request contains only minor modifications related to that issue.
PR process:
Testing:
___
> Changed the router-link tag to KrouterLink

- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeEditListItem.vue
- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
This PR aims to fix the misalignment of copy failure retry action which is triggered when the copy operation is unsuccessful in copying a node(s). 
To generate copy error state on the frontend, I raised an exception from the backend copy function. The verification steps I performed:
1. Ran all the tests
2. Checked if the frontend for the retry button is as expected.
Before:
After fixing the issue:
No. It was just a simple frontend CSS fix.
___
Closes #4272 
The CSS fix works fine for all devices. 
----
PR process:
Testing:
___
> Fix misalignment of copy failure retry CTA

- contentcuration/contentcuration/viewsets/sync/endpoint.py
- Fix the incomplete query for fetching the TaskResult and CustomTaskMetadata in return tasks.
1. Trigger a task other than apply_channel_changes, apply_user_changes.
2. Sync does not crash now and returns tasks correctly.
As there is no foreign key relation between the TaskResult and CustomTaskMetadata models the retrieval for both of them takes more than 2 queries fetching and filtering the same object.
closes #4323
PR process:
Testing:
___
> Fix the incorrect retrieval query in return_tasks function

- deploy/nginx.conf.jinja2
- k8s/images/nginx/Dockerfile
- k8s/images/nginx/download_sigil.sh
Fixes https://github.com/learningequality/infrastructure/issues/452. Nginx is the source of the timeout. Extends this to 300 seconds (5 minutes).
First commit is to update and cleanup Sigil, the templating engine we use for nginx.
> Fix timeout caused by nginx

- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeEditListItem.vue
- contentcuration/contentcuration/frontend/channelEdit/components/quickEdit/EditTitleDescriptionModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/quickEdit/__tests__/EditTitleDescriptionModal.spec.js
- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
- contentcuration/contentcuration/frontend/channelEdit/views/NodePanel.vue
- contentcuration/contentcuration/frontend/shared/utils/validation.js
- package.json
Add a quick edit modal to edit content nodes titles and descriptions.
https://github.com/learningequality/studio/assets/51239030/079589cd-fb94-41e8-b5c2-2c0d939f2342
1. Go to update a channel content
2. Click on the edit button besides the menu button of a content node.
Closes #3413
PR process:
Testing:
___
> Quick edit modal for content title and description

- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchFilterBar.vue
Fixes the `removeChannel` method in `SearchFilterBar` component by using the correct computed property name as per `FilterMap`. 
[video-2023-12-23_21.39.47.webm](https://github.com/learningequality/studio/assets/26724128/6cd6d346-ab0e-4d63-8d20-43fa2c9e39f0)
___
Performing manual verification steps should make this PR good to go. Easy steps -- 
1. Go to import search.
2. Search for any keyword.
3. Select a channel from the filter.
4. Remove that channel filter by clicking on "x" on the chip below search bar. 
5. No error on the browser console should be there.
Closes https://github.com/learningequality/studio/issues/4331.
----
PR process:
Testing:
___
> Fix wrong computed prop name

- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditLanguageModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditTitleDescriptionModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/__tests__/EditLanguageModal.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/__tests__/EditTitleDescriptionModal.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/index.vue
- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
Add a quick edit modal to edit content nodes languages. Also add an checkbox to update descendants languages, but this does not work for now until #4372 is merged.
https://github.com/learningequality/studio/assets/51239030/d78536f3-373f-48da-b939-aac0c0b32388
___
1. Go to update a channel content
2. Click on the "Edit Language" option on the content node menu.
3. Or you can select multiple content nodes and select "Edit language" on the bulk toolbar.
Closes #3415
The "clear" button on the search textbox should be included on KDS first, and we should add just a prop in this code.
----
Testing:
___
> Quick edit modal for content language

- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ChannelList.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchOrBrowseWindow.vue
When the new search page opens, the filter is not applied, to tackle this issue, we are using the 'languages' param which is then imported by the language filter.
1. Import from other channels
2. Select a language and search item and click Search
3. The new page will have the selected language
Before:
https://github.com/learningequality/studio/issues/4089#issue-1720351313
After:
At present, upon clicking 'back to browse,' the language selection is not retained. It resets to nothing. This decision was made due to the introduction of a new page where users can select multiple languages. Fetching the previously selected language(s) might lead to errors due to this change in the user flow. 
___
1. Import from other channels
2. Select a language and search item and click Search
3. The new page …
> [fix] Import applied language filter

- contentcuration/contentcuration/frontend/shared/views/LanguageDropdown.vue
Fixes #2074
As stated, the native_name has been changed to first_native_name as native_name can be a comma separated list of names.
1. Login and click on edit channel details
2. The dropdown of language is there which can be verified
3. The dropdown currently shows the list of languages which can be changed
----
PR process:
Testing:
___
> issue number 2074 resolved

- contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreePage/index.vue
- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
Updated IconButton to use KComponents (KRouterLink, KIcon & KIconButton) instead.
https://github.com/learningequality/kolibri-design-system/issues/219
The icons that have been changed
___
This is just a trial PR to confirm that I am headed in the right direction or not.
If this pull request is accepted and merged, I plan to submit additional pull requests addressing other issue with more extensive changes. The current pull request contains only minor modifications related to that issue.
----
Testing:
> Changed IconButton to KRouterLink

- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditResourcesNeededModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/__tests__/EditLanguageModal.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/__tests__/EditResourcesNeededModal.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/index.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/ResourcesNeededOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
- contentcuration/contentcuration/frontend/shared/utils/helpers.js
Add a quick edit modal to edit content nodes learner needs.
https://github.com/learningequality/studio/assets/51239030/0add180e-cf01-410a-8231-bbd5ebb8112f
___
1. Go to update a channel content
2. Click on the "Edit 'what is needed'" option on the content node menu.
3. Or you can select multiple content nodes and select "Edit 'what is needed" on the bulk toolbar.
Closes #3422
----
PR process:
Testing:
___
> Quick edit modal to edit "what you will need"

- contentcuration/contentcuration/frontend/shared/data/applyRemoteChanges.js
Here I've fixed the `undefined original_source_node_id TypeError`. After importing a contentnode, when this change was getting relayed to the other channel editor, we were getting that error on the other channel editor's end because the contentnode which has to be imported was not present in the Indexed DB. 
Investigation credits to our ironman @bjester. Code credits to me.
1. Login as a@a.com (admin).
1. Create a new channel with any resource, for e.g. one PDF file. Publish it and make it public.
1. Create another channel.
2. Invite user@b.com to this new channel with edit rights.
3. On another browser window login as user@b.com, accept the invitation and open the invited channel.
4. From admin browser, import a content from the public channel.
5. Check the user@b.com browser, the …
> Fix node availability when propagating import copy

- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeContextMenu.vue
- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeEditListItem.vue
- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/StudioTree/StudioTree.vue
- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
Catch keyboard focus when contentNode menus are opened. Added conditional render to menus since Vuetify just mounts the menu once by default, and this does not allow the `mounted` or `destroyed` hooks to be executed.
Verified that these menus are keyboard-accesible now:
1. ContentNode menus.
2.  ContentNode deails menus.
3. Breadcrumbs menus.
4. StudioTree elements menus.
5. StudioTree elements context menu.
6. ContentNode context menu.
https://github.com/learningequality/studio/assets/51239030/745e28d5-9acd-4116-8115-2a2c775e76c4
___
1. Open a channel
2. Navigate to contentNodes Menus with the keyboard
Closes #4369
Keyboard navigation is not entirely consistent for now (the outline color changes for example) But this would be solved when the menu is updated to `KDropdownMenu`.
----
PR …
> Make ContentNode Menus Keyboard accessible

- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditView.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/getters.js
The approach used to improve error reporting in the edit modal is by getting all the errors list. Mapping that errorsList with their names and reference objects. Using that reference object we'll be using scrollIntoView to allow the user to direct themselves to the required input left blank.
1. Click on a channel
2. Access and edit resources
3. The Edit details tab will open
Some changes that needs to add to the current PR are: 
- Some CSS properties need to be added to the list of errors such as hover cursor, and underlining.
-  The `scrollIntoView` moves into view a bit below the actual input element.
- If there is only 1 issue then the scrollIntoView will scroll to that one target element.
The PR is in reference with issue: https://github.com/learningequality/studio/issues/2924
___
1. …
>  Improve errors reporting in edit modal

- contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelItem.vue
- contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelStar.vue
Updated IconButton to use KComponents (KIcon & KIconButton) instead. This is the part of a series of changes, to be made under [Issue #219](https://github.com/learningequality/kolibri-design-system/issues/219) in Kolibri Design System.
https://github.com/learningequality/kolibri-design-system/issues/219
The icons that have been changed
Could not find the Bin icon under [Icons](https://design-system.learningequality.org/icons/l), so used delete icon for `Delete Channel` dropdown option.
Testing:
> Updated Components to KComponents

- contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSetModal.vue
Fixes #4144
I've added a new state mechanism to prevent concurrent save operations. Previously, multiple clicks on the save button could trigger simultaneous saves, leading to potential issues.
Changes Made:
Added a saving state to prevent multiple save operations.
Purpose:
This ensures that a save/submit  operation must complete before another one can be initiated, preventing unintended side effects.
1. Step 1
2. Step 2
3. ...
___
----
PR process:
Testing:
___
> double submit issue resolved

- contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreePage/index.vue
Fixes #4408 
1. Step 1
2. Step 2
3. ...
___
----
PR process:
Testing:
___
> Addressing Incorrect Topic Empty State Issue in Staging Preview

- contentcuration/contentcuration/frontend/settings/pages/Storage/RequestForm.vue
- contentcuration/contentcuration/frontend/shared/i18n/index.js
- contentcuration/contentcuration/frontend/shared/languageSwitcher/LanguageSwitcherModal.vue
- package.json
- yarn.lock
Upgrades KDS version in Studio from the KDS commit [e9a2ff34716bb6412fe99f835ded5b17345bab94](https://github.com/learningequality/kolibri-design-system/commit/e9a2ff34716bb6412fe99f835ded5b17345bab94) from Jun 7, 2022, to the new KDS `v3.0.0` (and several versions in between).
First, I audited Studio, KDS release notes and diffs to get an idea of the scope and affected places. Results are here https://github.com/learningequality/studio/issues/4411.
For components that shouldn't have breaking updates, I previewed them visually at a few places. Quite often on both desktop and mobile. I also tried to use them when relevant. Checked the nature of changes in the release notes, and if I knew about some updates that weren’t in the older release notes, I peaked into git diffs to see if there’s …
> Upgrade the unstable branch to KDS v3.0.0

- contentcuration/contentcuration/utils/sync.py
- contentcuration/contentcuration/viewsets/assessmentitem.py
- contentcuration/contentcuration/viewsets/base.py
- requirements.in
- requirements.txt
I have remove django_bulk_update function in 2 files:
- contentcuration/contentcuration/utils/sync.py
- contentcuration/contentcuration/viewsets/assessmentitem.py
1. pytest command used for testing
___
- Pytest command to check whether functionalities are working 
- https://docs.djangoproject.com/en/3.2/ref/models/querysets/#bulk-update
- Referencing issue https://github.com/learningequality/studio/issues/4409
----
PR process:
Testing:
___
> update django_bulk_update with inbuilt bulk_update

- contentcuration/contentcuration/viewsets/channelset.py
Fixes : #4145 
Description:
In the current setup, the frontend was fetching and displaying all channels without properly handling the edit flag or checking if the channels were associated with the current user_id. This inconsistency led to sporadic issues where channels would sometimes show up in the admin list and sometimes not.
Changes Made:
Modified the frontend logic to only fetch and display channels where edit is set to true or the user_id matches the current user.
Ensured proper handling to prevent channels from being displayed inconsistently in the admin list.
1. Step 1
2. Step 2
3. ...
___
----
PR process:
Testing:
___
> admin-panel collection error resolved

- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditSourceModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/__tests__/EditSourceModal.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/index.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
- contentcuration/contentcuration/frontend/channelEdit/getters.js
- contentcuration/contentcuration/frontend/channelEdit/mutations.js
- contentcuration/contentcuration/frontend/channelEdit/store.js
- contentcuration/contentcuration/frontend/channelEdit/utils.js
- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
- contentcuration/contentcuration/frontend/shared/views/AboutLicensesModal.vue
- contentcuration/contentcuration/frontend/shared/views/LicenseDropdown.vue
Add a quick edit modal to edit resources attribution/source.
https://github.com/learningequality/studio/assets/51239030/1095ea36-de96-450f-a430-dd706aff152c
___
1. Go to update a channel content
2. Click on the "Edit source" option on the content node menu of a resource (non-folder).
3. Or select multiple resources (non-folders) and select "Edit Source" from bulk toolbar.
Closes #3420
----
PR process:
Testing:
- [ x If there are any front-end changes, before/after screenshots are included
___
> Quick edit modal to edit Source

- contentcuration/contentcuration/frontend/shared/app.js
Track input modality so that we can recognize when we are using keyboard navigation and show kds inputs outlines.
Checked the outlines of some KCheckboxes and KRadioButtons, and all of them were working fine.
___
1. Go to settings > storage > Open form
2. Check that KCheckBoxes has the correct outline when navigating with keyboard
Closes #4428
----
PR process:
Testing:
___
> Track input modality in studio frontend apps

- package.json
- yarn.lock
Replaces KDS GitHub reference from package.json in favor of using the npm package.
I discussed with @rtibbles that it doesn't matter that much if we pin minor or patch because of the dependabot workflow, so we went with patch `~`. This has a benefit of knowing exactly what version is installed.
I tried to run Studio locally and briefly previewed.
I think it should be fine to merge. The package version corresponds to the previously installed version so it doesn't introduce any new updates.
----
PR process:
Testing:
___
> Install npm KDS package

- contentcuration/contentcuration/frontend/settings/pages/Storage/RequestForm.vue
- contentcuration/contentcuration/frontend/shared/i18n/index.js
- contentcuration/contentcuration/frontend/shared/languageSwitcher/LanguageSwitcherModal.vue
- package.json
- yarn.lock
- Upgrade to v3 of KDS in hotfixes branch
None - see https://github.com/learningequality/studio/pull/4412
Yes the merge conflicts with unstable will need to be resolved
___
see https://github.com/learningequality/studio/pull/4412
see https://github.com/learningequality/studio/pull/4412
https://github.com/learningequality/studio/pull/4412
----
PR process:
Testing:
___
> Upgrade KDS to v3 in hotfixes branch

- .github/dependabot.yml
- package.json
- yarn.lock
- Updates KDS version from `v3.0.0` to `v3.0.1` ([KDS release notes](https://github.com/learningequality/kolibri-design-system/releases/tag/v3.0.1), no breaking changes)
- Pins KDS dependency to exact version
- Configure dependabot to run on Wednesday to sync its timing with KDS releases planned for Tuesdays
As there are no breaking changes I think it should be safe to merge
----
PR process:
Testing:
___
> Upgrade KDS to v3.0.1 and configure dependabot to run on Wednesday

- contentcuration/contentcuration/utils/publish.py
Fix #4470
Changes `save_export_database` function and its calling context within the `create_content_database` function. The goal is to include the channel version in the exported SQLite database filename.
1. Open studio in broswer.
2. Publish a new channel ( or update an existing channel).
3. Go to `./.docker/minio/content/databases/` to see the exported sqlite3 file name.
___
> Fix #4470: Add version in name

- contentcuration/contentcuration/frontend/shared/views/LanguageDropdown.vue
This PR fixes the bug when removing the language from a node. Until now, when deleting a language it was set to undefined, so the Changes model did not detect it as a change. Changing the saved value to null forces the Changes model to know that this value has been removed.
1. Edited a Channel.
2. Set a language of a resource.
3. Unset the language of the resource.
___
Fix #4493.
----
PR process:
Testing:
___
> Fix unsetting language

- contentcuration/contentcuration/frontend/accounts/pages/Create.vue
Migrated `Create.vue` to use the `Checkbox` component instead of the `VCheckbox` element.
Fixes #4492 
1. Checked the UI and the functionality locally
2. Ran the test suite
This PR used the `Vuetify` provided classes `v-messages`  and `v-messages_wrapper` to to consistently style all the error messages. This might need to be replaced with manual styles later. 
___
----
PR process:
Testing:
___
> Migrate `Create.vue` from `VCheckbox` to `Checkbox`

- package.json
- yarn.lock
Upgrades KDS from `v3.0.1` to `v3.2.0`
No updates are needed. Related release notes:
- https://github.com/learningequality/kolibri-design-system/releases/tag/v3.1.0
- https://github.com/learningequality/kolibri-design-system/releases/tag/v3.1.1
- https://github.com/learningequality/kolibri-design-system/releases/tag/v3.2.0
Also fixes https://github.com/learningequality/studio/pull/4502#issuecomment-2067713375
- Previewed release notes
- Briefly run Studio
- You can see the release notes
- I think it should be safe to merge as it's just patch or minor releases
PR process:
Testing:
___
> Upgrade KDS from v3.0.1 to v3.2.0

- contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/actions.js
- contentcuration/contentcuration/frontend/shared/data/__tests__/ContentNodeResource.spec.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
- Updates resource method `getByNodeIdChannelId` to use proper format for the query parameter
- Updates other potential issues related to `[node_id+channel_id]__in` filtering
1. Create public channel with some nodes and publish it
2. Sign out
3. Sign into Studio
4. Create new channel (without opening the public channel)
5. Click <kbd>ADD</kbd> and select 'Import from channels'
6. Search for one of the public channel nodes
7. Click the clipboard icon on the node
___
Follow the above steps
I did update some clipboard actions that seemed to be passing a flattened array for `__in` query
Fixes https://github.com/learningequality/studio/issues/4508
----
PR process:
Testing:
___
> Properly format node_id+channel_id query parameter

- contentcuration/contentcuration/frontend/administration/pages/AdministrationIndex.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/BrowsingCard.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ChannelInfoCard.vue
- contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelItem.vue
- contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelStar.vue
- contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSelectionList.vue
- contentcuration/contentcuration/frontend/shared/app.js
- contentcuration/contentcuration/frontend/shared/styles/vuetify.scss
- jest_config/jest.conf.js
- Aligns `VCard` hover styling with how `KCard` hover styling will be implemented
- Removes previous logic related to handling hover background with `VCard`s containing buttons
- Updates admin to reduce row hover darkness
- Adds `.scss` file handling alongside existing `less` and `styl` handling for Jest
1. Created a new channel
2. Uploaded content to the channel
3. Marked the channel as public in the admin
4. Published the channel
5. Browsed the channel through 'Import from channels' modal
6. Browsed the channel through 'Content Library'
| Default | Hovered |
| --- | --- |
| ![Screenshot from 2024-05-02 08-00-18](https://github.com/learningequality/studio/assets/819838/567fa0d6-5114-496d-823a-bd7da793fdc5) | ![Screenshot from 2024-05-02 …
> Post-rebranding update to Card hover styling

- deploy/nginx.conf.jinja2
- Explicitly sets a few proxy settings to eliminate nginx configuration as a possible source of Studio 502 issues proxying to GCS
- Removes catalog server configuration
None
https://learningequality.slack.com/archives/C0WHZ9FPX/p1715724564260899
----
PR process:
Testing:
___
> Explicitly configure nginx proxy settings

- contentcuration/automation/tests/appnexus/test_base.py
- contentcuration/automation/utils/appnexus/base.py
- contentcuration/automation/utils/appnexus/errors.py
- contentcuration/contentcuration/tests/utils/test_cloud_storage.py
- contentcuration/contentcuration/tests/utils/test_recommendations.py
Implements the core funcitonlity and error handling of the `connect` and `make_request` methods on the `Backend` class.
Created various sub-classes of the `Backend` class testing its `connect` and `make_requests` methods.
___
Play with the `Backend` class, making sub-classes in the `test_base.py` file
Closes #4447
----
PR process:
Testing:
___
> Core functionality of `connect` and `make_request` methods on `Backend` class

- contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSelectionList.vue
Adds just a small quick-fix of margin and slightly darker drop shadow on hover so that the cards don't run into each other. 
More substantial fix to be addressed separately.
> add spacing and hover state to channel list cards

- contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogFilterBar.vue
- contentcuration/contentcuration/frontend/channelList/views/Channel/__tests__/catalogFilterBar.spec.js
- contentcuration/contentcuration/templates/channel_list.html
- contentcuration/contentcuration/views/base.py
- Removes pinned COVID card
1. Ran devserver
2. Loaded the channel list page
3. Verified no related errors from its removal
https://learningequality.slack.com/archives/C0LKEH6NM/p1717091295577929
----
PR process:
Testing:
___
> Remove pinned covid channel collection

- contentcuration/automation/utils/appnexus/base.py
- contentcuration/automation/utils/appnexus/errors.py
- contentcuration/contentcuration/tests/utils/test_recommendations.py
- contentcuration/contentcuration/utils/recommendations.py
This pr implements logic of the `embed_topics` and `embed_content` in the recommendations adapter
NA
- The `extract_content` method doesn't functions and will be implemented with https://github.com/learningequality/studio/issues/4455
___
Closes [#4448](https://github.com/learningequality/studio/issues/4448)
----
PR process:
Testing:
___
> Embed topics and content logic

- contentcuration/contentcuration/frontend/shared/data/applyRemoteChanges.js
This PR enhances the remote publish logic to safeguard against accidental overwrites of the `changes` and `published` statuses in IndexedDB, particularly in scenarios where multiple users are editing the same resource. It ensures that one user's publish action does not inadvertently overwrite another user's unpublished changes.
1. Log in to Studio using two separate user sessions (e.g., one in incognito mode and the other in a normal browser).
2. Make changes to the same content in both user sessions.
3. Publish the changes in one session.
4. In the other session, monitor the syncing changes. To test this thoroughly, you can throttle the browsers connection to offline mode and then restore it to confirm that changes remain intact before and after connectivity is restored.
5. Inspect the …
> Update publish logic with edge case

- contentcuration/contentcuration/frontend/shared/views/FullscreenModal.vue
changed lifecycle events in FullscreenModal for hideHTMLScroll logic
- The logic was handled by using the mount/destroy lifecycle events
- To account for all cases, replaced it with activation based lifecycle events
- Previous events led to sometimes having dual scrollbars"
after closing these modals, the scrollbar behaves normally
This PR addresses #1978
I have tested in Chrome 122.0.6261.131 (Windows)
tested in Brave 1.64.109 (Windows)
Firefox 20.04 (Ubuntu)
PR process:
Testing:
___
> Fix dual scrollbars when using FullscreenModal 

- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/tests/test_exportchannel.py
- contentcuration/contentcuration/viewsets/base.py
Implement cleanup of CustomTaskMetadata and add deletion tests.
- Properly clean up unwanted CustomTaskMetada objects.
- Add tests to ensure proper deletion 
1. Step 1
2. Step 2
3. ...
___
closes #4599 
----
PR process:
Testing:
___
> Fix regression with publish task

- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SavedSearchesModal.vue
- contentcuration/contentcuration/frontend/shared/data/resources.js
This pr fixes the issue occurring where attempting to save searches resulted in the error: `Attempted to save CreatedChange change for savedsearch before setting channel_id and user_id.`
This issue was fixed by adding `getUserId()` function to the Resource `SavedSearch`, using `saved_by` param to set user id.
This pr also adds a null check to the function `searchFilterCount()` within `SavedSearchedModal.vue` to ensure `val` is not null before reaching the string processing step, avoiding errors on `val.split`.
1. Sign in to studio and open an editable channel
2. Click the "Add" dropdown button and select "Import from channels"
3. Type a search term in the search field and click the "Search" button
4. Click "Save search" link
https://github.com/user-attachments/assets/26cf663f-52ef-4522-a34 …
> Fix saved search

- contentcuration/contentcuration/frontend/shared/views/details/Details.vue
Replaces use of `libraryMode` computed prop with `printing`, to prevent the improperly rendered external link icon on downloaded PDFs
On studio (with link):
Downloaded:
Channel (that has imported at least one piece of content from another channel) > Channel Details Modal > Download Channel Summary
Fixes #4094
----
PR process:
Testing:
___
> Fix mis-rendered external links on downloaded PDFs

- contentcuration/contentcuration/tests/views/test_settings.py
- contentcuration/contentcuration/views/settings.py
This PR adds a test case for the `StorageSettingsView` and changes the email subject line to explicitly use the user's email.
1. Ran `python manage.py test contentcuration.tests.views.test_settings`
___
Closes #4418.
----
PR process:
Testing:
___
> Add test for StorageSettingsView

- contentcuration/contentcuration/frontend/settings/pages/Account/index.vue
Updates string to more accurately display the current (if not ideal) behavior for account deletion with shared channels.
Create a brand new account
Create a channel and share it with someone so that they can edit it.
Go to Settings > Account and attempt to delete the account. See updated warning string. 
No, but it doesn't resolve the underlying problem, either 
___
Reference manual verification steps above.
Sort of fixes #4532 , at least as much as we can right now.
----
PR process:
Testing:
___
> Update account deletion string

- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ContentTreeList.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
- contentcuration/contentcuration/viewsets/contentnode.py
Avoid listing incomplete resources in "import from channels" view.
1. Tried loading incomplete resources that were already loaded in indexedDB.
2. Tried loading incomplete resources that havent been loaded before.
3. Verfied that the rest of valid resources/folders appear in the search.
Given this incomplete resource:
Before:
After:
___
1. Create incomplete resources in a given channel.
2. Publish the channel
3. Go to another channel and click on Add > Import from channels
4. Look for the incomplete resource, it should not appear.
Closes #4088
----
PR process:
Testing:
___
> Fix incomplete resource importable

- cloudbuild-production.yaml
- contentcuration/contentcuration/settings.py
- k8s/images/app/Dockerfile
* Changes how we read the commit hash, by setting it at app image build
> Set commit hash during docker build.

- contentcuration/contentcuration/tests/views/test_views_internal.py
- contentcuration/contentcuration/views/internal.py
* Adds a regression test to ensure that duplicate assessment_ids within a node raise a validation error rather than trying to make the node and then raising an IntegrityError
Wrote a regression test.
Fixes #4431
----
PR process:
Testing:
___
> Creates a regression test for and fixes duplicate node assessments returning a 500.

- k8s/images/app/Dockerfile
* Moves docker file arg and env var setting to the bottom of the docker file to reduce the impact on build caching
> Reduce impact on caching of arg env var setting

- contentcuration/contentcuration/frontend/settings/pages/Account/index.vue
- contentcuration/contentcuration/frontend/settings/pages/Storage/index.vue
- contentcuration/contentcuration/frontend/settings/pages/UsingStudio/index.vue
- docker-compose.yml
This merge request addresses the issue where external links in Studio did not have a visual indicator to distinguish them from internal links. The affected links also did not open in a new tab by default. To resolve this, the **KExternalLink** component has been replaced with the **ActionLink** component, and a CSS class **inline-icon** has been added to provide the necessary visual indication.
1. Step 1 : Replaced instances of `KExternalLink` with `ActionLink` to ensure consistent behavior and appearance across the application.
2. Step 2 : Added the `inline-icon` CSS class to the ActionLink component to display a pop-out icon for adjusting the position.
3. ...
https://github.com/user-attachments/assets/4db79b12-d93c-40a7-a540-77411d438270
- **In Settings -> page -> Account -> Index.vue : …
> Fix to issue #4606 : Links leading outside Studio need to have a pop out icon

- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/tests/test_contentnodes.py
- contentcuration/contentcuration/tests/views/test_views_internal.py
- contentcuration/contentcuration/tests/viewsets/test_contentnode.py
- contentcuration/contentcuration/viewsets/contentnode.py
Update mark_complete to handle completion criteria for non-exercises.
Use the updated function to add verification when a contentnode is marked complete via the API.
Added regression tests for new mark_complete behaviour, and for an API call setting a node as complete when it is not.
Fixes #4173
> Ensure that complete is not incorrectly set via the API

- contentcuration/contentcuration/frontend/shared/data/changes.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
When removing the last child of a folder, the folder was left without nodes, and within the undo transaction there was a resource.where() filter to find the siblings of the recovered node, but as it did not find siblings, it was making an API call, which caused the transaction to end before the api call returned, while there were still operations to be done within the transaction.
This PR just relocates the siblings query so that it is done before the transaction.
1. verified that removing the last child and then redoing it now worked correctly.
2. verified that the redo of the rest of the operations keep working correctly.
https://github.com/user-attachments/assets/c5cbbc1f-19b9-413d-9881-f0f8aaf33a18
___
1. Remove the last node of a channel/folder
2. Wait a couple of seconds for the …
> Fix undo remove last child

- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/tests/test_serializers.py
- contentcuration/contentcuration/tests/testdata.py
- contentcuration/contentcuration/tests/viewsets/test_flagged.py
- contentcuration/contentcuration/urls.py
- contentcuration/contentcuration/viewsets/feedback.py
Implements Serializers and viewsets to incorporate flag Feedback Mechanism. 
- Added serializer and viewsets required.
- URL routing for the same.
- Permission logic for serializer.
- Robust unit tests.
closes #4479
closes #4478
PR process:
Testing:
___
> Implements backend core to incorporate Flagging Mechanism 

- contentcuration/contentcuration/frontend/accounts/pages/Create.vue
- contentcuration/contentcuration/frontend/accounts/pages/Main.vue
- contentcuration/contentcuration/frontend/settings/pages/UsingStudio/index.vue
- contentcuration/contentcuration/frontend/settings/pages/__tests__/usingStudio.spec.js
- contentcuration/contentcuration/frontend/shared/views/policies/PolicyModals.vue
- contentcuration/contentcuration/frontend/shared/views/policies/PrivacyPolicyModal.vue
- contentcuration/contentcuration/frontend/shared/views/policies/TermsOfServiceModal.vue
- contentcuration/contentcuration/frontend/shared/views/policies/__tests__/policyModals.spec.js
- contentcuration/contentcuration/frontend/shared/vuex/policies/index.js
- contentcuration/contentcuration/frontend/shared/vuex/policies/index.spec.js
In `beforeRouteEnter` in `Main.vue` we check the `to.query.showPolicy` - if it's a valid policy it'll be shown to the user. Includes a check to help be sure this is the first page load.
The URLs would be:
https://studio.learningequality.org/en/accounts?showPolicy=privacy_policy
https://studio.learningequality.org/ar/accounts?showPolicy=privacy_policy
https://studio.learningequality.org/es-es/accounts?showPolicy=privacy_policy
https://studio.learningequality.org/fr-fr/accounts?showPolicy=privacy_policy
https://studio.learningequality.org/pt-br/accounts?showPolicy=privacy_policy
https://studio.learningequality.org/en/accounts?showPolicy=terms_of_service
https://studio.learningequality.org/ar/accounts?showPolicy=terms_of_service
https://studio.learningequality.org/es-es/accounts?showPolicy=te …
> Before entering Main, check for showPolicy query param to show policy

- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditCompletionModal.vue
- contentcuration/contentcuration/frontend/shared/views/contentNodeFields/CompletionOptions/index.vue
Fix save edit completion modal on exercise resources. MasteryCriteriaMofNFields was being validated even if we didnt need them.
1. Verified that edit completion modal was working with all completion types.
2. Verified that edit all details moadl was still working fine.
https://github.com/user-attachments/assets/2bc0c699-8fad-4175-9cf0-667f499988d2
___
Follow instructions in #4648.
Test that edit all details doesnt break.
Closes #4648.
----
PR process:
Testing:
___
> Fix save edit completion modal on exercise resources

- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
- contentcuration/contentcuration/frontend/channelEdit/views/NodePanel.vue
- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.spec.js
- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
- contentcuration/contentcuration/frontend/shared/data/constants.js
- contentcuration/contentcuration/frontend/shared/data/index.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/utils/pagination.py
- contentcuration/contentcuration/viewsets/contentnode.py
* Adds simple lft__gt based pagination to contentnode endpoint, only really usable when filtering by parent or tree_id
* Deletes unused pagination from the resource layer, and adds support for simple single value incrementing (e.g. lft) pagination to it
* Updates the UI to handle this
Make a topic with more than 50 children.
Check basic pagination works.
Clear cache and all indexedDB.
Load one additional page (so there should still be one more).
Reload the page.
Turn off the network connection in the network tab of the browser.
Press show more.
See that the additional page loads from indexedDB, and that even though there are no more nodes in IndexedDB, the cached pagination result allows 'show more' to still be shown.
Turn the network back on and press show more to see the remainder. …
> Paginate topics

- contentcuration/contentcuration/tests/viewsets/test_contentnode.py
- contentcuration/contentcuration/utils/nodes.py
- contentcuration/contentcuration/viewsets/contentnode.py
Add validation to automatically resolve cases where allowed none value of threshold was causing validation error. 
- Implement logic to resolve edge case with completion criteria objects.
- Add test to confirm the edge case.
1. Open studio in two different browsers.
2.  Login with admin user and userC.
3. Simultaneously open same ContentNode with content kind html5 in both tabs.
4. First change the completion criteria to reference model.
5. In one tab change to approx time model.
6. Simultaneously on other tab change the model to determined by resources.
7. Validation error does not arise.
Validation error would still come up for the cases where the changes just has a threshold field in it without the model information and may contradict with models that want it to be None. We would …
> Add validation for threshold none invalid cases

- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditAudienceModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditBooleanMapModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditLanguageModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditSourceModal.vue
Fixes #4649
Confirmed that on any individual editing action modal, '1 resource selected' does not appear at the top of the modal  
Example 
Now 
Previous 
___
----
PR process:
Testing:
___
> When only one resource is individually selected, do not write '1 resource selected' because it's confusing

- contentcuration/contentcuration/frontend/shared/views/policies/CommunityStandardsModal.vue
- contentcuration/contentcuration/frontend/shared/views/policies/PrivacyPolicyModal.vue
- contentcuration/contentcuration/frontend/shared/views/policies/TermsOfServiceModal.vue
Send the `policy` when emitting the `accept` event from Policy modals so that it works properly.
If you have already accepted the policies, you can use the following process to reset your user's acceptance. Be wary that the code will only update the first created user so be sure to verify that you're updating the user you want.
`./contentcuration/manage.py shell` to get a shell open
```
from contentcuration.models import User
me = User.objects.first()
me.policies = {}
me.save()
```
Now you should be able to accept all of the policies that need acceptance.
----
PR process:
Testing:
___
> Policy modals send policy to accept when accept is emitted

- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeOptions.vue
This pull request fixes the issue with the undo button's selection functionality not working correctly within the snackbar following the removal or deletion of a resource in `ContentNodeOptions.vue`.
The function `removeNode` is now called with an explicit argument, `onClick: () => this.removeNode([this.nodeId])`. This fixes potential issues by removing the reliance on direct access to `this.nodeId` within the function, which helps in cases where the function's context (`this`) may be ambiguous.
1. Removed a resource from a channel using the three-dot menu and selecting 'Remove'
2. Selected the Undo button in the snackbar.
Before:
https://github.com/user-attachments/assets/57e3feb7-d382-403b-9177-bfb1ec25b741
After:
https://github.com/user-attachments/assets/b355e627-bd05-45aa-96ba-faf7d95 …
> Fix the undo selection issue in the snackbar after resource deletion

- contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/Channel.vue
- contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNode.vue
- contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNodeOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/index.vue
- contentcuration/contentcuration/frontend/channelEdit/components/move/MoveModal.vue
- contentcuration/contentcuration/frontend/shared/views/form/Checkbox.vue
This pull request fixes the incorrect folder and resource count displayed when opening the `moveModal` from the `Clipboard` component. This pull request also fixes a selection issue in the `Clipboard`.
1. Select folder/resource in the clipboard
2. Click on the Move button
3. Observe the title with the correct count when the `moveModal` opens
Before:
After:
https://github.com/user-attachments/assets/99851e4b-444e-4b9c-8f4d-30091dc062cf
Fixes #3744 
----
PR process:
Testing:
___
> Fix clipboard moveModal incorrect resource count

- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/tests/test_contentnodes.py
Fixes regression caused by https://github.com/learningequality/studio/pull/4627
1. Created a regression test
2. See test fail
3. Fix test
___
----
PR process:
Testing:
___
> Prevent errors when extra_fields are null.

- contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelItem.vue
- contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSelectionList.vue
- contentcuration/contentcuration/frontend/channelList/views/ChannelSet/__tests__/channelSelectionList.spec.js
This pr fixes the UI glitch on card thumbnails experienced while creating collections. 
1. Click on the collections tab
2. Click on the "New Collection" button
3. Click "Select channels"
4. Navigate between "Content Channels" and "My Channes" while observing the channel cards.
5. Try to remove the description from one a channel and view it again
6. Also, try to select the channel by clicking on both the checkbox or anywhere on the card
___
See manual verificatiion
Fixes #4656
----
PR process:
Testing:
___
> Fixes UI glitch on cards in collections

- contentcuration/contentcuration/frontend/accounts/pages/__tests__/resetPassword.spec.js
- contentcuration/contentcuration/frontend/accounts/pages/resetPassword/ResetPassword.vue
- contentcuration/contentcuration/frontend/settings/pages/Account/ChangePasswordForm.vue
- Copies the string definitions for the password length validation to other places where passwords are updated (Reset password, Change password from user account page)
- Copies the validator functions over to the same components
- Ensures length > 8
- Adds a bit of height to the container of the KModal for the "Change password" because it would show a scroll bar whenever the errors were visible
1. Create an account
2. Change your password from your account page
3. Log out
4. Click "Reset password" on the login page
5. If you're running this locally, look at your server logs for the URL to reset your password otherwise check your email
6. Click the reset password link
- In all cases, if you put a password < 8 characters in length, you should see the appropriate error message.
- You should …
> (Change|Reset)Password components apply length validation

- contentcuration/contentcuration/frontend/shared/data/resources.js
Fixes oversight from https://github.com/learningequality/studio/pull/4615 where the frontend was not properly updated to use the new invitation accept API endpoint for synchronous acceptance of channel invitations
1. Invite another user to a channel
2. Accept that invitation as the other user
3. Rejoice!
Fixes #4643
----
PR process:
Testing:
___
> Fixes frontend to properly call invitation accept endpoint.

- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditAudienceModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditBooleanMapModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditCategoriesModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditLanguageModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditLearningActivitiesModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditLevelsModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditResourcesNeededModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditSourceModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/__tests__/EditAudienceModal.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/__tests__/EditBooleanMapModal.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/__tests__/EditLanguageModal.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/__tests__/EditSourceModal.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/index.vue
- contentcuration/contentcuration/frontend/channelEdit/translator.js
- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
- contentcuration/contentcuration/frontend/channelEdit/views/trash/TrashModal.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/getters.js
* Elide folders from text when 0 folders selected
* Update all usage of selection text to use common source.
* Update selection text to appear as text box label to maintain text formatting
* Flyby fix of string 'What Levels' to 'Edit Levels'
1. Selected a single resource
2. Confirmed that `1 resource` is displayed only for the selection text.
3. Confirmed that no text displays in the quick edit modals.
4. Select multiple resources or a folder, confirm that appropriate messages display.
Fixes #4650
----
PR process:
Testing:
___
> Consolidate selection text formatting.

- contentcuration/contentcuration/frontend/shared/translator.js
Adds strings to translator file to support #4651, per [decision in comment thread](https://github.com/learningequality/studio/issues/4651#issuecomment-2318654254)
> Add a string for helper text 

- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/InheritAncestorMetadataModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/move/MoveModal.vue
- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/index.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/mutations.js
- contentcuration/contentcuration/frontend/shared/constants.js
- contentcuration/contentcuration/frontend/shared/mixins.js
- contentcuration/contentcuration/tests/test_exportchannel.py
- contentcuration/contentcuration/tests/viewsets/test_contentnode.py
- contentcuration/contentcuration/utils/publish.py
- contentcuration/contentcuration/viewsets/contentnode.py
This PR adds additional functionality so that when a user uploads, imports, or moves a resource to a folder (moving can be with the "move" button, drag and drop, or copying via the clipboard) that has "bulk edit-able" metadata, they are prompted to select any options they would like that resource to inherit. 
Steps for manual QA: 
1. Create a folder and add language, categories, level, and/or requirements (learner needs) to the folder. 
2. Create a second folder and do the same, but with different metadata 
3. Upload some resources into one of the folders, you should see the modal appear 
4. Move a resource into the second folder. you should be prompted to add the second folder's metadata 
5. import a resource to either folder
6. copy a resource to clipboard, and copy it into a new folder …
> Add MVP modal for applying inheritable metadata

- contentcuration/contentcuration/frontend/channelEdit/components/publish/PublishModal.vue
This is a follow-up fix to https://github.com/learningequality/studio/pull/4666#pullrequestreview-2261447503
- See https://github.com/learningequality/studio/pull/4666
https://github.com/user-attachments/assets/fb2d961b-b027-4f9e-9fc2-3439d90f3971
- No tech-debt however https://github.com/learningequality/kolibri-design-system/issues/324 will need to be fixed to full resolve the the issue across the different products as this fix is only intended as a temporal solution.
___
- See manual verification steps above
https://github.com/learningequality/studio/pull/4666
----
PR process:
Testing:
___
> Fix UI glitch with KSelect in Publish modal

- contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/index.vue
This pull request modifies the computed property `topicAndResourceCount()` to address instances where items in the `clipboardNodesMap` may be missing the node `kind`. It introduces the use of `contentNodesMap` to retrieve the `kind` when it is not present in the `clipboardNodesMap`.
___
1. Select folder/resource in the clipboard
2. Click on the Move button
3. Observe the title with the correct count when the moveModal opens
Fixes #3744 
----
PR process:
Testing:
___
> Correct topic count when node kind is not found in clipboardNodesMap

- contentcuration/search/tests/test_savesearch.py
- contentcuration/search/viewsets/savedsearch.py
* Fixes regression in savedsearch endpoint
* Adds regression tests for minimal guarantees of behaviour
* Removes serializer fields for things set automatically in the backend
Fixes #4700
----
PR process:
Testing:
___
> Fix saved search endpoint and add regression tests.

- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditAudienceModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditBooleanMapModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditCategoriesModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditCompletionModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditLanguageModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditLearningActivitiesModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditLevelsModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditResourcesNeededModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditSourceModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditTitleDescriptionModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/index.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
- Adds analytics event tracking to quick edit modals
- Adds analytics event tracking to legacy edit modal
1. Use quick edit modals
2. Confirm the analytics data in the console-- that it's accurate and representative of the changes
3. Use legacy edit modal
4. Confirm the analytics data in the console-- that it's accurate and representative of the changes
___
Events and data should support the desired tracking defined in Confirm the analytics data in the console-- that it's accurate and representative of the changes
Notion doc for reference: https://www.notion.so/learningequality/Use-Studio-tag-manager-to-track-the-bulk-editing-feature-update-a225bb594ddf4571aa02d4ad349a92be?pvs=4
----
PR process:
Testing:
___
> Analytics for quick edit modals, relative to legacy edit modal

- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
- contentcuration/contentcuration/frontend/channelEdit/views/NodePanel.vue
- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.vue
- contentcuration/contentcuration/frontend/shared/data/resources.js
* Always save the pagination result, so we invalidate the cache if needed.
* Move pagination into NodePanel where the contents of the topic are actually loaded and displayed.
* Fixes issue with pagination whereby pagination at the parent folder will erroneously paginate for the node panel display
* Add > 25 resources to the root folder of a channel
* Add a folder, navigate into it, see that Show more is not displayed in the child folder, but is in the parent
___
----
PR process:
Testing:
___
> Move pagination into NodePanel where the contents of the topic are actually loaded and displayed.

- contentcuration/contentcuration/frontend/channelList/views/Channel/components/LanguageFilter.vue
- contentcuration/contentcuration/frontend/shared/views/form/MultiSelect.vue
Add checkbox change handler that was missing to handle filter items selection.
Closes #4702
1. Selected/unselected items from the dropdowns in content library
2. Removed items from chips in content library
3. Removed all items from VAutocomplete and VSelect
https://github.com/user-attachments/assets/1d6dafac-09cd-4164-857a-97ff3f63730f
No
___
Play around with the languages filter in the content library tab.
----
PR process:
Testing:
___
> Fix multi select filters

- package.json
- yarn.lock
- Bumps the KDS version to 4.5.0 to include fixes for KCheckbox which address (in part) #4636 
- ~I've found myself having to `volta pin node@16` a lot - any reason not to pin this?~
This is for review once merged (as I understand we test this kind of stuff directly on the unstable server?)
Check that the KDS update does not break checkboxes in general - can select things in Channel editor, clipboard, etc.
- Note that #4702 is not related to this and existed before this update due to the migration from Vuetify checkboxes to KDS checkboxes
- Note that #4691 applies the correct colors during the "selected & indeterminate" vs "unselected and indeterminate" checkboxes -- the state transitions should work here, but will not have the correct color in one case
> Bump KDS to 4.5.0

- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditBooleanMapModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/__tests__/EditBooleanMapModal.spec.js
- contentcuration/contentcuration/frontend/shared/views/contentNodeFields/CategoryOptions.vue
- contentcuration/contentcuration/frontend/shared/views/form/ExpandableSelect.vue
This pull request addresses the issue where the text 'This field is required' is displayed when bulk editing learning activities.
Fixes https://github.com/learningequality/studio/issues/4651
1. Select multiple resources with different categories.
2. Verify that the "mixed" tag is not displayed as a category.
3. Verify that indeterminate state checkboxes are not displayed.
4. Verify that the helper text is displayed: "You selected resources that have different categories. The categories you choose below will be added to all selected resources. This will not remove existing categories."
5. Verify that the "save" button is enabled only if one or more boxes are checked.
6. Verify that no validation is required, and no error message is displayed. …
> Fixed field is required' validation

- contentcuration/contentcuration/tests/viewsets/test_file.py
- contentcuration/contentcuration/viewsets/file.py
- Adds regression test that fails due to the bug
- Updates the FileSerializer#update method to call `mark_complete()`  on the File's content node
- Creates a Change update event to ensure the front-end stays up-to-date when the contentnode is complete
- Uses `UpdateModelMixin` in the `FileViewSet` ensuring that the File instance is saved, resulting in contentnode having its relation to the File updated
___
- Set a default channel-level License and Copyright Holder (or just do the Public Domain license)
- Import files to that channel
- Wait a few seconds (until the top spinner is done spinning)
- See that the nodes have not become "Incomplete" because they are, indeed, complete now that they have a file
At a high level, the issue was that a "Content Node" is not complete without a file - …
> Ensure `contentnode.mark_complete()` happens when File updated

- contentcuration/contentcuration/tests/viewsets/test_invitation.py
- contentcuration/contentcuration/viewsets/invitation.py
* Moving acceptance to a dedicated endpoint omitted to update the `accepted` property of the invitation object.
* This fixes that oversight.
1. Accept an invitation
2. Reload the page
3. See the invitation does not reappar
Fixes [#4698](https://github.com/learningequality/studio/issues/4698)
----
PR process:
Testing:
___
> Add regression test and fix for invitation not being marked as accepted.

- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.vue
This pull request resolves the issue where a channel containing imported resources transitions to the 'Unpublished View-only' display after opening a new tab and selecting a different channel. 
This pull request also fixes the console error `Invalid prop: type check failed for prop "nodeId". Expected String, got Undefined` which occurred when `rootId`/`nodeId` was undefined within `StudioTree.vue`.
- Edits `TreeViewBase.vue` with `rootId` watcher that triggers an API call if rootId is undefined, allowing the accurate view status of the channel to stay displayed.
- Extends the `v-else` `to v-else-if=“rootId”` to avoid rendering `StudioTree` when `rootId` is undefined, preventing the invalid prop error from appearing.
1. Created a new channel and imported resources from an existing channel …
> Incorrect view only channel

- contentcuration/contentcuration/frontend/channelList/views/Channel/components/LanguageFilter.vue
- contentcuration/contentcuration/frontend/shared/views/form/MultiSelect.vue
Reset scroll on blur for multiselects and language filter components.
1. Simulated lot of language items in language filter and verified that the scroll was being reset on blur.
2. Simulated lot of license items in language filter and verified that the scroll was being reset on blur.
https://github.com/user-attachments/assets/61bbce68-d698-409e-a26d-2b68a4ec975a
no
___
Replicate #4721.
Closes #4721
----
PR process:
Testing:
___
> Reset scroll on blur for multiselects and language filter

- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditBooleanMapModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/__tests__/EditBooleanMapModal.spec.js
Fix save edit boolean map modals. This PR fixes two things:
* When saving we do a filter of the current selected node, so we need to filter the values of `this.selectedValues` that have all nodes inside, but we have
```javascript
Object.entries(this.selectedValues)
.filter(([value]) => value.length === this.nodeIds.length)
```
which is an error as the value is the second element of the entries, not the first.
* Fix can save method, as we need to allow can save if there is at least one option selected, so we need to look for `.some(value => value.length === this.nodes.length)`, but we have `.some(value => value.length > 0)` and this is an error as this condition is true for values that arent selected across all nodes.
PR process:
Testing:
___
> Fix save quick edit modals

- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/InheritAncestorMetadataModal.vue
* Select all new uploaded nodes when the inherit metadata modal is open. And select just the first one after inherit modal is closed.
* Reset closed modal state when new files are uploaded.
1. Verified uploading multiple files.
2. Verified uploading just one file.
3. Verified uploading more files.
4. Verified reloading the page.
https://github.com/user-attachments/assets/4659ceb6-1ca6-4499-94f2-57eb563cbb55
___
Closes #4724.
----
PR process:
Testing:
___
> Fix selection on inherit metadata

- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditSourceModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
- contentcuration/contentcuration/frontend/shared/views/LicenseDropdown.vue
This pull request addresses the issue of the overlapping "About Licenses" dropdown button with the text `Cannot edit for public channel resources` by moving the `helpText` to the `LicenseDropdown` component as a new parameter.
| Before  | After |
| ------------- | ------------- |
| ![before](https://github.com/user-attachments/assets/627615a3-ea31-48af-a68e-efbff2d4e27b)  | ![after](https://github.com/user-attachments/assets/623fcbd5-d144-4b3a-a484-06d520d6f1bf)  |
___
1. Open a channel and import a resource from another channel
2. Open the Edit source modal for that resource
Fixes #4736 
----
PR process:
Testing:
___
> Move helpText to LicenseDropdown component

- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
- contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreePage/index.spec.js
- contentcuration/contentcuration/frontend/channelEdit/views/NodePanel.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/getters.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/index.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/mutations.js
This pr does the following;
1. Adds padding around the "Show more" pagination button
2. Streamlines the number of resources show in a particular folder
3.  Makes the "Show more" pagination button responsive when more than 25 resources have been uploaded.
1. Login to studio
2. Navigate to a channel or its folder that has more than 25 resources and observe the behavior
3. Observe that the resource and question count correspond to what is in the folder and exercise respectively
3. Also, upload over 25 resources into a folder and try to use the "Show more" button
**Padding**
**Resource counts**
https://github.com/user-attachments/assets/a503baa6-0519-4184-90c7-72dcaeb50ec7
**Uploading >25 resources**
https://github.com/user-attachments/assets/c463ab37-2269-4152-91d6-73cccba130af
- No
- See …
> Pagination follow ups

- contentcuration/contentcuration/frontend/channelList/vuex/channelList/__tests__/module.spec.js
- contentcuration/contentcuration/frontend/channelList/vuex/channelList/actions.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/tests/viewsets/test_invitation.py
- contentcuration/contentcuration/viewsets/invitation.py
This pr fixes the issue with a declined invitation popping up again. This fix updates the accept endpoint to allow for declining of invitations.
1. Go to https://unstable.studio.learningequality.org/en/accounts/#/ and sign in as user A
2. Open a channel and select the 'Share channel' option
3. Share the channel with user B by either selecting the 'Can view' or 'Can edit' option
4. Sign in as user B and decline the invitation
5. Refresh the 'My channels' page and observe that the invitation message has reappeared
https://github.com/user-attachments/assets/c5caa6f8-76c2-418a-a100-6411d84bff4c
- No
- See **Manual verification steps performed** 
- Because the fix updates the accept invitation endpoint, it would be great to do some extra testing to verify that the accept invitation is working …
> Fixes decline invitation

- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/InheritAncestorMetadataModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/move/MoveModal.vue
- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
- contentcuration/contentcuration/frontend/channelEdit/views/trash/TrashModal.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
* Conditionalize helper text in modal to not display general inheritable metadata title when only language is inheritable
* Ensure that the InheritMetadataModal in the CurrentTreeView can be used again after it has completed handling inheritance for moved nodes
* Make the frontend extra field name match the backend `inherited_metadata` to ensure that preferences for users to 'don't display this modal again' are persisted
Create a new resource in a folder that only has language metadata set - confirm the non language related messaging in the modal doesn't display.
Move a resource into a folder that has inheritable metadata applied, apply the metadata. Move another resource into the same folder, confirm the modal shows again.
Upload a resource into a folder that has inheritable metadata …
> Follow up inheritable modal fixes

- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
- contentcuration/contentcuration/frontend/channelEdit/views/NodePanel.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/mutations.js
This pr fixes a bug in the topics topics side panel where the topic tree is no longer being folded out. It also fixes a minor bug when select all is applied to a paginated list: the number of resources selected should reflect the number of resources currently displayed
1. Select a channel
2. Navigate around its resources using the side panel
**_Topic tree_**
https://github.com/user-attachments/assets/f7493b47-3f6a-44cb-9d6a-30b5619b1a82
**_Resource count_**
https://github.com/user-attachments/assets/95840048-0764-436d-bedf-3dbf24f920f2
___
See manual verification steps above
- Test the pagination workflow as the fix made some enhancements to the pagination implementation
Fixes #4756
----
PR process:
Testing:
___
> Fixes topic tree not showing

- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/InheritAncestorMetadataModal.vue
* Fixes saving of preferences by properly checking for the existence of falsy values.
* Defer setting metadata onto nodes in file upload until after all nodes have been created from file uploads
* On cancel of the inheritance modal, emit an empty inherit payload to ensure that consumers clear inheriting nodes etc. appropriately
See issues below for reproduction steps.
Fixes #4752 
Fixes #4753 
Fixes #4755
----
PR process:
Testing:
___
> Inheritance modal release blocking fixes

- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeEditListItem.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/__tests__/actions.spec.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
adds a flag to the updateContentNode action to determine whether or not we need to check for completion - required within the EditModal for validations to work properly, but not in other quick edit options. Previously, this check was setting `complete` to false incorrectly due to assessmentItems validation failing in situations where we hadn't loaded that assessment data (i.e. not EditModal). 
1. Copy a complete exercise from within the tree view (i.e. "make a copy") and confirm no false "incomplete"
2. Copy a complete exercise to the clipboard, and then move it to a new location, and confirm no  false "incomplete"
Regression testing: 
1. Create a complete exercise in the edit modal. After successfully passing validations/checks within the modal, after saving and closing, it should not …
> Fix incorrectly marked "incomplete" exercises on exercise copy

- Makefile
- contentcuration/contentcuration/tests/test_rectify_source_field_migraiton_command.py
- contentcuration/kolibri_public/management/commands/rectify_incorrect_contentnode_source_fields.py
We filter out all the contentnodes whose source fields have been changed after being imported and reset them to their original values.
1. Ran the query in hotfixes 
2. Verified the returned nodes conform to expected disparities. 
Recommended to run the query in hotfixes and verify the returned nodes. some of the fields to look at would be 
last date of modification and verifying what source_node_fields have been changed. 
If there is something that is missed migrations may be incorrect and may effect large number of nodes. 
closes #4190 
----
PR process:
Testing:
___
> Run migrations to fix incorrect source fields of contentnodes

- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
This pr fixes the count of resources/questions when copying resources that was inconsistent with the count of the originally copied resources.
1. Copy a resource with some resources or exercise with some questions
2. Observe the count of resources/questions after the copying is completed.
https://github.com/user-attachments/assets/3db7d750-8139-49c6-9fdc-515195124972
___
See manual verification steps above
NA
Fixes #4765
----
PR process:
Testing:
___
> Fixes count of resources/questions on copy

- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/InheritAncestorMetadataModal.vue
- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
* Use selected for node ids for inheritance when not uploading
* Ensure that we properly retrigger the inheritance modal checks when something new is added in the same edit modal lifecycle
1. Create a new folder, ensure that the modal triggers and applies
2. Within the same edit modal session click "add new folder" and ensure the same behaviour happens
3. Repeat with "don't show this again" behaviour
4. Create a new exercise, ensure that the modal triggers and applies
5. Repeat with "Don't show this again" behaviour
___
Fixes [#4762](https://github.com/learningequality/studio/issues/4762)
----
PR process:
Testing:
___
> Properly handle metadata inheritance for non uploaded nodes in edit modal

- contentcuration/kolibri_public/management/commands/rectify_incorrect_contentnode_source_fields.py
user_id was required for the ContentNode migration which caused the run to fail.
> Make user_id required false for migration

- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/__tests__/actions.spec.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
This pr fixes the failure to undo a copy operation
1. Copy a resource
2. Undo the copy using the snackbar undo button
https://github.com/user-attachments/assets/54238f2d-3dca-4879-b931-2cfa46fc1592
No
___
See manual verification above.
No
Fixes #4766
----
PR process:
Testing:
___
> Fix undo on copy

- contentcuration/contentcuration/tests/views/test_views_internal.py
- contentcuration/contentcuration/views/internal.py
When trying to chef a previously deleted channel, the API endpoint would return a 500 because the actor_id argument was not being passed to the save method.
This is required, as the channel would be undeleted by this operation, so this is needed for the channel history tracking.
1. Wrote a regression test, saw that it failed.
2. Fixed the issue.
3. Saw that it passed!
Fixes #4783
----
PR process:
Testing:
___
> Ensure actor_id gets passed in case channel creation API endpoint ends up in undeleting channel

- integration_testing/features/manage-resources/bulk-editing/apply-inheritable-metadata.feature
- integration_testing/features/manage-resources/bulk-editing/quick-edit-multiple-resources.feature
- integration_testing/features/manage-resources/bulk-editing/quick-edit-single-resource.feature
Adding some gherkin scenarios for the new bulk editing features.
> Bulk editing gherkin scenarios

- contentcuration/kolibri_public/import_metadata_view.py
- contentcuration/kolibri_public/tests/test_content_app.py
- contentcuration/kolibri_public/tests/test_importmetadata_api.py
- contentcuration/kolibri_public/views.py
Preemptively check for pk to be UUID and return 400 bad request otherwise 
- Adds validation for UUID
- Adds Tests
1. Ran tests locally
closes #4788 
PR process:
Testing:
___
> Validate UUID Format in Public API Requests to Prevent 500 Errors

- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
- contentcuration/contentcuration/models.py
* Adds defensive programming checks when author etc. fields aggregate to None rather than a list
* Checks that a topic has resource descendants before returning more details, as if it has none, the details are mostly useless
* Updates the check for disabling the publish button to disable it when it has no descendant resources, not just no descendant nodes
1. Clicked on the channel details modal for empty channel before publishing, saw no error
2. Add folders to empty channel, see that publish button is still disabled
3. Add a resource to empty channel, see that publish button becomes enabled.
Fixes [#4793](https://github.com/learningequality/studio/issues/4793)
----
PR process:
Testing:
___
> Channel details modal fixes

- contentcuration/contentcuration/frontend/shared/styles/vuetify.scss
Updates Card hover dp from the deprecated `%dropshadow-4dp` to `%dropshadow-6dp`.
> Update kds dp to the latest guidelines

- contentcuration/contentcuration/models.py
Restructure the way we run the query while deleting user_related data to stop the garbage_collection command from stalling. 
- Calculate tree_id separately instead of in the subquery. 
- Run the query once to set the parent_id. 
- Restored production database to hotfixes environment
- Manually started the job
- Observed running querie
closes #4780 
We need to have the settings.DEBUG=True to log the queries.
PR process:
Testing:
___
> optimize garabge collection command

- contentcuration/contentcuration/frontend/channelEdit/components/move/MoveModal.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ContentTreeList.vue
- contentcuration/contentcuration/frontend/channelEdit/views/trash/TrashModal.vue
- contentcuration/contentcuration/frontend/channelEdit/views/trash/__tests__/trashModal.spec.js
* Adds pagination to the TrashModal, the MoveModal, and the ImportFromChannels modal.
* Doesn't add it to other places that use the loadChildren method (like the navigation side panel in the main edit page) as this is covered by the NodePanel pagination logic
Tested each of these modals with number of resources/folders in a folder > 25.
Verify that the pagination displayed correctly, loaded additional items, and also updated properly after actions were performed (trash modal needed a data refresh after restoring or perma-deleting items)
Adds some cross component string stealing, we should clean up in unstable
Fixes #4809
----
PR process:
Testing:
___
> Add pagination to every place that displays long lists of nodes from loadChildren

- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/tests/test_models.py
- contentcuration/contentcuration/views/base.py
- A query that occurs when opening a channel was performing poorly, which this changes to use a CTE
1. Added regression test
Does an error occur if you open a channel?
Fixes: https://github.com/learningequality/studio/issues/4825
----
PR process:
Testing:
___
> Use CTE for server rev query, add tests

- contentcuration/contentcuration/signals.py
- We need to rollback the hotfixes database to v9.6, but the JIT change showed clear benefit, so making this conditional to avoid breaking things still on 9.6
https://github.com/learningequality/studio/pull/4834
I verified with no observed issues:
1. Started up devserver
2. Signed in
3. Created a new channel
Verified in python shell that this works:
```
>>> from django.db.backends.postgresql.features import DatabaseFeatures
>>> f = DatabaseFeatures(connection)
>>> f.is_postgresql_12
True
>>> f.is_postgresql_13
False
>>> f.is_postgresql_11
True
```
> Conditionalize the JIT setting

- .github/workflows/frontendlint.yml
Removes use of set-output in line with https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Follows Kolibri's use of the pre-commit lite action for committing unlinted files to PRs and branches https://github.com/learningequality/kolibri/blob/develop/.github/workflows/pre-commit.yml#L55
1. Step 1
2. Step 2
3. ...
___
----
PR process:
Testing:
___
> Remove use of deprecated set-output, use pre-commit lite action instead

- contentcuration/contentcuration/frontend/RecommendedResourceCard/components/RecommendedResourceCard.vue
- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeEditListItem.vue
- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeValidator.vue
- contentcuration/contentcuration/frontend/shared/views/errors/TechnicalTextBlock.vue
- contentcuration/contentcuration/frontend/shared/vuetify/theme.js
- package.json
- yarn.lock
This pr update studio to use the latest KDS v `5.0.0_rc10`, and also fixes any breaking changes introduced by the same. The guide below is used;
Fixes #4816
- Browse through the UI to ensure that the colors remain as before. The studio production version can be used as a guide.
- While reviewing the code changes, ensure the mapping has been applied based on the guideline shared above( and in the reference too).
> Updates kds breaking changes

- contentcuration/contentcuration/frontend/channelEdit/views/trash/TrashModal.vue
This pr fixes a pagination issue in the trashed items where newly shown resources are displayed on top of the page making it seems like nothing has happened on clicking the "Show more" button.
https://github.com/user-attachments/assets/979d6951-6f8a-4b17-ab92-3f33ca395d9b
Fixes #4837
1. Sign in to studio
2. Delete a large number of resources and open the channel's Trash page
3. Click on 'Show more'
4. Observe the behavior
> Fixes sorting order of trash items

- contentcuration/contentcuration/viewsets/channel.py
The following query-- which originates from the publish modal providing a list of content languages, or from testing the existence of a language in a channel-- was taking too long:
```sql
SELECT DISTINCT "contentcuration_contentnode"."language_id",
"contentcuration_contentnode"."tree_id",
"contentcuration_contentnode"."lft"
FROM "contentcuration_contentnode"
WHERE (
"contentcuration_contentnode"."language_id" IS NOT NULL
AND CAST("contentcuration_contentnode"."node_id" AS uuid) IN (
SELECT U0."id"
FROM "kolibri_public_contentnode" U0
WHERE U0."channel_id" = '<CHANNEL_ID>')
AND NOT ("contentcuration_contentnode"."id" IN ('<MAIN_TREE_ID>'))
)
ORDER BY
"contentcuration_contentnode"."tree_id" ASC,
"contentcuration_contentnode"."lft" ASC
;
```
The following issues were addressed with the …
> Optimize language existant query

- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
- The inherit logic was not differentiating drag and drop operations that are relative moves among siblings versus operations that are changing the parent
Fixes https://github.com/learningequality/studio/issues/4839
1. Open a channel
2. Add a new folder to the channel root
3. Open the folder
4. Add multiple resources into the new folder
5. Edit the folder and set metadata via the legacy edit modal
6. Observe an unresolved issue where the user is not notified whether the resources should inherit the new metadata
7. Drag a resource to change its position in the folder
8. Observe the inherit modal does not appear
9. Navigate to the channel root
10. Add a new file
11. Drag the file to the tree view on the left side to drop the file resource into the folder
12. Observe the inherit modal does …
> Inherit modal does not appear when sorting items in a folder with metadata

- .github/workflows/notify_team_new_comment.yml
With https://github.com/learningequality/.github/pull/11
reusable action is added to .github repo. This PR makes use of it.
Issue: https://github.com/learningequality/kolibri/issues/12567
Create Pull request similar to https://github.com/learningequality/test-actions/pull/53
Create issue and link it to PR
Change default repo branch to the branch you are changing in PR from (1.) due to https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#issue_comment
Post comment in issue.
> Use notify_team_new_comment workflow action from .github repo

- contentcuration/contentcuration/frontend/channelEdit/views/files/supplementaryLists/SupplementaryList.vue
Made background colour on hover of the caption area more subtle.
After Changes Screenshot:
Addresses issue [#4836](https://github.com/learningequality/studio/issues/4836)
…
> Made background color on hover of the caption area more subtle

- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ContentTreeList.vue
This PR addresses **issue #4838**, where the 'Show more' button in the "Import from other channels" section was not centered.  
- Updated the CSS in `ContentTreeList.vue` to center-align the 'Show more' button using `flexbox`.
- Verified manually to ensure proper alignment across different screen sizes and browsers.
- **Fixes:** #4838
- No new dependencies or mockups are introduced in this PR.
---
To test the changes:
1. Navigate to the "Import from other channels" section in the application.
2. Verify that the 'Show more' button is centered as intended.
3. Test the UI alignment on various screen sizes to ensure responsiveness.
> Hotfix: Centered the 'Show more' button in Import from other channels

- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/viewsets/sync/endpoint.py
- Ensures the frontend user session isn't overwritten
- Adds limit to the number of changes that can be returned from the sync API
Fixes https://github.com/learningequality/studio/issues/4896
See STR in issue
> Fix channel revision overwrite on frontend user session

- contentcuration/kolibri_public/tests/test_content_app.py
- contentcuration/kolibri_public/views.py
Our contentnode APIs had omitted the learner_needs field from returned data, this fixes this for Studio.
Confirm that the test updates are accurate.
I can't think of a place where adding the field would cause any issues - there's no payload validation in uses of the public API, so we don't error on additional fields.
Correlated Kolibri PR here: https://github.com/learningequality/kolibri/pull/12763
----
PR process:
Testing:
___
> Fix public content API to return learner_needs.

- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditAudienceModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/EditLanguageModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/QuickEditModal/__tests__/EditAudienceModal.spec.js
- contentcuration/contentcuration/frontend/settings/pages/Storage/RequestForm.vue
- contentcuration/contentcuration/frontend/shared/languageSwitcher/LanguageSwitcherModal.vue
- contentcuration/contentcuration/frontend/shared/views/form/ExpandableSelect.vue
This pr wraps the `KRadioButtonGroup` around the `KRadioButton` as specified in the [design docs](https://design-system.learningequality.org/kradiobutton?filter=kRa). It also migrates the `KRadioButton` to use the `buttonValue` over the deprecated `value` prop.
Closes #4869
- Test all areas in studio that used the KRadioButton to ensure no regressions
- Change language
- Edit language (bulk editing)
- Edit audience (bulk editing)
- Storage request form (`/settings/#/storage`)
- Run all frontend tests successfully
- Inspect the test logs to ensure there are no warning. For reference of the warnings, see #4869
> Migrate kradiobutton usages

- docs/host_services_setup.md
- docs/local_dev_docker.md
- docs/local_dev_host.md
- docs/local_dev_wsl.md
- webpack.config.js
This PR introduces a new documentation page, docs/local_dev_wsl.md, which provides step-by-step instructions for setting up Kolibri Studio on Windows using Windows Subsystem for Linux (WSL). The new guide covers the installation of WSL and Ubuntu, configuration of prerequisites (such as volta and pyenv), and setting up necessary dependencies and services. Additionally, the existing documentation pages (docs/local_dev_host.md , docs/host_services_setup.md and  docs/local_dev_docker.md) have been updated to reference the new WSL guide, ensuring that Windows developers are directed towards the recommended development environment rather than attempting a native Windows setup.
Manual testing was performed on a Windows machine with WSL installed, and all the steps in the new guide were verified …
> Add new local_dev_wsl guide and update host and docker guides with references to it

- Makefile
- contentcuration/contentcuration/tests/test_rectify_source_field_migraiton_command.py
- contentcuration/contentcuration/tests/test_sync.py
- contentcuration/contentcuration/utils/sync.py
- contentcuration/kolibri_public/management/commands/rectify_incorrect_contentnode_source_fields.py
* Fixes a long standing bug in the sync command where license_description field was not synced from imported nodes
* Reinstates the previous syncing rectification code, but targets it specifically to license_description discrepancies and rectification.
* Removes the date filter, as this problem will affect any node that has ever been imported.
Fixes [#4916](https://github.com/learningequality/studio/issues/4916)
Not sure if removing the date filter is going to make the query completely nonperformant - but it's only an extra two years? Not sure.
I think the fix is straight forward and neatly regression tested, so careful eyes on how I have modified the rectification script would be appreciated.
> License description rectification

- contentcuration/contentcuration/production_settings.py
- contentcuration/contentcuration/sandbox_settings.py
- contentcuration/contentcuration/settings.py
- contentcuration/contentcuration/tests/test_gcs_storage.py
- contentcuration/contentcuration/utils/gcs_storage.py
- contentcuration/contentcuration/utils/storage_common.py
- We updated the [nginx content routing](https://github.com/learningequality/studio/pull/4855), but missed that the code attempts to ensure files exist, like during publishing
- This PR updates the storage mechanism to allow reads to the production bucket in non-production server environments
Previous nginx update: https://github.com/learningequality/studio/pull/4855
https://learningequality.slack.com/archives/C0LK8QS9J/p1740667623559239?thread_ts=1740583957.541449&cid=C0LK8QS9J
Does the code and tests make sense? In order to properly test, this needs to be merged to hotfixes
> Allow read of production Studio bucket

- contentcuration/contentcuration/utils/gcs_storage.py
Corrects the order of backends: on a non-production server, we should check the non-production bucket first, to see if it has newer files. This shouldn't have a real effect on most storage since the files are stored by their checksum.
Original https://github.com/learningequality/studio/pull/4926
> Swap order of backends

- .github/workflows/pythontest.yml
- docker/Dockerfile.postgres.dev
- docs/host_services_setup.md
- docs/local_dev_host.md
- flake.nix
To prepare for production database upgrades, this PR upgrades docker and CI versions of postgresql from 12 to 16
https://learningequality.slack.com/archives/C0LK8QS9J/p1739490469782419
https://cloud.google.com/sql/docs/postgres/db-versions
> Prepare transition to postgresql 16

- contentcuration/contentcuration/tests/test_sync.py
- contentcuration/contentcuration/tests/viewsets/test_file.py
- contentcuration/contentcuration/viewsets/file.py
This PR fixes an issue where the `upload_url` endpoint was not properly sanitizing inputs, resulting in a possible `IntegrityError` on the `contentcuration_file` table (related to `preset_id` foreign key constraints).  
**Key changes include:**
- Created a new `FileUploadURLSerializer` to validate `size`, `checksum`, `filename`, `file_format`, `preset`, and `duration`.
- Added a custom `StrictFloatField` to ensure `duration` must be numeric (int/float) rather than a string.
- Updated the test suite (`test_file.py`) to:
- Use `"filename"` instead of `"name"`.
- Add a new test for invalid presets.
- Verify that string-based durations receive a `400` error.
- Ensured that large file sizes still trigger a `412` error for insufficient storage.
**Manual Verification Steps:**
1. Manually tested …
> Add more robust input sanitization to the upload_url endpoint

- contentcuration/contentcuration/frontend/channelEdit/components/AnswersEditor/AnswersEditor.vue
This pr fixes a bug where a numeric input answer is not saved and question is marked as incomplete after closing the exercise editor.
**Before**
https://github.com/user-attachments/assets/c510ea9f-884b-4c82-a4a7-cbecc7a70095
**After**
https://github.com/user-attachments/assets/c00bc6f7-eca5-4b0f-8b07-a77dea4693a4
Fixes #4910
1. Select Numeric input type of question in the exercise editor.
2. Add 1 answer and close the editor.
3. Reopen the exercise and ensure the ❗ mark indicating the incomplete question is not displayed
4. Try different variations as illustrated in the before video to check if the issue can be replicated
> Save numerical input answers

- contentcuration/contentcuration/tests/test_sync.py
- contentcuration/contentcuration/tests/viewsets/test_file.py
- contentcuration/contentcuration/viewsets/file.py
* Updates the new FileUploadSerializer to let the duration field be nullable
* Adds additional validation check to ensure that it is not null or non-existent for MP4, WEBM, and MP3 files
* Adds tests to ensure behaviour.
* Updates existing tests that violated these restrictions.
Fixes #4955
Can you upload video and audio files? Can you upload non-video and non-audio files?
> Allow duration to be nullable, but only for non-media file types.

- contentcuration/contentcuration/frontend/shared/views/details/Details.vue
- contentcuration/contentcuration/frontend/shared/views/files/ImageOnlyThumbnail.vue
- contentcuration/contentcuration/frontend/shared/views/files/Thumbnail.vue
- contentcuration/contentcuration/templates/base.html
Fixes: #4907 
This PR removes all instances of `material-icons` from the codebase and replaces them with corresponding icons from the [Kolibri Design System](https://design-system.learningequality.org/icons) where applicable. In cases where no direct replacement was available, the icons were removed (e.g., in `base.html`).
- Replaced all usages of `material-icons` with equivalent Kolibri Design System icons.
```
<svg
v-else
viewBox="0 0 40 40"
:aria-label="kindTitle"
class="nothumbnail-image"
:class="$isRTL ? 'rtl-image' : 'ltr-image'"
>
<KIcon icon="image" 
:x="-3"
:y="y - 14"
:style="{ fill: '#999999' }"  />
</svg>
```
```
<svg
v-else-if="compact"
viewBox="0 0 24 24"
:aria-label="kindTitle"
class="thumbnail-image"
>
<KIcon icon="infoOutline" 
:x="+10"
:y="y+20"
:style="{ fill: '#ffffff' …
```
> Replace Material Icons with Kolibri Design System Icon

- contentcuration/contentcuration/frontend/shared/constants.js
- contentcuration/contentcuration/frontend/shared/mixins.js
- contentcuration/contentcuration/frontend/shared/views/contentNodeFields/CompletionOptions/index.vue
- contentcuration/contentcuration/frontend/shared/views/contentNodeFields/__tests__/completionOptions.spec.js
- contentcuration/contentcuration/static/feature_flags.json
- contentcuration/contentcuration/viewsets/contentnode.py
- Adds an option for survey type for completion in exercise UI.
- add a feature flag for the new survey feature.
closes #4875
- Enable the survey feature flag for one of the example users.
- Login with that user and create an exercise.
- Check that there is an option to set completion as survey.
> Add survey completion option for exercise

- contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/Channel.vue
- contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNode.vue
- Fixed checkbox alignment issues in the UI that were causing misalignment between checkbox icons and their corresponding text labels. The checkboxes were appearing slightly misaligned with channel names and folder items in different views.
- The fix addresses the inconsistent vertical positioning that was affecting UI appearance
#**Before** -->
#**After** -->
Addresses #4771 
- Check that checkbox alignment appears consistent in:
- Channel listings (specifically Alpha channel view)
- Folder and file listings
- Content item selections
- Verify that the changes don't affect checkbox functionality - selection behavior should remain the same
- Test in different viewport sizes to ensure responsive behavior is maintained
>  Clipboard - The icons and the checkboxes Misalignment fixed

- contentcuration/contentcuration/frontend/shared/views/channel/mixins.js
- I have added the "Contains content from" field to the CSV export functionality to ensure consistency across all export methods. This enhancement addresses a UX gap where this information was displayed on the channel details page and PDF export but was missing from the CSV export.
- The implementation extracts channel names from the original_channels array for each channel and formats them as a comma-separated list in the new CSV column. This matches the visual presentation shown in the Details page, making the data consistent across all views and exports.
- Manual verification was performed by creating and exporting a test channel that imports content from other channels, confirming that the exported CSV properly includes the new column with expected values.
**Relevant Images** --> …
> Include Contains content from field in CSV export

- contentcuration/contentcuration/tests/test_exportchannel.py
- contentcuration/contentcuration/tests/test_sync.py
- contentcuration/contentcuration/utils/publish.py
Modify publish_channel function to take an optional use_staging_tree parameter as input. If set to true, the function will use staging tree as the base for publishing, and export a -next.sqlite3 database without overwriting or updating existing published database.
Tested locally that a -next.sqlite3 is created by running tests without mocking the storage.
Tested current publishing is not impacted by this change.
Issue: https://github.com/learningequality/studio/issues/4977
Broader task: https://github.com/learningequality/studio/issues/4471
Run unit tests with setUpClass and tearDownClass commented out. The -next.sqlite3 file will be written to minio storage.
Be sure to test the existing publishing behavior is not affected.
> Add optional use_staging_tree parameter to publish_channel function

- .github/workflows/unassign-inactive.yaml
This PR implements a GitHub Action to automatically unassign inactive issues based on a predefined period of inactivity. This action will help maintain cleaner issue assignments and prevent outdated issues from cluttering the project.
[#12837](https://github.com/learningequality/kolibri/issues/12837)
```
on:
schedule:
- cron: "1 0 * * 1" 
workflow_dispatch:
```
Action is scheduled to run every monday at 00:01 UTC
> unassign inactive users

- contentcuration/contentcuration/frontend/administration/pages/AdministrationIndex.vue
- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
- contentcuration/contentcuration/frontend/shared/views/LazyListGroup.vue
- contentcuration/contentcuration/frontend/shared/views/files/ImageOnlyThumbnail.vue
- contentcuration/contentcuration/frontend/shared/views/files/Thumbnail.vue
After the migration from less to scss, we were missing the [scss vars interpoletion](https://sass-lang.com/documentation/interpolation/) when we use scss variables inside css functions.  This PR corrects it in all places I've found that scss variables were used. 
| --- | --- |
| ![image](https://github.com/user-attachments/assets/156fe1b0-24ba-45af-910e-242f868cfa6e) | ![image](https://github.com/user-attachments/assets/3a33b436-e081-49d5-aa6d-a0df4ba0e471) |
| ![image](https://github.com/user-attachments/assets/8f2ff3dd-88bb-4de9-8d5b-c55b28e9bef3) | ![image](https://github.com/user-attachments/assets/fbba8361-65c4-4342-a7f9-57f4808b87f6) |
| ![image](https://github.com/user-attachments/assets/f77a656e-bd58-47a4-b9ef-3379969a6712) | …
> Interpolate scss variables in calc functions

- contentcuration/contentcuration/viewsets/contentnode.py
Due to how we handle client-side sorting, the `lft` value of client-side data can become floats if the user sorts their nodes - not always, but when done repeatedly, the `lft` values eventually half into infinitesimally small values. This results in a 500 error when the user goes to "Show more" nodes because we're using the float value as `lft` in our call to fetch the ContentNodes that we need to show.
This PR simply ensures we get a 400 rather than a 500 when this happens (effectively silencing the Sentry error)
Ultimately, @rtibbles noted that the ideal solution here would be to refactor some of the pagination machinery and how client<>server interact related to it.
This is an edge case that has only been seen a handful of times in Sentry (one of which was when I tried replicating it) …
> raise rest_framework.ValidationError when lft is not an integer

- contentcuration/contentcuration/frontend/RecommendedResourceCard/components/RecommendedResourceCard.vue
This pr adds navigation to the pop-out icon of the recommended resource card. (This was missed)
https://github.com/learningequality/studio/pull/5014
- Clicking the pop-out icon should open the location location of a resource in a new tab.
> Adds go to navigation to recommended resource card popout icon

- contentcuration/contentcuration/frontend/shared/styles/modulePlaceholder.js
- webpack.config.js
Historically, we've had some module replacement in our webpack config for Vuetify's stylus files. At one point, it was always enabled (hot and non-hot devservers), then we made it only enabled for non-hot, and now the solution seems to be to remove it entirely.
The issue was that running `pnpm run devserver` complained about `.styl` files:
```
ERROR in ../../../node_modules/.pnpm/vuetify@1.5.24_vue@2.7.16/node_modules/vuetify/src/stylus/components/_system-bars.styl 6:24-183
Module not found: Error: Can't resolve '../../../../../node_modules/.pnpm/mini-css-extract-plugin@2.9.2_webpack@5.98.0/node_modules/mini-css-extract-plugin/dist/hmr/hotModuleReplacement.js' in '/home/bjester/Projects/learningequality/studio/webpack-node-probs/node_modules/.pnpm/vuetify@1.5.24_vue@2.7.16/node_modules/vue …
```
> Remove stylus module replacement causing non-hot devserver to break

- contentcuration/contentcuration/frontend/channelEdit/views/files/EpubRenderer.vue
EPubJs was registering some ResizeObserver listeners when rendering the epub books, and somehow these listeners caused an infinite resize observer loop when the EPubRenderer component was unmounted. This PR destroys de epub book, which cleans these listeners, before EPubRenderer is unmounted.
Before:
https://github.com/user-attachments/assets/addf9e1f-a24a-48e0-be16-dbeba41e7867
After:
https://github.com/user-attachments/assets/c30d5feb-b925-4af2-8569-d08517240777
https://github.com/learningequality/kolibri-design-system/issues/960
1. Open a channel
2. Click to add/upload a file
3. Upload an EPUB file
4. Click 'Finish'
5. Check that no errors are triggered
> Fix ResizeObserver errors when uploading epub files

- contentcuration/contentcuration/views/internal.py
* Use consistent permissions checking when creating a channel, to ensure that admin users don't get blocked.
Fixes #5023
> Fixes oversight in channel permissions in internal endpoints which blocks admin users unintentionally

- package.json
@bjester had missed approving a build in the pnpm migration. This PR approves it
```
╭ Warning ───────────────────────────────────────────────────────────────────────────────────╮
│                                                                                            │
│   Ignored build scripts: vue-demi.                                                         │
│   Run "pnpm approve-builds" to pick which dependencies should be allowed to run scripts.   │
│                                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────╯
```
> Approve vue-demi postinstall build

- contentcuration/contentcuration/tests/utils/test_recommendations.py
- contentcuration/contentcuration/utils/recommendations.py
- Sets default port to `8000` for CA API URL, unless there's an explicit port already defined
Closes https://github.com/learningequality/studio/issues/5067
Test updates make sense?
> Handle port default for CA API-- port 8000

- contentcuration/contentcuration/frontend/settings/pages/Account/index.vue
- contentcuration/contentcuration/frontend/settings/pages/__tests__/account.spec.js
Changed Alert Component to KModel 
Fixes #5063
Export data from setting->account
click Export data button
> issue-5063 changes

- contentcuration/contentcuration/frontend/shared/views/InfoModal.vue
Ensured that item headers in the modal use h2 tag, leaving the main modal title as the only h1 tag, for proper semantic structure.
Fixes https://github.com/learningequality/studio/issues/5093
Each item in items renders its header in a h2 tag via the header slot.
> issue-5093

- contentcuration/contentcuration/frontend/settings/pages/Storage/RequestForm.vue
Updated the license info section to use the KExternalLink component for license URLs
Screen shot
Fixes https://github.com/learningequality/studio/issues/5092
Areas to test 
Learn More links in Settings > Storage > 'Request more space' form > 'About licenses' modal
> Updated the license info section to use the KExternalLink component for license URLs

- contentcuration/contentcuration/frontend/RecommendedResourceCard/components/RecommendedResourceCard.vue
- contentcuration/contentcuration/frontend/shared/data/public.js
This pr fixes the title duplication display that appeared on the recommended resource cards.
Fixes #5116
- Import from other resources and observe the information displayed on the recommended resources cards
> Fixes the recommended resource card title duplication

- contentcuration/contentcuration/frontend/shared/views/files/Thumbnail.vue
This pr fixes any unprocessed sass expression that was causing UI glitches in the Thumbnail.vue component. It also refactors the css code to limit the use of the `calc()` to only situations when there are differences in units used. Other computations are not done during compile time, not at runtime as previously done.
**Before**
**After**
Fixes #5065
- Have a large-ish channel on your Studio instance, with some nodes that have no thumbnail
- Open the Channel's details view
- Observe at the very bottom the Sample content from this channel has thumbnails (with and without an actual thumbnail picture), and in particular these thumbnails have an embedded kind header
- Open dev tools and inspect it
- Ensure that all SASS is processed
> Fixes unprocessed SASS expression in Thumbnail

- contentcuration/contentcuration/frontend/shared/views/TipTapEditor/TipTapEditor/components/math/FormulasMenu.vue
- package.json
- pnpm-lock.yaml
- webpack.config.js
Follows the advice here https://mathlive.io/mathfield/guides/integration/#integrating-with-a-bundler-or-an-asset-pipeline for including mathlive fonts with an asset bundler
Check http://localhost:8080/editor-dev#/ and ensure that fonts render appropriately for the math field
> Use bundler advice for including fonts for mathlive.

- contentcuration/contentcuration/frontend/channelEdit/router.js
- webpack.config.js
Remove redundant channel edit editordev route.
Only build editordev bundle in development.
> Make tip tap editor sandbox completely dev only

- contentcuration/contentcuration/frontend/settings/pages/SettingsIndex.vue
- contentcuration/contentcuration/frontend/shared/views/StudioOfflineAlert.vue
- contentcuration/contentcuration/frontend/shared/views/__tests__/StudioOfflineAlert.spec.js
Migrated the OfflineText Vuetify component with a new StudioOfflineAlert component that uses Kolibri Design System by following the guidelines . 
**KDS components used:**
- KTransition : for smooth transition of alertbar
- KIcon : disconnect icon used for alert
- KLiveRegion : Screen reader accessability
- Switched network offline and back online to overview the behaviour.
- Verified the alert appears with transition and UI consistency.
- Confirmed accessibility messages are announced via useKLiveRegion
- Checked responsiveness across viewports
- Related issue: #5123 
- Toggle the app offline and online to test the component behaviour.
- Ensure if the new component is visually appealing.
> Issue#5123 : Migrated the offline alert bar in Settings from Vuetify to Kolibri Design System.

- contentcuration/contentcuration/frontend/settings/pages/Storage/RequestForm.vue
Found three place which uses hardcoded colors in Storage/RequestForm. Updated them to KDS tokens
[5094](https://github.com/learningequality/studio/issues/5094)
Check everything is working as expected. 
Impacted area in requestForm. Check for below fields
- What type of organization or group is coordinating the use of Kolibri (if applicable)?
- What is the licensing of the content you are uploading? (Check all that apply)
- Organizational affiliation
> Do not use hardcoded colors in 'Request more space' form

- .github/workflows/deploytest.yml
- .github/workflows/frontendtest.yml
- .github/workflows/pre-commit.yml
- docker/Dockerfile.demo
- docker/Dockerfile.dev
- docs/host_services_setup.md
- docs/local_dev_docker.md
- docs/local_dev_host.md
- docs/local_dev_wsl.md
- k8s/images/app/Dockerfile
- package.json
> Update Node.js version to 20.x

- contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelList.vue
- contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSetList.vue
**Solves Issue #5218** 
Removed Vuetify that used  `VBtn`  from the following buttons in Channels:
That is `<NewChannel>` and `< NewCollection>` and used `KButton` to replace them which is a KDS component.
…
1) https://design-system.learningequality.org/buttons/ [ The buttons are supposed to be like this]
2) https://design-system.learningequality.org/kbutton [ the KButton format]
…
Upadted VBtn with KButton
…
> [Remove Vuetify from Studio] Top-level buttons in Channels

- contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNodeOptions.vue
There are two components named `ContentNodeOptions` which had the same string message ID with different string content. This renames one of the messages ID so it's unique
ran `make i18n-extract-frontend`
> Avoid string message ID collisions with component of same name

- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ReviewSelectionsPage.vue
This pr revamps the Review Selections page displayed whem importing from other resources. See [this](https://learningequality.slack.com/archives/C0LKG14NL/p1753452028375259) thread for proposed changes from design. Also, as part of the refactor of this page, the previously used vuetify components have been replaced with our design system components.
**Before:**
**After:**
Fixes #5211
Fixes https://github.com/learningequality/studio/issues/4086
- Select a channel to import resources into
- Import resources from other channels
- Select resources to import
- Click "Review" and observe the review page
> Revamps the review selections page

- contentcuration/contentcuration/tests/viewsets/test_file.py
- contentcuration/contentcuration/viewsets/file.py
* Adds a small validation check to file uploads to ensure that we don't allow uploads of files with mismatched file formats and format presets
* Adds/updates tests for the same
> Ensure that file_format and preset match during file_upload requests.

- contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSetList.vue
Updated ActionLink to KButton
Updated MessageDialog to KModal
Screenshots:
[5234](https://github.com/learningequality/studio/issues/5234)
Test new KButton and KModal in channels/#/collections
It should be working as expected.
> Updated collection link and modal in channelSetList

- contentcuration/contentcuration/urls.py
- contentcuration/contentcuration/utils/files.py
- contentcuration/contentcuration/views/internal.py
- contentcuration/contentcuration/views/zip.py
- contentcuration/kolibri_public/views_v1.py
Addresses most of code-oriented CodeQL issues shown in https://github.com/learningequality/studio/pull/5300 . Changes are similar to suggestions, but some are simplified. For the most part, the changes avoid injecting user supplied input into error messages, and thus the page responses. Cloudflare already blocks a lot of malicious inputs that would target these.
https://github.com/learningequality/studio/pull/5300
> Address user-supplied CodeQL issues

- contentcuration/contentcuration/frontend/channelEdit/components/AnswersEditor/AnswersEditor.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/AnswersEditor/AnswersEditor.vue
- contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemEditor/AssessmentItemEditor.spec.js
- contentcuration/contentcuration/frontend/shared/views/TipTapEditor/TipTapEditor/DevHarness.vue
- contentcuration/contentcuration/frontend/shared/views/TipTapEditor/TipTapEditor/TipTapEditor.vue
- contentcuration/contentcuration/frontend/shared/views/TipTapEditor/TipTapEditor/TipTapEditorStrings.js
- contentcuration/contentcuration/frontend/shared/views/TipTapEditor/TipTapEditor/components/EditorToolbar.vue
- contentcuration/contentcuration/frontend/shared/views/TipTapEditor/TipTapEditor/components/image/ImageUploadModal.vue
- contentcuration/contentcuration/frontend/shared/views/TipTapEditor/TipTapEditor/components/link/LinkEditor.vue
- contentcuration/contentcuration/frontend/shared/views/TipTapEditor/TipTapEditor/components/math/FormulasMenu.vue
- contentcuration/contentcuration/frontend/shared/views/TipTapEditor/TipTapEditor/components/toolbar/MobileFormattingBar.vue
- contentcuration/contentcuration/frontend/shared/views/TipTapEditor/TipTapEditor/components/toolbar/MobileTopBar.vue
- contentcuration/contentcuration/frontend/shared/views/TipTapEditor/TipTapEditor/components/toolbar/ToolbarButton.vue
- contentcuration/contentcuration/frontend/shared/views/TipTapEditor/TipTapEditor/components/toolbar/ToolbarDivider.vue
- contentcuration/contentcuration/frontend/shared/views/TipTapEditor/TipTapEditor/composables/useBreakpoint.js
- contentcuration/contentcuration/frontend/shared/views/TipTapEditor/TipTapEditor/composables/useDropdowns.js
- contentcuration/contentcuration/frontend/shared/views/TipTapEditor/TipTapEditor/composables/useEditor.js
- contentcuration/contentcuration/frontend/shared/views/TipTapEditor/TipTapEditor/composables/useFormatControls.js
- contentcuration/contentcuration/frontend/shared/views/TipTapEditor/TipTapEditor/composables/useImageHandling.js
- contentcuration/contentcuration/frontend/shared/views/TipTapEditor/TipTapEditor/composables/useLinkHandling.js
- contentcuration/contentcuration/frontend/shared/views/TipTapEditor/TipTapEditor/composables/useMathHandling.js
- contentcuration/contentcuration/frontend/shared/views/TipTapEditor/TipTapEditor/composables/useModalPositioning.js
- contentcuration/contentcuration/frontend/shared/views/TipTapEditor/TipTapEditor/composables/useToolbarActions.js
- contentcuration/contentcuration/frontend/shared/views/TipTapEditor/assets/icon-formatSize.svg
This PR includes an implementation for the mobile view, in addition to enhancing the responsiveness of the design in general.
It also includes some refactoring because the main changes that the PR aimed to include, exposed some areas where refactoring became the right choice. 
Since the mobile view is different from the desktop design to a point where it can't just be fixed with just CSS tweaks or media queries. I did some thinking&research and decided to take a Conditional Toolbar Layout approach where I've created different components for different screen sizes.
>[!IMPORTANT]
> 1. This branch has a dependency on PR #5189 
> 2.  I created a playground to test the responsiveness of the editor in a real page by replacing the old editor with it temporarily, the commits responsible for this …
> feat(texteditor): Mobile view and responsiveness enhancements

- contentcuration/contentcuration/frontend/shared/styles/main.scss
Adds global css that overrides the z-index, set as an element style, when using Vuetify's `VDialog`. No issues were observed across studio after this change.
closes https://github.com/learningequality/studio/issues/5266
Do other Studio pages and modals have issues after this change?
> Override top-level vuetify dialog z-index

- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ImportFromChannelsModal.vue
- contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogList.vue
- contentcuration/contentcuration/frontend/shared/views/BottomBar.vue
- Removes snackbar that would announce whenever you selected or deselected an item for import
- Defaults the bottom bar component to align items vertically and simplifies usages of it by removing redundant flex styling
| Bottom bar | Screenshot |
| --- | --- |
| Import modal (before) | <img width="1477" height="171" alt="image" src="https://github.com/user-attachments/assets/2b8001b3-b1ba-42a6-a45f-ef079b790fd7" /> |
| Import modal (after) | <img width="1477" height="171" alt="image" src="https://github.com/user-attachments/assets/5f8ee6f6-7558-44c6-a96c-f2e8377acbb3" /> |
| Edit modal (before) | <img width="1477" height="171" alt="image" src="https://github.com/user-attachments/assets/b6a01d48-4cec-44ea-8734-1e0adc82a243" /> |
| Edit modal (after) | <img width="1477" height="171" …
> Remove resource selection snackbar from import modal

- contentcuration/contentcuration/frontend/channelEdit/router.js
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchOrBrowseWindow.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/__tests__/SearchOrBrowseWindow.spec.js
- contentcuration/contentcuration/frontend/shared/styles/main.scss
- Adds route handler to the import search route, to ensure channel and import destination folder ancestors are loaded prior to rendering the import modal. Also adds more defensive logic to prevent possibility of blank pages.
- Prevents showing recommendations when folder or ancestor folder is missing a title (ref: (2) in https://github.com/learningequality/studio/issues/5329)
- Fixes small regression with overlay z-index:
fixes https://github.com/learningequality/studio/issues/5326
- https://github.com/learningequality/studio/issues/5326 : This specific issue only occurred if you searched for something in the modal first
- z-index regression: add a new folder but don't give it a title, then attempt to exit the edit modal
> Fix blank page when reloading import modal after a search

- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/BrowsingCard.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ChannelInfoCard.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ChannelList.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ContentTreeList.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchFilterBar.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchOrBrowseWindow.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchResultsList.vue
- contentcuration/contentcuration/frontend/shared/views/RecommendedResourceCard.vue
- contentcuration/contentcuration/frontend/shared/views/form/Checkbox.vue
Adds keyboard navigation links that support jumping between sections of the import modal screens, that are only visible when navigating by keyboard. Also leverages the focus behavior to scroll top into view.
- Adds 'Jump to recommendations' link that appears in keyboard navigation after search box
- Adds 'Jump to search' and 'Jump to search results' that appears at the top of the recommendations box
- Adds 'Jump to top' that appears at the bottom of both search results and the recommendations links
- Scrolls to top when opening a channel for browsing, changing a browsing topic, or switching search pages
Out of scope: the 'Channels' select box causes KDS modality tracking to lose its keyboard state
closes https://github.com/learningequality/studio/issues/5268
fixes …
> Add keyboard navigation links and scrolling for jumping in import modal

- contentcuration/contentcuration/frontend/channelEdit/views/files/ContentRenderer.vue
This pr fixes the `KLogo` display in the resource preview window during loading of resources
**Before**
https://github.com/user-attachments/assets/49667c6b-e9c1-4680-a741-2d481d54a9b1
**After**
Fixes #5327
- Sign in to Hotfixes with an account with enabled search recommendations
- Go to a channel with resources and try to preview a resource
- Attempt to import a resource from other channels and preview it
> Fixes the KLogo display in preview window

- contentcuration/contentcuration/frontend/channelList/views/ChannelListIndex.vue
Imported StudioOfflineAlert changing the OfflineText in ChannelListIndex, and  updated the file with the change in import.
I have checked there is no change in UI.
Closes #5219
There are only changes in ChannelListIndex.vue file.
> Imported StudioOfflineAlert in ChannelListIndex

- contentcuration/contentcuration/tests/utils/test_exercise_creation.py
- contentcuration/contentcuration/utils/assessment/qti/archive.py
* Add regression test for input question generation in QTI.
* Fix QTI generation, and add proper type information for text entry info.
Fixes [#5230](https://github.com/learningequality/studio/issues/5230)
I suspect this also fixes [#5291](https://github.com/learningequality/studio/issues/5291) due to the string coersion of the value field.
Create an input question with multiple correct answers, and ensure that it can be published.
> Fix input question related publish issues

- contentcuration/contentcuration/frontend/shared/views/TipTapEditor/TipTapEditor/TipTapEditorStrings.js
- contentcuration/contentcuration/frontend/shared/views/TipTapEditor/TipTapEditor/components/image/ImageUploadModal.vue
Instead of hard coding the accepted extension types for image uploading, I now compute them from the `ACCEPTED_MIME_TYPES` provided by the image upload service. 
Also I stopped translating them. I noticed this because I saw a mismatch that we didn't notice in the image upload modal.
---
1. Go to the exercise editor
2. Click the add image button
3. See the accepted extension types at the bottom of the open modal
> fix(texteditor): compute accepted images extensions from mimes

- contentcuration/contentcuration/frontend/channelEdit/components/move/MoveModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/move/NewTopicModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/move/__tests__/moveModal.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/move/__tests__/newTopicModal.spec.js
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchOrBrowseWindow.vue
- contentcuration/contentcuration/frontend/channelEdit/views/trash/TrashModal.vue
- contentcuration/contentcuration/frontend/channelEdit/views/trash/__tests__/trashModal.spec.js
- contentcuration/contentcuration/frontend/shared/styles/main.scss
- contentcuration/contentcuration/frontend/shared/views/RecommendedResourceCard.vue
- package.json
- pnpm-lock.yaml
This pr fixes unresponsiveness of the trash page **Restore** button and **Add New Folder** button in the move resource page caused by the css overriding done when fixing https://github.com/learningequality/studio/pull/5322. To fix the issue, a new prop `appearanceOverrides` has been added to the `KTooltip` component so its appearance can be better manipulated, particularly the `z-index` in this case. 
**Note:** Testing this pr is dependent on merging and releasing https://github.com/learningequality/kolibri-design-system/pull/1112
**Before:**
Restore button
https://github.com/user-attachments/assets/c6d50705-febf-4ddb-869c-a8b872dc5c37
Add New Folder button
https://github.com/user-attachments/assets/88e77270-fdf9-45a9-9e8e-49d4a30cda68
**After:**
The tooltips still work as before …
> Fix css override troubles

- contentcuration/contentcuration/tests/utils/test_markdown.py
- contentcuration/contentcuration/utils/assessment/qti/mathml/core.py
The pydantic implementation of the mo element I had previously done was missing the non-standard `accent` property. This was causing errors during publish for one of Peter's test channels.
I took the LaTeX from that specific exercise to make a regression test, and confirmed that adding the accent property to the pydantic class resolved the issue.
Fixes this error I saw when running publish in an interactive shell in a disposable pod on hotfixes:
```
ValidationError: 1 validation error for Mo
accent
Extra inputs are not permitted [type=extra_forbidden, input_value='true', input_type=str]
For further information visit https://errors.pydantic.dev/2.11/v/extra_forbidden
```
Cross check with the MDN page: https://developer.mozilla.org/en-US/docs/Web/MathML/Reference/Element/mo#accent
I also …
> Add regression test for and fix use of accent property for mo tag.

- contentcuration/contentcuration/frontend/channelEdit/components/ResourceDrawer.vue
This pr adds focus trapping to the resource preview side panel displayed when importing resources from other channels. It uses the [`useFocusTrap`](https://github.com/learningequality/studio/blob/01e8feef3af5d97cd9f9be6874216a6b2b6117e0/contentcuration/contentcuration/frontend/shared/views/TipTapEditor/TipTapEditor/composables/useFocusTrap.js) composable (implemened by @habibayman, Thank you! 🙂).
**Note:** This seems like best way to resolve the bug for now, however, ultimately, we'll want to migrate the side panel from Vuetify so we can take advantage of the `KFocusTrap` component, which won't work out of the box with the current side panel implementation.
**Before**
**After**
https://github.com/user-attachments/assets/96a027a2-2cd9-4878-abd6-e30252beb9fb
Fixes #5269
- Import resource …
> add focus trapping to resource preview side panel

- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/tasks.py
- contentcuration/contentcuration/tests/helpers.py
- contentcuration/contentcuration/tests/test_models.py
- contentcuration/contentcuration/tests/utils/restricted_filesystemstorage.py
- contentcuration/contentcuration/tests/utils/test_publish.py
- contentcuration/contentcuration/tests/utils/test_restricted_filesystemstorage.py
- contentcuration/contentcuration/tests/viewsets/base.py
- contentcuration/contentcuration/tests/viewsets/test_channel.py
- contentcuration/contentcuration/tests/viewsets/test_community_library_submission.py
- contentcuration/contentcuration/utils/publish.py
- contentcuration/kolibri_public/tests/test_export_channels_to_kolibri_public.py
- contentcuration/kolibri_public/utils/export_channel_to_kolibri_public.py
This PR ensures that if an older channel that does not have a versioned database file yet is added to the community library, the versioned database file is created.
Solves #5191.
~This PR depends on changes from #5228, and must be **merged after it**.~ _(Done)_
~After merging #5228, this PR should first be rebased onto the merged changes and only then reviewed and merged.~ _(Done)_
> Ensure channel version database exists when adding to community library

- contentcuration/contentcuration/frontend/accounts/pages/accountDeleted/AccountDeleted.vue
- contentcuration/contentcuration/frontend/accounts/pages/activateAccount/AccountCreated.vue
Updated VBtn to Kbutton in Account Delete and Account Created pages
Closes [5353](https://github.com/learningequality/studio/issues/5353)
Test Kbuttons in Account Deleted and Account created pages.
> [Remove Vuetify from Studio] Buttons / links on account created / deleted pages

- contentcuration/contentcuration/tests/utils/test_exercise_creation.py
- contentcuration/contentcuration/utils/assessment/qti/archive.py
* Fixes issue where free response questions with no set answers (i.e. all of them) would get set as having a float value in the QTI.
* Adds regression test and defaults to string value when no answers are given
* Update to check all candidate answers, so that users are free to input specified incorrect answers
Fixes the Studio aspect of https://github.com/learningequality/kolibri/issues/13754
Create a survey in your local Studio. Add a free response question.
Import it into Kolibri using code from this PR: https://github.com/learningequality/kolibri/pull/13791
Ensure that you can enter text responses and submit.
Screenshot of a successfully submitted survey response in the report:
> Ensure free response questions can be answered

- contentcuration/contentcuration/frontend/channelEdit/components/move/MoveModal.vue
Fixes #5355 
Updated Buttons from Vbtn to KButton in Move modal
Used KButtonGroup for the bottom right Buttons for 8px spacing.
IMAGES
• Parent issue: https://github.com/learningequality/studio/issues/5060
Login as a@a.com with password a
Go to Channels > Published Channel
Check topic or resource
Click "Move" icon
> [Remove Vuetify from Studio] Buttons in Move modal #5355

- contentcuration/contentcuration/tests/viewsets/test_contentnode.py
- contentcuration/contentcuration/viewsets/contentnode.py
Add regression test for erroneous randomize validation on HTML5.
Make randomize no longer required.
Prevent contentnodes from having their kind updated after creation. Ensure randomize is set at exercise creation.
Add tests for the above behaviours.
Fixes https://github.com/learningequality/studio/issues/5417
Upload an HTML5 zip. Ensure that it gets properly saved into the channel, and that the channel is then publishable.
I used Claude Code to write the tests here, and I don't think I had to modify them at all. Production code was also implemented by Claude Code, but I checked and reviewed every line closely, and it was in accordance with my specific implementation plan, I just verified that it did it as I intended.
> Fix validation to allow upload of HTML5 files

- contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSetModal.vue
- contentcuration/contentcuration/frontend/channelList/views/ChannelSet/__tests__/channelSetModal.spec.js
Replaced Vuetify's MessageDialog component with Kolibri Design System's KModal for the unsaved changes dialog in the Collections modal.
- Replaced MessageDialog with KModal in ChannelSetModal.vue
- Updated modal props to use KModal's API (title, submitText, cancelText)
- Maintained all existing functionality and event handlers
**Manual verification:**
1. Logged in as user@a.com with password a
2. Navigated to Channels > Collections
3. Clicked "New collection" button
4. Added text to Collection name input
5. Clicked close button in the top bar
6. Verified unsaved changes modal appears with KModal styling
7. Tested both "Exit without saving" and "Save and close" buttons
8. All functionality works as expected
After Changes Screenshot:
- Fixes: #5299 
**Test these changes by:**
Login as …
> [Remove Vuetify from Studio] 'Unsaved changes' modal in Channels - New collection
