learningequality/studio

- contentcuration/contentcuration/serializers.py
- contentcuration/contentcuration/static/js/edit_channel/models.js
- contentcuration/contentcuration/static/js/edit_channel/views.js
DONE:
- fix the GET serialization of `content_copy`, as to not have `127.0.0.1:8008` prepended to it. Did this by explicitly declaring the FileField to be `use_url=False`.
- Fix the URL construction of previews to correctly fetch the content.
- Properly find the files associated with a Format, by removing a hardcoded id.
@jayoshih
> Content previewing fix

- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/serializers.py
- contentcuration/contentcuration/settings.py
- contentcuration/contentcuration/views.py
I accidentally merged my PR https://github.com/fle-internal/content-curation/pull/57, I linked the commits in that PR for post-reviewing ~
> ContentCuration launch tasks Continue

- contentcuration/contentcuration/views.py
Added content_id to duplication logic so that when a curator imports from another channel, kolibri progress will be retained
> Update content_id duplication logic

- contentcuration/contentcuration/management/commands/exportchannel.py
Fixes the issue of Swahili assessment item JSON files not being written to Perseus files during export.
In fact, fixes the issue that *no* Perseus (i.e. KA) exercises would contain assessment items anymore, after some reason CC server changes. We just hadn't republished EN lately.
Also through in a small optimization (only need to run some migrations to create a content DB).
> Channel exporting fixes

- contentcuration/contentcuration/views.py
Since `HttpResponseBadRequest` is not an exception, we need to return it, instead of raise.
> Return `HttpResponseBadRequest`

- package.json
Lessify had some issues that needed to be resolved. Applied the pending PRs that allow for things like global styles, also brought in my own changes so that we can gracefully recover from less errors.
If i end up getting the npm packages, I'll change it back.
Suggested order of commands after merge:
```
npm cache clear
npm remove node-lessify
npm install
```
Then just build as usual!
See changes to lessify here:
https://github.com/DXCanas/node-lessify/blob/master/README.md
If you're interested
> Pointing lessify to @dxcanas version

- contentcuration/contentcuration/static/js/bundle_modules/base.js
- package.json
Using [this package](https://www.npmjs.com/package/promise-polyfill), promise support goes back to IE8.
Was going to try and employ [this technique](https://philipwalton.com/articles/loading-polyfills-only-when-needed/) so that we wouldn't even load the code, but it seemed like it might be a little messy to write a script outside of `base.js` (already dedicated to preparing the environment). @rtibbles thoughts? and if I do employ the implementation he suggests, where should I put that code? inside a `<script>` tag in [`base.html`](https://github.com/fle-internal/content-curation/blob/develop/contentcuration/contentcuration/templates/base.html)?
> Adding promise polyfill

- contentcuration/contentcuration/utils/logging.py
- contentcuration/contentcuration/view/internal_views.py
Add a trace function to trace functions that aren't automatically traced by our newrelic tracer.
> Add tracing decorator over convert_data_to_nodes

- contentcuration/contentcuration/urls.py
- requirements_dev.txt
Fixes #364 warnings about string args in `url`
> Fix Django 1.10 deprecation warnings

- contentcuration/contentcuration/management/commands/exportchannel.py
Should fix https://github.com/learningequality/kolibri/issues/1796 after publishing.
> Fix exportchannel so it doesn't filter out assessment item answers that are 0

- contentcuration/contentcuration/static/js/edit_channel/import/views.js
- contentcuration/contentcuration/static/js/edit_channel/import/vuex/importActions.js
UI handles the error case when `importCollection.duplicate` fails (e.g. during timeout)
> Show an error when importCollection.duplicate fails

- Dockerfile
Added `libjpeg-dev` for `Pillow` so that we can have the jpeg decoder. 
Here is the test result showing that jpeg support is now available:
```
--------------------------------------------------------------------
PIL SETUP SUMMARY
--------------------------------------------------------------------
version      Pillow 2.8.1
platform     linux2 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609]
--------------------------------------------------------------------
*** TKINTER support not available
(Tcl/Tk 8.6 libraries needed)
--- JPEG support available
*** OPENJPEG (JPEG2000) support not available
--- ZLIB (PNG/ZIP) support available
*** LIBTIFF support not available
*** FREETYPE2 support not available
*** LITTLECMS2 support not available
*** WEBP support not available
*** WEBPMUX …
```
> add jpeg decoder package

- Dockerfile
- build.js
- package.json
- yarn.lock
Fixes #464 
1. Modifies build.js to allow it to be called with a `--prod` flag, which set `NODE_ENV=production`
1. Modifies Dockerfile to deploy using this flag
1. Introduces `envify` library, per suggestion in Vue docs.
To test, you can add/remove the prod flag at this line
http://github.com/jonboiser/content-curation/blob/5596dab09cf09dd2841d03f8d7ccca7c462a6ba4/contentcuration/contentcuration/management/commands/runserver.py#L49
And run the app. The Vue warning should show/not show when opening the "import from other channels" modal, depending on whether the flag is set.
> Add a --prod flag to build.js for production deployment

- contentcuration/contentcuration/static/js/edit_channel/exercise_creation/views.js
- contentcuration/contentcuration/static/js/edit_channel/utils/mathjaxtosvg.js
1. change CDN used to load MathJax referenced in `edit_channel/utils/mathjaxtosvg.js`
2. change REGEX used by `replace_mathjax_with_katex` to be non-greedy to avoid problems like this
> Two small fixes around exercises

- contentcuration/contentcuration/static/js/edit_channel/uploader/hbtemplates/edit_metadata_editor.handlebars
Create a new topic in a test channel.
Before this change, see an author field:
After this change, ensure there's no author field:
... but ensure that the author field is still there when editing content nodes, i.e. when you click "Upload Files" or "Create Exercise":
> Don't show author field when editing topics

- contentcuration/contentcuration/static/js/edit_channel/new_channel/views.js
- requirements.txt
Tested on Mac + Chrome! Go to your channel list, click a channel, ensure it goes to the editor view in the same tab. But, when you hold down the command key and click a channel, ensure it opens in a new tab in the background!
According to the first comment on this [StackOverflow answer](https://stackoverflow.com/a/26823929/392426), this should work on Windows as well, as `metaKey` will map onto `ctrl`.
> Support cmd+click a channel to open it in a new tab

- README.md
Some notes:
- Seems like the DB name was changed from `contentcuration` to `gonano` in e623720ede947f3834a1496ddc48aa44ecfe4d0a
- Incorporates #561 — a command for adding dummy data with an admin user + sample channels
> Updates to the README, and for setting up on Mac

- contentcuration/contentcuration/dev_settings.py
- contentcuration/contentcuration/templates/base.html
Test plan:
- Remove `{% if not debug %}` tag
- Refresh or open 127.0.0.1:8000 in your browser
- Go to the Studio property on Google Analytics
- See 1 active user from your IP
- Put back in the `{% if debug %}` tag
- Refresh localhost
- View source
- Ensure Google Analytics tracking code isn't in `<head>`
(I wish I knew an easier way to test production mode ... I tried a bunch of things but decided to let it go after spending 5 minutes on this.)
> Add Google Analytics tracking to every page

- contentcuration/contentcuration/static/js/bundle_modules/base.js
Ideal case would be to include this in a bundle.
> Quick fix for inline JS at Django template level.

- contentcuration/contentcuration/views/nodes.py
That's bad, as two of these long running transactions that modify the same set of rows will likely arrive in a deadlock. See the "Deadlocks" section in this page: https://www.postgresql.org/docs/9.1/static/explicit-locking.html
> Remove long running transaction when moving nodes

- contentcuration/contentcuration/static/less/details.less
It lets long words get broken up in the channel content preview, so that they are still legible.
This is a fix for #765 
Before:
After:
I added a `word-wrap: break-word` property to the CSS.
We may want to add hyphens at some point.
> allow word breaking for long titles in channel content preview

- contentcuration/contentcuration/views/files.py
- contentcuration/contentcuration/views/nodes.py
Remove use of node_duplication_stats. Not working for all cases anyway.
Force JSON parsing of preferences. It's still only a string despite first parsing.
> Bugfixing from the QA session

- contentcuration/contentcuration/dev_settings.py
- contentcuration/contentcuration/urls.py
- contentcuration/contentcuration/views/files.py
Exercises with images need to use the /content/storage url to get images and can't use absolute urls. This will serve up files using the storage system at this endpoint (debug mode only)
> Serve files on the /content/storage endpoint (debug only)

- contentcuration/contentcuration/management/commands/setup.py
- contentcuration/contentcuration/settings.py
The default was a local memory cache, which was fast, but led to discrepancies
in each app's cache. Also added the `createcachetable` command as part of setup.
> Use a shared database cache. Fixes #803.

- contentcuration/contentcuration/models.py
> Merge user clipboard sort_order fix and _check_tree_space sanity check

- Pipfile
- Pipfile.lock
- cloudbuild-production.yaml
- contentcuration/contentcuration/production_settings.py
- contentcuration/contentcuration/settings.py
- k8s/helm-deploy.sh
- k8s/templates/studio-deployment.yaml
- k8s/templates/studio-secrets.yaml
- k8s/values-prod-config.yaml
- requirements.txt
We now have a [Sentry dashboard](https://sentry.io/learningequality/studio/) for all error reports, with much more context and helpful information than the old Google Cloud error reports.
Integration here involved adding sentry to our python code, and adding the secrets to our build and deployment pipeline.
For now, there's no user dialog box created, but we do get any backend errors at least.
> Send error reports to sentry.io

- contentcuration/contentcuration/management/commands/exportchannel.py
Fixes #858. Don't error out when a token for a channel already exists.
Instead just get it and reassign to the channel.
> Fix token assignment when it already exists for some reason.

- contentcuration/contentcuration/tests/test_utils.py
- contentcuration/contentcuration/utils/files.py
To ensure our changes don't change the current behaviour, we create tests for the current endpoint.
We then apply the following optimizations:
- share TCP sessions between requests
- parallelize requests between threads
- use a direct HEAD request when checking file existence, and check the status
code returned to see if it exists or not.
> Improve the file_diff endpoint speed

- contentcuration/contentcuration/tests/test_garbage_collect.py
- contentcuration/contentcuration/utils/garbage_collect.py
And then disable actual object storage file deletion ;)
Postponing actual file deletion until we implement some kind of checking to see if files are not referenced anymore.
> Test to check that we don't delete files referenced by orphan and non-orphan nodes

- contentcuration/contentcuration/static/js/edit_channel/exercise_creation/views.js
- contentcuration/contentcuration/static/js/edit_channel/models.js
Currently, if an AssessmentItem has invalid data, the exercise editor UI will fail to load and throw errors in the JS console. This makes it impossible for the exercise creator to delete or fix the problematic exercise item.
This change checks the existence of valid AssessmentItem answer data before trying to parse it. If invalid data exists, it will just not try to parse the invalid data and load it into the editor, which allows the editor and the valid data to appear. When the user saves, the invalid data will be replaced with whatever valid data the user provided while editing (or the invalid data will have been deleted).
#879 #892 
Since it is not clear how the data got into this state, the only currently known way to reproduce the problem is to manually add an AssessmentItem into the …
> Ensure exercise editor responds gracefully to invalid AssessmentItem answer data

- contentcuration/contentcuration/settings.py
- contentcuration/contentcuration/static/js/edit_channel/exercise_creation/views.js
> Add ContentConfig to installed apps so we get our bucket

- contentcuration/contentcuration/static/js/edit_channel/new_channel/views.js
This code is basically just debugging code to help us track down the Sentry errors we're seeing with some channel_list objects being null at unexpected times.
#900 
As we don't know the cause of the error, the only way to test this change is to locally inject an error into one of the get_user_channels_* calls. That is how I tested that this function works in the non-Sentry case.  
We should probably come up with a consistent approach to handling API call errors in the front end so that we have at least some default reporting / handling for failed API calls.
- Ivan @ivanistheone …
> Catch errors in channel load. 

- webpack.config.js
This helps us have better errors on our Sentry frontend reports. This creates an
external source map (*.js.map)  for each of our final JS bundles.
> enable source maps for our JS code

- contentcuration/contentcuration/apps.py
- contentcuration/contentcuration/dev_settings.py
- contentcuration/contentcuration/settings.py
Otherwise we don't need it on production (GCS already has our buckets). We also
don't need it on tests (we bring down and create buckets as tests need it).
We do this through the `AWS_AUTO_CREATE_BUCKET` setting. We set it to `False`
globally, then set it to `True` on `dev_settings.py`.
> Attempt to auto-create buckets only on dev mode

- cloudbuild.yaml
- k8s/create-cloudsql-database.sh
This PR is to resolve the issue that `develop` SQL instance does not exist in the `ops-central` google cloud project, so that when we run builds there, the builds will always fail. 
Check that the builds run successfully in both `studio` and `ops-central` projects.
> Choose the SQL instance name based on project ID

- contentcuration/contentcuration/static/js/edit_channel/queue/views.js
We don't check for errors before attempting to set the clipboard item color based on thumbnail.
#914 
As we do not have information on what error is triggering, the best we can do is test that adding an item with thumbnail to the clipboard works.
> Check for errors before trying to set color from thumbnail

- contentcuration/contentcuration/tests/test_public_api.py
- contentcuration/contentcuration/urls.py
- contentcuration/contentcuration/views/public.py
Adds an info endpoint which will help determine the type of device we are syncing content from. 
Basically is a copy of this https://github.com/jamalex/kolibri/pull/2
> Add info endpoint so Kolibri knows Studio can serve content

- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/tests/test_public_api.py
- contentcuration/contentcuration/urls.py
- contentcuration/contentcuration/views/public.py
Fixes a problem where I forgot to check for a null value and thus didn't handle the orphanage case properly in my save fixes.
#929 
> Save hotfix

- deploy/nginx.conf.jinja2
This speeds up browser loading for mobile devices and those with slow internet connections.
> Add browser caching on static files

- contentcuration/contentcuration/management/commands/exportchannel.py
- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/serializers.py
- contentcuration/contentcuration/tests/test_channel_model.py
- contentcuration/contentcuration/tests/test_channelcache.py
- contentcuration/contentcuration/tests/test_secrettoken_model.py
- contentcuration/contentcuration/utils/channelcache.py
- contentcuration/contentcuration/views/base.py
... and add testing to a bunch of stuff along the way.
This PR does 4 things:
1. Move certain logic found in views into Channel model functions:
- getting the public channel list
- creating a human readable token
- reading the human readable token
- getting the resource count for a channel
- getting the last modified date for a channel's content
1. Add tests for the functions mentioned above ^
1. Add a class called `ChannelCacher`. This class wraps any channel and caches
certain functions:
- getting the public channel list
- creating a human readable token
- reading the human readable token
- getting the resource count for a channel
- getting the last modified date for a channel's content
1. Cache the entire get_user_public_channels function.
I'm not able to fully compare the speed up …
> Add caching to the get_user_public_channels endpoint

- contentcuration/contentcuration/utils/gcs_storage.py
Fixes #967. The assertion was too specific too strings, and errored out on unicode.
> Rmove assertion error on file type

- contentcuration/contentcuration/utils/gcs_storage.py
Just return the filename passed in, since the logic is implemented through generate_object_storage_name.
> Create simplified implementation for gcs_storage.generate_filename

- contentcuration/contentcuration/tests/test_gcs_storage.py
- contentcuration/contentcuration/utils/gcs_storage.py
It may be causing issues with zip files. The compute instances are also close enough to GCS and have big enough bandwidth to make the caching negligible.
> Remove the GCS storage cache

- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/tests/test_channel_model.py
- contentcuration/contentcuration/utils/channelcache.py
- contentcuration/contentcuration/views/admin.py
- deploy/chaos/loadtest/locustfile.py
- deploy/chaos/loadtest/prep.py
Add basic caching to the `get_all_channels` endpoint. This caches both the entire endpoint's return value, and the listing of all channels from the DB. I moved that line of code to its own method in the `Channel` model as well.
Along the way, I needed to benchmark that endpoint to see if my changes are effective. I created a new `prep.py` file to create 1000 channels with editors and viewers attached. I also extended our load testing script to query the get all channels endpoint as well.
> Add caching to the admins page

- contentcuration/contentcuration/settings.py
Allows Django to handle fallbacks for each message (built-in feature).
Resolves #405 
Killed off a few languages, including pirate english :disappointed: sorry y'all.
Django has language fallback features that automatically update the code returned in `get_language` - if a regional version of the language isn't found, it'll fall back to the next closest thing (non-regional, then some other region).
Not that I know of, but this is why I included @jayoshih 
Please verify asap so that I can get the points for the bug bash :smile:
> Removing languages we don't have frontend translations for.

- Dockerfile.dev
- k8s/images/app/Dockerfile
> Work around pipenv compat issue with pip 18.1 by pinning the version.

- contentcuration/contentcuration/utils/files.py
- contentcuration/contentcuration/utils/gcs_storage.py
- contentcuration/contentcuration/views/admin.py
This is to fix the chef's failing to thumbnail upload issue on develop:
```
WARNING: The following nodes have one or more descendants that could not be created:
1 descendant (Internal Server Error)
```
This was a very weird issue because it didn't occur on local dev (mac), and in local docker-env deployed with docker-compose (linux). Issue is only occuring on develop.studio.leq.org
https://sentry.io/learningequality/studio/issues/720026215/
Two possible root causes:
1. Temp file returned by `default_storage.open` is is not read from the beginning (since last thing it saw was a flush so it could be at the end of the file "end" and needs to be.
2. OS-level disk buffering: the call to `tempf.close()` does a flush, but OS might have not sync-ed the data to disk yet, so when PIL.Image tries to …
> Image fix b

- contentcuration/contentcuration/management/commands/loadconstants.py
- contentcuration/contentcuration/tests/test_utils.py
No need to get from github json; prefer constants from le_utils package.
Added tests to make sure loadconstants doesn't break
> Stop getting le-utils constants from github

- contentcuration/contentcuration/models.py
We now dedupe by `content_id` when calculating the total resource count for a channel.
For example, brings KA english resource count from ~34000 to ~13000.
With postgres we can call `distinct` on a specific column, but it must be preceded by `order_by` for that same column. 
> dedupe by content id for resource count

- contentcuration/contentcuration/static/js/edit_channel/exercise_creation/__tests__/ExerciseView.spec.js
- contentcuration/contentcuration/static/js/edit_channel/exercise_creation/__tests__/__snapshots__/ExerciseView.spec.js.snap
- contentcuration/contentcuration/static/js/edit_channel/information/views.js
- contentcuration/contentcuration/static/js/edit_channel/models.js
- contentcuration/contentcuration/static/js/edit_channel/state.js
- contentcuration/contentcuration/static/js/edit_channel/utils/dialog.js
- contentcuration/contentcuration/static/js/edit_channel/utils/number_parser.js
- contentcuration/contentcuration/static/js/utils/get_cookie.js
- contentcuration/contentcuration/static/js/utils/offline_helper.js
- contentcuration/contentcuration/static/js/utils/studioJquery.js
- jest_config/jest.conf.js
- jest_config/styleMock.js
- package.json
- yarn.lock
Adds the basic tooling for doing snapshot tests in Jest with handlebars templates.
Implements three basic snapshot tests for the exercise editor tool.
Fixes up a few other things that cropped up while trying to get the tests to run!
> A snapshot of a snapshot

- __mocks__/backbone.js
- contentcuration/contentcuration/static/js/edit_channel/__tests__/ContentNodeCollection.spec.js
- contentcuration/contentcuration/static/js/edit_channel/exercise_creation/__tests__/ExerciseView.spec.js
- contentcuration/contentcuration/static/js/edit_channel/models.js
- jest_config/setup.js
This PR adds a regression test for, and then fixes the issue of assessment items moving to the last item in a list of nodes.
Fixes #1047
* Create multiple exercise content nodes
* Add an assessment item to each one
* Select all of them to modify the metadata all at once.
* Observe the assessment items not all migrate to the last content node.
(Also try this on develop to see it happening!)
This seems to be a result of an asymmetrical implementation between assessment items and files. It also might be a result of always calling save on a collection, even when only one model is being edited, but not sure.
> Moving exercises

- contentcuration/contentcuration/static/js/edit_channel/models.js
- contentcuration/contentcuration/tests/test_gcs_storage.py
- contentcuration/contentcuration/utils/files.py
- contentcuration/contentcuration/utils/gcs_storage.py
- contentcuration/contentcuration/views/admin.py
This PR contains three bugfixes from develop. 
- https://github.com/learningequality/studio/pull/1056  (subset of)
- https://github.com/learningequality/studio/pull/1034
- https://github.com/learningequality/studio/pull/1042
- https://sentry.io/learningequality/studio/issues/720026215/
- https://github.com/learningequality/studio/issues/1047
- https://github.com/learningequality/studio/issues/1030
> Oct 26th patch release to production

- contentcuration/contentcuration/__init__.py
Celery broke during deploy from 30 mins ago.
This is what happens on PUBLISH:
^ caued because publish `.delay` task hangs.
For some reason this wasn't a problem before the current deploy. Why??
Yesterday during local testing this fixed the issue. So I'm hoping this will fix prod now.
> Celery hotfix master

- contentcuration/contentcuration/__init__.py
- We ran into some trouble PUBLISHing channels on develop today.
- Instead of being an "async" call, studio backend would hang and timeout.
- I was able to reproduce locally, then found the missing piece of code
https://github.com/learningequality/studio/issues/1060
Before: no can haz publish
After: publish works again
> put back the celery import

- contentcuration/contentcuration/static/js/bundle_modules/base.js
In Sentry, we get a lot of errors that appear to be printouts of some form of the jquery XHR object. Some sample reports can be found here:
https://sentry.io/learningequality/studio/issues/658785918/
This PR basically implements the solution described here for catching jQuery AJAX errors:
https://docs.sentry.io/clients/javascript/tips/#jquery-ajax-error-reporting
With any luck, this will allow us to get AJAX error reports we can actually make sense of.
(Or, just try to copy a few thousand KA nodes on develop :) 
- Ivan ivanistheone …
> Get detailed Sentry error reports for AJAX call errors.

- contentcuration/contentcuration/static/js/edit_channel/new_channel/views.js
Ensures that channels correctly display their item count.
First, I broke it by accidentally changing the variable name in the template.  Then I fixed it by changing it back!
Before:
After:
> Correctly display channel item counts

- .pre-commit-config.yaml
- k8s/templates/studio-deployment.yaml
- k8s/templates/studio-service.yaml
This adds extra labels on our app and worker containers, and makes our service
route only to the app containers. This will avoid accidentally routing requests
to the worker container. The latter will just not respond, leading to 502 errors.
Oh, and remove the check-yaml portion of our pre-commit hooks. It barfs on our perfectly valid templated yaml files.
> Add extra labels to app and worker pods

- contentcuration/contentcuration/templates/base.html
Silence the last of the Sentry noise trifecta - the CloudFlare AlwaysOnline errors. (At least 151 of these in the error reports.) These appear to be caused by issues where CloudFlare tries to serve an offline version of the site. I'm not even sure if we should allow this, but in the meantime, we should at least silence errors generated by CloudFlare's offline cache versions as it doesn't seem possible to reproduce with the actual site.
Once this has been pushed to production, the reports should hopefully be mostly signal rather than noise!
Test is just to make sure we get Sentry errors.
#1069 
- Micah micahscopes …
> Silence offline errors

- k8s/templates/_helpers.tpl
We define a new environment variable, STUDIO_BETA_MODE, that sets that env var
on production clusters.
> Add STUDIO_BETA_MODE var on deployments

- docker-compose.yml
Alternate attempt to fix pipenv by turning off the emoji output. This would allow us to not pin pipenv.
> [Don't merge] No terminal emojis

- contentcuration/contentcuration/tests/test_files.py
- contentcuration/contentcuration/utils/files.py
Avoid creating the file multiple times by just setting the path in the file object after writing the file.
Addresses #1030 
> GCS 410 error fix for writing thumbnails repeatedly

- contentcuration/contentcuration/management/commands/exportchannel.py
This time, catch a thumbnail that's not an image!
We get this traceback:
```python
File "/usr/lib/python2.7/pdb.py", line 1314, in main
pdb._runscript(mainpyfile)
File "/usr/lib/python2.7/pdb.py", line 1233, in _runscript
self.run(statement)
File "/usr/lib/python2.7/bdb.py", line 400, in run
exec cmd in globals, locals
File "<string>", line 1, in <module>
File "contentcuration/manage.py", line 2, in <module>
import os
File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 356, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", …
```
> Image file error hotfix part 2

- contentcuration/contentcuration/management/commands/exportchannel.py
This time we put the `except IOError` in the right location, catching the function that actually calls ImageMagick.
> File image error publishing fix, part 3

- package.json
I've been getting a lot of `SIGTERM` errors when the time limit runs out, so I just removed it completely
> Remove wait-on time limit

- contentcuration/contentcuration/static/js/edit_channel/details/hbtemplates/channel_editor.handlebars
- contentcuration/contentcuration/static/js/edit_channel/new_channel/hbtemplates/channel_item.handlebars
Languages weren't being properly referenced on the handlebars templates, which was leading to languages not showing up.
> Fixed language not showing up

- contentcuration/contentcuration/static/js/edit_channel/router.js
Fixes the error described in the second half of #1134. Fixes an oversight during the global state refactor, where a reference to the router bound nodeCollection was left extant.
* Add something to clipboard
* Try to delete something from clipboard
> Pass the global State nodeCollection to the clipboard view

- contentcuration/contentcuration/serializers.py
- contentcuration/contentcuration/static/js/edit_channel/channel_settings/views.js
- contentcuration/contentcuration/static/js/edit_channel/image/views.js
The migration to a JSONField for thumbnail_encoding introduced a couple of bugs. This resolves them.
Makes the thumbnail_encoding field optional to allow creation of new channels without a thumbnail.
Updates the thumbnail_encoding frontend logic for the ThumbnailUploadView, and the Channel Settings Modal, to account for the fact that an unset `thumbnail_encoding` field is now an empty object, and not simply undefined.
Also fixes a hitherto unreported bug where thumbnails could not be removed from the channel settings modal.
A
- Create a new channel
- Don't set a thumbnail
- Finish creating the channel
- Great success!
B
- Create a new channel
- Don't set a thumbnail
- Open the channel
- Open channel settings thumbnail
- See thumbnail!
C
- Add a thumbnail to channel from channel settings …
> Fix thumbnail_encoding issues for channels.

- contentcuration/contentcuration/templates/base.html
We're getting a lot of IndexSizeError Sentry reports still, but we can't seem to reproduce or get valid stack traces, so these reports aren't very helpful. I have created #1148 to make sure we have a ticket for this issue for when we have more time to investigate.
> Add a couple more variations of the IndexSizeError messages to the ignoreErrors list.

- contentcuration/contentcuration/static/js/edit_channel/image/views.js
Don't check for base64 key of null in thumbnail_encoding.
Fixes #1153
- Open an exercise
- See questions have loaded
> Don't fall over for content node thumbnails

- contentcuration/contentcuration/serializers.py
- contentcuration/contentcuration/static/js/edit_channel/exercise_creation/views.js
- contentcuration/contentcuration/static/js/edit_channel/image/views.js
- contentcuration/contentcuration/tests/test_fileendpoints.py
- contentcuration/contentcuration/tests/test_rest_framework.py
- contentcuration/contentcuration/views/files.py
Change how we handle exercise image file uploads in the frontend.
Associate files with assessment item at upload time.
Simplify bulk update endpoint to just update.
Use explicit POST and DELETE for creating and deleting assessment items.
Fixes #1135 and resolves #1139.
- Create an exercise
- Create a question
- Add image to the question
- Delete the image
- Add another image
- Save the exercise
- See no error
No, but I think the approach of associating the file object with the ContentNode or AssessmentItem in question at the time of initial upload means that we can reduce complexity in the frontend trying to set foreign keys from there, and should be replicated in other file upload endpoints.
> Exercise Images Fix

- contentcuration/contentcuration/static/js/edit_channel/image/views.js
Quick fix for undefined as well as null in thumbnail_encoding.
> Do existence check rather than explicit null check.

- contentcuration/contentcuration/static/less/content-container.less
- contentcuration/contentcuration/static/less/styles.less
- contentcuration/contentcuration/templates/base.html
- contentcuration/contentcuration/templates/channel_edit.html
An improvement on [PR#1142](https://github.com/learningequality/studio/pull/1142)
This PR makes the topic tree navigator much more responsive on devices with smaller screens.  I even tried it at 1024x768 :tada: !
In order to make the topic tree navigation area feel more responsive, I introduced a nested chain of flexbox settings.  This ensures that the horizontal scrollbar will appear at the very bottom of the window, rather than at some awkward, arbitrary offset from the bottom.
In the future, it'd be great if we can get rid of all those extra nested containers!
1. Removed lots of `position: absolute` and `position: fixed` properties that were unnecessarily complicating the layout (as well as their accompanying `width` and `height` settings).
2. Added a nested chain of flexbox settings.
> Much more responsive channel edit page, part 2

- CHANGELOG.md
- contentcuration/contentcuration/context_processors.py
- contentcuration/contentcuration/static/js/bundle_modules/base.js
- contentcuration/contentcuration/templates/base.html
Sorry guys, can't take it anymore. Turning off offline js when Studio is in debug mode
> Turned off offline js in debug mode

- CHANGELOG.md
- contentcuration/contentcuration/static/js/edit_channel/related/views.js
- contentcuration/contentcuration/static/js/edit_channel/uploader/views.js
This will fix the bug where a user could select a prerequisite from the garbage tree on new content
#1018 
In the future, I would like to move this to vue so we can use the state more effectively instead of passing variables between views
> Don't allow user to set prerequisite from garbage tree on new content

- k8s/images/app/Dockerfile
The pdf export functions are generating blank pdfs as the font is not installed. This adds this to the build to make sure the proper font is available
> Add fonts-freefont-ttf to installation packages

- CHANGELOG.md
- contentcuration/contentcuration/static/js/edit_channel/exercise_creation/views.js
Currently, the HTML to markdown logic leaves div tags intact. The editor creates div tags whenever enter is hit.
#1199 
> Remove div tags from markdown output.

- CHANGELOG.md
- contentcuration/contentcuration/static/js/edit_channel/share/views.js
Look up viewers using correct channel model, not user model
Addresses https://github.com/learningequality/studio/issues/1194
> Fixed view-only icon in share modal

- CHANGELOG.md
- contentcuration/contentcuration/static/js/edit_channel/__tests__/PrimaryModalState.spec.js
- contentcuration/contentcuration/static/js/edit_channel/channel_set/views.js
- contentcuration/contentcuration/static/js/edit_channel/import/views.js
- contentcuration/contentcuration/static/js/edit_channel/vuexModules/primaryModal.js
Fixes a bug where Vue based modals weren't notifying their Backbone view when they closed.
Addresses a major issue where the Import modal couldn't be opened a second time.
> Ensure that Vue based modals close properly

- CHANGELOG.md
- contentcuration/contentcuration/static/js/edit_channel/preview/views.js
- contentcuration/contentcuration/static/js/edit_channel/uploader/views.js
When user opens Preview tab, load html apps automatically. When user leaves Preview tab, pause videos and audios
Addresses https://github.com/learningequality/studio/issues/728 and https://github.com/learningequality/studio/issues/1050
> Automatically load html previews, pause videos/audios on preview close

- CHANGELOG.md
- contentcuration/contentcuration/static/js/edit_channel/channel_set/views.js
- contentcuration/contentcuration/static/js/edit_channel/channel_set/views/ChannelSetDialog.vue
- contentcuration/contentcuration/static/js/edit_channel/channel_set/vuex/getters.js
- contentcuration/contentcuration/static/js/edit_channel/channel_set/vuex/mutations.js
- contentcuration/contentcuration/static/js/edit_channel/channel_set/vuex/store.js
Added Save & Close option to channel collection modal
> Add Save & Close option to channel collection modal

- contentcuration/contentcuration/static/js/administration/hbtemplates/channel_list.handlebars
- contentcuration/contentcuration/static/js/administration/hbtemplates/user_list.handlebars
- contentcuration/contentcuration/static/less/admin.less
- contentcuration/contentcuration/static/less/admin_grid.less
Fixes whatever is happening here:
> Update admin page spinners to use global spinner styling

- contentcuration/contentcuration/utils/export_writer.py
One small fix- pie chart is rendering strangely on pdf/ppt export
**PDF export**
**PPT export**
___________
**PDF export**
**PPT export**
> Fix pie chart styling

- CHANGELOG.md
- contentcuration/contentcuration/static/js/edit_channel/file_upload/views.js
- contentcuration/contentcuration/tests/test_files.py
- contentcuration/contentcuration/views/files.py
This fixes issues where people setting content defaults with non-English characters were unable to upload files.
#1004
> Content defaults fix

- CHANGELOG.md
- contentcuration/contentcuration/forms.py
- contentcuration/contentcuration/tests/test_forms.py
Sorts countries by localized names, rather than just presenting them in the order they are in the pycountry.countries list. 
Addresses #976 
> Sort countries by localized name

- CHANGELOG.md
- contentcuration/contentcuration/context_processors.py
- contentcuration/contentcuration/static/less/global-variables.less
- contentcuration/contentcuration/templates/base.html
There are still a number of users who are still using contentworkshop, which does not include any caching. This banner redirects users to studio.learningequality.org
> Added banner to redirect users from contentworkshop to studio

- contentcuration/contentcuration/templates/settings/issues.html
Adds more usage tips:
Before
After
> additional studio beta usage tips

- CHANGELOG.md
- contentcuration/contentcuration/static/js/edit_channel/uploader/views.js
User should not be able to add prerequisites to topics 
Addresses https://github.com/learningequality/studio/issues/1254
> Don't allow users to set prerequisites on topics

- contentcuration/contentcuration/utils/export_writer.py
The default MPL backend doesn't work when running in a virtualenv, so pick one that does instead. This is basically re-applying the fix made to pressurecooker some time back to Studio. Given the nature of this change, I didn't think we should add a changelog entry for it. 
> Fix for Mac MPL backend issue

- CHANGELOG.md
- contentcuration/contentcuration/static/js/edit_channel/uploader/views.js
- contentcuration/contentcuration/views/settings.py
Disable prerequisites on topics, remove deleted channels from storag request form
https://github.com/learningequality/studio/issues/1269
https://github.com/learningequality/studio/issues/1254
**Storage request bug**
**Topic prerequisites bug**
> Fixes for prerequisites and deleted channels

- CHANGELOG.md
- contentcuration/contentcuration/tests/test_garbage_collect.py
Adds a check that shared files aren't deleted when one of the file objects is deleted
https://github.com/learningequality/studio/issues/875
Not any new tech-debt items, just reiterating that we need to delete files that are no longer referenced by any objects
> Added check for shared files and garbage collection

- Pipfile
- Pipfile.lock
- contentcuration/contentcuration/utils/gcs_storage.py
Add backoff logic for the GoogleCloudStorage.exists() method, since it seems like that part doesn't handle server errors on GCS. Other gcs client methods seem to have it.
> backoff-or-else

- extract_frontend_messages.js
Fixes message extraction for modern JS.
> Use ecmascript 2018 for all espree instances.

- Pipfile
- README.md
[Kolibri-tools requires Node.js 10.x](https://github.com/learningequality/kolibri/blob/develop/packages/kolibri-tools/package.json#L88-L91).  Nodeenv is a python tool for managing Node.js versions and it works with python virtual environments.  
Adds a nodeenv development dependency and instructions for using it.
> Provide a system independent way of managing Node.js versions

- contentcuration/contentcuration/views/base.py
Now that the load constants are baked into the JS files, we no longer need to query and pass down all the constants via the Django template. This PR removes those queries, which probably constitute a majority of the page's response time.
I did a full text search for each of the variables, but I would appreciate a closer look by those familiar with this code.
- Radina @radinamatic …
> Constants are baked into the JS now, so remove unused constant queries.

- contentcuration/contentcuration/static/js/bundle_modules/base.js
As pointed out by @rtibbles, most 404s are actually unauthorized access attempts, but are given as 404s so as not to confirm the existence of the resource to someone without access.
Given that, we should treat 404s like 403s in terms of error reporting and silence them. We can differentiate in the backend, so that is where we should report a true 404.
No tickets, just a bunch of 404 Sentry errors. :)  …
> Silence Sentry 404 errors on the frontend.

- contentcuration/contentcuration/static/less/channel_list.less
Fixes an issue with channel item titles
**Before**
**After**
> Allow channel titles to wrap

- contentcuration/contentcuration/production_settings.py
Our deployments are failing right now because I accidentally removed the star imports from our settings. This re-adds that.
> Re-import base settings into production settings

- .gitignore
- .idea/studio.iml
This adds an ignore for the majority of the `.idea/` directory, a folder used by IntelliJ IDEs, like PyCharm. It also commits a file which defines the project structure for code completion assistance.
The changes to `.gitignore` use `*` ignore paired with an exclude using `!`. This tells the parse to ignore all files and directories except the file following `!`. The `.idea/studio.iml` was generated by PyCharm.
> PyCharm settings

- Makefile
- Pipfile
- Pipfile.lock
- k8s/templates/_helpers.tpl
- k8s/templates/celery-dashboard.yaml
- k8s/templates/studio-deployment.yaml
- package.json
This creates a dashboard for viewing currently running celery tasks. It also makes studio work on a dev cluster again by making certain volumes optional (studio the app will just error out).
Summary of changes:
- add "flower", the celery plugin to create a dashboard.
- make certain secret volumes undefined if the secret is not provided.
- create a new kubernetes deployment that launches the flower dashboard.
- ~~TODO: create a kubernetes service that allows viewing the dashboard locally.~~ not needed
- ~~TODO:~~ add instructions on how to view the dashboard in production. There's now a makefile target to launch the dashboard proxy for you!
- ~~TODO:~~ add dev scripts to launch the dashboard.
> Celery dashboard

- contentcuration/contentcuration/static/js/edit_channel/channel_list/tests/channelDetailsPanel.spec.js
- contentcuration/contentcuration/static/js/edit_channel/channel_list/tests/channelMetadataSection.spec.js
There is an issue with a couple of the front-end tests where resetting the state ended up causing pre-existing test components to fail. This deletes them at the end of every test run.
> Fixed failing tests

- contentcuration/contentcuration/static/less/global-variables.less
Uncomments material-icons rule that is used for spinners
Addresses https://github.com/learningequality/studio/issues/1322
> Uncommented material-icon rule

- docker/Dockerfile.dev
- k8s/images/app/Dockerfile
By default, the version of pip available in our base docker image is extremely old.  This was causing Travis builds to fail when there were apparently timeouts installing pipenv.
This also unpins pip in the production Dockerfile.  We may want to pin it again at some point.
> Upgrade pip during Travis build

- contentcuration/contentcuration/tests/test_thumbnail_encoding_json_migration.py
I was working to write new tests in this PR https://github.com/learningequality/studio/pull/1308 but when I ran `pytest` several tests were failing. The failures were due to an attempted DB transaction for a FK that did not exist in the test DB.
After investigating with Aron, we found that the tests were only failing after the `contentcuration/tests/test_thumbnail_encoding_json_migration.py` tests ran.
So, at a high level, the issue is that the tests in that file are running a specific set of migrations, but never reset the DB to be fully migrated. Any tests run after this test that depend on newer migrations being run will fail with a DB error
After fiddling a bit with loading migrations, traversing the migration graph and running a specific set of migrations - I found that you can just …
> Run all migrations in tearDownClass for Test*JSONMigration

- contentcuration/contentcuration/templates/policies/policy_accept.html
- contentcuration/contentcuration/templates/registration/registration_information_form.html
Makes sure jQuery is available before trying to use it on the signup and policy acceptance pages.
(All this change does is to put the code that uses jQuery inside of a `window.onload` listener.)
Addresses #1359
> wait for jQuery to load on signup/policy pages

- docs/docker_setup.md
Fix docker download link to one that doesn't 404
- [ Go to https://www.docker.com/community-edition and see that it does 404] *Step 1*
- [Go to https://hub.docker.com/search/?type=edition&offering=community and see that it does not 404 ] *Step 2*
> Fix docker download link to one that doesn't 404

- contentcuration/contentcuration/serializers.py
- contentcuration/contentcuration/tests/test_public_api.py
- contentcuration/contentcuration/views/public.py
Also fix content type value for public JSON endpoints.
The public channel list API gets its thumbnail from the `icon_encoding` field in the Channel model. However, in Studio, we never set this field. We only ever set it on the Kolibri sqlite db. In Studio, the thumbnail comes from the `thumbnail_encoding` field instead. As a result, Kolibri import always shows blank thumbnails for Studio content sources available to import.
To fix this, this PR updates the channel public list API serializer to return the `thumbnail_encoding` thumbnail if the `icon_encoding` field is not set.
Addresses #1299 
- …
> [Fixes #1299] Restore thumbnail data to public channels API.

- docker/Dockerfile.dev
Bakes `apt-get update` and `apt install` commands into the same layer so that we never run into issues when Ubuntu updates package sources.
Consolidated most of the apt-related layers to a single one, making apt installation failures due to out-of-date sources unlikely.
Weeded out some unnecessary commands to simplify the docker build.
No. Kind of resolves one, though.
> Docker Invalidation FIxes

- contentcuration/contentcuration/wsgi.py
This allow us to track more exceptions, and feed into our SLIs.
> Move newrelic initialization to the start of WSGI.

- contentcuration/contentcuration/static/js/bundle_modules/channel_list.js
- contentcuration/contentcuration/static/js/edit_channel/channel_list/constants.js
- contentcuration/contentcuration/static/js/edit_channel/channel_list/router.js
- contentcuration/contentcuration/static/js/edit_channel/channel_list/tests/channelListPage.spec.js
- contentcuration/contentcuration/static/js/edit_channel/channel_list/views/ChannelInvitationItem.vue
- contentcuration/contentcuration/static/js/edit_channel/channel_list/views/ChannelListPage.vue
Turns out there were two problems here:
1. There was a mismatch between share modes and list names, so all invites were defaulting to view only
2. Accepting an invitation didn't change the tab
Addresses https://github.com/learningequality/studio/issues/1395
> Fixed tab not changing issue

- contentcuration/contentcuration/tests/views/test_views_internal.py
- contentcuration/contentcuration/views/internal.py
* Adds tests to guarantee 200 if publish is successful, 404 if channel is not found, or no data passed.
* Adds tests to guarantee a 404 if a user is not authenticated to publish the channel (is not an editor)
Fixes #1415
> Publish internal API endpoint tests

- contentcuration/contentcuration/static/js/edit_channel/__tests__/ContentNodesState.spec.js
- contentcuration/contentcuration/static/js/edit_channel/state.js
- contentcuration/contentcuration/static/js/edit_channel/vuexModules/contentNodes.js
Added content nodes to global state to be used on channel edit page
Will need to update tests with ajax mocks, but can't do now as it messes with backbone methods
> Added content nodes to global state

- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/tests/base.py
- contentcuration/contentcuration/tests/test_chef_pipeline.py
- contentcuration/contentcuration/tests/test_contentnodes.py
- contentcuration/contentcuration/tests/test_createchannel.py
- contentcuration/contentcuration/tests/test_exportchannel.py
- contentcuration/contentcuration/tests/testdata.py
- contentcuration/contentcuration/tests/views/test_views_internal.py
- contentcuration/contentcuration/urls.py
- contentcuration/contentcuration/views/internal.py
Various cleanup tasks and helper methods to be used 
- Renamed create_temp_file to create_studio_file + refactor all references
- Updated ChefTestCase to use only Token auth
- remove code duplication in test_exportchannel.py
- add some docstrings to models and views
- Completely unrelated bunch of comment additions in `models.py` 
Prerequisite for https://github.com/learningequality/studio/issues/1438
Travis will do it
The `BaseAPITestCase` was calls `client.force_authenticate` which then ensure all API calls go through. I intentionally disabled this feature in `ChefTestCase` in order to test the token-auth works. 
I removed the self.header propoerty of `BaseAPITestCase` because it doesn't work as expected with the client magic. Instead have to call client.credenials with header …
> Cleanup and fixes around internal API tests cases

- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/serializers.py
- contentcuration/contentcuration/static/js/edit_channel/models.js
- contentcuration/contentcuration/tests/test_contentnodes.py
- contentcuration/contentcuration/tests/test_node_views.py
- contentcuration/contentcuration/tests/test_sushibar_endpoints.py
- contentcuration/contentcuration/tests/views/test_contentnode_views.py
- contentcuration/contentcuration/tests/views/test_views_internal.py
- contentcuration/contentcuration/views/internal.py
- contentcuration/contentcuration/views/nodes.py
* Adds permissions checks to every endpoint in nodes.py and internal.py that did not previously have them, or did not check permissions for every entity it was accessing.
* Uses `api_view` decorator consistently to enforce allowed methods.
* Uses DRF Response constructor consistently to avoid manually invoking `json.dumps`
* Removes all instances where JSON is rendered and then inserted into another object that is then rendered to JSON again.
* Cleans up frontend logic that did double `JSON.parse` to handle this, so that JSON.parse is only required once now.
Fixes #1454 
Fixes #1412 
Fixes #1414 
Fixes #1416 
Fixes #1418
I erred on the side of checking for editor permissions on the `internal.py` endpoints, with the assumption that only channel editors should generally be using those. …
> Add permissions to all nodes.py and internal.py endpoints

- contentcuration/contentcuration/management/commands/restore_channel.py
- contentcuration/contentcuration/settings.py
- contentcuration/contentcuration/tests/test_restore_channel.py
- contentcuration/contentcuration/utils/import.py
- contentcuration/contentcuration/utils/import_tools.py
This PR moves channel import functionality to a module in preparation for unit tests and for use in the UI (for Studio Desktop!).
> Move channel import functionality to module

- Makefile
Simple tweak to try and improve Studio server response times.
Addresses #1479
> Give each worker 2 threads to double the responses it can handle

- contentcuration/contentcuration/tests/test_restore_channel.py
- contentcuration/contentcuration/utils/import_tools.py
Downloads the perseus zip from the download server and reads it to create perseus exercises
> Added perseus -> assessment item conversion to restore_channel command

- contentcuration/contentcuration/serializers.py
- contentcuration/contentcuration/static/js/edit_channel/models.js
- contentcuration/contentcuration/views/nodes.py
- package.json
The `get_nodes_by_ids` family of calls all only accept GET requests, and so can safely be made read-only. Adding read-only versions of the serializers results in an overall 20-30% speedup in the locust tests, which means the actual API calls are likely sped up even more than that.
We already have tests to ensure that these calls only accept GET requests, and no serializer fields have been changed, so existing test coverage should suffice for this.
> Read only ContentNode serializers

- contentcuration/contentcuration/templates/base.html
- contentcuration/contentcuration/urls.py
- deploy/chaos/loadtest/locustfile.py
Stops the app server from loading an unused JS file for each page load, and offloads the jsreverse URL to nginx to be cached like other static files. 
> Remove unused jsi18n reference and use static jsreverse in production.

- contentcuration/contentcuration/serializers.py
The read only serializers PR didn't take into account the removal of parent_title as that hadn't been landed yet. Because it was new code, it didn't generate a merge conflict.
> Fix read only serializers after parent_title removal.

- contentcuration/contentcuration/production_settings.py
- contentcuration/contentcuration/settings.py
- contentcuration/contentcuration/tests/test_makemessages.py
- contentcuration/contentcuration/urls.py
The recent addition of django-prometheus is breaking the deployment by requiring postgres to run in management commands, even though it's unnecessary.
This PR moves django-prometheus to production_settings.py.
> Limit django prometheus to prod

- contentcuration/contentcuration/utils/nodes.py
Provides at least a 5x speed up of the move nodes operation by not delaying mptt updates.
Wraps all changes in a transaction instead, in case there is an error, to prevent the tree being in an inconsistent state.
> (5+)x speed up of move nodes operation

- contentcuration/contentcuration/static/js/edit_channel/models.js
- contentcuration/contentcuration/static/js/edit_channel/sharedComponents/ProgressOverlay.vue
- contentcuration/contentcuration/static/js/edit_channel/vuexModules/asyncTask.js
- contentcuration/contentcuration/utils/nodes.py
Instead of showing the progress dialog, just show the 'saving, please wait' popup instead. The code already properly blocked interacting with the moved node while the op is in progress. Especially after Richard's recent PR speeding up move nodes, it is probably reasonable to assume that it will complete in a reasonably quick timeframe and have the UI designed accordingly.
Also fix an issue where a transient connectivity issue with the server appeared to be permanent on the progress dialog, even after the connection was restored, along with tweaking the task percentage to be more accurate.
> Make move nodes ops appear synchronous

- deploy/probers/base.py
- deploy/probers/login_page_probe.py
- deploy/probers/postmark_api_probe.py
- docker-compose.yml
- docker/Dockerfile.demo
- docker/Dockerfile.dev
- docker/entrypoint.py
- k8s/images/app/Dockerfile
- Fixed minio check throwing a connection error when waiting for minio container to start
- Added some clean-ups to the dev Dockerfile
- Fixed login prober constantly failing due to connection error
- Removed unused imports and formatting issues in probers
- Removed adding `node_modules/.bin` to beginning of path, [see discussion](https://learningequality.slack.com/archives/C0LK8QS9J/p1562955249484600) 
May be worthwhile porting some of the clean-ups in the dev Dockerfile to the prod Dockerfile but I default to leaving such things alone unless necessary.
> Fix prober url and add clean-ups to Dockerfile

- Makefile
This ensures we consistently treat each Studio replica like a single-core machine, meaning we can scale up to 8 replicas per nodes. Hopefully I'm using the right terms consistently now! :p 
We may want to revisit this allocation after more doing some more load testing.
> Limit Celery worker processes as we do with Gunicorn

- k8s/templates/studio-deployment.yaml
From a conversation with @kollivier, it's best to set keep Studio's current number of gunicorn processes (3) and worker processes (3), while only allocating 0.5 CPU per pod.
This change sets the 0.5 CPU per pod limit.
> Set studio's frontend and worker pods to a guaranteed allocation of 0.5 CPU and 2Gi of RAM

- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/static/js/edit_channel/models.js
- contentcuration/contentcuration/static/js/edit_channel/publish/tests/data.js
- contentcuration/contentcuration/static/js/edit_channel/publish/tests/publishModal.spec.js
- contentcuration/contentcuration/static/js/edit_channel/publish/views/PublishModal.vue
- contentcuration/contentcuration/static/js/edit_channel/router.js
- contentcuration/contentcuration/static/js/edit_channel/tree_edit/views.js
- contentcuration/contentcuration/static/js/edit_channel/vuexModules/asyncTask.js
- contentcuration/contentcuration/static/js/edit_channel/vuexModules/channel.js
- contentcuration/contentcuration/templates/channel_edit.html
- contentcuration/contentcuration/urls.py
- contentcuration/contentcuration/views/nodes.py
Fixes a couple issues that arose during the bash, namely:
- 500 errors when calling duplicate_nodes_inline and delete_nodes
- No progress dialog when copying files in read-only mode
- Inability to view or copy content in read-only mode.
Addresses #1511, #1512, #1513, #1514
Once the Vue migration is complete, I suspect we will be able to manage state in a better way than we do now.
> Quick fixes for issues identified during bash

- Makefile
- package.json
During the bug bash, we realized that workers mingling and gossiping was causing them to lose track of their tasks and leave them unprocessed. Make it so that workers can no longer mingle and gossip, so that they can focus on their work.
> Disable mingle and gossip when running workers.

- contentcuration/contentcuration/migrations/0100_calculate_included_languages.py
- contentcuration/contentcuration/tests/test_included_languages_migration.py
Fixes issue with conflicting migrations by renumbering the calculated languages migration and fixing the migration dependencies to reflect the new order.
> Fix issue with two migrations numbered 0099.

- contentcuration/contentcuration/static/js/edit_channel/models.js
- contentcuration/contentcuration/static/js/edit_channel/move/views.js
Restores the progress modal when using the move dialog after changes to make dnd move operations show progress as an inline UI.
Addresses #1525
> Show the progress modal when using the move dialog.

- contentcuration/contentcuration/static/js/edit_channel/router.js
If TreeEditView loads before the value of canEdit is properly set, it will use the default value instead, which is always false.
Addresses #1557
> Set edit state before loading TreeEditView

- package.json
- yarn.lock
Pin Summernote version to 0.8.10 which is the version being currently used in `develop` and `master`.
This PR's purpose is only to prevent accidentall upgrade to latest 0.8.12 patch release that would break our editor (custom buttons would disappear)
https://github.com/summernote/summernote/issues/3249
https://github.com/summernote/summernote/pull/3284
> Pin Summernote version to 0.8.10

- contentcuration/contentcuration/static/js/bundle_modules/base.js
- contentcuration/contentcuration/static/js/edit_channel/sharedComponents/ProgressOverlay.vue
While checking into why we were seeing a lot of `/api/task` errors, I discovered that a lot of the "Network Error" Sentry reports we receive are actually just canceled requests caused by page navigation events like browsing to another page or refreshing the page. (The latter is why `/api/task` triggers a lot, since we refresh upon completion.)
This code filters out any GET Network Error requests that are not reported as timeouts. One thing I did notice is that there was at least one form submission that showed a network error, so I've made sure any non-GET requests with data in them still generate an error report.
Also, upon refreshing after task completion, I stop the task polling timer so it is not making extraneous requests that will just be canceled anyway.
> Tweak network error reporting (e.g. /api/task)

- k8s/templates/studio-deployment.yaml
Optimize our readiness probes to both succeed and recover as fast as reasonable. Also use /healthz for our readiness probe.
Extend the failure threshold before we fail liveness probes. Liveness probes cause our pod to get restarted, so we wanna do that less often.
> Flesh out our liveness and readiness probes

- contentcuration/contentcuration/tests/test_exportchannel.py
- contentcuration/contentcuration/utils/publish.py
Persists save on channel thumbnail to end of the command
It turns out that Django's save function acts more like a POST request in that all fields get submitted, rather than those that have changed like a PATCH request. This was causing an issue as the `publish_channel` function had one version of the channel and the `create_content_database` had another version. The `create_content_database` method would save the icon_encoding. However, any saving after the `create_content_database` function would then use the outdated model from `publish_channel`, which caused icon_encoding to get set back to null
This just passes the model itself to `create_content_database` from `publish_channel` so they are working from the same object in memory
Addresses …
> Fixed icon encodings not getting saved 

- contentcuration/contentcuration/templates/registration/channel_published_email.txt
- contentcuration/contentcuration/utils/publish.py
Email now contains token instead of channel id
```
Hello Admin,
Published Channel has finished publishing! Here is the published token (for importing this channel into Kolibri):
Token: kogig-vasil
Name: Published Channel
Thanks for using our site!
The Learning Equality Team
```
Fixes https://github.com/learningequality/studio/issues/1536
> Switched channel id to token in published email text

- contentcuration/contentcuration/ricecooker_versions.py
Setting "start of soft warning" version range to 0.6.21 means anyone using ricecooker 0.6.20 or older will get a hard warning. See [version logic code here](https://github.com/learningequality/studio/blob/develop/contentcuration/contentcuration/views/internal.py#L85-L92).
On the ricecooker side it will result in a prompt in case someone runs an old chef that uses `0.6.20` or older https://github.com/learningequality/ricecooker/blob/master/ricecooker/commands.py#L208-L211
As part of the deprecation strategy for the old Studio URL
https://contentworkshop.learningequality.org/
we want to throw HARD warnings for any ricecooker users that have the old version `0.6.20` (the last one to use the old URL).
> Make ricecooker 0.6.20 and older raise a HARD warning

- contentcuration/contentcuration/static/js/bundle_modules/base.js
See title! Basically adds a more helpful title than the generic 'error' title that Chrome gives us in these cases to help with tracking these issues as we work to address them.
> Make it easier to identify 502 and 503 errors in Sentry.

- contentcuration/contentcuration/views/base.py
The original code was leading to timeouts because it was trying to serialize all of the nodes for the first public channel. While this works on testing servers, it doesn't work for a bigger channel like African Storybooks
> Don't attempt to serialize all content nodes from the first public channel

- contentcuration/contentcuration/utils/import_tools.py
Some of the extra_fields might be stored as a string, so parse it as a dict under restore_channel
> Handle edge cases where extra_fields is stored as a string

- contentcuration/contentcuration/management/commands/setup.py
- contentcuration/contentcuration/migration_production_settings.py
- k8s/templates/job-template.yaml
- k8s/templates/studio-secrets.yaml
This is a new PR with a shorter branch name, to allow us to spin up a QA k8s server.
Here's the original PR: https://github.com/learningequality/studio/pull/1644
Here's the original description:
The DB migrate job has too many credentials that it doesn't need, posing as a security issue. This PR restores the old secrets that the frontend pods need. We then expand on the config map and add a new secret for our migrate job, giving it only the credentials it needs to deploy.
To test:
if you have a local kubernetes cluster (minikube or microk8s), you can test this by running:
```bash
cd k8s/ && helm upgrade -i local .
```
> Minimize the credentials given to the DB migrate job

- deploy/probers/base.py
- k8s/templates/prober-deployment.yaml
This PR is to add develop studio prober account since a@a.com doesn't exist on develop Studio.
Based on Aron's [suggestion on Slack](https://learningequality.slack.com/archives/GBSTQ6P2P/p1571351967001000), the account is not encrypted. 
It also adds an additional check in the login prober because logging in with wrong username and password also returns 200 status code.
before the PR, the probers failed because user a@a.com doesn't exist:
> add develop studio prober account

- contentcuration/contentcuration/management/commands/fix_dupe_trees.py
Re-numbers tree IDs on content trees when we get duplicates to fix corrupted MPTT indexes. 
> Management script for fixing dupe tree_ids.

- docker/Dockerfile.demo
- k8s/images/prober/Dockerfile
This PR is to upgrade the studio demo and prober docker image to bionic due to the changes made in [this PR](https://github.com/learningequality/studio/pull/1649).
For the changes in Dockerfile.demo, I copied the app Dockerfile since the only change between the two is the make command.
> upgrade studio demo and prober docker image to bionic

- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/tests/test_files.py
Fixes for two bug in deletion code that assumes files are in the local filesystem, but actually in a bucket.
Addresses https://github.com/learningequality/studio/issues/1455
> Fix for legacy local files delete -- issue #1455

- deploy/nginx.conf.jinja2
this causes issues with the user not seeing the new channel if they refresh immediately. From what we've seen in the field, this can lead to users creating multiple copies of a channel.
This is exacerbated when we have less frontend pods running, since users are more likely to hit the same studio frontend pod instance.
We need a smarter caching system to make this work. For now, we can deal with request stampedes by increasing our capacity.
> remove get_user_edit_channels nginx caching

- contentcuration/contentcuration/utils/publish.py
Certain exercise content nodes have `extra_fields` as str, not json. This avoids the error during publish.
During testing today, I encountered this error
```
celery-worker_1  |   File "/src/contentcuration/contentcuration/utils/publish.py", line 672, in publish_channel
celery-worker_1  |     create_content_database(channel, force, user_id, force_exercises, task_object)
celery-worker_1  |   File "/src/contentcuration/contentcuration/utils/publish.py", line 90, in create_content_database
celery-worker_1  |     force_exercises=force_exercises, task_object=task_object, starting_percent=10.0)
celery-worker_1  |   File "/src/contentcuration/contentcuration/utils/publish.py", line 149, in map_content_nodes
celery-worker_1  |     exercise_data = process_assessment_metadata(node, kolibrinode) …
```
> Fallback in case extra_fields is string-like

- contentcuration/contentcuration/tests/test_gcs_storage.py
- contentcuration/contentcuration/utils/gcs_storage.py
> Add a cache-control setting when we upload content databases

- contentcuration/contentcuration/collectstatic_settings.py
- contentcuration/contentcuration/templatetags/license_tags.py
- k8s/templates/studio-deployment.yaml
This is another tweak I have while adding pgBouncer and the network connection backlog prober.
We remove the `make` indirection layer here by running Gunicorn directly as a command in the k8s manifest. This allows us to tweak its settings directly without waiting for builds. This makes our startup time much faster since we don't have all the other dependencies we have in `make altprodserver`.
However we still need to run collectstatic. I added a new initContainer that is responsible for collectstatic, and otherwise doesn't need any other credentials.
> Improve startup time and gunicorn configurability by running gunicorn directly through K8s

- k8s/helm-deploy.sh
- k8s/templates/studio-deployment.yaml
- k8s/templates/studio-secrets.yaml
We accidentally removed a k8s manifest key. Deployments are failing because of that.
Re-add that in, and add other checks as well to force certain inputs to be parsed as strings.
> Fix the deployment by adding in a missing manifest key

- contentcuration/contentcuration/utils/gcs_storage.py
Upon more testing by @jonboiser, looks like this time it's nginx who's caching our content DB. This time we now set cache-control to private, and set no-transform, to ensure that the DB is never cached downstream.
> add more cache-control headers to gcs

- contentcuration/contentcuration/tests/test_gcs_storage.py
- contentcuration/contentcuration/utils/gcs_storage.py
The cache-control fixes we made previously still don't affect all sqlite3 files.
This time we check for the .sqlite3 extension when we apply the cache-control fix.
> Use .sqlite3 extension to set custom cache-control

- contentcuration/contentcuration/settings.py
- k8s/templates/frontend-pgbouncer.yaml
- k8s/values-prod-config.yaml
- k8s/values.yaml
- Fixes `RESERVE_POOL_SIZE` option that was referencing `pool_size` value
- Adds PGBouncer setting for `MIN_POOL_SIZE` so that connections are held in pool, which helps with periods of inactivity
- Adds PGBouncer setting for `MAX_CLIENT_CONN` so it's clearly defined
- Adds Django setting `CONN_MAX_AGE = 0` to ensure persistent connections are disabled
- Changes pooling mode to `session` instead of `transaction`
Regarding changing the pooling mode, Django uses features that are [not friendly](https://docs.djangoproject.com/en/1.11/ref/databases/#transaction-pooling-and-server-side-cursors) with the transaction pooling mode. Instead of disabling server-side cursors, I changed the pool mode because I have concerns regarding how SQL queries in a request …
> Change pgbouncer settings

- k8s/templates/celery-dashboard.yaml
- k8s/templates/prober-deployment.yaml
The PR is to add DATA_DB_HOST to both celery-dashboard and prober deployments so that they can directly connect to the database.
Previously, the variable was not added to the deployments, which led the applications to connect to 127.0.0.1 by default.
Note that the changes are live on develop studio now.
I will set up a demo server to double-check if things are working. 
Please let me know if you have any questions! Thank you!
> add DATA_DB_HOST to celery and prober deployments

- contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/MarkdownEditor/MarkdownEditor.vue
- contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/MarkdownEditor/keyHandlers.js
- contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/MarkdownEditor/utils.js
- contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/__tests__/utils.spec.js
- contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/constants.js
- contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/extensions/formulas/formulas.js
- contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/extensions/image-upload/image-upload.js
- contentcuration/contentcuration/static/js/edit_channel/uploader/components/MarkdownEditor/extensions/minimize/minimize.js
- contentcuration/contentcuration/static/js/edit_channel/uploader/directives/click-outside.js
A follow-up of #1688, It contains various improvements of markdown editor, especially in regards to formulas.
- md editor component code cleanup after PoC of formulas editor merge (#1688) - code better readable, fixes a couple of edge cases
- restrict default Ctrl md editor keyboard shortcuts only to actions allowed (Ctrl+A, Ctrl+C, Ctrl+X, Ctrl+V, Ctrl+B, Ctrl+I)
- add custom keyboard shortcuts for "Insert image" (Ctrl+P), "Insert formula" (Ctrl+F) and minimize (Ctrl+M) toolbar buttons
- show keyboard shortcuts tooltips for all toolbar buttons on hover
- custom copy-paste handler - clear all unsupported format
- handle cursor behaviour around math fields when navigating using arrow left/right and backspace
Addresses several [Vue Migration …
> Markdown editor improvements

- contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelModal.vue
- contentcuration/contentcuration/frontend/channelList/vuex/channelList/__tests__/module.spec.js
- contentcuration/contentcuration/frontend/channelList/vuex/channelList/actions.js
- contentcuration/contentcuration/frontend/channelList/vuex/channelList/getters.js
- contentcuration/contentcuration/frontend/channelList/vuex/channelList/index.js
- contentcuration/contentcuration/frontend/channelList/vuex/channelList/mutations.js
- contentcuration/contentcuration/frontend/channelList/vuex/channelList/utils.js
- contentcuration/contentcuration/frontend/channelList/vuex/channelSet/__tests__/module.spec.js
- contentcuration/contentcuration/frontend/channelList/vuex/channelSet/actions.js
- contentcuration/contentcuration/frontend/channelList/vuex/channelSet/getters.js
- contentcuration/contentcuration/frontend/channelList/vuex/channelSet/index.js
- contentcuration/contentcuration/frontend/channelList/vuex/channelSet/mutations.js
- contentcuration/contentcuration/frontend/channelList/vuex/channelSet/utils.js
- contentcuration/contentcuration/frontend/shared/views/form/ContentDefaults.vue
- contentcuration/contentcuration/serializers.py
I noticed some circular dependencies being logged during the frontend build, I think from a package @micahscopes added, so I've resolved those. I also noticed an issue with the content defaults form where a blank license wasn't being saved. I didn't experience that before because I had actually a user preference for the license will building it, but that got cleared when I reset by DB.
- Radina …
> Fix license handling, and circular dependencies

- deploy/chaos/loadtest/locustfile.py
Adds an async task to our load testing script so that we can simulate lots of async tasks running in parallel. Also fixes channel deletion so that the script cleans up after itself.
> Restore ChannelEdit tests and add content copy and channel deletion.

- contentcuration/contentcuration/management/commands/setup.py
Ran into the issue below running `yarn run devsetup` on the `develop` branch. I believe this may have been a side effect of the python 3 migration, but am unsure.
```
Traceback (most recent call last):
File "manage.py", line 11, in <module>
execute_from_command_line(sys.argv)
File "/home/bjester/.local/share/virtualenvs/studio-HDUuBaY8/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
utility.execute()
File "/home/bjester/.local/share/virtualenvs/studio-HDUuBaY8/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/home/bjester/.local/share/virtualenvs/studio-HDUuBaY8/local/lib/python2.7/site-packages/django/core/management/base.py …
```
> Fix reading on fobj that wasn't opened as readable

- contentcuration/contentcuration/tests/test_gcs_storage.py
- contentcuration/contentcuration/utils/gcs_storage.py
This PR is to compress the database files before uploading to GCS so that
- Kolibri users can save time downloading the channel database files from Studio (major)
- The size of the file saved on GCS can be reduced, which can save some cost for GCS
It takes time for Kolibri users to download some large database files (e.g. Khan Academy) under slow network.
I tested it the compress and upload part separately on my local machine. I'm wondering if it would be helpful if we set up a demo server and test from there.
> compress database files before uploading to GCS

- .gitignore
This PR reverts the mistaken ignore of `contentcuration/contentcuration/static`.
Currently this folder is both a source and a destination of the collectstatic command, so it cannot be .gitignored completely. Thx @kollivier for catching my mistake.
I'll open a [followup PR](https://github.com/ivanistheone/studio/commits/mv-cc_cc_static-to-cc_static) to discuss moving
contentcuration/contentcuration/static --> contentcuration/static
but we don't need to do that today.
> Revert .gitignoreing of contentcuration/contentcuration/static

- cloudbuild-pr.yaml
- k8s/templates/prober-deployment.yaml
- k8s/templates/prober-metrics-to-newrelic-cron-job.yaml
- k8s/templates/prober-service.yaml
This PR is to remove probers from demo servers because:
1. probers are supposed to run in the production environment
2. need to save resources for demo server cluster since we don't use probers much
Enable prober related k8s scripts only when in production
> remove probers from demo servers

- docker-compose.yml
There was a change on which port nodejs listens to, but we didn't update the docker-compose file. This adds the port-forwarding, and allows devs to work entirely using docker-compose.
> Forward port 4000 as well on docker-compose

- README.md
Replaced broken link with correct link concerning pull requests in README. 
Addresses #1790 
> Added correct link for pull requests in README

- webpack.config.js
Updates the webpack generation of source maps
https://learningequality.slack.com/archives/C0LK8QS9J/p1583787369110800
* do source maps load?
* can you view line numbers in source as expected?
see https://webpack.js.org/configuration/devtool/
> fix webpack devtool source maps

- Makefile
This adds a shortcut for purging a Studio development database.  It's helpful if there are a lot of changes and you just want to start over from scratch.
(cherrypicked the commit from https://github.com/learningequality/studio/pull/1794)
> Makefile command to destroy/recreate the db

- .gitignore
- Makefile
- contentcuration/contentcuration/settings.py
- webpack.config.js
Changes settings so `collectstatic` and webpack build outputs go in `contentcuration/static` instead of `contentcuration/contentcuration/static`.
Addresses  https://github.com/learningequality/studio/issues/1761
@aronasorman  || @lyw07  Please check that production setup is going to be OK with new directory.
> Move static output dir to contentcuration/static

- contentcuration/contentcuration/node_metadata/annotations.py
- contentcuration/contentcuration/serializers.py
Optimizes ancestor field on simplified content node serializer with faster querying methods
> Switched get_node_ancestors on serializer to use metadata annotations

- README.md
Added link to Kolibri Studio user guide in the README file.
Addresses  #1783 
> add user guide link to README

- contentcuration/contentcuration/db/models/aggregates.py
- contentcuration/contentcuration/static/js/edit_channel/models.js
- contentcuration/contentcuration/views/base.py
The accessible channel list returns a list of children in the tree, but wasn't returning it distinctly. Due to some Django magic it was doing to satisfy other parts of the query, the addition of joins causes duplication of children ID's which then gets passed directly back to the server in requests, which are significantly higher in volume than they need to be due to duplication of ID's. …
> Fixes duplication of children ID's

- contentcuration/contentcuration/utils/publish.py
- requirements-dev.txt
- requirements.in
- requirements.txt
This is to apply the same requirement-affecting changes done on the `vue-refactor` branch on develop as well (to avoid surprises later on)
1. https://github.com/learningequality/studio/pull/1804/commits/147c3057411b5e8142d9881a4c3465104357792a
2. https://github.com/learningequality/studio/pull/1804/commits/01e596cd394340841910fbe3f91c8faacd21d98e
3. https://github.com/learningequality/studio/commit/002a392b4214ca4d6751bc0bb434293f40540139
4. https://github.com/learningequality/studio/pull/1820/files
> remove ddtrace and upgrade service-factory requirements

- requirements.txt
I ran `pip-compile --upgrade-package le-pycaption` and only the version of `le-pycaption` got updated (a transitive dependecy) of pressurecooker.
No other package versions were changed. Woo hoo... the pip-tools way is very nice!
context: this was to avoid certain pip-related errors that people using py36 might encounter around requirements management commands due to the `enum34` package. Thx to @bjester for quickly releasing new version of le-pycaption.
Note: we need to keep studio `master` branch on `le-pycaption==2.0.0a3` since it still runs on  py27: https://github.com/learningequality/studio/blob/master/Pipfile.lock#L668-L674
> Upgrade to version le-pycaption that doesnt need enum34 anymore

- contentcuration/contentcuration/frontend/channelEdit/views/ChannelEditIndex.vue
- contentcuration/contentcuration/frontend/channelEdit/views/sync/SyncResourcesModal.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/currentChannel/actions.js
Implements the sync resources workflow that consists of four modals:
- sync what? (this PR)
- confirm (this PR)
- sync task progress (handled by asyncTasksModule)
- sync done (handled by asyncTasksModule)
Relies on asyncTasksModule for steps 3 and 4 of the workflow.
No tests.
- JB
- Jordan
> SyncResourcesModal component

- contentcuration/contentcuration/static/js/edit_channel/tree_edit/views.js
- contentcuration/contentcuration/static/js/edit_channel/views.js
Fixes https://github.com/learningequality/studio/issues/1080
> Fixed multiple copies of nodes getting copied to clipboard

- k8s/templates/studio-deployment.yaml
This PR is to fix the issue we have on demo servers that the admin account a@a.com is not set up.
It is because we call the command `make setup` in Dockerfile but overwrite it in k8s scripts. 
I made changes so that k8s script checks whether we are in demo server mode or not by checking the value of `productionIngress`, which is set to be true in servers such as production, develop, and some more when we use `cloudbuild-production.yaml`.
Since we use `cloudbuild-pr.yaml` for demo servers, the value of `productionIngress` is set to be false, so we will run an additional command `make setup` when setting up workers.
> run setup command when not in prod mode

- deploy/nginx.conf.jinja2
Previously we were using CloudFlare to block access to `/content/`.  With this PR, instead Nginx is used.
See here: https://github.com/learningequality/studio/issues/1838
> In Nginx, block access to `/content/` root

- contentcuration/contentcuration/frontend/channelEdit/components/AddRelatedResourcesModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/RelatedResourcesTab/RelatedResourcesTab.vue
- contentcuration/contentcuration/frontend/channelEdit/pages/AddNextStepsModal.vue
- contentcuration/contentcuration/frontend/channelEdit/pages/AddPreviousStepsModal.vue
Preserve the current _Edit Modal_ mode in _Add previous/next steps_ modals so users will be navigated back to the right place after clicking _Cancel_ button in _Add previous/next steps_ modals.
Addresses #1816
`back` query parameter
> Preserve the current mode in "Add previous/next steps" modals

- contentcuration/contentcuration/frontend/channelEdit/components/AssessmentEditor/AssessmentEditor.vue
- contentcuration/contentcuration/frontend/channelEdit/components/AssessmentTab/AssessmentTab.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/__tests__/getters.spec.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/getters.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/index.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/getters.js
- contentcuration/contentcuration/static/js/edit_channel/uploader/views/EditView.vue
- base validation on assessment ids
- do not show validation errors for newly added items (first validation run for these items is triggered after a new item closed)
Closes #1848.
|---|---|
| ![before](https://user-images.githubusercontent.com/13509191/79969151-60f4c600-8491-11ea-9056-5b5dfd0af747.png) | ![after](https://user-images.githubusercontent.com/13509191/79969149-605c2f80-8491-11ea-9a8f-390f99456ce5.png) |
> Exercise creation validation improvements

- contentcuration/contentcuration/frontend/channelEdit/components/AddRelatedResourcesModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/NodeTreeNavigation.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/__tests__/getters.spec.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/getters.js
Remove `getContentNodeParents` in favour of `getContentNodeAncestors`.
Closes #1815.
> Node parents getters cleanup

- Pipfile
- Pipfile.lock
Tests have not caught the following missing deps, and they're breaking the deploy:
- grpc
We add these deps to our pipenv explicitly.
> explicitly add missing deps

- contentcuration/contentcuration/frontend/channelEdit/components/AddRelatedResourcesModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/NodeTreeNavigation.vue
- contentcuration/contentcuration/frontend/channelEdit/move/MoveModal.vue
- contentcuration/contentcuration/frontend/channelEdit/router.js
- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
- contentcuration/contentcuration/frontend/channelEdit/views/NodePanel.vue
- contentcuration/contentcuration/frontend/channelEdit/views/StudioTree.vue
- contentcuration/contentcuration/frontend/channelEdit/views/TreeView.vue
- contentcuration/contentcuration/frontend/channelEdit/views/trash/TrashModal.vue
- contentcuration/contentcuration/frontend/channelEdit/views/trash/__tests__/trashModal.spec.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
This PR contains various fixes related mostly to tree navigation within channel edit page mentioned yesterday [here](https://learningequality.slack.com/archives/C0LK8QS9J/p1589354076000300). Those issues showed up to be a composition of more smaller problems with asynchronous and reactive behavior. The diff is not large though to understand particular issues, please review commit by commit - I tried to explain what was the problem in detail in commit messages as we should be aware of these things in general. There are better solutions to some of those issues though I am currently actively working on staging channel that uses some of the functionality affected and will need to do some more updates - for now I just wanted to get these fixes merged to `vue-refactor` for everyone.
This also …
> Various reactivity and asynchronicity fixes

- deploy/nginx.conf.jinja2
This ensures that only the following paths are allowed for requests to `catalog.learningequality.org`:
```
/
/api/catalog
/healthz
/stealthz
/api/get_channel_details
/jsreverse
/i18n
```
This is to ensure that Studio's WIP refactor isn't exposed prematurely!  [See here](https://www.notion.so/learningequality/Make-sure-all-non-catalog-related-urls-are-blocked-9ce74987da3e4a1fb0498414195a04c6) for more info.
> nginx: use an allow list for the catalog server

- deploy/nginx.conf.jinja2
This is a fix to the `proxy_pass` configuration for the catalog server nginx allowlist.  See [here](https://github.com/learningequality/studio/pull/1908) for details.
> nginx: fix catalog allow-list proxy_pass configuration

- deploy/nginx.conf.jinja2
This denies access to the `/content/` root while still allowing access to `/content/*`.  It's way simpler than the approach tried previously, which relied on regex.
The original changes, which used regex, and evidently were stirring up trouble, were reverted here: https://github.com/learningequality/studio/pull/1913
> nginx: block /content/ root, round two

- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
Last/current item was missing in breadcrumbs on channel edit page.
|----------|-------- |
|![before](https://user-images.githubusercontent.com/13509191/82887072-c08a3980-9f47-11ea-94a5-3b1531dec28b.png)|![after](https://user-images.githubusercontent.com/13509191/82887110-d1d34600-9f47-11ea-8219-6620057c6f00.png)|
> Channel edit page fix - last item missing in breadcrumbs

- contentcuration/contentcuration/tests/test_urlendpoints.py
- contentcuration/contentcuration/viewsets/assessmentitem.py
- contentcuration/contentcuration/viewsets/base.py
- contentcuration/contentcuration/viewsets/channel.py
- contentcuration/contentcuration/viewsets/channelset.py
- contentcuration/contentcuration/viewsets/contentnode.py
- contentcuration/contentcuration/viewsets/file.py
- contentcuration/contentcuration/viewsets/invitation.py
- contentcuration/contentcuration/viewsets/tree.py
- contentcuration/contentcuration/viewsets/user.py
* Adds basic IsAuthenticated permissions to every ValuesViewset endpoint.
* Creates RequiredFilterSet that will error if a filtering filter is not specified!
Fixes #1890
- Login
- Try loading /api/channels - see a 412
- Try loading /api/channels?id_in= - see a 412
- Try loading /api/channels?public=true - see results
- Try loading the endpoint for a single channel: /api/channels/<channel_id>
Checks when filtering that at least one valid filter has been specified.
Removes filter_queryset call when retrieving a single object - wasn't quite sure why DRF does this by default, seemed OK to remove.
> Permissions and filtering

- deploy/nginx.conf.jinja2
We now have 2 nginx server blocks on studio:
- the regular studio block, which allows most endpoints
- the catalog studio block, which blocks almost everything except a certain whitelist.
They're both listening on port 8080.
This PR sets the default block for port 8080 to be the regular studio block.
> set the second nginx server block to be the default for port 8080.

- contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSetModal.vue
Actually let the frontend know that we are not loading channels.
> Set channelsLoading to false.

- contentcuration/contentcuration/frontend/shared/data/applyRemoteChanges.js
- contentcuration/contentcuration/frontend/shared/data/constants.js
- contentcuration/contentcuration/frontend/shared/data/index.js
- contentcuration/contentcuration/frontend/shared/data/mergeChanges.js
- contentcuration/contentcuration/frontend/shared/data/registry.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/frontend/shared/data/serverSync.js
- contentcuration/contentcuration/frontend/shared/vuex/channel/__tests__/module.spec.js
- contentcuration/contentcuration/frontend/shared/vuex/channel/actions.js
* Reapplies any unsynced local changes when data is refreshed from the server
- Load channel list page.
- Wait 60 seconds
- Edit a channel's details
- Save changes
- See the changes persisted on the list page
Reapplies any relevant changes for fetched data.
For Create, Update, and Delete changes, applies this before the bulkPut.
For Moved changes, applies after the bulkPut as requires database access anyway.
> Don't swamp local changes on fetch

- contentcuration/contentcuration/frontend/shared/constants.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
- contentcuration/contentcuration/frontend/shared/vuex/channel/actions.js
- contentcuration/contentcuration/frontend/shared/vuex/channel/mutations.js
* Change channel editing to simple, in component diff tracking.
- Creating a channel then canceling works
- Creating a channel then saving works and redirects you to a 404 - on returning back to list page it is present
- Editing a channel then canceling works
- Editing a channel then saving works
The original plan to implement changes in the vuex state broke down, because changes would get swamped by any background fetch events (so if the browser had initiated a fetch in order to refresh a stale cache item, the successful resolution of that fetch could swamp a recent edit).
Just implementing a simple diffTracker object in the component then became the simplest way, preferring values from the diffTracker, then the vuex object. All edits are then tracked in the diffTracker on the component …
> Diff tracking and rollback

- contentcuration/contentcuration/frontend/administration/components/ClipboardChip.vue
- contentcuration/contentcuration/frontend/administration/components/ConfirmationDialog.vue
- contentcuration/contentcuration/frontend/administration/components/__tests__/clipboardChip.spec.js
- contentcuration/contentcuration/frontend/administration/components/__tests__/confirmationDialog.spec.js
- contentcuration/contentcuration/frontend/administration/pages/Channels/ChannelActionsDropdown.vue
- contentcuration/contentcuration/frontend/administration/pages/Channels/ChannelDetails.vue
- contentcuration/contentcuration/frontend/administration/pages/Channels/ChannelItem.vue
- contentcuration/contentcuration/frontend/administration/pages/Channels/ChannelTable.vue
- contentcuration/contentcuration/frontend/administration/pages/Channels/__tests__/channelActionsDropdown.spec.js
- contentcuration/contentcuration/frontend/administration/pages/Channels/__tests__/channelDetails.spec.js
- contentcuration/contentcuration/frontend/administration/pages/Channels/__tests__/channelItem.spec.js
- contentcuration/contentcuration/frontend/administration/pages/Channels/__tests__/channelTable.spec.js
- contentcuration/contentcuration/frontend/administration/pages/Users/EmailUsersDialog.vue
- contentcuration/contentcuration/frontend/administration/pages/Users/UserActionsDropdown.vue
- contentcuration/contentcuration/frontend/administration/pages/Users/UserDetails.vue
- contentcuration/contentcuration/frontend/administration/pages/Users/UserPrivilegeModal.vue
- contentcuration/contentcuration/frontend/administration/pages/Users/UserStorage.vue
- contentcuration/contentcuration/frontend/administration/pages/Users/UserTable.vue
- contentcuration/contentcuration/frontend/administration/pages/Users/__tests__/emailUsersDialog.spec.js
- contentcuration/contentcuration/frontend/administration/pages/Users/__tests__/userActionsDropdown.spec.js
- contentcuration/contentcuration/frontend/administration/pages/Users/__tests__/userDetails.spec.js
- contentcuration/contentcuration/frontend/administration/pages/Users/__tests__/userItem.spec.js
- contentcuration/contentcuration/frontend/administration/pages/Users/__tests__/userPrivilegeModal.spec.js
- contentcuration/contentcuration/frontend/administration/pages/Users/__tests__/userStorage.spec.js
- contentcuration/contentcuration/frontend/administration/pages/Users/__tests__/userTable.spec.js
- contentcuration/contentcuration/frontend/administration/router.js
- contentcuration/contentcuration/frontend/administration/vuex/channelAdmin/__tests__/module.spec.js
- contentcuration/contentcuration/frontend/administration/vuex/channelAdmin/actions.js
- contentcuration/contentcuration/frontend/administration/vuex/userAdmin/__tests__/module.spec.js
- contentcuration/contentcuration/frontend/administration/vuex/userAdmin/actions.js
Added tests and created a separate channel details modal as per [this comment](https://github.com/learningequality/studio/pull/1977#discussion_r449301833)
> Added admin page tests

- cloudbuild-production.yaml
- k8s/helm-deploy.sh
- k8s/templates/prober-deployment.yaml
- k8s/templates/studio-secrets.yaml
- k8s/values-prod-config.yaml
- k8s/values.yaml
Previously we use the account lingyi+prober@learningequality.org for the login prober. But it does not work anymore. Changing the account to sushi chef admin account so we can have the probers running successfully.
Create keys `loginProberUsername` and `loginProberPassword` in google cloud KMS and fetch it in Cloud Build
- Radina @radinamatic …
> change the login prober credential to another account

- contentcuration/search/views.py
Title says it all! 
It appears we don't have a unit test suite for search, so it rather adds to that tech debt. Probably not worth addressing in this branch, but we should make sure we have coverage for that in develop.
> Allow user to add Kolibri URLs or ids to the search field.

- contentcuration/contentcuration/frontend/channelList/router.js
- contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSetList.vue
- contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSetModal.vue
Fatten `/collections` routes in channel list app + related refactoring and cleanup.
Click through the collections tab on the channel list page. Check that back navigation works properly. Try to reload pages.
> Flatten routes 3 - channel list - collections

- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/viewsets/channel.py
* Fixes two bugs caused by previous work:
* Reinstates backend annotation of view, edit, and bookmark by using a more efficient subquery - this now improves performance when filtering by any of the three compared to previously, and does not degrade performance otherwise.
* Reinstating this fixes a bug where the channel edit page would always appear in view only mode for a fresh user - even if the channel was editable
* Updates the fetching code for related resources to filter on `id__in` rather than `id` previous edit to this was either missed or got squashed somewhere.
> Fix bugs on channel edit

- contentcuration/contentcuration/frontend/channelEdit/router.js
- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
- contentcuration/contentcuration/frontend/channelEdit/views/trash/TrashModal.vue
- contentcuration/contentcuration/frontend/shared/views/channel/ChannelDetailsModal.vue
- contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
Flatten trash, channel details and channel edit modal routes in the channel edit app.
Visit the modals from the channel edit root tree page. Check that back navigation works properly.
> Flatten routes - channel edit - trash, channel details and edit modals

- contentcuration/contentcuration/frontend/channelEdit/vuex/importFromChannels/actions.js
- contentcuration/contentcuration/tasks.py
- contentcuration/contentcuration/utils/nodes.py
- contentcuration/contentcuration/views/nodes.py
* Removes use of sort order in the duplicate nodes task
* Removes call to backend to get sort order value when calling duplicate nodes task from the frontend
* Import a node
The sort_order property is deprecated and no longer has any impact on ordering in the tree, so this removes that.
What I am not sure of is with MPTT updates disabled and using bulk_create, how the task is currently working - but nothing that this PR does makes that any worse.
> Update duplicate node task to no longer rely on deprecated sort_order property.

- contentcuration/contentcuration/frontend/channelEdit/router.js
- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.vue
Flatten nodes edit modal routes in the channel edit app.
Visit the edit modal from various parts of the channel edit root tree page (edit node/s, file upload, create an exercise, add a new topic). Check that back navigation works properly.
> Flatten routes - channel edit - nodes edit modal

- contentcuration/contentcuration/frontend/channelEdit/views/ResourcePanel.vue
- contentcuration/contentcuration/frontend/shared/views/ContentNodeIcon.vue
Added the questions preview to the resource drawer
Fixes https://github.com/learningequality/studio/issues/2057
Or for empty exercises
> Added questions to resource panel

- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
Fixes #2041 
| --------- | ------ |
| ![before](https://user-images.githubusercontent.com/13509191/90249148-41b3e700-de3a-11ea-83c3-48907f9f93c1.png) | ![after](https://user-images.githubusercontent.com/13509191/90249179-4b3d4f00-de3a-11ea-98fb-d6cf492c723b.png) |
> Don't show node options for a channel in breadcrumbs

- contentcuration/contentcuration/frontend/shared/views/MasteryDropdown.vue
- contentcuration/contentcuration/frontend/shared/views/__tests__/masteryDropdown.spec.js
Non-integer exercise success criteria will not be allowed.  If you are editing exercises:
- You will not paste non-integers into the M or N boxes
- You will not type decimals into the M or N boxes
- Even if you somehow manage to get them into the boxes, they won't be valid
https://github.com/learningequality/studio/issues/1774
I used `@keypress` and `@paste` handlers, and additionally added a validation rule
It could be useful to wrap this logic into a custom component if we ever need something like this again, since Vuetify 1.x doesn't have an integer input field.
- Ivan ivanistheone …
> Prevent non-integer M of N criteria on exercises

- contentcuration/contentcuration/frontend/channelList/views/Channel/mixins.js
The Content Library (a.k.a. Catalog) page was using vue-router's `router.replace`, which doesn't call `history.pushState`.  Switching to `router.push` will enable the back button while browsing the Content Library page, which could be useful if, for example, someone changes their filter but forgets exactly how and they just want to bail out and go back to the previous filter state.
The immediate issue this resolves is #2051.
My main uncertainty is around why we were using `router.replace` in the first place?
- Ivan ivanistheone …
> Enable back button when browsing the Content Library page

- contentcuration/contentcuration/frontend/settings/pages/UsingStudio/ReportIssueForm.vue
Include the `showInvalidText` prop on `KTextBox` because typically we only show validations on fields that have been focused and then blurred, but we can force it to show anyway if we also pass the `showInvalidText` prop.
Fixes #1947
> showInvalidText on report issue KTextbox

- contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSetModal.vue
- contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
Fixes #2089
I've also opened a tech debt issue #2101
> Prevent modals from closing before unsaved changes confirmed/cancelled

- contentcuration/contentcuration/frontend/channelEdit/components/StudioTree/StudioTree.vue
- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.vue
Fixes some of the styling reported at the QA session around the topic tree navigation drawer
* Smaller text
* Max width increased to 500px
> Fixed styling around navigation drawer

- contentcuration/contentcuration/frontend/shared/vuex/file/actions.js
- contentcuration/contentcuration/management/commands/set_content_mimetypes.py
- contentcuration/contentcuration/tests/test_gcs_storage.py
- contentcuration/contentcuration/tests/test_storage_common.py
- contentcuration/contentcuration/utils/gcs_storage.py
- contentcuration/contentcuration/utils/storage_common.py
- contentcuration/contentcuration/views/files.py
This PR contains various fixes to fix file presigned url creation.
- Use `blob` instead of `get_blob` to instantiate GCS `Blob` objects. `get_blob` returns `None` if the file doesn't exist yet on GCS.
- Enforce a mimetype during upload by using the `content_type` argument.
- Use the `content_md5` and `content_type` arguments to enforce these 2 headers during upload, rather than using the `headers` argument of `get_presigned_url`.
- use a python `TimeDelta` object to calculate the expiration date of the URL `x` number of seconds from now, rather than at the start of the unix epoch.
Note to @rtibbles: we will have to ensure that the client-side file upload code **only sends the following headers**:
- `Content-MD5` -- has to match the checksum we sent during signed url creation
- …
> File upload fixes for GCS

- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
Fixes [this issue](https://www.notion.so/learningequality/Clicking-copy-icon-in-resource-drawer-doesn-t-do-anything-a5497260b6bc470b854bb7218238b92f)
> Added clipboard action to resource drawer

- contentcuration/contentcuration/frontend/shared/mixins.js
`statusMessage` method in `shared/mixins.js` tries to get a file and did not account for what to return if there is no file (which is nothing).
Fixes https://github.com/learningequality/studio/issues/2114
Read https://github.com/learningequality/studio/issues/2114 and replicate the error on `develop` - then check out this PR and see that the error message no longer shows.
> no status message about the file if no errors or file

- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/test_settings.py
- contentcuration/contentcuration/tests/viewsets/test_channel.py
- contentcuration/contentcuration/tests/viewsets/test_contentnode.py
- contentcuration/contentcuration/urls.py
- contentcuration/contentcuration/viewsets/assessmentitem.py
- contentcuration/contentcuration/viewsets/base.py
- contentcuration/contentcuration/viewsets/channel.py
- contentcuration/contentcuration/viewsets/channelset.py
- contentcuration/contentcuration/viewsets/contentnode.py
- contentcuration/contentcuration/viewsets/file.py
- contentcuration/contentcuration/viewsets/invitation.py
- contentcuration/contentcuration/viewsets/sync/endpoint.py
- contentcuration/contentcuration/viewsets/sync/utils.py
- contentcuration/contentcuration/viewsets/tree.py
- contentcuration/contentcuration/viewsets/user.py
* Adds tests for Channel viewset
* Adds tests for ContentNode viewset
* Refactors sync endpoint to delegate change handling to viewsets
* Makes CRUD and sync handling parallel in viewsets
* Create mixins for opt-in bulk processing and change event handling
* Handles ContentNode creation in a way that does not mess up the orphanage tree
* Adds read/write permissions to orphanage tree for all authenticated users
* Adds regression test for bug for creation and copying events
- Create a topic or resource on a fresh DB
- Make sure the sync endpoint returns a 200
> Sync endpoint robustifying and node creation bug fix

- contentcuration/contentcuration/frontend/channelEdit/router.js
When we enter the root route `TREE_ROOT_VIEW` we init some Vuex then redirect to `TREE_VIEW`. This would `push` the new route - this PR ensures that we replace it so that there are no unnecessary history entries.
Fixes: https://github.com/learningequality/studio/issues/2069
Go to Channel Edit to edit a channel. Click your browser's back button. You should be returned to the previous page as expected. (ie, if you go to the Channel Edit from `/my-channels`, you should go back to it from the editor).
Neat to note that the `next()` function in nav guards take a `replace` option that allows you to do a `router.replace` instead of the default `router.push`. *neat!*
> Fix issue going back from Channel Edit

- contentcuration/contentcuration/utils/db_tools.py
* Fixes a bug in the treebuilder implementation that incorrectly passed down the root parent_id to all descendants
> Propagate the correct parent_id in tree generation.

- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/BrowsingCard.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ChannelInfoCard.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ContentTreeList.vue
- contentcuration/contentcuration/frontend/shared/views/ToggleText.vue
Fixes channel thumbnails not showing up (need to set width), text causing the cards to grow (removed grow attribute), and uses ToggleText component to fix the show more action link
Fixes https://github.com/learningequality/studio/issues/1988
> Fixed import modal styling

- contentcuration/contentcuration/frontend/channelList/views/Channel/mixins.js
Catalog filters were not working due to how we tried to update the route's query params.
Need to `Object.assign(...)` when borrowing `this.$route.*` so that we can modify a copy and replace the existing route.
Fixes https://github.com/learningequality/studio/issues/2073
Go to the "Content Library" catalog view and mess w/ the filters. They ought to work as expected. The URL's query params should reflect your selections. You should be able to update your filter selections both by way of the form *and* by removing them using the little `x` icons in the chips/pillboxes that appear above the channel list.
> Catalog filters fix

- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/MarkdownEditor.vue
- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownViewer/MarkdownViewer.vue
- docs/markdown_editor_viewer.md
I still need to work on our formulas plugin documentation, but a high-level overview is ready. Please let me know if it's clear.
> Add markdown editor documentation

- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/actions.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
Ensure that we've loaded the clipboard tree nodes prior to adding to it.
Additionally, the `contentNode/loadClipboardTree` action would not work properly if the clipboard is empty because `contentNode/loadTree` wasn't being called when there were no channels returned form `/api/get_clipboard_channels/`.
Fixes https://github.com/learningequality/studio/issues/2122
Fixes https://github.com/learningequality/studio/issues/2118
Fixes https://github.com/learningequality/studio/issues/2108
In Channel Edit, can you select 1 or more nodes and "Copy to Clipboard" successfully?
Please review the three linked issues and see that they each are fixed by this.
> Load the clipboard tree before adding to it

- contentcuration/contentcuration/serializers.py
- contentcuration/contentcuration/tests/test_serializers.py
Just a version of the previous PR for this targeted to hotfixes, so we can test and then push both the changes to master together.
> Make sure repr calls on Serializers don't evaluate querysets (hotfixes edition)

- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/mathquill/mathquill.css
- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/mathquill/mathquill.js
- docs/markdown_editor_viewer.md
Document markdown editor formulas plugin.
Make clear and document what's the original MathQuill code and what are our customizations (closes #1852). It will make more sense to review commit by commit.
> Formulas plugin and MathQuill documentation

- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/MarkdownEditor.vue
- contentcuration/contentcuration/frontend/shared/vuex/file/actions.js
I've discovered several places where some more information would be useful for debugging purposes while documenting image uploading. I assume that we'll implement some UX to display errors and upload progress but for now I added at least some logging. I am going to open follow-up issues and link them here soon.
> Add some more error handling and logging to the image upload

- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ChannelList.vue
During "Import from channels" process - the dropdown filtering which kind of channels previously allowed users to quickly switch between selections but did not handle the case of a user triggering another load causing issues.
This solution disables the dropdown while we're loading. We may opt later to optimize this so that people can change their selection without having to wait for the change to load.
Fixes https://github.com/learningequality/studio/issues/2110
Go Edit Channel -> Add -> Import from channels and then try to change the selection of the "Channels" dropdown before it loads. This may be difficult to test locally if you don't have many channels. I set my Dev Tools -> Network -> "Online" to instead be "Fast 3G" once I had loaded the page to slow down the triggered requests …
> disable the channel VSelect while loading during import from channels

- contentcuration/contentcuration/utils/nodes.py
Most of our remaining deadlock errors are coming from `move_nodes_task`, and are caused by small moves triggering full tree re-indexing on both the source and target trees.
This PR changes move behavior to not use `delay_mptt_updates` by default, but will use it in cases where a large number of nodes are reindexed and the number is higher than 2X the total target tree size.
In terms of code review, please check it with an eye on if any scenario could end up worse than before. I know this is some fuzzy logic, and it may trigger in cases where `delay_mptt_updates` could be slightly slower.  I tried to keep the logic simple and easy to read / predict to keep overall risk down. 
I considered simply removing `delay_mptt_updates`, but I know this is being used on trees with thousands of nodes, …
> Only use delay_mptt_updates() when it is really needed for move operations

- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/MarkdownEditor.vue
- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/__tests__/plugins/formulas/formula-html-to-md.spec.js
- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/formulas/formula-html-to-md.js
I've noticed that I can't add a text before a formula if it's the first entity in the markdown editor.
- Add non-breakable space before the formula
- Remove duplicate logic for the conversion of non-breakable spaces to markdown
> Allow adding text before a formula field when formula is a first entity in the markdown editor

- contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelItem.vue
Makes ChannelItem cards into actual links, for accessibility benefits, the ability to open in a new window or tab, etc.
Fixes #2156
I used the `v-card` component's `to` and `href` properties.  The `href` property was necessary because the channel tree view is in a different single page application, but in order to navigate to the channel details modal, it's necessary to use the `to` property.
If we ever consolidate everything into one single page application, we can simplify this a lot.
- Richard rtibbles (full …
> Turn `ChannelItem` cards into real links

- contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelList.vue
Fixes an issue where it wasn't possible to exit the `ChannelModal` right after creating a new channel.
Addresses #2154 
I made sure that `$route.query.last` was passed in.
> Ensure we can exit from the new channel modal

- contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
- contentcuration/contentcuration/frontend/shared/vuex/channel/actions.js
The `commitChannel` action's signature matches `updateChannel` and works similarly until it doesn't.
No known reported issue addressed.
However, the issue was that creating a channel would not work because the newly implemented `diffTracker` pattern where a component (in this case ChannelModal) will locally track changes to fields and pass them to the `commit/updateChannel` actions depending on whether or not the Channel is `new` or not.
Make a new channel and you should be redirected to `channelEdit` for that new channel.
I initially wanted to DRY the repeated field-specific logic a bit but decided that there's no need. Maybe someday we'll want the `commit*` and the `update*` to handle a certain field differently than the other, so …
> Channel creation bug fix - use diffTracker in commitChannel 

- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
I removed the `return` here https://github.com/learningequality/studio/pull/2143 for some reason - replacing it fixed the copying issue reported in today's bug hunt.
https://www.notion.so/learningequality/TypeError-Cannot-read-property-tree_id-of-undefined-when-adding-to-clipboard-this-ought-to-hav-ee495afe152643de83a262415a345e1e
> Fix copy to clipboard (again)

- contentcuration/contentcuration/utils/nodes.py
Fixes issues where progress will stay at 0% until the first move (and any subsequent reindexing) has completed, giving a sense that the task hasn't started. Also makes the percent calculation the same for both slow and fast reindexing paths.
This is not fixing an actual bug in the move handling, just improving the UX.
- Radina @radinamatic …
> Move tweak

- contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelItem.vue
Adjusts channel card according to specifications in [this doc](https://www.notion.so/learningequality/card-layout-cleanup-9b33f256f93b47678288b9e83d2e4b27).
Only thing missing is title reduction - need some guidance.
- Shifting HTML
- Tweaking line height to achieve double-spacing.
Really missed the immediate gratification of styling work.
> Card layout cleanup

- contentcuration/contentcuration/frontend/channelEdit/components/StudioTree/StudioTree.vue
- contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreePage/index.spec.js
- contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreePage/index.vue
- contentcuration/contentcuration/frontend/channelEdit/router.js
- Remove `beforeRouteEnter` hook from `StagingTreePage` route. 
- Implement the data init logic from that hook in `StagingTreePage.created()`
- Apply styling to `StudioTree` so that the `<LoadingText.../>` component cannot be so tall that its loader isn't visible unless you scroll down the page. This was very obvious because `StudioTree` would take longer to load than the channel I was testing on that had 200 topics in its root.
Fixes https://github.com/learningequality/studio/issues/2106
1. Find a ricecooker channel that you want to use - such as the one created by the `devsetup` command. Go to that channel and extract its ID from the URL (which will be the `<ID>` in `/channels/<ID>`).
2. Create a file `contentcuration/make_staged.py` with the following code (replace the `<ID>` on line 2 …
> Load staged channel in created() not route hook to show loader

- contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
- contentcuration/contentcuration/frontend/shared/views/channel/ChannelThumbnail.vue
- contentcuration/contentcuration/frontend/shared/vuex/channel/actions.js
Channel edit was not saving thumbnails, now it is.
I also found that the X "Remove" button in the image above wasn't doing anything and fixed that as well. Now we can add during create, edit and remove a channel thumbnail altogether.
Fixes https://github.com/learningequality/studio/issues/2155
- Create a new channel and upload an image when you do it. 
- Go to channels list and see the image.
- Go to that channel, edit it, then change the thumbnail (you have to click the image) and save your changes
- Go to channels list and see the new image.
> Channel thumbnails upload fix

- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/MarkdownEditor.vue
Absolute lightest touch way I could think of to allow for destruction of Vue components without messing with the rest of the code. Have some ideas for iteration, but will wait and see what the original devs think of this solution.
Surely, there are more elegant ways to do this. But it's not the right time for a refactor :upside_down_face: 
Addresses #2079
Track the Vue components created, delete them when their associated elements have been deleted by a user's markdown edits.
Rather than manually binding HTMLElements to DOM, add them to a tracker Array `imageFields`.
Continuously scan the DOM (in the case, listening for the `change` event on the Squire body element), for `<img>` tags - if the `<img>` belonging to one …
> First pass vue component cleanup Resolves #2079

- contentcuration/contentcuration/frontend/channelEdit/components/NodeTreeNavigation.vue
- contentcuration/contentcuration/frontend/channelEdit/components/RelatedResourcesTab/RelatedResourcesTab.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditView.vue
- contentcuration/contentcuration/frontend/channelEdit/pages/AddNextStepsPage.vue
- contentcuration/contentcuration/frontend/channelEdit/pages/AddPreviousStepsPage.vue
- contentcuration/contentcuration/frontend/channelEdit/router.js
Fixed issues on related resource navigation and added snackbars + breadcrumb components
Fixes https://github.com/learningequality/studio/issues/1847
Fixes https://github.com/learningequality/studio/issues/2208
Fixes https://github.com/learningequality/studio/issues/2209
Fixes https://github.com/learningequality/studio/issues/1814
- [After entering and exiting the selection screen for related content, and then exiting an exercise edit modal, somehow I'm inside of the exercise like a topic in the topic tree](https://www.notion.so/learningequality/After-entering-and-exiting-the-selection-screen-for-related-content-and-then-exiting-an-exercise-ed-cf6c8408c7b24d3da2fb8400b4d24a97)
- [Seeing previous steps in previewer but not in the related …
> Fixed related tab issues

- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditListItem.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/data.js
- contentcuration/contentcuration/frontend/channelEdit/views/ResourcePanel.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
- contentcuration/contentcuration/viewsets/contentnode.py
Annotate the assessment item count directly to the contentnode viewset to get a more accurate question count
Fixes https://github.com/learningequality/studio/issues/2127
> Annotate assessment item count directly to contentnode viewset

- contentcuration/contentcuration/frontend/shared/views/ActionLink.vue
- contentcuration/contentcuration/frontend/shared/views/InfoModal.vue
- contentcuration/contentcuration/frontend/shared/views/LicenseDropdown.vue
- contentcuration/contentcuration/frontend/shared/views/MasteryDropdown.vue
- contentcuration/contentcuration/frontend/shared/views/VisibilityDropdown.vue
- contentcuration/contentcuration/frontend/shared/views/__tests__/infoModal.spec.js
- contentcuration/contentcuration/frontend/shared/views/__tests__/licenseDropdown.spec.js
Standardizes the styling for info modals
> Updated the styling on info modals

- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
When editing multiple content nodes, text was not saving properly or as expected.
Fixes https://github.com/learningequality/studio/issues/2235
Applies to other fields in addition to `author`.
1. Select multiple items to edit
2. Edit one item's author field
3. Click directly onto a different node in the left panel without clicking anything else (don't blur the text field)
4. Author field stays around, depsite having switched to a different node
Previously, changes would not be persisted if you clicked away without blurring the edited field.
Do the same with Provider, Aggregator, etc in that section.
The Vuetify `@input` and `@change` event listeners were not being triggered _on input_ but rather on blur. So if we don't blur the field, the value of the data isn't saved and that's annoying. …
> Use native input and debounce it for text fields in content edit

- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/MarkdownEditor.vue
When editing exercise content without images, an error would occur:
```
vue.runtime.esm.js:1888 TypeError: Invalid attempt to iterate non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
at _createForOfIteratorHelper (channel_edit.65365769d7eabef89041.hot-update.js:37)
at VueComponent.initImageFields (MarkdownEditor.vue:637)
at VueComponent.imageEls (MarkdownEditor.vue:166)
at Watcher.run (vue.runtime.esm.js:4568)
at flushSchedulerQueue (vue.runtime.esm.js:4310)
at Array.<anonymous> (vue.runtime.esm.js:1980)
at flushCallbacks (vue.runtime.esm.js:1906)
```
This was because `imageEls` was being initialized as an empty object.
> Fix iteration over empty `imageEls` for exercises without images

- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeEditListItem.vue
- contentcuration/contentcuration/frontend/channelEdit/components/StudioTree/StudioTree.vue
- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
- contentcuration/contentcuration/frontend/channelEdit/views/NodePanel.vue
- contentcuration/contentcuration/frontend/shared/views/ExpandableList.vue
- contentcuration/contentcuration/frontend/shared/views/IconButton.vue
- contentcuration/contentcuration/frontend/shared/views/details/DetailsRow.vue
I broke down the changes by commit, but in summary, this PR fixes some of the minor styling issues on the resource panel and main channel editor page.
Fixes [this issue](https://www.notion.so/learningequality/On-content-items-in-list-the-Show-topic-icon-button-is-bigger-than-the-context-menu-icon-button-n-8ced304710474bf59447da1dc1cc8d14) from the QA session
Fixes https://github.com/learningequality/studio/issues/2250
> Resource panel minor UI fixes

- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/currentChannel/index.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/currentChannel/mutations.js
In ChannelEdit, when you select a node or nodes using the checkboxes and click the "Edit" button, your selections will remain selected when you return to ChannelEdit's tree view after closing the EditModal.
Fixes https://github.com/learningequality/studio/issues/2239
- Select multiple nodes.
- Click the Edit pencil icon
- Close the EditModal
- Your selections should remain selected.
Additionally, please test:
- Clearing all selections, then select a few individual nodes and do the above.
- Selecting all and then do the above
- Selecting all, then deselecting nodes then doing the above.
Added state to `currentChannel` Vuex module. 
Added get/set computed for `selected` in CurrentTopicView and mapped the new `currentChannel.selectedNodeIds` state.
Also, clearing selections was being done by …
> Maintain selections between channel tree view & edit modal

- contentcuration/contentcuration/viewsets/channel.py
* Removes an order_by that we can do without to avoid a quicksort inside our count
Help with our channel endpoint optimizations
> Change how we distinct content_ids to avoid a slow order_by

- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/getters.js
- contentcuration/contentcuration/frontend/shared/app.js
- contentcuration/contentcuration/frontend/shared/utils.js
- contentcuration/contentcuration/frontend/shared/views/LicenseDropdown.vue
- contentcuration/contentcuration/frontend/shared/views/__tests__/licenseDropdown.spec.js
- contentcuration/contentcuration/frontend/shared/views/form/ContentDefaults.vue
When getting licenses, search by both name and id so that `content_defaults` string keys can be found. When setting license on a node, always use id to be consistent with frontend and serializer behavior.
I tried to get the `ContentDefaults` view using `LicenseDropdown`, and functionally it seemed to work, but it broke some conventions because it was a composite field but ContentDefaults treated license and description as two separate fields. My Vue-Fu was not strong enough to figure out the right fix for this and didn't want to start refactoring enough that I may break other things, so after fighting with it for a while, I realized that this was one battle best saved for another day!
If you are looking to assign …
> Fix issues with license being passed as a string rather than id.

- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditListItem.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
Fixes https://www.notion.so/learningequality/Fix-issue-Not-seeing-validation-in-the-resource-list-while-uploading-for-EPUB-and-video-56b55ca445524ac7a6d77af6ee9229d8 (Private Notion Doc) by making the `uploadingFiles` computed prop more accurate (a file is in 'uploading' state only if it's progress is strictly less than 1)
The bug might have been most visible with Documents (PDFS, epubs) and videos because they require uploading a file. It wasn't visible with custom exercises (no files to upload).
See the Notion Link above
Fixes #2200 
Probably fixes #2201 
*Delete any items that don't …
> Fix filter on `uploadingFiles` computed prop + probable fix for "0 errors to fix" bug

- contentcuration/contentcuration/frontend/channelEdit/views/ResourcePanel.vue
Fix side panel previewer not showing previous and next steps.
Fixes https://github.com/learningequality/studio/issues/2215
Have some content nodes that are prerequisites for each other and verify that the same thing is shown in the Related tab of the editor as are shown in the previewer on the right side when you first click a node.
I found the convenient getters for this data and used those to get the data properly.
> See previous & next resources in preview panel

- contentcuration/contentcuration/frontend/settings/pages/Account/DeleteAccountForm.vue
- contentcuration/contentcuration/frontend/settings/pages/Account/index.vue
- contentcuration/contentcuration/frontend/settings/pages/Storage/RequestForm.vue
Addresses two issues from bug bash:
1.  https://www.notion.so/learningequality/Errors-don-t-show-on-validate-if-I-haven-t-interacted-with-form-fields-on-the-storage-request-form-c0b2768e419b4e41845ecb8c52fb9e60
2. https://www.notion.so/learningequality/Delete-account-validation-isn-t-showing-up-a2c2e2a177b6406e8a6f901f38c0f4d6
I also found a bug where a function tried to read for an array somewhere that the array can be undefined and fixed it. This stopped me from seeing the account page when signed in as my `ivanbot` test account.
- Check that the proper fields are being validated as expected on the Storage Request form.
- Check that invalid or nonexistent email addresses i the "Delete Account" form shows when you click to submit.
I used the `showInvalidText` prop on `KTextField` that …
> Account & Storage Form Bugs

- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
I tested the sharing modal by going to a channel's editor and clicking the top-right context menu and selecting "Share channel" and found that I could not leave the modal unless I hit browser back. Seemed to be missing a param to make it happy.
When you go to the page initially to the "Share" tab - Vuetify doesn't update the selected tab properly so "Details" is seen as 'active'. I could not figure out how to make it act right and gave up on it for now. 
Go to a Channel Edit and right click the upper-right context menu -> Share Channel then click the appbar X to leave the modal. It should do what you think it should.
> Now you can leave the sharing modal no matter what

- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/MarkdownEditor.vue
- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/__tests__/plugins/formulas/markdownFormulaElement.spec.js
- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/formulas/MarkdownFormula.vue
This is a followup on #2232, and includes three main things, following @nucleogenesis's feedback [here](https://github.com/learningequality/studio/pull/2232#pullrequestreview-491667655):
1) More comments throughout the code
2) I renamed "buffers" to "spacers" for clarity (referring to the extra non-breaking spaces that must surround custom editor nodes)
2) A more thorough fix for the delete key behavior, so that you should only need to press delete once to delete a formula.
TODO: It'd be nice to have tests for the TUI.editor key handler fixes, but I haven't quite figured out the best way to do this yet.
> Some more markdown math rendering fixes

- contentcuration/contentcuration/frontend/channelEdit/__tests__/utils.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/AnswersEditor/AnswersEditor.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/AnswersEditor/AnswersEditor.vue
- contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemEditor/AssessmentItemEditor.spec.js
- contentcuration/contentcuration/frontend/channelEdit/utils.js
When editing an answer, Input fields can only accept numeric values.
Also - if you change from one question type to the Input question type any answers you've added to the previous question type will be removed if they include anything other than numbers.
The modal confirmation already says something along the lines of "if you change you will lose non-numeric answers".
Adds a validation string for non-numeric values: 
Fixes https://github.com/learningequality/studio/issues/2199
NEW TO TEST:
In Chrome and Firefox, enter valid and invalid values. If you ever blur away from an invalid field, you should see the validation error. Note that `e` is allowed in an exponentiation context, `+ and -` are allowed to sign the values and floats are valid as well.
Old instructions for testing below:
1. …
> Input question on AnswerEdit is now a type=number field

- contentcuration/contentcuration/viewsets/base.py
- contentcuration/contentcuration/viewsets/contentnode.py
* Fixes an issue where sync changes with no writeable data would cause None type is not iterable errors
* Adds complete field to the ContentNode serializer
Fixes #2297
> Prevent errors when sync returns changes that are not persistable on the server

- contentcuration/contentcuration/viewsets/contentnode.py
* Adds a guard against the value decoded from JSON in thumbnail_encoding being None or an empty dict.
* Fixes #2302
> Don't try to get from None.

- contentcuration/contentcuration/tests/viewsets/test_assessmentitem.py
- contentcuration/contentcuration/viewsets/base.py
* Adds tests for empty and unwriteable updates to the assessment item endpoint
* Fixes an issue with m2m_fields being undefined for empty or undefined updates
Fixes #2304
> Add tests for unwriteable and empty updates and fix them.

- contentcuration/contentcuration/models.py
* Removes the Django signal that causes files to be removed from GCS storage when the last File object referencing it is deleted.
* Resolves decision at post-mortem that decided we should preserve files on GCS in order to assist in restoration processes for users.
- Delete every File object referencing a particular checksum and extension
- Confirm that the file still exists in storage
Deleted the signal that does this, but left the utility function in place so that we can implement cleanup commands in the future.
Still need to implement the later cleanup command
> Remove file auto delete signal to preserve files on GCS until further notice.

- contentcuration/contentcuration/frontend/shared/data/resources.js
* We were accidentally using the resource methods for doing client side only updates of counts
* Changes these to use methods on the underlying Dexie tables, in order for IGNORED_SOURCE to be set properly
* Updates the transaction helper function to allow the source to be explicitly set.
* Fixes #2294
- Create an assessment item
- Check that the value of `assessment_item_count` on the contentndoe changes
- Check that this change does not get propagated to the backend
> Set IGNORED_SOURCE on transactions properly

- contentcuration/contentcuration/frontend/channelEdit/vuex/assessmentItem/actions.js
* Fixes issues where assessment items were not being properly referenced by the [contentnode, assessment_id] combined index primary key.
* Fixes #2305
- Create a new assessment item (question) in an exercise
- Delete it
- Refresh the page and confirm that it is deleted.
> Properly reference assessmentitem ids.

- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/ImagesMenu/ImagesMenu.vue
- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/MarkdownEditor.vue
Do not trigger image upload and do not display an image in the content area of the markdown editor immediately after drop. Instead, open the images upload menu with the image and let the menu handle the rest of the upload and insert process.
Closes #2177
> Use the images upload menu when an image dropped

- contentcuration/contentcuration/frontend/administration/router.js
- contentcuration/contentcuration/frontend/channelEdit/constants.js
- contentcuration/contentcuration/frontend/channelEdit/views/ChannelEditAppError.vue
- contentcuration/contentcuration/frontend/shared/views/errors/ChannelDeletedError.vue
- contentcuration/contentcuration/views/base.py
1. Adds a new type of error for the channel edit SPA (Channel Deleted), which shows a different error page and a path to restoring it in the Administration SPA
1. Create a channel, then delete it
1. Try to visit the channel edit page for that channel (try other nodes other than the root node)
1. You should see an error page like the one in the screenshot
1. Clicking the "Restore channel" link should take you the administration with the specific channel the sole entry in the table.
- Jordan jayoshih (full …
> When a channel is deleted, show an error page prompting user to contact an administrator

- contentcuration/contentcuration/db/models/manager.py
- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/ricecooker_versions.py
- contentcuration/contentcuration/test_settings.py
- contentcuration/contentcuration/tests/test_contentnodes.py
- contentcuration/contentcuration/tests/viewsets/test_contentnode.py
- requirements-dev.in
- requirements-dev.txt
* Adds tests for concurrent insert and move behaviour
* Adds tests for deadlock handling
* Adds pre-emptive locking for node saving and node moves
* Adds handling for deadlocks that result from the pre-emptive locking and does a single retry
- Do tests pass?
- Is the code self-explanatory/sufficiently commented?
> Use pre-emptive locking to prevent tree corruption, and handle resulting deadlocks

- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/tests/viewsets/test_assessmentitem.py
- contentcuration/contentcuration/tests/viewsets/test_channelset.py
- contentcuration/contentcuration/tests/viewsets/test_file.py
- contentcuration/contentcuration/tests/viewsets/test_invitation.py
- contentcuration/contentcuration/tests/viewsets/test_user.py
- contentcuration/contentcuration/viewsets/assessmentitem.py
- contentcuration/contentcuration/viewsets/base.py
- contentcuration/contentcuration/viewsets/channel.py
- contentcuration/contentcuration/viewsets/channelset.py
- contentcuration/contentcuration/viewsets/common.py
- contentcuration/contentcuration/viewsets/contentnode.py
- contentcuration/contentcuration/viewsets/file.py
- contentcuration/contentcuration/viewsets/invitation.py
- contentcuration/contentcuration/viewsets/user.py
* Adds new class methods to Models to define their queryset filtering behaviour for viewing and editing
* Takes queryset and user arguments, returns filtered queryset
* Implements on Model classes to avoid having to subclass both queryset and manager
* Adds tests for viewsets that had no tests so far
* Adds specific tests to test for Foreign Key permission setting
* Consolidates all queryset filtering by user onto the models, and extends the base values viewset class to look for the model class methods
* Fixes numerous bugs that were uncovered by the addition of the tests
- Do all the tests for the endpoints pass?
- Does everything still load as expected for the frontend data?
> Add permissions filtering for foreign key setting

- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/settings.py
- contentcuration/contentcuration/tasks.py
- contentcuration/contentcuration/utils/cache.py
- contentcuration/contentcuration/utils/channel.py
- contentcuration/contentcuration/viewsets/channel.py
Removes AdminChannelViewSet annotations and defers them to be executed in an async task that will cache the results.
As operations are executed asynchronously, the values are not immediately available if they have not been previously cached. In this case the values are marked with a DEFERRED_FLAG so the frontend knows that it can request them later.
The structure of the created object can be seen in the contentcuration/contentcuration/utils/channel.py and it's done according to the https://www.notion.so/learningequality/2020-12-24-Team-Sonic-counting-descendants-meeting-7ea0f46d4a6648109a22eefbba124a92 decissions
NOTE: some small optimization have also been done, mainly removing unneded order_by requirements in some of the queries, and the use of CTE to avoid scanning the whole File table …
> Cache channel metadata

- contentcuration/contentcuration/viewsets/base.py
You can move nodes now. A variable was named `changes` was turning our expected object into an empty array.
However, it does not fix the fact that moves are not triggering the call to sync. They're in the respective `*changes*` tables.
Fixes https://github.com/learningequality/studio/issues/2339
Move a node then in your dev tools console call `window.forceServerSync()` and then see that the move has happened as expected.
> Different variable names for different values

- contentcuration/contentcuration/tests/viewsets/test_invitation.py
- contentcuration/contentcuration/viewsets/invitation.py
* Enhances tests to ensure no new invitation is created after one has been deleted during an update call
* Fixes #2347
- Make sure no new invitation gets created after accepting or declining one
> Prevent a new invitation being created after an old one is updated.

- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
Fixes a couple issues on the edit details page.
For all nodes w/ a license and copyright holder, it was not saving if you took an auto complete suggestion. Now it saves that.
Also - I noticed that the mastery criteria wasn't being saved. That is also fixed.
Fixes https://github.com/learningequality/studio/issues/2324
First - replicate the bugs on `develop`:
1. Go to an content node's edit details page. If there is a copyright holder already - remove it and save. In any case you must have already entered a copyright_holder in order to get the suggestion dropdown (see https://github.com/learningequality/studio/issues/2324)  - Ensure that selecting from the list doesn't work
2. Set your mastery criteria and try to save the node, then come back and be disappointed by the failure of the app to …
> Assign copyright_holder w/ @input & ensure mastery criteria is saved

- contentcuration/contentcuration/frontend/channelEdit/components/move/MoveModal.vue
- contentcuration/contentcuration/frontend/shared/data/serverSync.js
Polls for unsynced changes and then syncs them.
Fixes https://github.com/learningequality/studio/issues/2338
Bonus!
Fixes an issue I saw where the selected nodes were still selected when moving nodes by selecting their checkbox and using the move icon in the context menu. https://github.com/learningequality/studio/pull/2356/commits/015331019aa24fcc306919831b8c5ad3982b8a91
*Double Bonus!*
Fixes https://github.com/learningequality/studio/issues/2326 because the trash is just a place to move nodes to and from. 
Checkout `develop` and try moving some nodes. Check your `_syncableChanges` table in IDDB and you'll see some sweet changes sitting there getting absolutely no love or attention. No `/sync` call in Network tab - nothing until you refresh the page (it will sync when you refresh the …
> Poll for unsynced changes then sync them

- contentcuration/contentcuration/tests/viewsets/test_clipboard.py
- contentcuration/contentcuration/viewsets/common.py
* In a story as old as time, we have to handle null extra fields.
* Adds a regression test that triggers the original issue.
* Adds special handling to our get_value method for nested update handling.
* Fixes #2374
> Handle extra fields being null.

- contentcuration/contentcuration/tasks.py
- contentcuration/contentcuration/utils/user.py
- contentcuration/contentcuration/viewsets/channel.py
- contentcuration/contentcuration/viewsets/user.py
As done in #2333 , here we're caching and delaying to be asynchronously calculated some of the annotated fields for the `AdminUserViewSet`
Slow or impossible view with thousands of users in our Studio database
Added also an api for the frontend to fetch delayed data. Example of use:
http://localhost:8080/api/admin-users/deferred_data?id__in=1,2,3,90
One task to do all the users calculation is implemented (a single user task is not needed by now):
`cache_multiple_users_metadata_task`
Values are stored in the cache and recalculated when they are requested if one hour has passed since its last calculation. To avoid cache stampede the expiration time is calculated with the `@cache_stampede `decorator that uses a randomized gaussian function so not all the calculations are done simultaneously …
> Adding delayed calculation of annotation values for AdminUsers

- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.vue
I think because of a layout change to TreeView, the 404 error that was supposed to shown gets pushed out by `CurrentTopicView`, which just shows an infinite loading widget. This fixes the layout so the error page gets shown properly. This can be tested by going to any place in the channel tree and changing a UUID by one character to make it invalid.
Before
After
> Fix PageNotFound error being pushed out of frame by loading screen

- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditList.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditView.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/SavingIndicator.vue
- contentcuration/contentcuration/frontend/shared/views/BottomBar.vue
- contentcuration/contentcuration/frontend/shared/views/HelpTooltip.vue
- contentcuration/contentcuration/frontend/shared/views/ResizableNavigationDrawer.vue
Updated the layout for the edit modal:
* Added bottom toolbar with saving indicator, finish button, and storage information
* Moved add more button to edit list
* Fixed the tabs to the top of the screen (added shadow effect when scrolled)
* Removed dividers
* Switched to single column layout
Fixes https://github.com/learningequality/studio/issues/2318
Fixes https://github.com/learningequality/studio/issues/2308
Also fixes:
* [Move 'finish' button to white bottom bar](https://www.notion.so/learningequality/Move-finish-button-to-white-bottom-bar-4d41285eba9545a1a60feee3be77261d)
* [On exercise editor, 'Assessment options' section should maybe be moved up - and/or 'Editing exercise' title should be added to top of screen](https://www.notion.so/learningequality/On-exercise-editor-Assessment-op …
> Updated edit modal layout

- contentcuration/contentcuration/frontend/channelList/views/ChannelListIndex.vue
- contentcuration/contentcuration/frontend/channelList/vuex/channelList/mutations.js
- contentcuration/contentcuration/frontend/shared/views/channel/ChannelSharingTable.vue
- contentcuration/contentcuration/frontend/shared/views/channel/__tests__/channelSharingTable.spec.js
A few issues surrounding invitations on the frontend - each commit fixes a separate issue.
- Only show a person once in the channel edit -> share page. Previously an invited user would show as invited still even after accepting
- Exclude accepted invites from channel list. I was seeing previously accepted invites showing up on page reload - but this may be due to https://github.com/learningequality/studio/issues/2347 - in any case - now we'll not show any invites to the user if they're accepted.
- We were overriding given information by setting `accepted` and `declined` as false between reading from state and displaying to the user so state would not be reflected properly.
Fixes https://github.com/learningequality/studio/issues/2067
- Make invites, accept them and test that the above are …
> Accepted invites not shown as invites on ChannelList anymore

- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ContentTreeList.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchResultsList.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
- contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSetModal.vue
- contentcuration/contentcuration/frontend/channelList/vuex/channelSet/actions.js
- contentcuration/contentcuration/frontend/channelList/vuex/channelSet/mutations.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/tests/viewsets/test_contentnode.py
- contentcuration/contentcuration/viewsets/contentnode.py
* Makes all references to content nodes use the content node getter for consistent frontend representation
* Don't load additional data for detail view on upload, as no detail nodes to load
* Fix copy paste errors from switching channel set modal to use the diff tracker
Fixes #2412
Edit modal loads (further investigation of any residual 504s will have to happen on develop)
File upload loads
Import from channel loads in browsing mode:
Import from channel loads in search mode:
Channel collection creation works:
> Follow up fixes from Many to many field work

- contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
New empty values were being overridden by the original channel values because of implicit conditions which caused issues when new values were empty. I used the same `diffTracker` technique that's used for thumbnails to fix it.
Fixes #2418
Fixes #2407
Please test the whole channel edit modal workflow with focus on deleting values. Try to save the modal and check that correct values were saved to backend (you can remove IndexedDB and reload the page after saving the modal).
> Channel edit modal fields fixes

- contentcuration/contentcuration/frontend/accounts/pages/Main.vue
- contentcuration/contentcuration/frontend/accounts/pages/__tests__/main.spec.js
Adds a banner to the login form that that shows when the page has a `next` URL query parameter, instructing the user they must sign in to proceed.
https://github.com/learningequality/studio/issues/2119
Login error (existing):
New banner:
New banner with login error:
With `next` param:
Without `next` param
> Add login form banner message shown when authentication is needed to proceed

- contentcuration/contentcuration/utils/publish.py
* Updates the prerequisite error catch to catch a missing kolibri contentnode, not a missing content curation content node
* There is a test for this, but it doesn't seem to be testing what it is meant to be testing, and I think my pipenv is now broken.
* Fixes #2431
> Catch a missing kolibri model, not CC model.

- contentcuration/contentcuration/tests/viewsets/test_contentnode.py
- contentcuration/contentcuration/viewsets/common.py
* Prevents errors caused by a non-object being passed to the dot path mixin
* Primarily to prevent errors from an Array being erroneously passed back
* Fixes #2424
> Catch non-objects being passed to dot path mixin.

- contentcuration/contentcuration/frontend/accounts/pages/Create.vue
- contentcuration/contentcuration/frontend/administration/pages/Channels/ChannelItem.vue
- contentcuration/contentcuration/frontend/administration/pages/Users/UserPrivilegeModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
- contentcuration/contentcuration/frontend/channelEdit/components/move/NewTopicModal.vue
- contentcuration/contentcuration/frontend/settings/pages/Account/FullNameForm.vue
- contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
- contentcuration/contentcuration/frontend/shared/views/channel/ChannelSharing.vue
- contentcuration/contentcuration/frontend/shared/views/form/ContentDefaults.vue
Adds `maxlength` and `counter` attributes/props to all the TextFields that need them in order to provide some basic validation for CharField models.
Hopefully fixes #1411 , although I have no idea where that original error came from.
Example: The channel details modal now has counters for all the text fields
- Go to every form you can think of. If the value is going into a DJango model CharField, it will have a counter and max-length validation.
- Aron aronasorman (back end, …
> Add maxlength and counter attributes to TextFields that need them

- contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemPreview/AssessmentItemPreview.vue
Make sure hint previews render nicely for long hints
Fixes #2403
> fix hint preview rendering for long hints

- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
Fixes an issue where Select All checkbox's state on channel edit wasn't working properly.
Fixes https://github.com/learningequality/studio/issues/2311
1. Navigate to a topic
Make sure this is fixed - only happens after first page load on first navigation to a topic when broken:
> Error 1: select all checkbox is checked, even if no items are loaded. Probably better to hide it until the items load so user doesn't interact with it beforehand
1. Select some items
2. Navigate to another topic
Make sure this is fixed and state is reset between topic navigations
> Error 2: select all checkbox shows as being partially checked, but selection should get reset between navigations
Select All previously was `this.selected === this.children` but it really only matters if `this.children.length > 0` so …
> Select All checkbox shows proper state during and after navigation

- contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
Get rid of the Vue Router "How dare you try to navigate to the same route I refuse to do this and will complain loudly about it" error.
Also - I saw a place in the code where `this.currentTab` was being set to `false`.
Fixes https://github.com/learningequality/studio/issues/2394
Go to edit a channel's details (name, description, etc) and change between Sharing & Details tabs then click the same tab you're on and you should no longer see Vue Router saying it avoided redundant navigation.
> Avoid error replacing route with same route

- contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelItem.vue
- contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSetList.vue
- contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSetModal.vue
- contentcuration/contentcuration/frontend/channelList/views/ChannelSet/__tests__/channelSetModal.spec.js
Addresses the following items:
* [Collection info modal should use secondary color](https://www.notion.so/learningequality/Collection-info-modal-should-use-secondary-color-605701276264409cbfac9e1d47267a90)
* [This looks like an icon button that we don't use. Should be a link](https://www.notion.so/learningequality/This-looks-like-an-icon-button-that-we-don-t-use-Should-be-a-link-b0eec3be9c204111a98fd6a4bf11f584)
* [New collection "create" needs to be a final action in a bottom bar. With # channels selected as the left info indicator](https://www.notion.so/learningequality/New-collection-create-needs-to-be-a-final-action-in-a-bottom-bar-With-channels-selected-as-the--4d597c915d274554bddfa235643c2e9d)
* [Need to add dir="auto" to channels under collection …
> Collection ui fixes

- contentcuration/contentcuration/frontend/shared/data/__tests__/ContentNodeResource.spec.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
* Fixes an error caused by only doing a shallow loading of requisite relationships from IndexedDB
* Does a recursive load of all requisite relationships from indexedDB
* Adds a test to guarantee this behaviour
* Adds a block for cyclic relationships
* Adds a test to ensure cyclic relationships do not result in infinite recursion
* Fixes #2422
Nodes are unselectable even after a refresh:
> Do a full recursive loading of requisite relations from indexedDB.

- contentcuration/contentcuration/viewsets/common.py
Forces casting of the field used in the array_agg postgresql subquery
Fixes #2367 
1. Edit a channel
2. Click on Add - Import from channel
3. Open the browser dev tools
4. Do a search
5. Check no server errors appear in the dev tools
As the ouptut field of the `SQArrayAgg` class is `ArrayField(CharField())`
casting the field to `text` should not have any side effect.
If other type of fields were going to be aggregated  a different class should be used
> Array agg needs to know the field type

- contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSetModal.vue
- contentcuration/contentcuration/frontend/channelList/views/ChannelSet/__tests__/channelSetModal.spec.js
Bug fixes and more specs for `ChannelSetModal`, which is responsible for adding new or updating existing collections.
Regarding existing tests, I've removed functionality reaching to `ChannelSetModal`'s internals and simulated users' behavior whenever possible instead, so that we don't need to refactor tests when updating `ChannelSetModal`'s internal methods, data etc.
Fixes #1778
Fixes an issue when it wasn't possible to close the modal immediately after adding a new collection
> ChannelSetModal fixes

- contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNode.vue
- contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/TopicNode.vue
- contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/index.vue
Addresses the following issues:
* [Need better handling for clipboard counter](https://www.notion.so/learningequality/Need-better-handling-for-clipboard-counter-d4b61eeeca9243a18002fd35b9b09b25)
* [Clicking the menu icon on topics in the clipboard opens the topic. Should only open the menu](https://www.notion.so/learningequality/Clicking-the-menu-icon-on-topics-in-the-clipboard-opens-the-topic-Should-only-open-the-menu-b3f797ce306a41eda675568416f61a21)
* [Reduce padding between clipboard items to save space](https://www.notion.so/learningequality/Reduce-padding-between-clipboard-items-to-save-space-c126b16c5ec64846bcf2fb26fbc043f9)
* [clipboard width can use another 100px. too narrow](https://www.notion.so/learningequality/clipboard-width-can-use-another-100px-too-narrow-315c930f922f4b58a8 …
> Clipboard ui fixes

- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/BrowsingCard.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ContentTreeList.vue
Apply several suggested improvements per @jtamiace's notes in #2414 in the Import from Channel modal.
- Added an `info` icon button that opens the content details overlay for content items (not topics)
- Clicking a content item's card opens the details overlay
- Remove the <a> tag link-style card title - also I made sure its the same font size as the cards on the channel list (18px)
Not mentioned in the issue:
- Fix misspelling `resourece -> resource` (noted to @radinamatic and she has updated it directly in Crowdin).
- I also removed some padding to make give everything a cleaner appearance (IMO) - happy to revert this.
**NOTE** I took the screenshots before fixing the fact that the info icon is showing on the topic - that is no longer the case.
BEFORE - Notice the extra whitespace on …
> Import from channel card interaction improvements

- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeValidator.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ResourcePanel.vue
- contentcuration/contentcuration/frontend/shared/utils/validation.js
Some validation fixes:
- The ResourcePanel (right sidebar) `license_description` was showing because logic didn't account for whether the selected license was `is_custom` or not.
- Some fields had a `!` they didn't need in their validation logic.
- Add check for `isExercise` on a question-related validator
- Use `isNodeComplete` rather than `node.complete` in the ContentNodeValidator component.
Fixes https://github.com/learningequality/studio/issues/2314
Fixes https://github.com/learningequality/studio/issues/2334
ResourcePanel:
Edit a node so that things are invalid and save the node, go back to the node listing page and select the node again to see that the proper error messages are shown and that there is a red `(!)` on the item. Try all validated fields `copyright_holder` `license` …
> Validation error errors | ResourcePanel & DetailsTabView

- package.json
- yarn.lock
So if you put `git+` in front of the URL to a package on Github that you want it will always check for and use the latest. 
- Fixes clipboard icon
- Will ensure latest KDS is in Studio until we pin it
> Ensure latest KDS

- contentcuration/contentcuration/frontend/channelEdit/__tests__/utils.spec.js
- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
- contentcuration/contentcuration/frontend/channelEdit/utils.js
- contentcuration/contentcuration/frontend/channelEdit/views/ResourcePanel.vue
This gets rid of a circular dependency chain, which was causing lots of extra warnings in the console.
> Get rid of circular dependency chain

- yarn.lock
In order to ensure we are pulling the latest KDS builds during development, I deleted the yarn.lock file and regenerated it.
That is - for sure 100% - the way to ensure you're pulling the latest from a Github branch. `rm yarn.lock && yarn` will do the trick.
@rtibbles This bumped a bunch of other stuff to, just figured it'd be good to get some eyes on it. Looks to me like a bunch of patch/minor version updates.
This will resolve issues with console spam regarding `z-index`.
> Regenerate yarn.lock, get latest KDS

- contentcuration/contentcuration/frontend/channelEdit/components/StudioTree/StudioTree.vue
- contentcuration/contentcuration/frontend/channelEdit/views/NodePanel.vue
- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.vue
- contentcuration/contentcuration/frontend/shared/mixins/draggable/container.js
- contentcuration/contentcuration/frontend/shared/mixins/draggable/handle.js
- contentcuration/contentcuration/frontend/shared/utils/helpers.js
- contentcuration/contentcuration/frontend/shared/utils/helpers.spec.js
- contentcuration/contentcuration/frontend/shared/views/ContextMenuCloak.vue
The `extendSlot` helper consolidates modifying `VNode`s from elements passed into a specified slot. It is used for our `Draggable*` components, which transparently wrap elements to add draggable functionality. This PR adds some tests for the `extendSlot` helper, and ensures that it behaves as expected. 
My main concern was ensuring we had some test coverage on the helper, and that it functioned as expected regardless of using scoped or unscoped slots. With unscoped slots, updates are now handled differently to protect against any confusing bugs or gotchas related to implementing components that use the helper. This is a achieved by utilizing a flag on the `VNodeData` to determine when we're inserting vs updating, and when updating the `VNode` it will force an update.
It _addresses_ …
> Add unit tests for extendSlot helper and make it more robust

- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/tests/viewsets/test_file.py
- contentcuration/contentcuration/viewsets/base.py
- contentcuration/contentcuration/viewsets/file.py
- contentcuration/contentcuration/viewsets/sync/endpoint.py
* #2340 accidentally removed permissions filtering for file objects
* This reinstates these, and adds tests for this behaviour
* Enhances file permissions to allow unclaimed uploaded files to be edited (required for the upload file workflow)
* Reduces the capabilities of the file endpoint so that all file object creation has to happen through upload_url requests
* Adds tests for no file creation through CRUD or sync, and adds handling for unsupported sync changes on the sync endpoint
> file permissions

- contentcuration/contentcuration/tests/test_exportchannel.py
- contentcuration/contentcuration/tests/testdata.py
- contentcuration/contentcuration/utils/publish.py
Kevin finally got around to making incomplete nodes not publish!
Also, this PR fixes false negatives in publishing tests that were caused by the way we constructed our test channel. Fortunately, switching to the channel fixture in `testdata` allowed us to remove this test data entirely, and removed the false negatives.
This is not a new item, but we don't update the counts precisely right during publish. If we have empty topics or, now, incomplete nodes, we still count them as "one" node in the progress update. This is not very noticeable because we set the progress to the right value at the end of the step, so I don't think it is worth addressing at this point in time. 
If you are looking to assign a reviewer, …
> Don't publish nodes that are incomplete.

- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
- contentcuration/contentcuration/frontend/shared/mixins/draggable/container.js
- contentcuration/contentcuration/frontend/shared/mixins/draggable/handle.js
- contentcuration/contentcuration/frontend/shared/views/ContextMenuCloak.vue
- contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/constants.js
- contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/submodule/getters.js
- contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/submodule/index.js
- contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/submodule/mutations.js
First, it looks like after I added Draggable to the `ContentNodeListItem` along with changes to the context menu, I lost the slot I added for the context menu so it was no longer showing. Also, there were a variety duplicate reference and reactivity issues with the Draggable code that this addresses.
> Misc fixes to draggable state and components, and context menu fix

- contentcuration/contentcuration/models.py
* Deleting nodes causes reordering of MPTT fields
* This adds an mptt field DB lock when deleting content nodes
> Add preemptive lock for node deletion.

- contentcuration/contentcuration/frontend/channelEdit/views/trash/TrashModal.vue
- contentcuration/contentcuration/frontend/channelEdit/views/trash/__tests__/trashModal.spec.js
Ensures that the channel's topics load when restoring from the trash, even if the user has refreshed the page.
Fixes #2307
Made sure a channel's contentnodes are loaded into the Vuex state upon navigating to the `TrashModal` component in cases where previously they hadn't been loaded.
> Ensure that topics load when restoring from trash

- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
Fixes [Upload files view should not have bottom bar](https://www.notion.so/learningequality/Upload-files-view-should-not-have-bottom-bar-7cbf9c58ae254665a0a8c9b2c085c004)
> Don't show bottom bar on file upload default view

- contentcuration/contentcuration/migrations/0121_auto_20200917_1912.py
- contentcuration/contentcuration/migrations/0122_assessment_id_index.py
- contentcuration/contentcuration/models.py
* Fixes a typo in index where `~modified` was used instead of `-modified`
* Fixes a typo in index migration where `contentnode` model was set instead of `assessmentitem`
* Neither of these affect the created migrations, but will cause Django to be confused in the future
> Fix typos in indexes and migrations.

- contentcuration/contentcuration/frontend/settings/pages/Account/index.vue
- contentcuration/contentcuration/frontend/settings/pages/Storage/RequestForm.vue
- contentcuration/contentcuration/frontend/settings/pages/__tests__/account.spec.js
- contentcuration/contentcuration/frontend/settings/vuex/index.js
- contentcuration/contentcuration/templates/settings.html
- contentcuration/contentcuration/views/settings.py
- contentcuration/contentcuration/viewsets/channel.py
Bootstraps user's editable channels onto settings pages for use under storage form public channel question and delete account section
Fixes https://github.com/learningequality/studio/issues/2468
> Added channels to settings pages for delete account and storage form sections

- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
- contentcuration/contentcuration/frontend/shared/views/draggable/DraggablePlaceholder.vue
Made draggable placeholder into a shared component and made it support RTL
Still need to add grouped item view
> Dragging placeholder component + RTL support

- contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemEditor/AssessmentItemEditor.vue
- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/image-upload/index.js
- contentcuration/contentcuration/tests/viewsets/test_assessmentitem.py
- contentcuration/contentcuration/tests/viewsets/test_contentnode.py
- contentcuration/contentcuration/viewsets/assessmentitem.py
- contentcuration/contentcuration/viewsets/contentnode.py
- jest_config/setup.js
* Updates the existing assessment item file association code to limit queries
* Adds tests to ensure file editing and removal
* Updates frontend image rendering logic to use storageUrl utility
* Fixes #2080
* This explicitly does not follow the same pattern as contentnode file handling
* I initially tried to do this in parallel to contentnode file management
* This was complex due to the fact we don't use assessment item FKs on the frontend
* And we can't generate assessment item PKs no the frontend because they are autoincrementing integers
* I then tried to do it as managed many to many keys on the assessment item
* This fixed the issues above with FKs
* However, it would have required a more complex structure on the frontend to encode the checksum and file format
* Without this, we …
> Associate uploaded exercise images with assessment items on save

- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
- contentcuration/contentcuration/frontend/channelEdit/components/StudioTree/StudioTree.vue
This PR makes the "options" and "open topic" icons always visible in the channel view, rather than having them become visible on hover. 
Addresses #2400 (Do not hide context menu icons on listed content nodes)
I edited the CSS to remove the hover state in the Content Node List Item and the Studio Tree.
Based on the files that I changed, I am not sure if this might affect the visibility of icons in other views. The Notion discussions indicates that we are trying to ensure that all of the icons are visible, so I think if does affect more files than just this view, that would actually be a positive.
> make options icon always visible in channel view

- contentcuration/contentcuration/frontend/channelEdit/components/edit/SavingIndicator.vue
This PR updates the argument that is passed to checkSavingProgress() in the SavingIndicator, so that it correctly resolves and displays when data is updated in the questions tab. 
Addresses #2419 
I updated the argument that was passed to checkSavingProgress() that included both the contentnode and the assessment_id, per the AssessmentItem in resources.js and some help from @jayoshih.
> Update arguments passed to checkSavingProgress so saving indicator shows

- contentcuration/contentcuration/utils/db_tools.py
At some point, we've started using `type` field instead of `mastery_model` to save the mastery model type on exercise content nodes. However, the obsolete `mastery_mode` was still in use in the development server setup script, which caused error messages to be displayed for the sample exercise in the channel editor and in the edit modal.
> Update obsolete mastery model type field in the development server setup

- contentcuration/contentcuration/frontend/administration/pages/Users/UserDetails.vue
- contentcuration/contentcuration/frontend/shared/constants.js
- contentcuration/contentcuration/frontend/shared/vuex/policies/index.js
- contentcuration/contentcuration/frontend/shared/vuex/policies/index.spec.js
Fixes #2508 and #2317.
Firefox automatically converts dates to the local timezone. This isn't a problem when we work with Date objects. However when we send data to the backend for saving, we lose this timezone data and and the date saved will not be equal to the policy modal date created in `constants.js`.
This change makes sure we use UTC dates during the conversion. We also change the dates for the policies in `constants.js` by standardizing on parsing strings when creating these dates.
> Stop repeating policy modals on Firefox

- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.vue
Fixes issue where hierarchy drawer was appearing above overlay
> Fixed z-index on hierarchy panel

- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/BrowsingCard.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ChannelInfoCard.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ChannelList.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ContentTreeList.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ImportFromChannelsModal.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchFilters.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchOrBrowseWindow.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchResultsList.vue
- contentcuration/contentcuration/frontend/shared/mixins.js
Fixes https://github.com/learningequality/studio/issues/2506
Fixes https://github.com/learningequality/studio/issues/2512
Fixes https://github.com/learningequality/studio/issues/2507
Fixes https://github.com/learningequality/studio/issues/2577
**Browse resources -> Browse channels**
**Browse -> Search**
**Search-> Browse**
**Review -> Browse**
**Review -> Search**
> Retain channel list type between browsing/reviewing/searching in import modal

- contentcuration/contentcuration/utils/google_drive.py
- requirements.in
- requirements.txt
We now use google's application default credentials mechanism for authenticating with google sheets. This allows us to be more flexible in terms of how we authenticate in production and local testing.
Local testing can now use the `GOOGLE_APPLICATION_CREDENTIALS` env var to point to a service account json file, or can use `gcloud auth activate-service-account` to activate the service account login once and not have to worry about the service account key location.
> Use GOOGLE_APPLICATION_CREDENTIALS as the auth mechanism for connecting to sheets

- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchResultsList.vue
Looks like the duplicate calls has been fixed with debouncing, so it's okay to add fetching results on mounted back to the search results list
Fixes https://github.com/learningequality/studio/issues/2593
> Load search results on first entry

- contentcuration/contentcuration/templates/base.html
Ensure JS code involving sentry requests are the last thing to execute in the tag script to avoid blockers break the code in the script
Addresses #2549 
Blocking sentry with adblock or other tools (PiHole in the reported issue),  does not allow the user create a channel, because var user_preferences is never parsed when `Sentry.setUser` fails
With this pr, all the js code is parsed before executing the  `Sentry.setUser` call
> move sentry request to the end of the script tag

- contentcuration/contentcuration/frontend/shared/constants.js
PR adjusts the dates for terms of service and privacy policy.
Addresses #2558 
(Dates are adjusted to May 25, 2018 and December 10, 2020, but I'm in PST, so dates are reflective of my timezone)
OR
Changed the dates in `constants.js`
As seen in the screenshots, the dates are adjusted to May 25, 2018 and December 10, 2020, but I'm in PST, so dates are reflective of my timezone (PST). Is this an issue? …
> update terms of service and privacy policy dates

- contentcuration/contentcuration/utils/publish.py
Fixes issue when publishing exercises containing graphie images on Python 3 caused by the switch to Unicode by default.
Note that this is a blind fix, I just ran the unit tests but as it is a minimal change and can be quickly verified by publishing an exercise with a graphie file, I figured I'd go ahead and make the PR.
Addresses #2571 #2545 
- Richard …
> Encode delimiter as bytes since we are dealing with a bytestring

- contentcuration/contentcuration/frontend/shared/data/resources.js
This is a reimplementation of a fix @rtibbles made that somehow got lost.  It makes sure we avoid checking for new updates if there are pending changes in the changes table that still need to be pushed.
This might address quite a few syncing related bugs!
> Only request updates if existing changes have been pushed

- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/BrowsingCard.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/importFromChannels/actions.js
- contentcuration/search/viewsets/contentnode.py
* Changes the default page_size in the search frontend request to sync it with the backend params
* When searching in tags, the number of possible results is limited to 250. It's not limited when searching in description or title
* Multiple fields, annotations and grouping from `ContentNodeViewSet` have been removed as they proved to be unneeded for the search results.
* Paginate first, then do the annotations (drastically reduce the queries from minutes to a few seconds)
* Cache count results for five minutes, so browsing between pages is much faster
After making measurements:
- Worst cases are for searches on very generic words as 'maths', they take around 17 seconds for the first page of results and 3 seconds for the next pages . Before this PR it took more than 20 minutes
Relates …
> Annotate after paginate (and some more stuff)

- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeEditListItem.vue
- contentcuration/contentcuration/frontend/channelEdit/components/StudioTree/StudioTree.vue
- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
- contentcuration/contentcuration/frontend/shared/mixins/draggable/container.js
- contentcuration/contentcuration/frontend/shared/mixins/draggable/utils.js
- contentcuration/contentcuration/frontend/shared/views/draggable/DraggablePlaceholder.vue
- contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/__tests__/utils.spec.js
- contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/actions.js
- contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/constants.js
- contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/getters.js
- contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/index.js
- contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/mutations.js
- contentcuration/contentcuration/frontend/shared/vuex/draggablePlugin/module/utils.js
Addresses a variety of issues with drag and drop issues.
https://github.com/learningequality/studio/issues/2552
https://github.com/learningequality/studio/issues/2570
https://github.com/learningequality/studio/issues/2562
https://github.com/learningequality/studio/issues/2484
- Further enhances coordination of the drag event's drop effect and effect allowed to ensure proper handling upon drop
- Prevents dropping a topic into itself in the hierarchy tree
- Adds a minimum drag time of 100ms to avoid accidental drag and drops
- Emits deselection when content node list item is destroyed by dragging to new location
- Removes CSS transition from floating placeholder, which speeds up its movement
> Disallow dropping nodes into themselves, ignore drag and drops less than 100ms, and deselect after dragging out

- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.vue
Hides the "updates banner" for users who only have "view-only" access to that channel; only users who are editors are able to see the "updates banner".
Addresses #2538 
Screenshot for user with editing privileges:
Screenshot for user with view-only privileges:
Added `canManage` getter to the component, and added that to the v-if directive in the template.
> makes update banner hidden for view-only channels

- contentcuration/contentcuration/frontend/channelList/vuex/channelSet/__tests__/module.spec.js
- contentcuration/contentcuration/frontend/channelList/vuex/channelSet/actions.js
- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/viewsets/channelset.py
This PR filters the ChannelSetList (aka "Collections") so that only the current user's Collections are displayed.
Addresses #2542 - Admins can see all Channelsets/Collections, even if they do not have edit access to them
I created a FilterSet on the backend for ChannelSetList and passed a parameter in the front end .where() query and updated tests for this change.
> Filter channelsetlist by user

- contentcuration/contentcuration/frontend/shared/data/serverSync.js
We squash changes a couple times before them to the sync endpoint, but the function that does the merging wasn't always getting changes passed in the right order.
I'm optimistic that this will fix issue [#2572](https://github.com/learningequality/studio/issues/2572), and it might help fix quite a few other issues too.
> Make sure changes are merged in order

- contentcuration/contentcuration/frontend/shared/data/serverSync.js
In `syncChanges`, make sure changes are ordered by `rev` before calling `last()` to get the most recent change.
See #2629 for context.
> Correctly order changes when looking for the last change

- contentcuration/search/viewsets/contentnode.py
After #2511 was merged, the column names that were returned by the endpoint were not clear in the code.
With this small change the number of delivered fields is reduced and they are explicitely stated.
Use the search feature "Import from other channels" after the ADD dropdown button available when editing a channel
> Being more semantic when annotate after paginate is used

- contentcuration/contentcuration/frontend/shared/data/mergeChanges.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
Following #2629 and #2630, this PR further ensures that changes are getting merged in order, at least for changes that have a `rev`.  If they aren't in order, it logs an error, but doesn't currently do anything to prevent stale changes from overriding new ones.
- If possible, it could be nice to gracefully handle these errors by passing on changes unmerged, or by sorting them and starting over.
- This needs tests.
> Ensure changes are merged in order, log an error if not.

- Makefile
- contentcuration/contentcuration/context_processors.py
- contentcuration/contentcuration/settings.py
- contentcuration/contentcuration/templates/base.html
Imports and modifies logic here: https://github.com/learningequality/kolibri/blob/release-v0.14.x/kolibri/core/kolibri_plugin.py#L36 and inserts it into the context processor which exposes a dict w/ `I18N_URLS` key returning the properly generated and minified JS code that sets `window.Urls` to the currently used i18n lang code.
Also helps ensure that browser language code is respected. 
Fixes https://github.com/learningequality/studio/issues/2627
Set your browser's language to a non-English language of your choice.
Navigate the site's sections:
- Sign in page
- Channel's listings
- Channel edit
- Settings
- Profile
You should never have your URL default back to `en` as you navigate.
> Ensure window.Urls has correct language code & browser lang is respected

- contentcuration/contentcuration/frontend/shared/vuex/snackbar/index.js
Addressing issues noted in #2338 where locks would be generated and properly instantiated with an `expiry` of `0` - but - in some cases the lock's expiry would not be set to a proper time in the future. If `expiry` is always 0 then the lock is forever locked.
Fixes #2338 
However - it doesn't apply the specific changes noted there. Per @bjester the issue lied in unresolved snackbar promises causing the bug occurring.
The following steps should first be done on the latest `develop` branch to replicate it please. 
Then - repeat the following steps again after checking out this branch.
- Clear your IndexedDB altogether so you are starting fresh.
- Open Dev Tools -> Application -> IndexedDB -> KolibriStudio
> In the DevTools - you'll see at the top of the table of entries a "Refresh" icon - …
> withChangeTracker bugfix - call hideCallback in snackbar if it exists

- contentcuration/contentcuration/frontend/administration/mixins.js
1. Adds a missing line in `administration/mixins.js` to update the `page_size` query param when the two-way binded `pagination` object and it's `rowsPerPage` field change.
1. Removes `rowsPerPage`, and `totalItems` from being added to the URL query paramas, since they are not necessary
1. Removes `sortBy` and `descending` query params from URL when they are `null`
Fixes #2362
> Update ‘page_size’ query param when it is updated on the the Administration User/Channel tables

- contentcuration/contentcuration/frontend/shared/data/__tests__/mergeChanges.spec.js
- contentcuration/contentcuration/frontend/shared/data/mergeChanges.js
- contentcuration/contentcuration/frontend/shared/data/serverSync.js
This PR fixes two sync related issues:
- Sometimes syncing was getting kicked off before changes had finished getting added to the changes table
- The function that merges updates was not passing along the latest state
It also adds some basic tests for the merging functionality.
This is a followup on #2629, #2630 and #2638.
This should fix a number of assessment item related bugs, and possibly other bugs where updates were happening somewhat rapidly in succession.
Special thanks to @rtibbles for helping me see just what was going on and teaching me all about the sync code!
> Use the latest state when merging and handling changes before syncing

- contentcuration/contentcuration/db/models/manager.py
* Simplifies the copying of associated objects (files, assessment items, tags)
* Uses the generated dict of source_id to copy_id as the source of truth about which associated objects to copy
* Avoids an issue that resulted from previous dependence on a queryset generated from MPTT's `get_descendants` method that occured during concurrent copying when the lft and rght values for the descendants queries were no longer current
Fixes #2556
Copy operation after (see issue for before):
- Have two topics with content in them side by side
- Select both the topics on the main channel edit page
- Press the 'Make a copy' button
- Observe that both the topics complete their copy operation
> Fix concurrent copying

- contentcuration/contentcuration/frontend/channelEdit/components/ResourcePanel.vue
This makes `?tab=details` and `?tab=questions` valid query parameters when viewing the details of an Exercise node. This lets the change between the two tabs be tracked in the browser history (including more convenient back/forward browser button behavior).
Fixes #2399
video of me browsing the topic, sometimes using the UI buttons, sometimes using the mouse forward/backward buttons.
From `ResourcePanel.vue`, I removed the `tab` from `data` and made it a more complex computed prop that would
1. Always return `details` if the node is not an exercise
1. Return the value of `?tab` if it is an exercise
1. Synchronize the value of `?tab` if `this.tab` changes (i.e. in the mounted/watch hooks).
1. Convert the `VTabs` to use `router-links`, which link directly to URLs with …
> Add `tab=questions|details` query param to Exercise Detail URLs

- contentcuration/contentcuration/utils/pagination.py
- contentcuration/contentcuration/viewsets/channel.py
- contentcuration/contentcuration/viewsets/user.py
* Does a correct sorting of the queryset if a mapped field is used in the Admin Channel and users section
* Deal with the erratic behaviour of the `ordering` parameter provided by the `request` object: sometimes is "`_undefined_`" , others replaces `sortBy` and others repeates `sortBy` value
Closes #2544 
Play with the admin section of Studio, sorting columns both in the Channels and Users sections
#
> Solve problems when sorting by mapped fields in the admin tables

- contentcuration/contentcuration/frontend/administration/vuex/channelAdmin/actions.js
- contentcuration/contentcuration/frontend/administration/vuex/userAdmin/actions.js
- contentcuration/contentcuration/utils/pagination.py
- contentcuration/contentcuration/viewsets/channel.py
- contentcuration/contentcuration/viewsets/user.py
This PR removes the 'ordering' param from being set in the front end, and the backend code that filters this param, because it is not used for the tables in `/administration`. It duplicates information that already exists in `sortBy` and `descending`.
Addresses issues discussed in [PR 2617](https://github.com/learningequality/studio/pull/2617)
Before - information duplicated: 
After - ordering not passed in URL params:
I did not see any issues with removing this and I find both the front end and the back end seem to be working as expected with manual testing. It is possible that there are issues with this approach that I did not foresee, so any feedback, especially regarding the backend, would be appreciate.
> Remove order parameter admin view

- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/frontend/shared/vuex/channel/__tests__/module.spec.js
- contentcuration/contentcuration/frontend/shared/vuex/channel/actions.js
Fixes https://github.com/learningequality/studio/issues/2622
Calls channel detail endpoint directly to make sure changes get sent before page navigation
> Make sure channel deletion endpoint gets called

- contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/Channel.vue
- contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNode.vue
- contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/index.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/clipboard/actions.js
- contentcuration/contentcuration/frontend/shared/views/LazyListGroup.vue
- Fixes conditionals hiding move button on clipboard so it shows when current channel is editable
- Fixes channel title overflow on clipboard
- Other tweaks and fixes
https://github.com/learningequality/studio/issues/2564
| --- | --- |
| ![Screenshot from 2020-12-08 15-33-19](https://user-images.githubusercontent.com/819838/101554263-216ce280-396b-11eb-91d4-2160574ae174.png) | ![Screenshot from 2020-12-08 15-33-47](https://user-images.githubusercontent.com/819838/101554278-26ca2d00-396b-11eb-939c-a0d0ca22d54f.png) |
> Fix clipboard move action visibility

- contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNodeOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/components/ResourcePanel.vue
- contentcuration/contentcuration/frontend/shared/views/ActionLink.vue
- contentcuration/contentcuration/viewsets/contentnode.py
- Fixes imported channel name by coalescing with current channel name
- Fixes broken link to original location for imported topics
- Fixes broken link to clipboard original location
- Truncates external link text to original location in node details (see screenshots)
- Adds title to external link and `notranslate` class
https://github.com/learningequality/studio/issues/2659
https://github.com/learningequality/studio/issues/2660
https://github.com/learningequality/studio/issues/2589
| Before | After coalesce fix | After truncate |
| --- | --- | --- |
| ![Screenshot from 2020-12-09 14-35-48](https://user-images.githubusercontent.com/819838/101705014-dde1a980-3a3a-11eb-8971-b2162292dc7e.png) | ![Screenshot from 2020-12-09 14-37-59](https://user-images.githubusercontent.com/819838/101705024-e3 …
> Fixes external link issues and sometimes incorrect imported channel name 

- contentcuration/contentcuration/frontend/channelEdit/router.js
- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
- contentcuration/contentcuration/frontend/channelList/router.js
- contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelItem.vue
- contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
- contentcuration/contentcuration/frontend/shared/views/channel/__tests__/channelModal.spec.js
Updates routing to use a `/:tab` value that can be either 'edit' or 'share' rather than the query `sharing=true` in the share and detail modal. Also makes sure the tab indicator aligns with 'share' correctly on open. Replaces [PR2547](https://github.com/learningequality/studio/pull/2547).
Addresses #2004 
Option 1:
Option 2:
> New channel modal toggle tabs

- contentcuration/contentcuration/frontend/channelEdit/components/move/MoveModal.vue
- contentcuration/contentcuration/frontend/channelEdit/views/trash/TrashModal.vue
1. Passes `TrashModal.selected` into its child `MoveModal`'s `moveNodeIds` prop to get the proper header in that latter modal.
1. Adds a `moveFromTrash` prop to `MoveModal` so it begins at the channel root node (was starting at some place related to the route's `nodeId`, so would either be invalid move destination or otherwise unpredictable).
Fixes #2559
**After**
Notice that the message before pressing "Restore" is consistent with the header
From selection screen:
From move modal:
1. Move some stuff to the trash
1. Restore from trash
1. Confirm correct header and navigation experience within Move Modal
> Pass selected trash nodes into `MoveModal` `moveNodeIds` prop

- contentcuration/contentcuration/frontend/shared/data/__tests__/mergeChanges.spec.js
- contentcuration/contentcuration/frontend/shared/data/mergeChanges.js
- contentcuration/contentcuration/frontend/shared/data/serverSync.js
This fixes an issue where some changes weren't getting added to the changes table, which meant that they were never getting synced. With this PR:
- `rev` must be set for changes passed to `mergeAllChanges`, and the changes must be in order, otherwise errors will be thrown
- `rev` will be filtered out on changes committed to the changes table
I also organized the unit tests for `mergeAllChanges`, and added some test cases to make sure `mergeAllChanges` throws exceptions when confronted with disordered changes or changes with no `rev` set.
When the changes passed to it didn't have `rev` set, the `mergeAllChanges` function was returning a squashed change with `rev: undefined`, which meant it couldn't be inserted into the changes table, which has `rev` as an auto-incrementing primary key. …
> Ensure `rev` is only set on changes when it needs to be

- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
Adds an extra function to the callback of `removeNode(s)` in `ContentNodeOptions` and `CurrentTopicView` to do an appropriate navigation to a "higher" position in the hierarchy if the user removes the currently-viewed topic, or an ancestor of that topic.
Fixes #2581 (3 different scenarios)
Test the three scenarios in #2581. The main thing is that if you are viewing a topic or a resource detail panel, then the UI cleans itself up after removing that topic/resource from the tree.
Test the removal operation on all of these widgets
Don't forget the bulk deletion widget
> Navigate out of active views when deleting topics or resources

- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.vue
This adds a guard to the `TreeView`'s `created` hook to prevent it (along with the `NodePanel`s `created` hook) from doing two types of overfetching:
1. At a channel's root node, `TreeView` and `NodePanel` will collectively request the root node twice
1. At a channels' non-root node `Treeview` and `NodePanel` will collectively request the root node once, and the current node twice
Here I'm using a shorthand of "request the node" to mean "make a call to `/api/contentnode` with the query param of `parent=node`".
After this fix:
1. At a channel's root node, `TreeView` will not request the root node. And `NodePanel` will request the root node once.
1. At a channels' non-root node `Treeview` will request the root node once. And `NodePanel` will request the current node once.
Fixes #2316 …
> Add guard to `TreeView` `created` hook, to prevent data over-fetching

- contentcuration/contentcuration/frontend/shared/i18n/index.js
- contentcuration/contentcuration/frontend/shared/views/files/Thumbnail.vue
Fixes https://github.com/learningequality/studio/issues/2631
> Make sure $isRTL is set properly + thumbnail rtl fix

- contentcuration/search/viewsets/contentnode.py
An annotated field, `original_channel_name`, had been incorrectly removed for the ContentNode search as it seemed useless, but it happened to be used sometimes
Closes: #2672
When editing a channel, if a content node being the root of the channel is hit by the search , there should not be error retrieving the channel name instead of the node title.
As the annotation is added after paginating, perfomance impact should be minimal.
> Add original_channel_name annotation in ContentNode search viewset

- contentcuration/contentcuration/tests/viewsets/test_assessmentitem.py
- contentcuration/contentcuration/viewsets/assessmentitem.py
- contentcuration/contentcuration/viewsets/base.py
If the front-end tries to update an assessment item that's missing from the back-end, this PR makes sure that a useful error is returned, instead of a confusing one.
This us a followup on https://github.com/learningequality/studio/pull/2655.
This will make https://github.com/learningequality/studio/issues/2679 and https://github.com/learningequality/studio/issues/2603 less severe by adding proper error handling for attempts to update missing items.
- Added a unit test for attempts to update missing assessment items
- Stopped `remove_id_values` from mutating changes unexpectedly
- Used `id_value_lookup` method for consistent keying of assessment items
- Changed `id_value_lookup` to use a tuple instead of a string, for simpler conversion from front-end `change["key"]` array representation. …
> Misc fixes to serializers' handling of attempted updates to missing content

- contentcuration/contentcuration/frontend/administration/pages/Channels/ChannelDetails.vue
- contentcuration/contentcuration/frontend/administration/pages/Channels/ChannelTable.vue
- contentcuration/contentcuration/frontend/administration/pages/Users/UserDetails.vue
- contentcuration/contentcuration/frontend/administration/pages/Users/UserTable.vue
- contentcuration/contentcuration/frontend/settings/pages/SettingsIndex.vue
1. Uses the `updateTabTitle` mixin to update `window.title` (aka "tab title") for pages under the Administration and Settings SPA. The naming convention used is that suggested in https://github.com/learningequality/studio/issues/2537#issuecomment-742825262. E.g. something of the form `Detail Page - Main Page - SPA name - Kolibri Studio`.
1. Fixed a bug for `UserDetail` page where the user's full name would not display if going directly to the URL
Part of #2537
GIFs show me navigating through the Settings and Administration pages (view the tab title)
I continue (from #2681) to wrap `updateTabTitle` in a component method called `updateTitleForPage` that is called late in the component lifecycle to update `window.title`
The strategy I used in the …
> Display informative "tab titles" for Administration and Settings SPAs

- contentcuration/contentcuration/frontend/channelList/router.js
- contentcuration/contentcuration/frontend/channelList/views/ChannelListIndex.vue
- contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSetModal.vue
- contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
- contentcuration/contentcuration/frontend/shared/views/files/Thumbnail.vue
Uses the `updateTabTitle` function to update the tab titles on pages in the `channelList` SPA.
This is accomplished in various ways depending on the page, so basically:
1. We mirror the tab name (e.g. "Starred", "Content catalog") for the highest-level pages
1. We put the channel or channelset name for detail-level pages.
This is one step towards #2537. Later PRs will fix the issue in other SPAs.
- Go to every possible page in the `channelList` SPA. You should see a tab title that is not just "Kolibri Studio"
- Jordan jayoshih …
> Update `window.title` value for pages in `channelList` SPA

- contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
* When closing the new channel modal, we would try to soft delete the channel
* We had not committed this channel to the backend, so this would fail
* Hence you could not close the modal
* This fixes that by just removing it from the Vuex state where it has been stored
Fixes #2676
- Click new channel
- Type something in the title
- Press the 'X' to leave
- Press 'exit anyway'
- Confirm the channel does not appear in 'my channels'
> Don't try to delete a channel that has not been committed to the DB yet.

- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/views/nodes.py
- contentcuration/contentcuration/viewsets/common.py
Optimize the database queries to create an object with the channel details
Closes #2272 
_(Caching of channels details disabled in all cases)_
Before (after filtering the data catalog to see channels in Spanish and excluding KA):
After (with the same channels):
Before, including KA: interrupted after waiting for more than 18 minutes
After including KA:
- Modify the function parameters to include available information (channel id) instead of calculating it again 
- Modifying and optimizing every query used to fetch the tree node data
- using cte when it improves the times
- inserting all what is possible in annotations to reduce the number of queries. 
- sorting is removed whenever it's possible
- retrieved fileds are reduced to be only those that are used in the code.
Open the content …
> Multiple changes in node details calculation

- contentcuration/contentcuration/db/models/manager.py
- contentcuration/contentcuration/tests/test_contentnodes.py
Copying was trying to use the node which was being copied as the `target` - which ought to have been the `parent` of the node being copied (because they should end up direct children of the same parent).
The position was `right` which caused issues in `resolveParent()` where it resolves the `target` immediately if the position is `last-child` or `first-child`. I changed the calls to use the default `last-child` position and to pass the node's parent ID as the `target` - which results in nodes being copied successfully into the same topic as the node they're a copy of.
Fixes #2686 
- Copy a Topic folder. It should appear in a "loading" state at the bottom of the list of content nodes you are viewing. 
- Once the copy is completed (not loading anymore) - navigate to the topic node you …
> Copy to parent of copied node with last-child position

- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
- contentcuration/contentcuration/frontend/channelEdit/components/edit/__tests__/editModal.spec.js
- contentcuration/contentcuration/frontend/channelEdit/getters.js
- contentcuration/contentcuration/frontend/channelEdit/pages/AddNextStepsPage.vue
- contentcuration/contentcuration/frontend/channelEdit/pages/AddPreviousStepsPage.vue
- contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreePage/index.spec.js
- contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreePage/index.vue
- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ImportFromChannelsModal.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ReviewSelectionsPage.vue
- contentcuration/contentcuration/frontend/channelEdit/views/trash/TrashModal.vue
- contentcuration/contentcuration/frontend/shared/views/errors/PageNotFoundError.vue
Adds tab titles to all pages in the Channel Edit SPA. Tries to follow this pattern
`Page/Node Title - Channel Name - Kolibri Studio`.
Fixes #2537 
Visit all the pages in Channel Edit SPA, the title should update with an informative message
> Update tab titles for pages in `channelEdit` SPA

- contentcuration/contentcuration/settings.py
- contentcuration/contentcuration/utils/gcs_storage.py
- k8s/helm-deploy.sh
- k8s/templates/studio-deployment.yaml
- k8s/templates/studio-secrets.yaml
- k8s/values.yaml
This re-adds GCS keys to use for interacting with GCS. Fixes #2703.
Previously we depended on GCP's Application Default Credentials (ADC) to authenticate to GCP APIs. This is simpler for the majority of cases and makes administration simpler. However for signing we need access to an actual keyfile.
This adds a change where any GCS interaction reads from a keyfile specified by an env var, if defined. Falls back to ADC if the env var isn't defined.
> Re add gcs key for signing

- cloudbuild-production.yaml
I forgot to add the new DB location arg for helm-deploy.sh in cloudbuild-production.yaml, so new deploys aren't working. This adds that back.
> add missing arg to helm-deploy.sh in cloudbuild.yaml

- contentcuration/contentcuration/frontend/channelEdit/components/AssessmentItemToolbar.vue
- contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNode.vue
- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeContextMenu.vue
- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeEditListItem.vue
- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
- contentcuration/contentcuration/frontend/channelEdit/components/StudioTree/StudioTree.vue
- contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreePage/index.vue
- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchFilters.vue
- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/index.vue
- contentcuration/contentcuration/frontend/channelList/views/Channel/CatalogList.vue
- contentcuration/contentcuration/frontend/channelList/views/Channel/ChannelItem.vue
- contentcuration/contentcuration/frontend/channelList/views/ChannelSet/ChannelSetItem.vue
- contentcuration/contentcuration/frontend/shared/app.js
- contentcuration/contentcuration/frontend/shared/views/AppBar.vue
- contentcuration/contentcuration/frontend/shared/views/Breadcrumbs.vue
- contentcuration/contentcuration/frontend/shared/views/ContextMenu.vue
- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/plugins/image-upload/MarkdownImageField.vue
- contentcuration/contentcuration/frontend/shared/views/Menu.vue
- contentcuration/contentcuration/frontend/shared/views/ResizableNavigationDrawer.vue
- contentcuration/contentcuration/frontend/shared/views/channel/ChannelDetailsModal.vue
- contentcuration/contentcuration/frontend/shared/views/channel/ChannelSharingTable.vue
- contentcuration/contentcuration/frontend/shared/views/files/Thumbnail.vue
Fixes https://github.com/learningequality/studio/issues/1836
As for the other items described in the issue:
- I was unable to reproduce the exercise answers overlapping, so I opened [an issue](https://github.com/learningequality/studio/issues/2706) so we can keep an eye on it
- I opened [a separate issue](https://github.com/learningequality/studio/issues/2705) for the pdf numbers as it seems like it might be tricky to resolve soon
- It looks like Firefox automatically localizes the numbers, so I'm not sure if there's anything we can do about it on Chrome. Opened [an issue](https://github.com/learningequality/studio/issues/2707) for it anyways just in case
> Fixed menu and thumbnail icon alignment

- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/ImportFromChannelsModal.vue
- contentcuration/contentcuration/frontend/channelEdit/views/ImportFromChannels/SearchOrBrowseWindow.vue
1. Fix issue where selections would be cleared when going from Search to Browse
2. Clear selections when going backwards from SearchOrBrowsePage to TreeView
3. Clear selections when going forward from ReviewSelectionsPage to TreeView
Fixes #2573 …
> In "Import from channels" workflow, clear selections when exiting

- contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/ContentNodeOptions.vue
Fixes the clipboard item's context menu action for moving nodes. The action was not using the node's context for determining what nodes to move. In this scenario, we also want to ignore the current selection state, for which there was existing support for.
Resolves https://github.com/learningequality/studio/issues/2721
There are a couple other unresolved issues I will look into:
- The move modal doesn't show accurate topic and resource amounts when moving from the clipboard
- The context menu is left open after move
> Pass appropriate options to move

- contentcuration/contentcuration/viewsets/file.py
When I upload new files, it isn't updating the user storage because the serializer update code doesn't call the File.save() method. This just calculates on the update function
> Make sure we recalculate user storage on updates

- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/tasks.py
- contentcuration/contentcuration/viewsets/contentnode.py
Long running sync operations and deadlocks seem to be occurring in a small number of situations, and seem to be self reinforcing.
To deal with this, move operations are put back into an async task, with some limited handling for error to revert the front end state.
Fixes #2739 
Fixes #2740
To test, move a node. Verify that it is moved and that the move persists after refresh. Further, confirm that the tasks returned from the tasks API does not contain a residual move task afterwards.
> Reinstates move as an async task

- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeListItem/index.vue
- contentcuration/contentcuration/frontend/channelEdit/views/progress/TaskProgress.vue
* Deletes copying tasks when they are complete
* Doesn't show determinate loader until non-zero progress is registered
Fixes #2709
- Copy content
- Verify that the progress loader doesn't appear until after some progress has been achieved
- Verify that the task gets deleted after completion
> Copy task tweaks

- contentcuration/contentcuration/frontend/settings/pages/Storage/RequestForm.vue
- contentcuration/contentcuration/frontend/shared/views/form/CountryField.vue
- contentcuration/contentcuration/frontend/shared/views/form/MultiSelect.vue
- contentcuration/contentcuration/frontend/shared/views/form/__tests__/countryField.spec.js
Just needed to register the language data. Also fixed the styling so it's not the only box-styled textbox under request storage
Fixes https://github.com/learningequality/studio/issues/2723
> Fixed French translations on CountryField

- contentcuration/contentcuration/frontend/channelEdit/components/publish/PublishModal.vue
- contentcuration/contentcuration/frontend/shared/app.js
1. Run sync before publishing a channel to ensure that all updates are included
2. One follow-up commit to address[ this comment from a previous sync PR](https://github.com/learningequality/studio/pull/2699#discussion_r555926270)
Closes #2536
> Run sync before publishing a channel

- contentcuration/contentcuration/tests/test_contentnodes.py
Adds a test to ensure that null complete is a valid value on content nodes
> Add test to ensure that nodes can be saved with null complete.

- contentcuration/contentcuration/tests/test_storage_common.py
- contentcuration/contentcuration/utils/mime.types
- contentcuration/contentcuration/utils/storage_common.py
Attempts to properly set mime types for GCS upload
Fixes #2553
> Mime types

- package.json
Fixes CORS issues with file upload failing locally.
> Add localhost to minio allowed origins

- k8s/templates/studio-deployment.yaml
- k8s/values.yaml
- Ensure we have 5 replicas. A temporary hack to make sure every new deployment doesn't scale down the number of replicas to 1. Later one we should convince helm instead to not scale down the number of replicas when set manually.
- Add in NodeAffinity to workers that ensures they run on nodes that have full GCP access scope. Otherwise they can't access GCS.
> Tweaks to the helm deployment

- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/tasks.py
- contentcuration/contentcuration/viewsets/contentnode.py
Makes node deletion an async task
To Test:
* Move a node to trash
* Permanently delete the node from trash
* Verify that the node stays deleted after refresh
* Verify that no task remains in the task endpoint query once the deletion is complete
> Make node deletion an async task.

- contentcuration/contentcuration/frontend/channelEdit/components/edit/DetailsTabView.vue
- Fixes an issue that I found today where selecting either Author, Provider, or Aggregator from a dropdown did not trigger a change to the value, so it wouldn't be saved.
- Allows editing of tags when editing multiple nodes @jayoshih 
Basically the same fix from @nucleogenesis in PR https://github.com/learningequality/studio/pull/2358
> Edit modal fixes for dropdown fields and enabling tag edits for multiple nodes

- contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
Make sure channel validation gets triggered so it's clear what the error icon means if a language is missing
Fixes https://github.com/learningequality/studio/issues/2657
> Validate channel modal automatically on existing channels

- contentcuration/contentcuration/frontend/channelEdit/components/ContentNodeOptions.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
Addresses #2565 
Before: 
After:
> remove autofilled title value from contentNode

- contentcuration/contentcuration/management/commands/mark_incomplete.py
Makes updates to the mark incomplete command to separate out different checks
Adds order_bys liberally to reduce scanning
> Separate out different categories of incomplete.

- contentcuration/contentcuration/tests/test_exportchannel.py
- contentcuration/contentcuration/utils/publish.py
Queries task model to see if there are any blocking tasks we need to wait for
> Added checks for existing long-running tasks on publish

- k8s/values.yaml
1 worker in production is not enough, and I don't want to be manually setting the scale every time we deploy :) so set the default worker scale to 5 for now until I figure out how to tell Helm not to update the replica count.
> Set the default number of worker pods to 5

- contentcuration/contentcuration/templates/base.html
Disables the PWA manifest to avoid an issue with PWA rendering on Android.
> Disable PWA manifest

- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
- contentcuration/contentcuration/frontend/shared/views/MasteryDropdown.vue
Fixes https://github.com/learningequality/studio/issues/2796 and [M/N labels disappearing issue](https://www.notion.so/learningequality/M-of-N-field-label-texts-disappeared-a20dfbd293064b4585f1cfc5bc15a0e0)
> Don't overwrite extra_fields data on updateContentNode

- contentcuration/contentcuration/tasks_test.py
- contentcuration/contentcuration/tests/test_asynctask.py
- contentcuration/contentcuration/utils/celery_signals.py
Adds tests to replicate InterfaceError behaviour.
Adds fixes to ensure that connection is not expired during and after task execution
Fixes #2849
> Ensure that dropped connections do not disrupt task execution or signal handling.

- contentcuration/contentcuration/tests/viewsets/test_channel.py
- contentcuration/contentcuration/viewsets/channel.py
This PR creates a ThumbnailEncoding serializer so that the encoding fields, which are nested, can be managed on the backend.
Addresses #2774
> Create Thumbnail Encoding Serializer to accept nested values

- contentcuration/contentcuration/db/models/manager.py
- contentcuration/contentcuration/tests/db/models/test_manager.py
Adds a defensive check to `mptt_refresh` when attempting to set refreshed MPTT values pulled from the DB.
Resolves: https://github.com/learningequality/studio/issues/2824
- Added test for this scenario [`db/models/test_manager.py`](https://github.com/bjester/studio/blob/mptt-refresh/contentcuration/contentcuration/tests/db/models/test_manager.py)
> Add defensive check for node while refreshing mptt values

- contentcuration/contentcuration/frontend/accounts/pages/Main.vue
- contentcuration/contentcuration/frontend/shared/languageSwitcher/LanguageSwitcherList.vue
This PR adds "dots" between the languages on the sign-in page for Studio so that it matches the links for Privacy Policy, Terms of Service, and the link to LE's website.
Addresses #2725
|Studio RTL lang|Studio LTR lang|
|--|--|
|![Screen Shot 2021-01-19 at 8 37 29 PM](https://user-images.githubusercontent.com/13563002/105127766-5d30b700-5a96-11eb-866c-e4197f393486.png)|![Screen Shot 2021-01-19 at 8 37 49 PM](https://user-images.githubusercontent.com/13563002/105127759-5a35c680-5a96-11eb-8d18-66ea6b33a830.png)|
|Currently|Kolibri|
|--|--|
|![Screen Shot 2021-01-14 at 3 04 55 PM](https://user-images.githubusercontent.com/13563002/104659916-6a0a7080-567a-11eb-9904-fa3f3fee1630.png)|![Screen Shot 2021-01-14 at 3 09 47 PM](https://user-images.githubusercontent.com/13563002/104659984-90301080-56 …
> Adding dots between languages on sign-in page

- contentcuration/contentcuration/frontend/shared/vuex/channel/actions.js
This seems to fix https://github.com/learningequality/studio/issues/2815, the apparent deletion of one old channel upon the creation of a new one.
Addresses https://github.com/learningequality/studio/issues/2815
@jayoshih's [recent PR to hotfixes added pagination on the channel list page](https://github.com/learningequality/studio/pull/2788).  This PR ensures that newly created channels get added to the page so that they will be displayed.
I found a whole host of weird symptoms of this that I still don't fully understand.  Why, for example, was the newly created channel showing up in place of an old channel?  This is something that still baffles me.
There may be more issues here, and I'd suggest a more thorough revisit of the channel list pagination code when things have stabilized a bit.
> Add newly created channels to the current channel list page

- contentcuration/contentcuration/frontend/shared/views/MarkdownEditor/MarkdownEditor/MarkdownEditor.vue
- package.json
- yarn.lock
Fixes basic formatting issues for viewing published exercises in Kolibri.
Markdown from the markdown editor wasn't rendering correctly in Kolibri.  HTML tags were being displayed literally.
We weren't ever applying TUI.editor's HTML to markdown conversion.  So I tried applying it, but then it led to some other quirks, so I added a markdown conversion library called "showdown", which is a bit more customizable compared to TUI.editor's.  So, currently the state of things is, roughly:
- Showdown for HTML to Markdown conversion
- TUI.editor for Markdown to HTML conversion
(Most of these were existing tech debt issues)
- In question answers, paragraphs are still rendering inline in Kolibri, but it doesn't seem to be Studio's fault.
- Formulas aren't styled as nicely in Kolibri as they are in …
> Fixes for exercise rendering in Kolibri

- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
- contentcuration/contentcuration/management/commands/setup.py
Check if nodes' `complete` attribute is correct when nodes are loaded on edit modal open. Fix it for nodes that are marked incorrectly.
I wanted to add tests but I've found out that we skip all edit modal test cases. After removing `skip`, everything fails. This makes adding new scenarios difficult. I can see that we skip tests for more related views. I think this is our tech debt from times when we needed to do some core refactors and agreed to comment out certain tests to be able to merge asap so other folks could work on related features. I am going to raise this issue during content dev meeting and hopefully will address that soon and also add tests for this new behavior on that opportunity.
> Self-heal validation on edit modal load

- contentcuration/contentcuration/models.py
Adding annotations over a channel without resources in it was causing errors due to empty resultsets
Closes: #2868
From the admin page, click on a channel with no resources. Before this PR is applied a server error will happen. 
As an example, this channel has not resources https://studio.learningequality.org/en/administration/#/channels?page_size=25&page=1&descending=false&sortBy=name&deleted=false&keywords=33350aadd5324cfb9f28be6e16f4fdad
> Don't calculate data when there are not resources in the channel

- contentcuration/contentcuration/frontend/shared/data/__tests__/ContentNodeResource.spec.js
- contentcuration/contentcuration/frontend/shared/data/applyRemoteChanges.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/tasks.py
- contentcuration/contentcuration/tests/test_asynctask.py
- package.json
- yarn.lock
The content node copy operation was assuming the relevant nodes were already loaded, which in the case of importing from search, wasn't true. 
This PR unwraps code out of a transaction such that we can use our resource methods that will attempt to retrieve the object from our API if it's not present locally or is stale. This required unwrapping it because the API response must be inserted into the IndexedDB. To prevent against edge cases that could cause inconsistencies in rapid calls to `ContentNode.copy` or `.move`, I added a small in-memory locking memory to ensure that if it does retrieve objects from the API, the operations should still happen in order.
Resolves: https://github.com/learningequality/studio/issues/2820
Preconditions: A channel created.
> Ensures nodes are loaded prior to copy, a use case for importing from search

- contentcuration/contentcuration/frontend/shared/vuex/session/index.js
This fixes logout problem when `/logout` was requested before `/sync` which in majority of cases resulted in `403` for the `/sync` call.
> Fix force sync on sign out

- contentcuration/contentcuration/frontend/channelEdit/components/StudioTree/StudioTree.vue
> Use empty folder icon in topic tree hierarchy to reflect topics without resources

- contentcuration/contentcuration/frontend/channelEdit/pages/StagingTreePage/index.vue
- contentcuration/contentcuration/frontend/shared/data/resources.js
* Replicates `where` stale while invalidate behaviour in `get` - as opposed to the previous stale without invalidate
* Redirects to the root staging view when we detect that the root staging id has changed
Fixes #2361 
@bjester interested in your thoughts on the change in the `get` default behaviour for cache invalidation.
> Fix for stale staging tree loading

- contentcuration/contentcuration/frontend/shared/data/resources.js
@sairina Found an issue that is preventing copying to the clipboard, that somehow eluded me in testing :facepalm:
> Fix error preventing copying to clipboard

- contentcuration/contentcuration/frontend/shared/data/__tests__/ContentNodeResource.spec.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
- contentcuration/contentcuration/tests/viewsets/test_contentnode.py
- contentcuration/contentcuration/viewsets/contentnode.py
Fixes an invalid function call to `.get` with params that are only supported when requesting collections. Adds more unit tests covering relevant code.
Resolves: https://github.com/learningequality/studio/issues/2903
- This fixed a bug in the sort order code that would cause issues moving items to the end of a list, and could only occur when dragging downward, to end of the list, and dropping
> Fix call to get with unsupported parameters

- contentcuration/contentcuration/frontend/channelEdit/components/Clipboard/index.vue
- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
Removes the options to "undo"/"cancel" in global snackbar popups when performing the following options to/on the clipboard:
On clipboard:
- "Make a copy"
- "Delete"
To clipboard:
- "Copy to clipboard"
Addresses #2890
1. Login to Studio
2. Click a channel
3. Select some resources and add them to the Clipboard
4. Click the floating Clipboard icon in the bottom right corner
5. Browse the resource tree and select a single resource
6. Click the Delete button in the Selection toolbar that appears
7. See the item deleted from Clipboard and the snackbar notification
8. Make sure it is deleted and check that the snackbar indicates it is deleted, but does not have an option to UNDO or CANCEL
9. Repeat but with a resource to copy
1. Login to Studio
2. Click a Channel with imported content
3. Select …
> Removes "undo" and "cancel" options in popups

- contentcuration/contentcuration/management/commands/mark_incomplete.py
Update license validation queries to skip topics. The previous version validated licenses of topics that were previous set as complete. That doesn't make sense because we don't require license on topics and was also one part of the problem occurring for some historical topics incorrectly marked as incomplete (see "Steps to Test" for details)
I've discovered this issue by restoring ["Be Strong: Internet safety resources" channel](https://studio.learningequality.org/en/channels/d0ef6f71e4fe4e54bb87d7dab5eeaae2/#/f520e497104d42ccbb0611038db8850b) that contains topics with a license set but copyright holder missing even when it's required for the license, and even when we actually don't require a license for topics nor have UI to edit it.
Then I run ` yarn run devsetup` and many topics were …
> Fix mark incomplete command for topics

- contentcuration/contentcuration/frontend/shared/utils/helpers.js
… are empty
Fixes the broken PDF generation functionality by adding a fallback value of '0' when `style.getPropertyValue('border-left|top')` return `""`. This prevents the `x` and `y` local variables here from evaluating to `NaN` and later causing problems with the PDF generator:
https://github.com/jonboiser/content-curation/blob/cdfd96e8b3adb237fb0283700df564236048d79f/contentcuration/contentcuration/frontend/shared/utils/helpers.js#L184-L192
Fixes #2914
Fixes #2912
On the Channel Details modal for any channel, try to download the Summary PDF file. It should work on all browsers.
*Any additional notes you'd …
> Add fallback value of ‘0’ when ‘border-left/top’ style of a node is empty, during PDF generation

- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
Because the functionality of "Delete channel" from the Channel Edit page is currently not working, we are just hiding this option from the view for the time being.
Addresses #2894 (but does not fix the issue - this is only temporary)
|Before|After|
|--|--|
|![2021-02-01 14 19 11](https://user-images.githubusercontent.com/13563002/106525286-99054c80-6498-11eb-98c4-117f5d5a375b.gif)|![Screen Shot 2021-02-04 at 7 54 06 PM](https://user-images.githubusercontent.com/13563002/106989217-8607ac00-6726-11eb-8237-8340ec31e61c.png)|
This is temporary, and the functionality needs to be fixed in the future.
> Hide the "delete" option from Channel Edit page

- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
- contentcuration/contentcuration/frontend/channelEdit/views/progress/ProgressModal.vue
- contentcuration/contentcuration/frontend/channelEdit/views/progress/__tests__/progressModal.spec.js
- contentcuration/contentcuration/frontend/channelEdit/views/sync/SyncResourcesModal.vue
- contentcuration/contentcuration/frontend/channelEdit/vuex/currentChannel/actions.js
- contentcuration/contentcuration/frontend/channelEdit/vuex/task/index.js
This PR updates the Progress Modal to be used for Sync Resources tasks to provide user feedback - both when there are resources that can be synced, and also when there aren't.
Addresses #2555 and #2688 
I wouldn't say there is new technical debt, but there is still some technical debt in the sense that not all of the tasks are truly managed by the ProgressModal - it's just the foundation that is there. This doesn't really change that, and there will probably have to be more changes that are made in the future based on use cases for different kinds of tasks/feedback.
> Update progress modal

- contentcuration/contentcuration/models.py
- contentcuration/contentcuration/tests/views/test_views_base.py
- contentcuration/contentcuration/views/base.py
* Ensures proper behaviour of the activate channel endpoint by ensuring that staged files and active files are properly compared against current usage.
* Adds tests for the activate channel endpoint
* Properly wraps the activate channel endpoint so that it gets a non-anonymous user from the request
> Fix activate channel endpoint behaviour

- contentcuration/contentcuration/frontend/channelEdit/__tests__/CurrentTopicView.spec.js
- contentcuration/contentcuration/frontend/channelEdit/store.js
- contentcuration/contentcuration/frontend/channelEdit/views/CurrentTopicView.vue
- contentcuration/contentcuration/frontend/channelEdit/views/NodePanel.vue
- contentcuration/contentcuration/frontend/shared/utils/testing.js
- jest_config/setup.js
MoveModal open/close logic was conflicting with a condition based on selected nodes length which was causing the modal to be closed prematurely without properly calling logic that is supposed to run on its close.
Contains some smaller updates related to testing - please see commit messages.
- Fixes #2866
- Fixes issue when selecting a node that was previously moved unexpectedly reopens the move modal
- Fixes issue when a snackbar wasn't displayed after move operation finished (can be also seen in the recording above)
> Nodes selection and move modal fixes

- contentcuration/contentcuration/frontend/shared/data/__tests__/ContentNodeResource.spec.js
- contentcuration/contentcuration/frontend/shared/data/resources.js
- Collaborated with @micahscopes 
- Adds parameter to `get()` and `where()` to skip the async refresh of local data, since that could interfere with data that has changed during the time until the request completes
- Repositions `sortBy` of siblings so it's _before_ determining the target's index :facepalm: 
Resolves: https://github.com/learningequality/studio/issues/2905
Resolves: https://github.com/learningequality/studio/issues/2902
> Skips async refresh of local data for copy/move queries, and fixes sortBy finding new sort order

- contentcuration/contentcuration/frontend/shared/views/channel/ChannelCatalogFrontPage.vue
Adds guard in the `ChannelCatalogFrontPage` component to handle cases when `channel.accessibles_languages` is `null`, to avoid a type error when trying to access `null.length`.
This might be the root cause of #2914, which only occurs when trying to download a PDF report of multiple channels.
> Add guard when `channel.accessible_languages` is `null`

- contentcuration/contentcuration/views/base.py
Completes the update of the activate_channel endpoint to a DRF APIView by using request.data
Fixes #2930
> Fix bug in activate_channel endpoint

- contentcuration/contentcuration/tests/views/test_views_internal.py
- contentcuration/contentcuration/views/internal.py
Updates the create channel endpoint to allow passing the data for a custom HTML5 app to attach to the root node of a channel, and the extra fields setting that is needed to flag the root node as a custom navigation topic.
> Updates to create channel internal endpoint to handle custom channel navigation creation

- contentcuration/contentcuration/models.py
`filter_view_queryset` was adding a left join on Invitations that was causing duplicated results when showing a list of channels.
This pr replaces the used query using only the list of pending invitations the user has. 
In any case I wonder if we should show to the user channels that have pending invitations
By the way: this issue hadn't been seen before because admins don't have this problem and most of LE staff are admins when testing Studio 
Closes #2899 
Documented in the refered issue
Login as a non-admin user
Look at the list of channels and check there are not repated channels in the list
> Avoid left join when filtering for channel permissions

- contentcuration/contentcuration/views/internal.py
Our ricecooker API for adding nodes uses `disable_mptt_updates` and defers tree processing until `finalize_channel` is called. However, after the removal of `sort_order`, this causes MPTT to order the nodes incorrectly. Correct this by removing the `disable_mptt_updates` call and allowing MPTT to order the tree properly at add time. 
Currently this PR has only been manually tested. Ideally, we would have a unit test that confirms the order of children, but unit tests can confirm changes do not introduce regressions. 
Note that we'll want to run this with a large-ish tree on hotfixes to ensure performance isn't impacted too significantly. (I can take care of this part.) 
- Aron aronasorman (back …
> Allow MPTT updates when uploading tree to ensure proper order.

- contentcuration/contentcuration/frontend/channelEdit/vuex/contentNode/actions.js
- contentcuration/contentcuration/tests/viewsets/test_contentnode.py
- contentcuration/contentcuration/viewsets/contentnode.py
1. Adds `randomize` to `ExtraFieldsSerializer`
2. Fixes diffing code to properly handle the case when going from `randomized = true` -> `randomized = false`
Fixes #2864 
- Edit an exercise. All the fields should synchronize as they are modified
> Fix "randomize question order" field not being synced when toggling its checkbox in EditModal

- README.md
- requirements-dev.in
- requirements-dev.txt
Add [Flower](https://flower.readthedocs.io/en/latest/) to dev dependencies and mention that we have it available in README.
@aronasorman When I run `pip-compile`, it also changed other dependencies' format (maybe it's because I am using the newest version?) Is it okay? To make the review easier, I run `pip-compile` on the original _requirements-dev.in_ without adding any new updates and committed the diff. Then I added the `flower` package to requirements, recompiled them, and committed this change in another commit.
I hope this will make locating this tool easier for developers who are not so familiar with backend tooling like me. Also, I noticed that we actually [run flower](https://github.com/learningequality/studio/blob/develop/package.json#L45) already as part of [services …
> Add flower to dev dependencies

- .gitignore
- contentcuration/contentcuration/frontend/administration/pages/Users/UserDetails.vue
- contentcuration/contentcuration/frontend/shared/views/details/Details.vue
Fixes #2960, which was caused by an outdated URL in `Details.vue`
> Fix channel thumbnail links in Details.vue

- contentcuration/contentcuration/frontend/channelEdit/components/ResourcePanel.vue
Allows the header to expand to the width of the panel.
Addresses #2892 
|Before (Computer)|After (Computer)|
|--|--|
|![Screenshot from 2021-02-01 13-05-00](https://user-images.githubusercontent.com/1680573/106518056-2a22f600-648e-11eb-953a-f58e07fb48b4.png)|![2021-02-17 20 06 26](https://user-images.githubusercontent.com/13563002/108304090-1c42c580-715c-11eb-9b26-274b9abc0e38.gif)|
|Before (Responsive)|After (Responsive)|
|--|--|
|![Screen Shot 2021-02-17 at 9 09 49 PM](https://user-images.githubusercontent.com/13563002/108308388-83647800-7164-11eb-855b-ef587d53f64c.png)|![Screen Shot 2021-02-17 at 9 05 23 PM](https://user-images.githubusercontent.com/13563002/108308300-62038c00-7164-11eb-9804-920c50d534bd.png)|
1. Log in
2. Click on a channel
3. Look for a topic. Click on the three dots …
> Fix resource panel header width

- contentcuration/contentcuration/frontend/channelEdit/views/progress/ProgressModal.vue
This PR fixes a mismatch that was occurring where the Publish Task text was the default, and it was appearing before the Sync Task text appeared during sync tasks. It also removes some extra code and comments out (but doesn't delete) strings that aren't being used.
Addresses #2977 
Before (Sync Task @ 0%)
After (Sync Task @ 0%)
> Fix mismatch between Progress Modal content and current task

- contentcuration/contentcuration/frontend/channelEdit/components/RelatedResourcesTab/RelatedResourcesTab.vue
Replace VDialog with KModal in "Related resources tab"
Part of https://github.com/learningequality/kolibri-design-system/issues/156
| --- | --- |
| ![before](https://user-images.githubusercontent.com/13509191/108755692-dd3fb600-7547-11eb-9fdf-bc5b094beada.png) | ![after](https://user-images.githubusercontent.com/13509191/108755716-e4ff5a80-7547-11eb-936d-f7107ce8955a.png) |
> Replace VDialog with KModal in "Related resources tab"

- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
- contentcuration/contentcuration/frontend/channelEdit/views/progress/ProgressModal.vue
- contentcuration/contentcuration/frontend/channelEdit/views/progress/__tests__/progressModal.spec.js
- Use `KModal` instead of `VDialog` in `ProgressModal`
- Related refactoring and simplification of the component
- Enhanced test suite
At first, I tried to only swap `VDialog` and `KModal` in this component. However, in this case, it seemed to be easier to switch to the KDS approach completely, for the whole component, especially due to differences related to the actions buttons slot.
The first commit contains a small cleanup that has made all my further work easier. See the commit message for explanations.
One part of https://github.com/learningequality/kolibri-design-system/issues/156
|---|---|
| ![before-publish-inprogress](https://user-images.githubusercontent.com/13509191/108539172-ee868980-72df-11eb-9be5-cbed0cf6bc85.png) | …
> Migrate ProgressModal to KDS

- contentcuration/contentcuration/tasks.py
* If a node with the specified id already exists in the backend when we try to duplicate, this can lead to an IntegrityError
* We then fail to have a referent for passing the change back to the frontend
* This case likely happens when a copy change is sent to the backend twice
Fixes #2904
> Prevent reference before assignment error

- contentcuration/contentcuration/frontend/channelEdit/components/edit/EditModal.vue
The `handleClose` method tries to call `$refs.editView.immediateSaveAll` even though that ref is conditionally rendered. This simply checks to see if the ref exists before calling that method.
Fixes #2949
> Check for $refs.editView before calling immediateSaveAll method

- contentcuration/contentcuration/viewsets/channel.py
Counts every resource in a channel even , ignoring if the content_id is repeated, so different resources with the same content and different languages are considered.
Closes #2757 
1. In the main channels page select any channel, and take note of the number of resources
2. Open the channel and count the number of resources for every topic, adding them all must match with the number in 1
Easiest fix in a long time (after you know what the problem is)
> Count every resource even if the content_id is repeated

- contentcuration/contentcuration/frontend/channelEdit/views/TreeView/TreeViewBase.vue
- contentcuration/contentcuration/frontend/shared/data/resources.js
Fixes deletion of channels from the channel edit page.
Fixes #2894
There were two small bugs:
- Two functions shared the same name
- A promise was being returned from inside of a Dexie transaction
> Delete channels from the channel edit view

- contentcuration/contentcuration/tests/viewsets/test_contentnode.py
- contentcuration/contentcuration/viewsets/contentnode.py
[This issue](https://github.com/learningequality/studio/issues/2927) was caused by a pending call to get the ancestors of the root node of the channel, which blocked the loading of the page and thereby prevented copying. Unfortunately, this ancestors call can take several seconds on hotfixes and production (90 seconds on hotfixes for me once), even though the root node has no ancestors. This PR makes a change to take a shortcut in that scenario to only return the target node.
Addresses https://github.com/learningequality/studio/issues/2927
Addresses https://github.com/learningequality/studio/issues/2889
> Don't filter for ancestors if target is root node

- contentcuration/contentcuration/frontend/accounts/pages/Main.vue
Disable the login button while the login request is running to prevent subsequent clicks and more active login requests than one at a time.
Closes #2937
**After**
> Disable the login button while the login request is running

- contentcuration/contentcuration/frontend/shared/views/channel/ChannelModal.vue
- contentcuration/contentcuration/frontend/shared/vuex/channel/actions.js
This adds an additional form validation to see if the language field on the form has a value, to account for validation error that is occurring in some browsers due to having set a default language in the old Studio. 
Addresses #2895 
(I will be asking @radinamatic for a QA review - in addition to asking a dev for review - since she has and account set up that will allow for testing on her machine and I want to be sure I'm correctly understanding and addressing the problem.)
> Add additional language field check 
